apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret-taxi-svc
  namespace: chetan-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBUEaD7eKxgI7oOyf4BcMNW8TrJfWuDSQNmweq6U+cdvLAn13saqfU1LesSdOvauhNijLvUsjYDcMlu4KkrqbqgcNa5yz/LifSCETPN1IvlNJaa6K7x5YTSZL4NNe8D2E54Qmp8EXFd5XHJYqOfl+bB8lHsBjV3rYfyLbnbAkBUGf1o/T8MtccXMMG5okppGgFI5Uwz4NOHeV1PiurVmV1uLUKbiL5+e380BKTQJVqD03f54OchAoJUw8Tv2BLjXdfTKlVdrf77tZMVcKONGAYW5k0WUg2rLdnChBd6Tb1HbqkRcMFr6/EVMzqtnHcXZ15nU4vy9yJkqJXtWJW0aBzqWctgOhgCjgytPHf1IkcgT7nWVcSkQ4xx5MfBx4Rc9Bj1LX3zwDbZJjxGnUqalEdlxW1vUCf79kz6om2++NtgDNjWQ7RM/ywwpkEzFst4sRiF1gYZ+tei6+hVBzDm2ghAkg0xi88pcqzZafmn8Szj65ZYFCWE/DgBnXHm3AQnw5Rf6s4mvJ41c/eaHe49kF8AsBbGy6vkYStgZiCY7VbbdlgPxGlckaaEauoGEl9jWPaX5jat3///qnNFYurut1iWspixLVukh0aMP82K/TuMooYFPj2XCoCPERVtrLHfrhbicBD6DtmOyas7zZjFvZ7WcyKpKRTKvR6Iw+iIqaDZaBAXVORGCVDurywrBuhIIXHJei0=
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret-taxi-svc
      namespace: chetan-cicd
    type: Opaque
status: {}
