apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: commit-status-tracker-git-secret
  namespace: cicd
spec:
  encryptedData:
    token: AgADTXtKk0jtiJ/nLf27g9qOPqjXPLnEIWwubhi9Umvk47y79ZH6j91dfdSn2LMYocw4bZZL2ggptoERnzYFnQJqVBeGV+qW/p0GYQLgzcpgaoMHvdoNbEBKlnr3+3rViFHhD/qdGV/YmXSMEbIvwyXdABtV1YA7cDXkiczb+d0E1iAZxZG0gVQG7LxadQZ5UyB7l9BDbxPxz/dXraBZuypXCJtYnV6eGOeic9lzVrMNgbILIUeU1OsY88TvwgiWg2zSp17a0KqYUs0yNJDDuEC5VGqJ168fQ4vXz2TBHnQjwMlVVDWAkvue6fLr7GlDCcAKPtYzjPFU9ZMU8N6CLL/+ILlsV/g2cZR/nPi5wEdrLUQNGB8JbONZTNbUtfQXx+ZulDElEw1IHCyTZXJr7Ym/9PY6MOvS9MpP91G/CmzVvauGCgpPKU+93503OkhEgzJ+2+4A0g2EG7CSvxrXuwh7rHWJ/86VZQfBrrKO3pAuX3So4uGqPRcA17OkyDHQq9pKhHcCXCCNNClorTieOmfDn2Lc+9rYA/IXXkyO9l99THzcJPiLrHkV3Zxz2PxAyhO72i/WHs99DwwBS6zXeTVodAwFrpULfL30AEZNIrlUaqYTqi8w6bcFY7YcmKIekP036eowEnBUmqlyuMGCsZb0iDPjkIGfolgrELBqa+TNo4pY4l/TNyrqFiQbGAA9fM65oQIakVZCnAvfu2dhGAs7/2+1YM5001e2vVLYHJZg2aOHa8p1Pb1M
  template:
    metadata:
      creationTimestamp: null
      name: commit-status-tracker-git-secret
      namespace: cicd
    type: Opaque
status: {}
