apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBFKyMM3j8RjLrz+P3i3GMO1FrIjKWMzkBrHXaPIYTQhBM3rdocN/R6ePBuOc3oAN693wVZNrLQy4HnMVNU1gXjag8M/+p+tY0vAl1w/YeOU+fvwgm4WfXVAVtWQf3pejQ/JVWM1yfelPiTKbLdbDTEMQm5KpXYYFgRLuet+1G3TA/ggv53zND1h2eWFnMyEQ4CZKmWjzvcfWFBiK5Tfl+fa7LMkmTX3naCjPUaEdbQajBKqkszHUNBWjugmFwxdvuAZvgc8j6sl20MC5OYdN38PB7ciwwyaLjaDcgGEz64CfeTjYKL3/iEPYUjMsxn9qPXH8gYRL9fvpoy2a+qyAb48NmdavasdvG3vNAIzyMUjItg4Yk0weEeIyxLbchJiff2XbQMmHZPM4L8xQZmjyXhQnUpgGsHD4Y49v83ZaQ0ML45BvK+CIdzUkgu6+mVsKEzavGZslB5dSiJpQrqNE2mBoGFSQho6l9323WJRdew1ydeGyvWhk30x7Q9MJzQgz/PHi/pyDAiYi7my/QoLGpq4gn29kJakr5a5nXRP6O6Zbulgbpvp5aYuDplvktJEybQBDsKc0FNfElAEHvjnEepjlIjguwjR+z8FPx2RPjvb1LCCXo2bn2cph2kazpOXJ3WgqvN5033imSYoPWz0tny/9CZZMNMXfhEOrAhTlAD+1Aj+KwwK3XdMCzi8PwvZ26G1BCcsHj65p+wM/OPhC1tQ566/HPI8l8IRRYWk6IZx+mjy8wavIJTY6NNsEGYDwZodNZloBHHWppe0/6pxbs0WsAN+GV8VnmUnSIwfTL1EH66MR/9c7XxQo5B3L3CP2BxTqQEXyjHCX+JFDPNO/Ep9H78hWvRPdYLohu8U9M0axrmU8FTzK4lvDX3Z3kbEFHAo0eXAWPS+SAjh6QpFVCERJw+nL5x0EHJ7VvVBL+X6gEOGbOwFRWKS7Svu/z8YTo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
