apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgDGWsOgCWrYdt1ptiMIEezPcnb0NcGSDBKnZGCw3iUiJjnhXIFSfHMluPox13A9MNKfxXw6UQhDfvF3xRFp9FEDVkD0r7DhksTvNVtKc0uw7A189+hQePM45QqqPWJAEYNHhlivDTgjyzo+4y8qI4+HwUNkib1bhnIYwipvSW3kUgnJwlLVFjLp5Em9x5iSvoDP74PKPBlji8E34TCY2QnPRfhfhqqC+7k+UFpnGNvCpsfSXtqcRV+33CH2Y7B/xzhbj8mcXsbGkd1bhVjdMQGf6PQ26We65MD64KEby/ROX37M9JrznnOzsmkuia1J/O+0tL21jC9KgrijOWooH8M7VZgas6aWLa7MligvWhYgf3KRazdbF5TZKf7v46Bb8USAvmIFmP7slsMPK0mWB882tFkBOv+XEj5fUFLJQKQ21xE4DKoGc4NKBB0P7aLozDiug761msqeq+2C5MbmGzyNeIf519ugmj/hE5xCBExuy7MGnP9R/6CX3rNJAiemPMvZcxPBG9wVPxKgwXCbpe2xSr12H+TQcJVezQMnJuv0tzFxtQCu6MztM1GnvuByCOvQTk583TjIoQLO5U/toKLvR9WmyYpd60J3q1kY786KcpIWrcI0Xyk+5grtI2sDDzYMUXY+wJWAIDgQrOpyR/X6zBOqDe4Uep2XW5IM7QVdYCX8WDoS92nOrII/mrvfUZsh8G29xKdzqpPA3hhbPKg9PsSE7gJuInoEQFcrpHAQArlUF/SEaenhq1XxhfgUtePCYZLlQX/MmGs9DcKWmr3n8ndSRYAumOcyi6xpsJAEBzVEcoISvZY7QrUeFIHYtrJiQQeMpWcL9su5Qx0BtoghI2TYFtMQiwBpIWEE+8krNrkBF5Ju551QJTz/H6vW5XKgfBRt9GqhKCH0rfebDNpiUyRFKkBQMVlAiE5h2G5MSGlhRjzp6TNF1tWwOH72T7A=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
