apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgATidLoBU2d5uqYqjBc4CIuvfImwNzcOaIkrUaqO1lzqV8F5/05cV3jsOwrxzu/O9hm91G3IgHT7rTj3wZzPWSZSvuaiyoYe7GcgaJDe6/XKsao+tiZ9fKon0+tyVIC94DPgFpPK/WQ0FpH99aQT6PL/AQGywNd73gTk9a9E9HF1zFCtbpudDoQfbXRJqzKtenMGyzLtR6kbbQCIJL88hAPFUEoGz1VQC7orYcbGqtmv0ovAGftSyklJrn5j6WwVe375dsx2hQtOmjNC1aqmf4uvayT42cDe3s3l13Eihw5rzwlibTblShfamD9A1s+FIgTH2auhllCaBdcwkSe+pqU9tQp5k9WDqelPbbJKHu5/VVGylc+dGVBW+j8TFhPqFTuyEpjB6cGLqf3Sqn4OLBs86S4srEwUsDox19lctjLY3t9pZfFmp3VSXMnaXfwmXjADssLVCh2Cb9RM8RFX3UHjzUWaoWvomf6qg5tKbiOnd/HatCWPAs008qtWlzl7v/iDJ2PCaDoEzpH5F8rEcZqEziDKnOFOfBiJn7Mh3GWoij+OSALXJsnEtH0T/MutLTo2gkIYquS6780gqaCZrMeoJefguC/eKcEA/0EfScdNsvCPAfXMbyZqAmhmJJEEmt0QUl1SBjq63kB7VoCGZEl4oslidU7TTKGh+JsY5YNjy6lsgiSpiUq95WFIa1zFSVW8Ln0UGsYf3Vppx8cj+rbpo2Ey5kD5g6yfs+vt611qItzeEW+Z40GSlko68/eeumgCU3Ze1WM2Bg/NGwacm8agqGxXJRf5Zt7oAtpLi9WU5spAGPIY2fAIaK1e2Q3pFdhmwdnNnQFvf6nkPNG8VUzOJ71n6rqieacleSYln1NTixkBO1Dwqumzj5ayhEyg5a4hXSLbq2DT2RFMYWH6jFBNHT+MiqLmVrYMq6CNe58hNEFjRn+mq5rJkWc7De1DGM=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
