apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgB4optOMZomypMn21jZdm/5qr6ayJwgGe7PfAXB0q5mhbCUWr08oG1AZtVQh7oFLJMXvuZnNObAYTIW8VpEXCP742jD97/ly9hWWd2Fn31af1TAuObcUlQOCeYua2IUbwIGWN7XBp5/PELVbgnBqnysF6B1dCSzVc4jXDIUXKxs4OWk6S91ofXFT7+xeJptzAgVxOaaRZejOI3ieLMEsZQQBz1TXPD3Q52KnnWyVPDVPAe5/MLDY423nRSFqIdhEsq9/29COHd1xMC40Fai/Qxi7hd/Xa7LB9utASbbkImBo/aozjh9Nbz83dfxNZKtm21i52lvFNyz144wjaWmKsE6Ez4EQs8EGGYgvh4ieyg/Pkhokn7Y8E8jnkg+UBS+dITuMq9YGPO76ppu1py221VUIFfygdkzL9FlbGuQe0ueLLxObaL+M3I0GWjKAt/dzWfXh4NNzhJlJDme8rVMepdDq4RiL2EM+ZdfXE7xICeOUhWHl2dnxtGj5Dl1EeRe6n2XbcF/Ye9J3HS/WIJ6T8TkqHvoFyTYIaoU8A4JFFkWZjdtOnvjL1ypxUTO2Gdb0pg2vFOKphIJHG7535ZyRGCC4ICjbIPeWkt1vTjVGTM5p4m6N9Cds9zfmQaxG5dcHHyBJSjJAdt0J8Nf/K7GBlZlor/FjAD0Vtp4XWPUy8RdQjijeX7eh80rndCEOkncH1C14t7S0AX8iZDekYjL+SdJB10OKRSzPgfhFQEB5brVZp1m0VqJ3M4assbgS0hvxV8wbIXnWtznpXDCHoM2+PqAx1S+sDIks/FQ30O6U+hl3/0t3xa5WIfbFZOSTd9I7/W3fqrOMw0HwFytnY71ydTgvKNakhZe/40r4HGZiZK2pDXwFV3SO25h/vpIX+3lJ1D0i+WztcBXBi2e4AgnVuWarfI0SZbT683mFp4YhETglDoM4KPJ6CpPAaRTWQHjuoY=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
