apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBWnN/KPcyhnYDHgbB+O9RPDKo6KJIg9c+bNw5CcOBEhbthD4fLui2zUFiyvgVIyk7qZXomRMXxN38HrYRQrngwzxLBldIpZU0wUu+nIpHQ9hIpz6d491dlckYSXeXFmdb9CEMNrpdmxYD/rjiO28qNMlOF6h9kzWuOOwIhrH70wP0A3QVKMpapXobcHcXgQqEcdWPtUs1gzY5JtsT14pIvfCqQrzNHgSkia89kD1cRxvODcsEnDzbwfdZQNlU7UVY+SvWO1O5JFLUOTenf+f8+9NGnuI9iZ9f4MzNJfiM6Zv3U6vSX6HBrTUzcSUIubv9uvpFluGYo7MyoAgUFDJsBHCtxTS6l+ZtgA6fXnON5x7w7kBnZY1Hv6ouHMgpn0RQGcW8GWRoeVHocoW27sGcA74E8U4a/f/wkgnPc8z0L1fzeWVzIyq3KlZa6/wm8EyLVR72TDiZcmZgsz9KCiZv+SmTxuOebNVPsgXr6SE8BjOSEEd4rbwCqG3orvsawSHWIQyGW7dyeUMdzduYUDmXkfH59BjmjP5BeWgZxChtuzUtWENv0+dVAPLU3SD67WO9xMmAAveKSzb+4vEebtuSX7bt0OAtaUZpi3opx4lfiCs7JBZB5k7+EcXeVz2TWVgWIKO41bz9U799q4MVkWIG3AbIbKjwzOtjiEAUIpsoQ0G7v1wPfPyRWIqe30DN3AT/HfD0WVg57f/uW476Kd0ybacDpnPDJtmc5duPeag6FVEwNTXzSR9Id+c8NM659Amm6v4H4+VQlGan2ZWLFN4RlR+5xJDqvAUzbC7VwyizzB7sZ6MBN69LirKWsmNs/6D66pBELXpMwnxSnRRQqeoFLO9aJzlS7OZlgacvMXq6eLXi4MBZLCj1w1x8fQKGL3tjfMqcAHEfiGEHHnL8uS9YE4lAnVC80zZZUzWS2zHiKuIkKy3x4+WUgCgTfjbPwoJA=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
