apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCLYyPJtPgJE6/1Zr++VWV8O0FR1mNW5t46QL+8ApKMfi8YNLm5PI5TnYhr9BPsC36RNCkNHE5rwdqPFl3B7oxtDYl8sNwNDskGKyZHaELJbaYUJA4IplMXWkh+LZsZxI2oXKCKGfHQBE7a8Bwef2bUwsuytC/IO1zNX7tmRxBmT6lETd0+Oet8SpsRsjm63ba0jbLLC5jokQDY9DNwCiK3/Xfg3nMpnb8GWdHpuCYi1Ty6qWVCxmJVCUn1x69IOXdboZI7rrUjjj5sXiInXdEj4f2+Dq3VjPaecSpGGZUJ5llqcNY0qwbNGqFp7SN4tkaZnG2YZQZhlj920RArKIFfpVBcSLQGKR7es5PjnsUGyDgktB+kWGeUVbabwo7hNrjYgh1qVNKJLfwapdcNpT+nIJ+Tg56ALQd1KQwT1GlZN+4ncamQhS9SmR4pkBbeJtBg9k90G63Rf7ciA8Kgnip4EZgJdu++rAWcAIJ2yeibphmYSrFIWhw7Hl0aaBQUAE8yBkVA+WBe4ENlZFtFNUAhn7zKDaeHh4i8Rf0UUDNFvpzHrpnkNAY+OW2Eh1mb9EsR9VRm4ZuQeDp5SfKgWQHCRYP3N/2pzc7keDEq/TXQOX7o1sf3YGrs/03qM2KjhJuRe2pfYjrl5VsISL9mzEYR4EfSCkhKxNkg39kCPiYPbHmy6ceE31ie095+drsjgM0Ogkm/NWKCxMrV12WphZL6xC4v99XHOZ9TRivDi5SFAJkjjG6gj55j3K6aFvP3PRVFXTRVKS+nTH9coGRVigbvl2LfKY+mhJDrebrMi/dRtwwUb3nvWMMge5E1VRBdECXqGSC6SurR9aucGAHCYf18LAtK4+LmKZP2xIhaomVGuLlrJ5MrSEm8GXrJF9KG316yGLW7hXmkknLHF9+7zs6oIcDyjQikXSNi7Qw7mQDraMPZ8WKr6xGnI5TcDi7UJ1U=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
