apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA0njGl3idZVxcbAElVPj8Z/tcYLXXfQ8MRM8ZTqfl9F825tIOhdPu/2+CeY6R7i56o/tNRXT8hQGmEbOQTI7BcH6MKWrZ2LyQqRvMAZ9OC9vG9pvN77h60X4LDCORWTR/1akCTOr3nnAKGhwBbWZ8Q3WQpWFzYNWTvjtBVXtU6GMCJXnl+jafvWzx39xYKvSjIVyHZWSaqMO8bUauWrGb4GlYwIA7jyMPoVqR3ZOs0Y3OuHvBEL73mOKKoOJRir8H3aZd8rJy7ntIBnLCbayS0/JwulZvr8piOHEb+nQD+P8YPSHlLvPwOt/gWkSN3y983RWNIjCLL8CXir2RcY3a5dUdXaI0nMmr9hFzR8bHD3oQ7YB9a1qkolYnspr2RANZcuVmHcb5CwAmES/SK3sFdhk1IQV8UB6xNdHObpiqHM6AoTUpWxaiWuOI1CuCXzbLeQwbuk7O8fCihOoyLk6T5fKdSJX0HgffxMQZsITm4oPwY+V/d/mdUQ/5GPeC2TFvDTnF5qH5vSxrFk6qA6hHyxg8Z6fY8r2alke88wRsb3hvjgbc3107noEd3Z1V2zPJscbb3U5NQOTDeuJhQAmeh12b1fzStXLcCna9njnMYhemyvTy31v/NaOANGY/I49kqNbkj6FvJge2U016MPtwuExWrgOYpZZxz1Hu+rZAvDFL9MOSZ+AldH66WOk+ufmnWACObbTORvy5FnL+jErRYoqT6F92mLv6r9hCZPhTcPeFE9pep+fJyYPF/iTU+Iv0QX7RMCmSmxuonmZYwuSiyjG/WUfzpKcLuGs3M4g9/Xzookn4KymHK6updJ2UK0PXFSySsAKyFypYnM8d8TlN9uIYBjRAlZTiZpBK/UgoALUZp+/dtmS8uGYZBR+EJgpOZX2ywYTCJoWdEdEIwU3/yvz9IGZTX/ROeoCsaL5ZHQaB93K6So8VhLakmHl30I0g=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
