apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAXL0IytC1FXp1U/9Vy/Y4XU9u+ACBg3KMooBbkKkWw/c9dT9R/CxuXu5QAmpVafcQNjic/JSuFbAeGHxDJsqESdA6uPbzWMU0aftqb52tHDZIAhDT6B0OSpr0JSInlsZvadV3E4wBejaydBld5TBY0lBBxqJB1tKm+8bveQYoRWYPChIJ6c0Hnk+B2/8VM+ppe8HiDizgu2yWQl8qkwXgdY45hzUriVkhSugErObEoezMsAYPibUOWkUF2mLBiqEZ6ejRGb3SeskytCImrAd/5zKNrzzEOhMVDBK+DK156t0/VbfTug7mcSbFQec4nzhIzBSkO1SJgfDHf62vdNCo7iheTISsZdJfTgkVERV3WKlW3Oh635+bThjQtFOFnP9JJOTqpl7GuKA9104eRmG7nh0sEUspU536SN+jb8y08sPYu2ccsMCi+Hk39B0Z1xdK1vTxBZTSKQbOcGCp0hnhnFXi3d6MfCYFYdX3/41asywVgE+MbSnQ/fg+h6l3gmSxHrAmtAd7qvPzYp30JrWx7xRuIdV44AGJFyGGdD4TpEbpYMizTjWf0Muwnd7dkwo0aHiIwcsqTtjh5orsq9UVDCcCqimqeRzdK3mfB7iyjGhRWiuKDzpAiBtI615FGjI7LhvXkWT66zSh5wtZ9QQ4McUDm9gv8eK2GAOqfBoJy3PfSKEeP4kkLppKDYCez4URMad/Bz6YxNfYbKp4M7tn6fu/hxMSdCQv+ofRgFvwyJAURGx+5UTuBLd7ZLVCM/Hx7O5DHTFtCwo/yckCA9OCRBrwVH6wwT8XKAhZi6lDJHVUbKn3mTEeFycbnOihrS/bA/jzHomO9qhPngOtU0AsauZo+Io8cITcXGHCd1yBhLvDgQEUdmlBZ6iznO6QtVIYun4iSoK4mpPCnpiMerEWaAdFEfS/3JXRpV6Pcyaag7KNuSvxMWMfT52pf7O6+y2o=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
