apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBQxloX1TXhJr44E0Ft6CQ1Ie7vOtAXgBY7/xbQ1fbKJNFvz/3gVgv6bs7y0sv4Pn5Q8TBQOY7PUJabn+mO6C4nT8OPzdni6mQeuka276U3/GALrm7BQAjT7nWN3kDL3ExKL2GLL23hfLA4Gwstkv8h5r+3gIeDHITmYvC6G/UT0M/NSBG66ZIkTxq88aRLQ+vLbnxN4Vqfvrip+yUKUshGkI2X878PulHB338MAl1fF5eBHegdAcmsme5pNGkbFU5JoiZWf/kLCbRJ5DJUsXKvlso+BdjNKpFBb6/8gzBuo9pyGRvpuM8ohYRWPcQvN0cu93Z/JIP8MzVnTzk1IlL0QSODIC41FBywjbbu7FnBeJ8OIJmtv88j1R+6mgRAIrbGpiOSaW38tuddwz4gAilXLU9NVgX48wwqIKdQ1TRZEZn9BqWWJYXHt1NRp6Z0TI1MAoU1L0Ezo/hvjzvSqOpLkpqD5GyjPNx3lo81kINkobrdcpKmlWnaMkRSydN8VbaM/b6OEK6vWBbbNxUJTI/vEY9GJ8wt06vy0tErdeOyPGGxy9waLFqDDK1DbzwgQbZfykoPOAE1zevi3e6/EH3OuMwj/6EndgQvoRfyUlqu8pPEHnq/NcKuqDUHd99JdFOJcSqFC7+wk5HYWk2GcqLVQ1y5rjRvR9dmgV/lZmyjMi5YUeqFHgC7e2jn02GXihdIFCH+95JZWhdMADKNoFZH5sMJTsD1iiwRl9gMpb14IQtZJJbryMQJCJGfWDGY1ArSOxvYm2Mt8R1ZjGzTlFMindLbk8S0a67BXWj5H6Xutmil7t+z5CaH7DCf5ZukiG9T3MP8dACzIAMAhuOjSejHtYGrrGNEboZaFcKmOnPNwj/V8ZcpGBn8eKqm3efV502qpq1YoI1BDVKv2QS/UpigEc41VTAZndlcxElqM7R2dmzaS43VU08ly3J8WKWlwcw=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
