apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBQi293g2z01j1SgLUPByOwjlkOAB3UMm+AFJFw5pmYb/YmNoKEhntyBTQY7W0F4wlhC331A+xA9zFrpZ/9L8Brqw23kPZWVtqnPEtN3ZHsSsMTX1amVml+2gWY+KokKmz/bRM+MUjcks0cWPYdXwvsk+j6k4f1LStIZjXUrJr336S7mbHvluaMXakSn6DtytyH0JHTLNk8SdEee/cOY9LpLV/LkuK1Q4MJ3pZoH5CWYh1wbRZ4rHfjSVQHLaSfHJf0KMJVdXJhgcJoYDDMksW+dwigFVQH2eKrLwFQTWWi2hv/u2PAEqfGhmAGn8JDOVn98RSRVp4HXSK0wb178MnHVqLjayveNXrvOWjILOr166T8x5OedspgorRIjdE+sY4it111R1C4LYsqYLAcM95h7gngC9yX/TI0vMlmMfdqAsksihJiHgpXrY3ma9aJMiAVV1zPeyDU10XE0ry8xZzwZMlqYs7WlzG5ie9jbdlbNz7ZhVpb/jCE707bJ575ub7N2T8NtO9ZxnmFMRMw44HWMWgU1J8+LUxwtsO55quyirlSgoShN4gzs711M2GvtwkxCIgRGmRW01oJwIalxLrjecLZ2hOf31WTvoPDUDmH93ut0w5KgHZCt0kpT5ORD/pBJ8jKkGPrc0p9RdU5eitU40QWPeUWlH+NdHt1mB86RP0AH8Zko0ksg6PIa6aVHkE6sLuVgiDGyag1D80sXCrdszuwg5L0S9pmibEbvUM9hJZ9KvhiMDy5fLAI5ARE7fgghWlFX0ENnAxH0EWqrjgfsWcKRlUTDZKOgone7/g5mau7qeGaxSjiYo7nHGtzBboZotrVonbt/tqWpFli2GabGciNMvXjmktA3aisNi3ZcAQn2EHgRJ7lFu3xY05QsflfecWpsr7RmurqjPAx1GY76XCQbLEe8A0lNkakBtHSz754M9BGcBcdFSdiMKQsiaw=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
