apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAO8swTBHqRbfhcrFO7otQe5tyW7pbWKvxQj6dGl3IYiLoMg77Q5PmsyNtLD/xHqx0csqSHT70enTnfKuzNt7Ot+OR1DdzQadEiJXOpZqK/B7JRo7qeTjpK04CkQL5/TNXSK5QNuCIaoTKtxqOoDhenxk9bT/PlPCT3yVJjmbBt5xODlQGEPn3DrQ0jRIoua3NixMbkIVuDF2FN6JvH3/QolA1tKdk9dQu1JplxmcBVDLxoRCX4Y5QEcih03tnKiYfQ4kirqh3/pBqzwHDOTqb3V4bYek53BW3QklIk1m6ytfeo/qRe0gcP1UtoHx8bN175BefrZ9u9n/BD95Y8aJlmlYK5O6u+szZOyyTt/r1rccxAjknN2n8dnVKvB1SaPVih+RHmOjJs+Oo1Su/uWDKU4pCuJH+SAd0igmupWUU+yzsDi90/TXcdxZHXQ7Jk6cr0bSez8myxOj12Nlr6YAhKmMY5SocsCcRfVuKbDSEXfJnX0GUt7qL354x9F7ZpbwvyOY9d/CdQQXFoNOM0lnSBJvPHyA7BKoloYPddFVt4VAYTr7G2RptTq7V4pT2rMiRQZ0AP9OHbyYyWEqpFWWVEl8RcvFQyxQNusO1Kev+jR+vFizDPhkD7xUhQfrhuHdzR2z8qmGw4ffIyrIp+JPZaV3BR+uM3+Ex9c8viiIYUJh6LJe8W6oXy9GBc8o5oKEHwSiHBwFp6cbxALg8p4D19lb86jGweuaRUP4urRFsxzYDxnPzL68OUpvyXQqJ7iUTyO18Pxf4sWxXxdeMY5uJMaZ+NnFNzbvWV/JYsb5hpLXk8Urq8wrv5dFcssSudprImbisQhlBYSYLOCgZ7CWyKg6Pku6dMj5BbIjhhG0hOcq26IK9Y/GKfNOvMElBXqKq+tg6ofplnq3WrnMLNxqkc2o/dhwtCRPIAO7q+YWT3rhUPyGrTmfHLPXS3f+yu2iw=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
