apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA4eqqAdxqjCm5fQv0VVFES+2HArsXF+KxbYEAwXtOZ8YeXot3EBMxEnbJ9shl5JQnDN3TjneFACB00O7KzjOdH3nX/3E/xz00l8WQ60wPIh5WiJq5+i8D/2O8LVmitThZgHTwTtSORu4yfwxqlwrdBOR1DOemQPs/hXn6A7QI4zD88QwgJw/eIG6XYGEI6eBhwUy5YU3fPNoW6MlD0xyPOLduIvCBGd9YVYy9nvM9TCokHagDnGSBMENVMvhIzzUJ7uHpS6LLrYBxTHF0paRL96twXWwvTVVKzMBVLCV7vXvsVcGIhbAIZw8Fstg1pbicwT/0uhPLoUBifY63vZObV6bBNVqzPSi9W7aJIH8O2QJ3wSzxPFdf3rNxfSrbu91O0Q/bvGf331xavP2BTvQ0Fm+C72i00dJdr51z95gPW+OdmIr9tNYoRW0/uIA4dwbhTvRaLMYKtgFUGTDrgeHsw6Ldb2fIQ18DIHHHjGjoY5xe2wyS6QhPLYbY2NIV/q75cY5luobZMn/AP9AYhv/mi9URTmlVpgFWxZSYUGCU263jRT+7voyBo5RbnSoFv3llijd0Wa/hMOTjb7CAuMLGvnBdGRHdvAgxksM0wO44LLk6+vRxsn1CF0boYZm7vgULtpSNt9Y/Cs7a3fvd+CqLjQ7NW+xkDQuBn9qZjBSqim2J+nlOQc/zO+ecmcj4basGsBUyIvTcNbAVBLM/FynPgduGqUwrq4ESGdljhYNPEFDxfKHtF1bF7ebMp//iL9TNGJ+NIJ44c2QEs2MxsaJdt/M3yyviP8Zhqk+axg/ihqaHVs4Mb7uIBECCU0KjP56y4UCIWjiebg13xfHAZ0YbZtXgzOVaKo4VVeT0dWAKZ+7w9omatHY6kAsuaFjCuM/RE475ZfAh2DP86mLV8YrXNmgz+Fxdc3HUy5fqkVVizfSc16faoH88SiGKMaUoBnGs=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
