apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBbXWt4Qk4ez9em4PIwezKT2CmNZJbjA4BPM7onh29NjTuu1s3iCp01s4bhZ6ZgxRgQGTndOG1CiE2WEQmZlaEdBA769DvugubiQf6kIXd92ZV48nPo1//Gz34IQM95rrhEwyJ+qDnhlUHyUuqABYranzukw/qe4/O7AvfjUFr+C0ZZ582RueZEdhIXcc1k2Pdxtq4aDZ5dhEtpmvS7q1aToNEkTgnqFPE36Y0zVDRt4bGckO1+EQDWOj0KkjC92LoLuS9Id65wnZRdYxuF9HqEc6rddGakeqJEImVoStyJWU2CVSHpEYu237MiRVEF8hbqhz6ArxyT0IKbT6RR5ZT/S48YNOVpL8dAZaM6/z4XYmEwzZqsg7NVR+R9xirdjEN1GSHfuX4WRxTbJmEtrrwzn4QnkWWrYdT/6z/tG9D4G0GHeUk4qH8GyLZaRGNK9UUo1/7au82isDI2IkkkHfuFVMV394JQx6TkvbYAyCyJ4lc6hbpWzcnETh78oPyLThZU/9pRqSek6+0ntii2GCThUKyMCs8K+dmWVl1eiDiZfD0Sv3Nl6Rom5BjpCMABYsblK8cF87oUS9WCoOMu6OtcOBVmmC8KZmsZW70gKBlTEO6VQ4lxXT6HoU689JNwXSZPZuR5bMSzAjtnW+8NORCnvS0gw+OtQPk4gsa27b84ylDNOepu037wOVyNFJAsy9cOsD0LjIGB4sOMs8gJn3mlclBUw1aYU3WfKEgEO/45eDT0Wqiwlho6yKU/FhqrNOlc7O8pQWP3UrFcwglESVAAUHX+1Sxgw/OwO3s0Yz47v423Pu4StedYsVR+1tBNG+eDWz3PMfZAu/dzmcEnFS1ASuiafAMRSxbJDoRTK3hyeU29zR/nJz6Kd1pT2neYdvAbXT9u/+v/vfTMh5PIGW2OtFC8VyMLqlTKtv2COXBm/xBKaxm/y5D7boN6tIz/IOc=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
