apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCTXJNOqynAOkvZmlv4kVkPoqWzoz03DiK8eiVuyaaYqYiCCza4yLkCPWT/iID2JTc5wLcPi2bY9JNM9CXp+wKyO7nE6zxxTgAYVAlFVTQWWUGay73Snb1GsqZRp0/bpDBOabnyj6BKZPNfEER7s5UUbhph7QJhhG2fF77V4uw2gw6Lk3xklTOgVTxTk1MaPiKQqNavgOIVvUacNhWZB6cjTLFeVvh+NkXnrTj3ySJi2kyNCyJkXVw3AQ+4Sdr5P8ATHj5SgWR2jcUrVSDdInjyYFcJQpKzvVjMIJDmr8Vjd0Er4en6YeUQ0Alx4HV56TI70gHY6M0WNegDaY/e4HEjKbquQ2VNQDf4dfJKQchdOaErgT2uKhk63q7cVKTtcmCq2Wk1j/B0EEQSAzqBUbCnXr+Cpjvc5zkibLTc6nrPBJNQsT27pVJbhAhWnRBF2287nkHH+D/YE6GRxe/ucSHq706YrTxDzdtTowOwqLcrXm8pmXNGAjRWI9NtoTjBanYk/2to9WKkyXAKry7lWE5t0oKuruRrv0hLhYPZCOglm4mw19ZntLS+RGPNgzP6oM4A2VgeDBi2jZ083+KQYFgurW/rLGaCdNXxCD6UeeMlpDH3S5Agjb+/fMtSEC1aSFoyxasBqXIOE3YbM7zlSyyFP2A1w5PGq5rvkC1vJeVUMDI63qi2CBwLN2gkmLzWPrWTChCBmk8Z+lplcp+DvarTwtbuaXsb6TFBfJ4QkqHlXOeQ3UhL6jX5v9yjevOnA7QIZVYrrKARyyjUE4+hCRmT4/8s9Mt/5Thvcd2lIDtgqUL8pLysMggZihEb5RunhNWMVCgEwkeQUvCUkuhWwBYTSrBQb/VKI04O49A2edEohnMQ9X2U1sD6PheXnUQTYKCj1ucH2K7uo7uGlqH7sMC0/9zMajtrMdvh6ae0NrXJ4P4dofPHYomKxden6e6DztM=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
