apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCDfKYx/UWb2/3AI4t+eLa1BUrYP3eT5UdUY3pCOJQ4K+k8GRIzL1uOUyaH9mVS0RG4kgZ35bgXW2JFQ0w2MBamClPGD9W7R46xShFw2V6tGJFQlg6XfsDoPbfKEaVxSr6fvQH/keQXgu1JpGjBwcCr82EL6arcBhXfsJySjjwUdLwq3akvVqbUFk0lKhPAuqJQvkO1H4Q9D9YjGSNN4ZqQYk50uehU2m9BRmBPCu6jcvUmfBMlgdUGVgV7DWJllsxTdHvqml4n20PvzTayv9VN294fwhSlwQ+trCf+WmDFdHgwp/MlKtKPfviWUSlzoFaFGvv7PdGMSVUUh2Xvv5AZcJc11RcarfWcP3ZG9K4U2ttyb4HLtQcCGcc50w2SCpcuHu/TAib1T3Gu0J1WmuwbvstBS1ZbwyRr+VhmkFgv78wdAXq8Iduy/R2VnmLJN57x6z1dOvSbbRE5UmqkSMH1qleYbKnNeCPYq43WPqJdCH6q1Ez8Bz6PxMGFE3G0EBM9CssZ9kAZvIbck5nqmwdvFrZd4hblRcTF2dS5f5ve6eiGF3SZ53oWElHS/875PW1vimqT9ruz6KtEzBCDsZoEeeCBn8VhiiAFvLkrcPAqUMWT7nNn1eo88o5GslIkvDLZbInwveQwfgUUzHD8r8095clzc5H/owmRWAFwxl59SnMszTSQ5c5LAqZBh4LEBwzEts+LMT4Dg0/7Bg1C65hKCp8gTiP12Ml9r+qKGJMgfQYCNQWo3xCHtpyCXEf+CnMOLMsrCoQO+AZ7bEMYZ/dZ+k+QaUAE0GroBf5Sw8IeSdqvqp1zGGlWXLEtMBEPJlA0suOpqqkK825RXgrUGk8n8N0nqYaLZTxq73JAnr7NPV+C/DE8ragzFi1RqOXOvUxuCSaPiOT6E8x4lnjZ4nWOUSdEQIg6TPEInZE6fd18DWonJ+HWnHs0ZQL0g/bBLTo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
