apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgDIemPn4TvRPoPYIlBme2Ov+/HVtvYN6Ya6r8UK6eJB1bLli6T5/Swnmh7a925MZk5cvEJfGB6vU5pDmIaAcUaqzk7MrbsHmTBWyo28NC9vT0bxXVfKGTa3fR7DIOhUUL6x78UPFvHVn4hSoY8ZRRsJvF/kFeypoVvpjrvLbZ4ChgDKk4tixCZ17wLr7YLSQvncT91y+Br/cNRVO1a8LsZ2K3Cd1h4WDdR3YKdcol1pVgjgZoLkrb1yEpHVhvYoJOjC6TH1Kx02MB5v4naHRbUqBkxt3l5m7kL9VPum22aIhUpKuPLsgbNsp8wLfBCP34c7eIP44HLrTE2+prMg701Ag8yJxH6kVtepz4VtXMyJdqqjYnksTruy92xNGgdo5bsWBf6LBAFDeLj67GrRkgJAzg/T3SLDE6NsrFzFaltxADQICUqYPHRCj5YRlW8svRSk6idJJMfcNQ0GJjURSaZHOlf4dZgYy3NoKPqpGwFiUjm5h6OCk56G776YNZ29/bcFtWjjXxg9z0Ia5C3GL1RUgYZknZiHxRU2/cAdfs3EBMIkoLiB93g1UDcXvzvlknE9hTHHvSOXhuTzWh0/vbHXSl7El+cLwkUUE8Kq1PwzFt1xy8zljUXGo0NkomuzXbES9if0yttomQ6w85Zjl6Q+cfrkeVufxZdRg+QF27o0BfbRM1DVBvO9HjkUl4V5m4bZC5QOi3t3FkxrM4mgRcH8eHkGkd3l8xHXG8uxcYw1dnL7hkCv5PMnUhiJo4Q5zE7iQohPs3LsGPTIGvZxERDpqljWCTxWogoS2yrDXBlw9m16LxdQcxBVTTKw3KEZVvF7tuN9Lt6NNnGwbdUTmVUo/b2W6/ExflC3wbA/1D3QsU4sy7AkeFNksw6tE8sINKBQ6JHieO7dK7eMHBKlZON/RQ1h+RG7EQ5nZWYSlMHdp3jQgZ/A3FRGuue2hg5igkQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
