apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA+bcMz84uW5OAMPX38jmjFtc8QyXlQO8PgjzTAZtKaLTJJQMY6ZjzBvS3Zx89v0IAlW5eW/rNkonP1YRrxW5ZLvVaavWxZHTHAAsUnCH1eQV0gFTO6gSPL8Jhezp7O4gH0rDnoZ2oncPcocFWZR5U5FIBT6lxaMDAPMyTFT/7q5XE1wPyuG0N2esKEiKe5OsYe0FVLmh/ix6uzm23Tom+Tteo3JJtHNlIyNT7Xjl+C70UxJVJeoxkQ6KcZU6JcD1N1ENJxoEBfmxthHiYjrFDGA9uhCU2hXfpMRGHKoRLeAaJAkJCh2HhhFM/CzVLCzeK7aPwYp33tICGa619hQqW2y3Ao+vMKr/UTP+/pYqX4SaTbKxIPB7czEU43J0RtZHnfwd2wKlYuxJ/s5CCWhWq2cWD92mfvxJl511jI7d8YSeouTmSyMN9QxGofHXL0af8j0BTx9M9RMH1IR3U2afTFn79lnbYuWZBw3iml4vaIOB1HK5omettgKsKuRFYtPqitV5o4Y864EIwpWxhtgXt53bNU7WFmDwW4CJunhnPP9Gpsi7mpfxDTQiN+wWbgWfsQqbEhIIqcgtM2hhi2qWbA8jHT+iL8XTr0nVNNqcAtCofrMueTWISueW+BcZpkOw0ctaOF4AhaRNcFTWSFJE3Eebo5bUTKlSFMmM25zgP97MheWgcsRfGQtc31tVePmitmVqPDvlD2WHpn79K0Lr9sGzj28aVa9F3ZmP1A0OUGZvfZzn9fTl6YoftUaEe/4rbUtP5FyIjlNImqnyqyj96jXZN7gxTbVCuT/tdnuuUW7GFYZ3Pvh2cdeAHrtjbO3XBu4K3pwa2G9c6paTcjQ2Z0eLgZSjIp4w05uBKOIHXr7xc9am4e//iiz1SUiIiwnlJyRufKeBiVNYwBVZ5bHn3xiuWkle7adwuRkixYB7MAiuy0wAa9bZNqadHH1NBVKCQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
