apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCbFJQhwiGvyrnzKQYa5NDAolHWqSH6DPyjAMwqXTln0N2oAKuvmtYkT7BHfy/ordIQzsf4N6rxm2KjaajjXgnmAzRAyn20iMWvzEvObzNb+NiHeu/dAgFkw/HLFdfm7iKXPtwCBc4JVZh9FjtILCuPB1BDQQawiQ/2SRcpnXtob5vxF9lzm0l7+xMaMhEPfIlEXUEJgDql7hdMe5gpzsQyMfZWVT7cgTDrbbnIX4uSdvAXRJcA3TX1ZQ3NZ/WbSp9/ElFBlfop8J2aHb7ctaPfhC9twdC4BxA/0aYdlyjeR52mhuxsUVfbCCiikK/8Go0KH/8SdAu8fnvEeHLlqNFBlattAjY+wrlgbdKCOZxz0TOjy0zfm+3dymUTOy57+/tBblDWKjUBGLQju2D8J89I+J7fvj8uCuO9sNTBl/g1dNkqb1iyOYx8xeF3QgBqf80xclfK7ZSXLZpf+s/hIaTwJ4ZOSU2Di6JgHLNzr5fbJus77bi0pZh3X9SmGOsm9UyilCHfwbdKyCqIBMlbHXi4Wy9DlM+oCXVhuCe0EbbMqo5mVhThJwaxwuxT52qACb/RCBLyPcs171M7+0IvoWzuP6RHvNS/lOnifj3PNgwrfLXFCaE8vGXrjExaK8Y7HlVjkUkMwnDyPANc3KP7v3exdQP5eZO1B2Id6/j5/+mumCg12JX7XYMckf9x1LvbftuoYF3Kiq4qowGLyo7fUxwto7lF8Br+nIl2lnJGs+n2iR5bGazUtk+8UjFBmyH7FqJl801cUhWGkwmWYTMuynN6Swg823b6Gfakyw3LNPlMEXxfqKjJRkCgqsYBZgOJeFN4nu1Eb7OybDyT/VSbnOilw0UI7dpdOmAaKFWApMToZkMXHHklXvS7po5ZektdXO8T+mHLTdYe5DcoqMyw6yQgAfBwenxj/Oj6iY7d2XW5wh6Sf170imQVEj85SJmjVMg=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
