apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBw1ymwIchW0XWglGnbZqmRyD+5wAkKfwgTLgVQkUAScEvw2Uxq55y1C9jdZRvlO4eSPjrWa5EfWrM57O3hjS+vaGHRqz+uzG5E7+KENzIGUrq+kUuKcByeCMZ/3A3NiiAKDKY0q0gDCnUjaFg1+Xh2s9HA+RXBNNsVB55yV6GJ2ogrmXnZ1a6DBwJvMQTdXd7l9FvyICTxRq1LeE4sm6mMzSpZUHAVJA1/UYI5/lUoGXsqMmgOI+tGNMj/H+AQ8AQLky/pVZeGb4RHNsks4IZJMgFrcnbCU4TqGBeUw9XNV9WekPziy1S++EPcU17q6jVAhC0BJtG57+5ExTOzMGdHZqd+rHv7e3OqmfEG3SJf1Cgf5Bm2cD+c/RGCLcdeMOJE1r/Bi05L22Vn9/6J1Ed5bv9AD1NvcukhwuZbfv0Josfuhi4HXS9U86o1UqEx5YITOO0NXjFJwQOfuRkza1Rgwu3ycH6IxQL9s309eq99gEKbldfKQGL4zYiia/1PgC/OsUFDOrxvOiYu/TD8URdmmxjGV/UjwU9+Gq0XQNtZxa3PhyFXn0eEPhhxia3uXprPNF/uoNZnuBTsvDQ+OzQ/V2tJnnup3OyOQ7CIv5FivrNohoJ8n0cxfh5wEyRr2WAoo8B399/S4TUOF+koLqAhapamBKXUz0Ck8OBUCXIb+SX6W6cZPEifF767uhgeg0rlRGuf+8G2rMPCDhIeCjltbHp+qq4HMp1Ttw+4vBoQMmSqwLvLhxBW9x8wuHUDF1aCuC6vFNaxKVUGFVI5PEoV0llJkbSOyMHfWvSNamUIPJi7wsD6hMNhHACgYKiKSO4E7SfEtCsc5wOG7bBF2jsUxP5bS1mY7xDE0SA6vBlPNFWVSKoDpQyLof0jY6Hm2at4OsxrYY303WIkXtgYtRPIYy6EhY8TofUMDvVmWcoxvlCoNJoO9VMHNvcTsW/LOok=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
