apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAZhNDUa4h08roF2mSnaa05W0AgFtlM8wLhL5YM4VR5w5t1yVphjVuyAfS/v493ahNymBX1uCPjBlQT1W91rceIDO0ARI3QHjPCP3ZApP9Tjg/SmMJ/lQO5IyHl3K1cv86rle4SwOBoLAREIJTT20jCcwwZTJJ2T3kdGSTdZx+IfK8dBpJlfJHJMwrMDUPzoBBB3Z+c6jEMsM/DpjVNt5qfNHaqd5RMk7VUsoHH8ivktEut8sNAV1erVSqobjdejKoC1AOp2bzLtSgHwtDI+kRjEL0Ny/vs11c5Psj/W5+NPjH4gXZL7zgJwxquJC/zM1fKqqn7lUeLEbq5F5eb1MWO+epC0OZxtNDJ0+A9GxWXe9hG78b8i4onvVkKtDNhXFxyMmDoEBLZMakGwhdiU90wxg/8wjwzbOuTPQnE/Li7IGkc48zynk2WpocSE7EAaJeFRjH98xoYm4QiZGXmnd7VmfUgDsLuztUDHBSHtBFVxOu9MXnj/OWnX7da3pFR1kMsdp/w3CoFa66/Bg/W461QgQ3wp2OrB8Do6rjvfD/DqpqtXaP+T1Dhoa7hGvXqw0BIJcqYAaKmBdZDEzRZLvRz4meJvs/rppzWbpukNOo3UaMTmonHqh67GqcfHeh89wGCFwShrQKUPprAKm7HLibiyYAynIvNtKv7lNdpbj8ZnAbNeGMgKnbmda5fBQ6512mmByuxGh35U4EUnX/gcycqbbmmUqabb3/no7O1lgDTKQGz9CjqzANvCzyc6Pe35DCNQgtpRf5w76+QKrQz6/uK6SlL1TZiBXihWlbwZBEZl5fNXnHuhHV38LO0CT3pKg+aK3EVUz79ZOVnHFeUdagxpZ1rzVa9g/yKtErrfohchZwDDXDpAK/uPOfb5VGbJN1l0Cc97t6xu4CYJlV3Efrz492qNvXVPFh82Jb5nnUP13TOLvzgTsWuQNi0dhFMv5Q=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
