apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgB83wTBN5QzqT3iFTXLtINMBxSiFSXI7vC/fNJDlloiZIDaViBJ39EgkJv+0faf0EWRYEmY9riYzWZvPT1rNXN7xZ6TXO/qSeG65FxzyqBMLf3n8IrPAxdOytNPxvC9zRTlRT8QEth7ZrwbYEHAObUUJE33WvTUQIPYW4rPSrcsRSyM1s3WIcC9uxfOguRAwbpIYwbiPw9YdYeZCHx1qBbLpsV2XSZA2aTmAKrbuxF/kjAx8x/qyideEP9GOJJDMRcvq4iki37qNq7RBjVLQXWUh/mS7Wq+81eAGTPirIRglxxyBTm+QFErHnoXWJhrG4jf4InRHbnk/Mi5xzaFjg0Qo23ZSA3puV64P5juV+sjavmgrFK1MfE7BuP6Ld5NLPYrTiO+KlK95jr5Qwi0C89F3/ZbIaM8LuAH2X1Y351TSpBZrGOwPGuxzEgZKuqsFs0UzX9z1UUJwBZrBfCYil01WBmicnRIllnYtpV6aopFCBayw9hFHAi35MW8PdN3VTb4a9RO4EL4QwM7o+s1dWVPvEq7S0KpdAxj2T+TzK7ATqDSTrhjdY7UQ2/ltOeqqUMlCl4mEpMK3ZWk93NrhJKN2AG6OhTZsGqVRzCorsUiLzwc1+leXkCG3HcSJ9wd9nDtgm1z7bMQZz0qNODt5P7lnxxC2dwsiAoI7rTeTGKEY3v5PDfaun8fxbyA4nQzE5TyGoEbvIvLRLM0sparODnvNJhS08a9myj+SKTUvzLZsz/39UCVhgvW/AiGE4kzVsO8TQQVvTHqJjORcs1zLFj4JxEBiNfNBO1XC4huK1xgwS1C4MENJobojD+sfdsgYTd2ZY1v6rK6VeEeC2XULArUBuODu8Fku4STgLEkZO+1Z1nxFasamcYMzBJqgJFIdGi3+9roXSOc6zTpNpbMnISRhGkI3OWkVRjLAyakyXByi2VT7etI7VIQ2WHlzOQUbtk=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
