apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBFi54ct16JN39VzVt0uOUtXsXtxSjTrOLHt8aai3Ys/eHB4M60MEh6w+PnDfKYHtQsS3tSZAxlO7+XS/VWShhI10ocrYnbXsYiAo7V/0XDcwbVTpDQi0CocHjb4ELiMxnuR2mzOvobmAZEOH2kOFlvyiEB2C/4iYV7/84p4fA0x1LBHtg1j0r/YzsYSV2ceP90VhorRBFTEsKPe4rEivMT2cNAZ999hYTRHO/6J/qhv3D3zc1Bgky9LruCB+oHMWzxsdQCPMAc9mewtf/fYd9Sigx91875H0SEOGSQXg3KE2l7t8LP1IJIrEqBJHNn4faKrLUPIWVs3trSRzRAHrRbWsnnZLQYgdg5Vnbx2LMWZV97KLLvJ5H9WUlr8wK9S1LjqvGBpJVUPpBwQ7RyxAw67evnZz/wFcgkesD1LfDkBpZP6qi27IdUC/q4HtSHZ7BBPMzivmZQ7wSVuWsWADqnzYICz3jLIivnimuaJ8SD6qmGseG6HkUDeyrikvKrATjI3YLmi4YIxc+ERlMnzeMB2b1SM0ZQWCE5jDaz1OGhG9s67w74gjnnqYwekrl9IhdibLZYzZE/GWl0G1mdLNo79eEiTjh+Cjt1g3FoOuXsdU3pWLpdSIOBUXjRuI3xObIXz6/fUhP2vreCZ7piPkW47BzDtgH52X1g8qy7LC5Jiz1lh1stOSvUD+Ieu9lcSau3/YygfTuiA4fwVCJcdtPExWxizHz2/6bYJCSul07A/qkX+845PjUtpRAavJz5tsIEsLjAGdzf5zGPxXCxFEpb4UD9a650OssdSCsQNT+B9TOFDqxXUuRV7e+kICuZv+xi6tavrJPAGoay4YSZg0y51GJC8tqbueDOqDZj2EKoUCLd3A2tSsGJAFqkK0F6/DD/1enrLMIcqCIueg9s0fxZElvA3ENY4Nwv25Q1Dhiy5oR7KqHEq3VMWRnlWxtnLYE=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
