apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCi1UCKU5oG1KeRcwnqeGUbNChSGBsk31L6ctrWKBnNtbbNOtqxX7xpM/vZDPykcVPr3EdMn6UDrMyOREijc5ELKQUttWdNNTL/YziNC8OeCuzTxJDOi57EWEnxe9S5E0l6GS1alZAecM9cdNjBCeHVDmwjEkUYBqIcZyAejlMPLzCpCaeHw7WFl/V4IbUlW+PWcW/+0+rQ8j5tPEAQtEQZI1lzjeO+TgGSYWL6pIyR+GixCeGjGkWNnzNnMyKfQlwaNmAlndVe86oIFDQYebAFsHAualQ9hNpd9reBYDjwTF8HrXKMXpfB4bQj/OVQRUcldvMJJwwadngYgG/g3qzMvmLNkSuCiZSL3pIcwN2T4xo6kpaAFjan9LwEmcsrVfQ1rbM96NSpdAbmZE7CMhj6nKHA6lk746nIqnQS6msbtrfWO3HFglLC724OIANHF/48jJG62jfu+JaX80kChS60GWW7T7foTU7pjREB4ZxkVKEnQlE4Q9ilHjlPnU4+zwV7tDg58F4um01+dFJeg/pK+45TKBMelbUgFc1qZBbgttGviXE+a/PmVAfiBpoBS+zIx+2dr6qtuqYjQyzAezJ8E0TkFF9kUxvqzSHT208p3O0JUAQC17ipSHMewTKwPRpYS5ZvqykFbJqt3v4rznw4cLEj1c4h0lAd/ejIZU4qgySWzkvXndptZzkK4xr0CDr1DSNlMZOGxTzXLNxzRd4ciUnDVtjJH4yeV+FFD6gTlyacKCaoI/nWr2jqK9d9W/zorDEEUaQDJgvxzVsaBqFT153B6ZMtN7v+wem4KiM8D3O9HTHb9FcJU19z/9KkMoIQBdKH6WbgHuKasD43e8WHBUZ+tPUPry+lOJe1Ru6pV6juApIuovcfEh1+FlucN13ZnpvRulqVYxLiFcS2U0xIpmwgxFtM8WjFUmanLbuMTnQcb1d5j2N7Wp0/z7pbFS8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
