apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBO+ybPqOnqRfZNs7RT4X5FCJOo7zqgxPNPXDHFaNjo1+OzBZ4gh2yZIy2pD74eDWMHhUXsXBb1FW/704WGdtfragM6UR+3rUsewzXLW6U7uurmXO1MkGClCmLRLvymZyD/Iq0RUl2nVRaAVQZzDTggOO7atOx6a8vioufAT0S75+tqFpQrc6gbkvw2EpiWZ/xCIzYU7DsIjKlIV0WfadSxx+06q/PhZe8Kq7BAH8pen6SRz+Jm+VHj6VjIAOZnvBH+vOV970bMlCt7za7G8nAzxsLwVsJBgfuytPJeb+YWTYMFy4fHM8OfMQAkUSpbSxxV76v21eaiTKNagku1PJdbGrj5teRQdIuiP3HswwaqPfApvhov6aUQhjSdMSbfdsM17Up1NYGHeuADNoV6qbZzGUyn9N+/kwFJ/WWiR8Q7t4rT+AEtwBsveWuaZenT9hg2zGS3PbBLjuGXPb+e6O1GnHU+flYWpCGRnepkGj0G7kJ+uIYgrNo+G0PDLRt2rUvz27g48/J2ccePcpZ8FAm70VEW9tOfqs0thQbzibMiGZtK+bUWKz1wi9otjSdNodV/PijlS9yUeTExbFFBSwyfdPiEkpAJNmY2MJ1qVAELuqAjNC7hIZrqRBBNLMrv80auNScVhtQhCUnM9dt8i0knb2n45yxMew3zqjuahAJPH3bU/p1eUN2/zvmJ/ZskCtRkYGj93GkBEqGcaJSpv4ddjgLSvWavd1xDCYJ1QWb8HsGjUE8eNPk2NoODUcENDuE88oq8hON5xTBDRWrYwyrEvoPnyWjGfdgzwWDoTEgezlNonZvpuCmGqnC/Sx7ivZF17E1Vb/FDEdW6CmaNWChunfU/GdFjHg3CMrc4Cf5yceo0cEUSq/TuAhh0pmPtrGq1kEtZK03tUondURGJNjhJrtVixYp2EugP3RUiPEQoVWJGOyz0YFbzujPupDjiajY=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
