apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBETFMva8XjzxpYi5nJylpBRbz4wK/N3EaoCkolMrFwNBdBvDZA0MZy/1AAteFL22fQWz7o1r5sbtwAwq1loc9G3sLcMx81ItVsN6VSwYZsbsKSQTFR85eR295wEAYNp4H2JsR/W5RJ9oQ72SLE2XvyHXA4aotBe4BpKvS2Due8r7l5shg/TY9u2U+tyyCJph5wmk95ghv3yIr324Vvn1+vtdgiBF1LLYw74mXYVEf11WS7o+DR13ASdBxaQIThCib/vIoM3txWyebEqXY8RukbGqHlRL3M+4s+pEl4W15QgKr/4Zls2+tFqGgrQ7kYavBhNe3XFiV3ObokHUomTqJf7PBcMMk57/L3ZFjB+1syxZZuv8cS2e60KDuozscBcr2V4iSQeJIfDQ2e8JRGvk78YDpNY8clumUkXlxFnVfX7irfBZH5CAZtNjJrFguiPy26krLTVeHowoIqb6LkQ2QGEEN7w8JmYYXCEE2HaBkTA75mYTJOc8+lTDX+1pPx6PVqLTQGKpwxCItbFVGGLGjKd9+KU6DhqjSn63WP5Whif+oxp89D/UoUxA5tW4m/E95dQ6ynLrCZqzJHEZ+0jlshtlhUXR8n+ynMmwG4z7VeI0licMe4WFoWf7g6rTUYHfptLeRPxtengS4Gm0+59mMxzbDmoHR3kY0VBTBKRH/hwxvBdOEMis3ePk7i09atEq4N6qVbL5S9tuF8UNU8que2H0ZsnrlrIVMvqUxLMrU2aOWZAzsyKv7QFViVcLcq8v298s3UPZVrN+3SFIa4KTBC5vi45KcGTlpCSrH/TQaAobsQiAcQqBfZFSKBSmqIOacDDk/AHpPXX+KbeRk97p2M0p4kzk7wH7cBPAWikQpjrKkmQ/wV5FwOhTZlRhEgYl1a0bxxcoTLd54dvmEG5W+4u3rY5+7NjnGxATJp6cnivuCWiyjLZg7/kKXIy+JL4hQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
