apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBO7NE0PdVZoihe4J3dRt4BzghPKOeJkSWkUZ7FdEo7GUL0K3mJX/BepbKyU94aO950UtOqhMfxRP26lm2aqxl2h66yqwANawqsqlqsK7pkPvG7BRAKajc2cEMZBOmJ64THRRLbccxBBzxU1Ud1dF84QF/5UcYh3YBGZNcwVuqZmDcIx5Pm/Za2/uhv2IbmS0n9avKtPC52NYfkQ3nGwu1sq8HLKMbTNUcEHm3Okajkke4PEoJaXJlcHz/UbD5kNIwjbQQfWpnnrMJA7nVx0cQCk6ktGm/NjUZC+lVnoNERnErGIhPghy/hwgjVdLZUCpa7kj8M5w3AdaN2zml21wZEZRhc11GesDzXtNV85uKF7HVSU4/VulekdbQMpLoQINoHyDohWIfSV+FJ25MHQZqOSCJV47zaHHGN5Hl31Y4ccYlx/7alLlzc0ZfcIHrjl2QYwbwegfeAXM530SVaHY+pvrca05q155F32jbrxu+RZmJYwG3WYe7CNTow4LpDHCfcRcehdpMTc7AlWush3LDGQnipeNrQCTSLPcrNLUbA1W68vskrvbdAlXVAYFML1474nepoGzXh4fWP1smFGVUU/bRFSqeZCANPTpjvxy9mn7oLsO+p4FyScRLRHG3Xqa0jNJK//HdWu+roInbbWlFS9sEJOKtiC3fBZAQqOlxu6gbuJ0ndsOKXO7ijHEXOqS21GJ5GQsbqgbr0k9sBMgqqNZM3ES7GjxJyEth+WTgUMqjsXpi9KwYzn/KpvPAkY3IZnN/HDpyyqFv6R1HHi3DNRbWjgUulhfwDt+SfqVyx1/EGOJdU+JOPBnOE8aX8Rl0xwML6am2WJ71qRBEC1FZMXb0pQolZXWxy2AbT5EaMALxPyG2L9Uoh3EL0BJt2OK6bNFFeJ8uoYoavj0SksMF0XZhqPiYX6dimsWYVE85dBBolQUiOp/a6oz/+H/IWWoI=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
