apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBO268iDa6TAm/Otb6vr/c0X2963bNum42mZioXp2jqctfDrArsbH9Ehejtinms2AkwuxqwfGB9EBEGsjUVLfWuj+QlIscJlkk9SXa16jp5+9c0SN1KbWAHELvNcG2o0iGZenAyhjjHpBiAfPHQBkStdKtJ8SVwXxi55e3UMtm/biz0Oo0EWl/eIbmLUUMIf2UzATLV6GlpoGgrw9pHzG2ImVzcAwoXpkBQECcYgrexyW4+RoiL4LvMPWu2He47Cpij5urWaMnyc4jsN3jR9V2qFpkVaQuytsViBQinC5pgFvKDlaUipdBYfRGZkky1cCwkw3ENnESb/o5xJswwh5XyNXXjVCql2sCyHYk1xCtqAv9twWc29pK3thVncgvR9ASUBeK+clKfawAQWJTndZY7VuOROgQg6b0w9uQS8cIaAPaCdqODiDlfk40SfYSPP5qb8O8ziPybvYakqdTL9gPYf+2Jue76TkktK8s1USQGyPVd+yIj5Wf5eRZMieJ48+/MWxLz118V1ACjEWtBeI41FRJ/iVG3WIaV51jf2GtracjETG7KP62Ct+Zu+V9yO8yq3ILqcdcDHSvIcdAYNzO4je2oFGQxu0WPn4KaGUFhbNS4GR8qN9YSzTEWPgCrWV0xnSz3RFgHFbGhFwCJ6dSYLZNNvgLmOJe3axmHapVAzh1gzAEaMXBF25O7pXraKHsrkKaAJdTbhE2U9i+oz4Mt4qmbCVuXI16rhCVkdk/H6rnj+mGqGx9eKIroFvqM2a0hBM6Yep6Y8Ww0g5rd7DZ27In5+7UCR3C8AhtloH01czNviwSE9xZMJ56rbpBOKb77twYLOszL2nFKup9h7+lNt3BJXUXkpYJ4XrgaMBHSLJjAfysCmvHZS+hrGkDKSdKGqfmQFPWspEmk03cFFicT6L3YnTwYBWyfIJFR9ex8fp06/wF1Vj8celuQwtatRJ8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
