apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgByoJN8wOBTRUb0D6IGlJ23kQH5hDQ+UfCwwS76GB+wgnvP3eilONAxkHyOcxznrDdXFo6xKsqgSvRk7XT+oAAfBPqW1e6StckcwqBG4SnK6qx7ZzwNQJQrCHl2hmWtBCpjMsNOCIfGmN2CaDy0G4mwjJw1JR/Kizx0gehBIakvz6buIl+azdicekU974moJ31BAxRHIlqejMCIL3aVpNM8POhP30Q9Ep2aaZzrCwce54ObtlHAADJhL2beHDoxFMSOc2pP3EU24uLx+g2g2v1RszUxcMIWz6qc7cbpR+vPVa7YxttBG5bhdDLxA3/Z9oaMB27gzAEgC3KWaFHeMb9mHMd675CeFej3AtVqW7W56/L3+Lpsr/Hjm9RAoY0EAv+odjL4YXpFERoq0AwWkMu/N4DuQ3gmg4c9wUw1krwrK97S3o5+qmqYSSlkPE1F9Dyp2C98ip2NTxqEIkYTDuEx/Mfypqpj5sj0A4uLhyDjiUC7ZsML1ZrHa3fTUsk3fuxtsMsDQednOQF4CXbKBWM9zMVq8GKsmsnvnA73GasaLqak+zByeKWpA3m8C7WFf87kCHT4o9Ub9/sEs6Xzednhy8JPdct7IWvgrAGNbY/WUpMH3+nteCCdZVTfWj8OR7MrXotxWvYMMdf4+8gnEFBV4zh4gE3YxG1C3txbD4epYJI1va5Vu0swgWXAgyLe0G1Yt40=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
