apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAcGKXnCmB79f70SexGzkGd9CW5GOsRppk4LFXuIZZQnjujUuUCRn4f7QHtYBS1wqJyHNZyOUgfr8U2Cp9AVbwrNWur/QZoU5RqN5D0vhdqaq/zLdcucNt6RKR39CqSbD+sw0QKYAkmmbQR96eBS9aclluZps7uVqOW3DlG4zXvLzcsy+vwWZFHreTrP6/i+CnRTpbE6AYofiPPHkBXZ2Y5+jMGvDeWjphzOkukRD4mBhytiwrRzITRU/KCY4TMNtYUeWMH19tneSxphbW+Moc5nscDz+hBCfIjlGoSv5R+I+i22UJLujvh6ueyf0L8DhUdMra30/HbTS8jwgM9tGmaG4Lv4XvY6squkwgwNBrHFgnFUMKWdGhaC1IhMIq+8W6BjhcJi7fMDXtkm8mpkq+jMFoUQRr8+J1HB5yc79PRdi7AzXm3eGm7pNwa91QQF4v3pQN2zfVfI425MQ6BHrbnss35uLHwp3gj7sa+wth8ul7uVuUbjDTzcjVIAYVOummJc8NKarM3JNSWOsKhb89DY2u58wIO8DkY7p34bW74EvckXmcoF4d/H0J8Rm3NOg97lGaKvpXPjtZH0kqTv7uqGc8buYOCr/Ld0/yF4FCcylW5y6GY2R1Dw4IoAijlBKmOM+4AH/CEqnHfEhC5sb5G9VEGUuPnLteEWF8iQaddWHrqxxRV0/z6ROdp43Jm9LvkCKY=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
