apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB5LFZYTRmtYG7ZZm8mI8cpB+TbpR4clxMXGPFuKefhiQ79d9/54aaQeDP1t6ALGWygizG5/hh2dDEgMJh5UWAALLy6HVTkw6zgHHmI/E3lLxpzuAJxaj5mcE99zLfKB1FolrVWfbIxnUlHT3agD3O3/hAlFdiBnwBXZuB+y2lluT3NyevQYAitosUY3L2u84Fnj/M86l54KAE0QdvwTgC/akRjbI/ESTRcXeAPEevIvm6+kflXGLwyaeh/5m37KNB6Ye1sNJNrX3iuFVc9A/u0jEIKP+JGgvvNoos9eEh5DL84uUEWPBUKvyls5MSY9MOMCtcUm8ydxlRjOGOCTQM1iaVz02yuokEaz/3UlRngmFYOjGVMpcpPMDUMaeRHJAIDJvbe2GehBf5agG/yd9ommAAwswCA9+9lmBlw2ElrBmtGTjnleZsSfx8Se+4+JEYkIsn1k8rscuhTkIg6HIcpcD7IOOYi6b/kWMI6AjRVUwWbbdZfEpGkDv3EsJugU9oWhQaMy9UUOD7uE0BKRXuwFFhfDBQJoIR/zvQxeACmH6g38jMR5t1QXFOmY7AALEhcbaEIxk4bc+0EY6CAP3PUHmtfV4KLSZvK3c+iLUYrLoc3WLWdgOMm/XrCWDbg0RpTOaSNrSOHAT5mz59TXo/h2gni8YjwzDP6O79JfOj4rph36C83wDS11CPd1vT8SuNL08Q=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
