apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAYNntPnks/Rba8da/d1bnrDRgQHnhWJlBBZSCGu8lLbKeXw6yhw3NVt2is5nJh3xva6InauzLqxRKepPddiBJ4D3sP6ZdRxIkGaynj77+5DhM3fIEemEwxh30zQBlhz2u8vhnnUqv8QXQKl2PGzNjJ1rmAqMdtRSh39ZYmeWMfZZ/JcyT9gW46Bx52eVuQ0V8UQoDMreQ0r/h6ifTPebWkZetYFVZHxA7rI2hD6ZgFdhO4wcAVyQoNyZyGNktzpjhMpOXGno6dDS7aYQYgXCtuFUGIOtdMV0UNwpdo8CwJh03vJy0yX9+Sqi1PNf1fw9VyuAmCwr0idt9u+IlIwuuts9vRrmQxfv1/jJwt7Zd8EMZyOKc2OjKv/swASfehlCt2fc+E+qT7B/sHY4zagJH7MeUgpHxRAbIIPRei33zYl79gMN8+qSeGX1brV76LCTSCtscQMKPaVs0sxS6TqLiNoCtBWDLIKorwUMUy64w6Uel+JmpjNzTThkH49X+gvGdHs+gpfkGx8Toio1H+FE2HFaENcuDPBtEgCZC8n0r7A1c2spU5RBPhn5wpQ9YJpDCSxSD10Uj6FZvrcitV8dUjh/dHuHo9cuD2k4Bh4MGOs6Fg+sHFonJtKdZb/7FMRvZuMKPCEmEAjgRftVVApKzW0nVaAyuERKh12x1H7/NVGwUENMN9EwqNU5OWq6sumH65rQ0=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
