apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCDd3dAN0cS1NWlze1d9QdBUIeliSi5g+RyGhgKfbPrVvWcL9k9mqqzfI7GXAQfspqbW4XUH0i+HwkHxvvf+kRGoFyb62YGp9glKkaC0PkUf89/lcgO6tnJBaoSbytRlYxv3XW1x/mYZ3gx54vDAGJu2Un+CoG3mpY2vS1h4AKyoBereqoQNIrHceL5ptb9SpG2oGNmA7vtWl7o8uA2T8p27UZkSROKTPccyVJsU78nqGlHFg6b4IxQmgARjjAl2biok51WgzCh3f16KZEmnmdD7mdLtdkB8OqiOHFD6Tma7ZxziYdcmocaAAPFrj0SSjzhkYozS4Q3WjPhUF1uRo5YWIOG+9/QKoQwrCVnAj2ZbKJYqXZE42KIs8S+KtBBcoqfOMgfwAuuNDGwdM/V6rL+IkRDAtXUY8wnxtPfDYN5+SlxM5Xbs6rDZMwuQShcas6qYBsSI3C9/0UCfkhwd0qRm8W0mslFNgQIIPS3hwpOH5nBIda7qWEb/XssS9FcnF9XwLD4jQvAY7/1Wf6trj4gCvPynVA9NwCNsPrrK0E5m1Q9pnkYHdOFbRhCkiqwFoAMGkIKTtUrcPxp9EDwunMcrwrf+fwwj8XKOTXuj0ELRH/1YxFeFoll1UDTHP0GE2Oc84KDZuOz9F5xZcwkGpYaLORei3ZziAxQGCtWEKTLMf6lREw5CGkyIhkbkcyAFSesjE4=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
