apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBixIgwYIzKhgCpsqY96byMfhpnvgyFjmDdWYjmyQDHXk1wp+5pP9tj6w1+1tdhVfaTIclzJLe+MG/jCBXAa5tvPB/Un2WvatX18fdZwtGYrohPTDzgYKEuJm3fKW5rAgPEdu+6sR5L40d4iC/v/cL+8RmX8FwzXW0zRMPlz3bf9320gLA5SJdaOP0KP6CMXSGMI4mlGBe0OBldJmxrEXc9G0/rBQrGeL9bQSNN2ywsyDmULQYz3ef3gumVaXJNAjW6d0O0Cy3E+OJy3rzuL2GyrZlzYlq/R65VJQYPtetkh7cWd3URSnIbvMXJ/GgxkwMl5vlf0QWQvYupWXtU8MVcP5+PdPk22o8TiMDSVrNMpqcfsIWAi7yrWrKn9KlHRKWd3ycth7696wKi+NnrhcuXAUmR3hlKg1W9Df03Ce2Mpa3sqhGujrdNvHkn2DxtqznQo8EwhNaDf6r6w//D5rCYOKLHensJVPKRcRjedX3OwcpbNP6qr6ltWx3zlXMO5hZtayzi7Xta1xqrJj3c97vJbsx29CkF8wd2o6Mv5rce7mv5lihgAeSWahQOYZzAZL7utik124jKhGUBJXkWLcFOKwEEKhijJhYVVD6wmy+svG+Iu3jFUmu8qn4C4ZYuTSx8v4QxfatT30LFrx47Aqs+oc8tt++9/XSOKsM0UdHDOMS5iwBF/pQzylvw3Iqbgm1slv8=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
