apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC1bOPEKHfRImEg+EwP9wioBRaoWJPx2sdaPm7JVM9wzWSmSihYsrsgNxbQzQnPCSFoItJRmYBaboRXywh50SdC7er5d10wYzGbpulCfQgEEZHBjenTWpuH07o6xeuzYzQAXIv2VoVlPmaJqQJWM3cTLgA/x6MFP7eLijHFdh5h6pYLsoaB1/byOceXQmIqyQGjdOOLvCgAwwORMD6VR4+0J4a926+xtLNICWzCqNq3KvSnVpodtSkPV8sLyIkPvsAShrppakTPLzjfQHMu/KVe4C9aJnChZ2WnHhkcUwBcx5QRwlwiFdWDo+EcgWKwLUF63GJ4Q/9WTH2E2GK3iDVjkkbVxRph2ISgoQNmsskkoGM/DENO/r6b+BZOycwZvGBGW+5gd08R6DyS6GJbOQGSK9F+LgyVpX2nkwM86x/x97F3mKnqEmSDIVmlUoEw+JDKtwNIIhs8uwCmuA42mhjgbrhd/dfU0HmYvnvN5AhSwlccDx7a4uLc4vZEB+bbcDS1OwbPJbrrh/keX32PEGZ88NmL94cW1JpWhbD+herVn8iN00OPtB6c0RHi9V2mJafgAycs2/Xg1eyOiDNui+3od2gGXNsLiTNWZb+xvq8E2t2EZd9HgYfi3OnIbFFQz0EJK4dshQSvC1NDFFRZbld/lgwKdZQ+8xxveWKTooLoFTnIymWoj3u3a5CKCaZhslhU/5Q=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
