apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC7olP9xwwwBcZYxLShv6Gt4m/dVjEz3qnl3E3D8VKfVOx/jDFTgToDS1/AhG8snY66nYrm/hZ/ZUUN2iWo/Ss23WMBNoKX78j3imGnWBkwiv1E+n+Yx8N3r/GZL1Y4WRGdMKRsNl/eKdBXZ6lek5FlyU9CPXN6Xz7AYff12BVjvZ98oSy4TNfjGa5vKSJ5MeLGIH8vp90P6EvU9DDTbOahRd4Gijk82vtsCUmUWdZWO1wf4tENIlHzUbYgWolkwd6l4iS7mBo1KMP8jxufRuHKih+XD8n3qe00nLa/q/oqlk11H8BSPv7y9bySW2R3EmnyaSKzSRJrbMJB83sZhT1wIIeFx63CReOnPfP8gQqnRrAaqgu3byQauCS0NDxg5GEokAadRPSdIRqFI6EQowDfeoLZdXCfBgJzDdRZ/A3xYIsma3jhHJHwYSdDJuw7CbBHd9hFzh/8qtje0SqRZD7HV0iTf8y1bNLdUsDw0a05PkUIENlXkwBNUuTRf1V60qWmNfYBNe6MXP4KMCeMDHwjdC4t5vWWB5W5m+Mt2nwOITF4ZtOBHJzldnRXkY4NnCcIcIE/4OUEuITIHTnOEwubceEtETvmCSVD9iOVi587drlKiE9bw2WBRZCif50JxUePgOKHeSFwN8rNzwhV+myzXzKbIAxeiRAucEEXWMwIL2ZFHz/IDYRTU+gRD/8wUbrth14=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
