apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBkNiZe9lDI7YkW3CpBpfV3XeiTstMz1txYdk6mEGqosGEWCQ4nC4xb8F647qkBFUTNmJcd3ubx+pVGgcN2RSQfzWrgkyxwn7MfF2Rkif2e0T729Gurkhx2s21em8K3MOAE8scelROLe+zndUSK2+ilP8AewN1DybceeZxL5yG4BW0veNl+bN9mO2sHJR+slDpHp1iBC2sPFHUatziIHuenD6ioGuzVBgAfB6+ASv+9GIKxi3CRqesEQh4eQzPf5slHfmvHWLZ4wU3ohCvsGimEZdCxUZ9LNQHdmOJhy4mmrq9dBJxHaJYw0pr84DRShz7QCGybiQn5PrF+ZggdF0Wtk6S+XiVcD2p7U+VC4Ksi/GV8iERSP6cE0JXjoLpe4cJovJpKCo+54/vxF0+R7FBIYw3/njYfpb5FlH0b7wStEhYRnG9w8788gk5TXCEuxNZyKhFS3dwWKElxAIYOwdEZ1dhAKBIptz0QOaW9/8zMp9HUxScJJY0pyzXepVnMINkBlDXaZkLJe8HM++hNMhxEiLN0vXo95rQXlt8ZPk/ycwXmTevt8u8UFdTM7e8QRoL+6RsU+Qr9LA8cgHjKt9B/Uw7KugC2H+pq5IJWSHPdeKjCfMIXPVYZtGkgVtVfVcaLakPlk3l5h18CxEWEo119LhrfDniCOvWIzXO0fZcha9ZKWMZ567gva5sxQxWsLmOnD2Q=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
