apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBlmJsPOa9jVM6RIRfc4EHUuCVG7EDaYyF6LoUmg+q6Gn5qsaaxdKqu9tmYnD4l3E/TsKZbb7Gh08LxFe/B1hjCIG2vKN0DdCFhHO+4plkrfxLT1vc1RUE+RvuwPi98OO/ziAK52ueNxoxf3yjh8eGT0IV8P33rI7KCwMOA9AvH56uuJ83HyazRnJwYGUZuDkk5cmu0llvIAcJbiuV7n3byUJ+UlnegLoNUzOKZ1/kYzZyyUupq7IDH5jpcYxfc8O21XYQeaEDAn8Q8olmWyRfKdjaWrrYK9C2qKWlSJzQYGmxyc6dn/NZSNwgT8Or5EFl+wZRuziUnq17uYF3/wKlH+3F6rOoqqzPJCDyElT/qqHKdU+PFzqCf5b0k45lcILANMkzjnwciqNRJMs9yYqMo0VLU9QwMxOzLo2/k4bO2bH15cIqwE9DUbWHlt050yVqWmwA4RUp11IMZOB5dmRepCHDlWlaIh46DnKxUke6c0nfl0HSGZjVOG2V+ZqFC8EdQFQCBFknyxhr9o5SKXhOBlR33ElShYAzpi1nwOmb6lyxLTspJhyH7tI3YiNkxyD8fy9jHUK8xD5Na9dlTM2r1JG9+XNfMl931JU4r1vmx0+WP6VVjXi6tmv1dgCneLjxW0p6Ljb4aOalq0T2J61ftFYe3ek/MZ4xFRjcF6fDERRMg2g6BDg3rJZ3uok7oHPr4rC0=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
