apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBjJKI8qkwk3dE7ecNINVY4o1SX8dt/dNFfMwDD6tA8JSrdSK4bWwyEaUtXWfRxRLsdcuHwDvFy1FPznWvWP6HG7FOVWLSFKkVJgVGT+O9r2yrVz6KWjcjVK21Bvalg5KB3Pvm95hreR21aR+dyYtOV5uJjnPfHKHqEDF6/I92xu6gHUqdjIFKdO1trX9ii/LmQkwVEtqDkApNlOlyPiSTtioudAdnfTM7XSw6+L1A+D5J7Z68CCCxqJZZbmtuLvfoQk/RV6r13Pp7ZRtn/AKcfQ1uSZiFljJASrcS2rQRWoygxAt8Vi3F1nAxShmZGn9NwYQYzEy+C5ZcZdR8a8Pgz9Q8NSbHHHjwCN3x9Pz58/Gbm6PWvou54MsdbOeLCRrn6/sbOcZSJtOkjsJ8PwD9Sw4Ww/4SnIZ4YQfPQgVtJL1dgon5qvIICDWs+QAmRCLXQ32oI2a+cwFhNEfUqyCP/b+L0L7qHW2pWy0MJ8eOv53VShG+X5hUJ0bUOcs42/3pZAECiSA0+D1hHqXUpftAH+qXIa17Go3p2xnwsWto3zmM8G4SgSNh1HVeHyJ4QENsZWMRFd82ZYvzuWA35J4/33rdNlrbyWeUOdBPOU9a9pGdewPuGDJdZ8QwgH6lli4d/PDI3eSP9ybbUzpRXu7Te1ObR6XlAhtA+dVpiNao1hHVy4eu4UGYxZkZn+Z9rLSl1rkc=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
