apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAkHd+/nv8s5qlNY9/74gY3wzhRmxuRpI2CK8xQXRScezv5+ikHbpBzcxT2sdnJC77ztQ1eTPNVFmFW5UlQLRh9ju+O91+MtkxDNVQoOb0Mqxw7UrV2WGjgg5H/kXbpaCAahjXk4FdtZ+bSzZOgjIPg6uxp29LnQki9+bEDAW37qkrxTwyeg2LpvkMYpw4tzY/EyXdMj8YYxS6VXCTHBO9K/hvED8Zh0t3RzRIRbOsxl2ppCE2fz2BPqDhleuWpUsYKNsHXEsmrs7jyAYCgJUZpMwmeYWJTBqk5W5YBrTnYR7PADJTCJIkzlH5g2VGvBWHguTAPstta6dcv8pmp+lk9K08JzTIGuf6lnDnojFNFTh1km7uwiBaOBe6sdbzMNhwD1HZnDq11mKtWxUMWjwhz6yJALcxVur1gj+0aewBtbUantVHiDBlSQCO5NT3oR8Er+CwX0HdWJYBy79U3EpAGeJdNM0N/e2D9Dur+t7FNO0JuQeq0JfV2qFLglqtH66JKAonFvSunCqFTiueLtV0t0ZyrKTrW8NjFIY7kmfDYPyseJq/C66Zp9j6Vqed/bEagk5e8UdRApofQcz/3wJiha4nSbsL9myYj1GcGC3E1QG1M55XhS9XqymfouHzCrKN8zTZ7bwPIc8WWCEF+cHy2f0JhdbbA16SINytwNZM3EWMjwcODAeCiAXXb+yD7NAqROUM=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
