apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgApesV96xp44x1mDA3pSX8mI6kLTkRgIN0ONud5yirqy8a5txc/Mpz0Zq1li1SCKwDQmVAwOUddxXxZghvJqF4OY/jCVPglDN4DVV1+kcSMn6/S2tc/P0tDeRDmygay9OkO45bHL/zhk+IsruFCU/ii56q5McPeCE0BJN+Rq0FxI+fJpJOw7xFEXzuClI6N1fNrp4aYVtslLYSfXty4kAQcLQkqDANfCAnRfSD9snFsE0jv5Qi7k32V2jvPLqc2THvgDniBYJojhdzIuUDqzxm8vUKFd0DNpUGrF2jEhIwkq4Rlnevs5a+vEOH7fd26rV4hEsgxlG5DTmpYqYZTJxPVP7JrMay1uYSJbww8i3n4YxX0HFAUDmm68lfz3Lwdvvk6miOtzK3mt7h8EPs0HCp4vv6me7c0+v0B9M+Wt1EHPxMdD2GNARDsgG2P+OWePLIMlFhYiQXxehFMUInQJyr7k7uXFKcphTcMqjGqrAoYI8zBSBt7suSqqfX4K2tFtfn6DTQMCWbkBVqMp/N5BFArxqqhgyWaR1cFYvTc2fCTwBzRNqOLP1bbFls5rO3W7ET6TU49ewTTJ912gFxvtyv1V6fIPjzxtQlMnoc/gPelLU7+Vy3ud6nGA8XgpnU21do0TnBuNZ/mRsQArcCyiu5cRaRfK0R3kcu3+eTcpyN+2vcIqeKOqH97ART+HptUJ0GSvxo=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
