apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAqqLsRrcC4mcJVoH3aWklaArhk1g4Dus49tIxn5mM9AC/EldaGXNl5+qxwZQ3BrLMovRkcDwpn3b/V7ASjybHzNx9QZ2OX2yr4bD9YQXZOYAtJ9LRuMfwvZ1V5Kud1RULbPbz/JuXHT1jPeeTRExaqDlc+6uLG6nM/Nb1C0I8pqX5rHZS0oVHI53JWihrxruzNYSDu+gV3L437+J2siT1zeUFVSV5QLJVZQ2V78fvl3zLuH2JVClUaCtalLPjIcHZ4hJ+JZJ++cF4tDzT0N0DgRsiENhpU8UNL/jvuTBSMjtykJzPOc6mSQJqmrQgvjHk/07UzRR/bl/YZSc9t7IXMUdbc+XrZj2KKetnS4jI0NK51dZVlBfQxjyn6MJF7/KROq2XDCa9KUzsEUaxWk7+/0hZU964DZPbBmT3TBiNawf6pcWPbfLa0SvjpiQeqgV8VJSivPBz1rDeddD/2f1ebN4qSBMmNSIVIQ2o28IVjGbDhpMRLVJEtoOD8DhCGL4JCY87Xk0MQ/OQ3/8yU4gStURjfGAyNJt/cEYFpZStVHVR4MBQ2z+l5tTHf8gUBWgM2Fd88a9F/rOm7Lnm3WCSSzQHSc+J06Gq/Kc8PO3jKW6qtVijWLj6CXOM239lTi4BDovI63XrkunDM1J47V4eWuLY7kkfVbj/0iKNtGhbFfxFD7BQ34LDpebR2PK4L5NSu8tA=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
