apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgClreUmpL5ak4v9nuEbdsWyBiiCbsAdHd4JeyTnuEDISc+k5w2ogzvFgTeKCTPya6ng6HkiuGQMn7fNNg5rweqC+1MIUjo23kA/UXfHmWu341Qzx8HJmeug6r1vBQ1gI+J8MerOr+TmoPXGaFlSQHRUypQxNMA5B1Ci6q2T31jyKLhoha4NfiLEgGNt8iPPSOtH3Wi0aJpoo20P01KdFGAidC24DDBUH9fNgMPKtmy1Ogu7J7WkXcLnHxKcSkI3yv2RnXedh83ctwHolMUwiHTjFUeQriU7zBQLV1mDCMG1SnP8BHYtj14uME2RXsDmneGerN1P4O4/1NRS78sm35HfsnQtuV/b2j9K7TCYOLIEUGizSHh5j22b0OlTblcgwHEjpjdHdpaIzjKpDdl1/6ial0muxeEcXZmcXaFWMOcEI+4t0kGbD9WUCnR80+3Tt/KO7SNOdKqwZUcZbMiRAZM4VJ0F31NJbxFEEGap2rOPyUiZe4vs/HoYd9oZxgoI17RDrk7TiTFaRaV5vxozNm+CluTAu+XwKisp0eVRiaCGlnbFagUDsAiF7KY2++/oheNih9bf6NtxSfuUDI9INoRgYQHjrj/XadCxPKO6zWVjjfA4F0ANimE785HInsUBQWMaKrphJd2Ra++mX9QnG1/v6m5X0j0ifcTLRShWQUpypcFKfEciPwOaetEJFrLcd3BMHl8=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
