apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAa4JT7/yOiVKaBIGNIwpA4Rz2nxpqNsSGVc86n62WEwEh8mvo9ckGGASXaLIazPkNu5HOLFU5cb5Rx/11vZSToninMILyEMYLK7JXu1dCADt5r7UYsm4Wupu/tFnCMN7CjpGuErViDI3OhutJGozn2KhGeAfmNLmUZnt4x0QmDKzMoY6qe4k3J/O30GHbwrQYn7o9EaWjSetg7xENULr/x/EagUquzOLj9j85jOcTVI19nWMgBRA1jNBmK6ckhxwu7+/BSSB3gWO06vM4ydum4F0qpPbF2puBD+zPYkjy5qcMCYFoTjVPCtCGgEECKI4cShPHqJqhzMcGeJgjOty7aqG1a3T1P5T34bM28LQDo7FHOiKaV3wc1JX1BC9U5xRdx6qR7yeABWUu+EosjItjyixCKVaH0jibutYllPpMGXULCbt9PIAihsxUSyyuG7vtE3zZ7Xz78WlCzbCtBG+As/cFF8OSTTEJYxYBfEnYXTlmV1fjE01tMIwCDG4ZPf0iC1Zl/mb5mQIJJWGmKCed+ReDEv+P+LTLmaCN/qks1KD/4eA6vLg0Ipb3AQEViXxUBK4CtPf8pMLhZ9wUuJVK7dKYxf8r14nY59JVxuB8cZwbnR3USL4GqwpXMGygh3hY5YRNnnrdePirQ+/I9EjIZBAO6AsEDV8z8h1Im5XNcVXN7rIL4gQsy7uqW9ZITRi1PHEU=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
