apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAqYEs+PH031qWhJQ+wZ9fxabwKbr+DE3oN/8Vx9LIeJTCuROWIFUd9BP6hSRP16kufX1MvG8oIT04YvNjDj0QlGWpPzbvHn5yMYU0Evqrq7GMwvfEEAbhJ2M25BcWivy/Tz5EzAlcPe4CtKrmolEK2qcPlljgjAF/e4uaig0SyBZ/BstHbci3f8gMth4k0y+dhlFfxy2eWQEloomBpT+9jOY/1OdNeK6NnAn6js1fD1GhoCCHHkfiFjTJ5IOl6WIWhtrMM2Pm2j4CDc8PCNhrfVxOusy3scSoy9tfxCoj2nT4ReEqJ7nEmXMdTgk01PKLd349qW4uaHQYxCIrvZopYt8+3yGWwV4Pqw80ZHJ2LdMMTt/PIfK5Ichg38YuEvUxQRL7wN3HIlbtxKPwCxlpcgW7zBD6kkA48vV4+LYvJKWdpe58WFI5z0qv9opZvWaapd9xCbcE0hcSD58WQcRI7qjeZl4FtpTLCIf7tTnz99hxvJjdow+5BwDMdGwRJ3iVdS6kHRQFrcYxTbHkX0sjD0EZeDDZr+gORTiUsibSuFQRtFmvgA/ZIHPeSPN+fkFzsLH84D9znVFOB/iFijxvZa1OJu2/V4v1CHz1e1ra5mk4JAwlPeWBF8+z/CpESSokcku4byAy6YdXWGX/MuDMytaHMkKhfzbAcmzwSo+tqjmN4EMT5siFXzT2ov5d4C9e4Mv4=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
