apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBvGKvbOcllg/qjqODBIm0+DKNomK41T8AkUa+7T27rvdv5xIRYJHILo4mqb6zrdecNIX1ojGd0In+0A6UWeO3k3j4wUq95xmov/VrQX+QhUDr4Z/JaLz44hvBeLCpVfHTfPDXKIYVC7mIqN6g7+P8jqNiTa8LJwVwYo6TkRvkAlWoPdtvq51L+amXsVAhgF3Kh6E6BPQXXeI3+SRan0lbm6tTz5/HBalgLnLQRcuqR9cpsqMJZf0GSY+Vr34PEySJmr2BTMZzA/memqqUsDxGvKTsT8oAI++FYPMdFWLGajy0tegmHuGWd+Inn6r8IyZ/zASFOVwgXAdybWx/w9sPS6HRwhfKfaVrKOTQ+1Ni1Y5rQQ4igNgDisud5dhlZIl6LAJTCqKUGNIqzz7rqqVv5+RQUO07dUKkwlu3kW1tom+Kdkhf9WasvJNFL6tLyThGlGtzgK9H0SlMYT69cfjEBhGIZzsl/yr3sMOWQLiAvEu6zOkefCeMHfOh0IDY7RMjLDeS2FHejZRbOs63MC85SQSiBjmsRJIX2H9o5g4SHf6WaNsV6mHxewBnarxgK9YROxDHSSW2bn7ooB3jlgTLtX5Xbsq0INM0r+MUUP9sgO8KSxnAF4xkgKh4Hf1ZZHsVJ87XkuBKchmFOdd5yJcVnDTsEroXCP/s7+oFLDHUegFphNs3sAgukvgt6vXgBHJwnztk=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
