apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCak9PPAzg0qc4xkkfmMcOzqhS4o6QEiIP2gkyd7PIQF0lUjDwLeq0fymFEcRdoraYezTnwe2I2RhzBSHB8XL8OT0iS+3lloWCSNR9J8aYAk58HrV2P/cJszo4/AV6PutaZnYBLRF49YQUYfQ2V8uvFJbC07d2f/5QzpturKtYzSLbS/VFpGD/eD/TH+i/WS6kPJOzrX3Mo4REMoY/MebKSFexOnffgdlJ7fAR2Qrk9wWgJBtHsAnb0Gga95jixF3GeKTcLR9A+MyR4GJstmQ7dkv/ZeCC1StU/mZR13JzRcbGht8M7AQtneUSy4wfIRxVGdlV4blLFUT5/RnKCLXM7n7zF0zLd/3qXmCvTDW5zsj9NG9GUazGDoeVs6S0Xveq6VQr6gUhuI9DI915t4KAYE93b80rxe/xyZq5rUI0xoz4IMJQEO9aY4+LJLPpGVDZdju4LsU8DjRMTiymXXoYjTa15ekb+j3h9u4IR1tJgLeOchSxgtj/azuhjUkqTcX8U9G7ABGBCH/n7g+mSWNr+L6vT+mm0KcVjeInLOWAA7AZIFC11erREpTpMGRW1JA7IXRkp7wnSW/939TVeqOxSTWg6T7AWCXO7LPUpu/AdCZheEb7y02v3SY7sLokkVub5yZoaDHlU4O0+fu7wa1NAG3EZ2Cf+MfJXDUr5KU02XqEktPlmxaobdnBuG+mGmWpyzVY=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
