apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAk7RhXgb4VznOxA71bEt6cNHG82G+KyUE816thjjyauIzrxGAZHvjvEqZQrE54PfLZ5rGReMnhdxdmJNvFMBGH//b1Nk7VOIp/RCAn9keElo1uvyBF/Myp1XwBh0+kHYga1bE9EZTVRcEp0WBsXxu0q//2XpfNOGqqU4siYmnuzJ4Mb+woVX+HJMXmFgJCQQjy5lHn/KHxOEzeDXMcMw0oDe8vcTE/C61fMGPvFvW1lA+TSjiXpooQGIKTO1z7LRQRrUYSChgmP+ToOccoS5kTttChler876yjhYZcWwjsNxP2vg93Bto9LfDhp/oxRLLzlsXZxnveX3tIXEBlxjLds9psyQnZmbkXJ4uYgkkGg7LeCzWLV5/uwJQfW6U/8zzy0e5pfm6kGwBp4Gl8vcwRjHR8EUGVfeu0IBuCL98gzU/HKN5FRTkGduaMxHE9Suh7q4KEa6atIDMy7GhjLUisoQNUfYwrXwrcV3d23qzahW4lwQCNdZ8PrJiQbmnDyL84akW393K3FirDMwdRtzKAuxtigwB6LGgSW0U784oKvrAxGxTZwXeTrxmC9E3MWhDojEBfQgz8aVysFq/lelsc7oGoihmyNPfVEUcxGTzHhZ+dOMj+usZK2P3Ry+Hy6cWgGOX7E2YOq21pqhi7Jh892LpwKpLc2oErLp2Ki04BgIrEkElWLAOL1aD8vmOXxa+xL3Y=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
