apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgADncFk4iKszObYknrS4GXbtC/so6K0mBW89B5gVEfC7YthEA1ZExkuc7CR4aE6E7fdVQWvfEwdrMZomwQam1NSYmPUNpXRPMN6Gdov+piqC+3dNGSPmhKOChkU45I3ZkHhgz+RLgoIFpLrAZRxlbgcqt8DDm5E4qMyxSQk2gHEi0/TQrLtAU0VRQ6VHOc46QVfa+K+wqpMOJS8FwHSmETDCC6zQ/Gyotuml8f8Mxcte9ojrsDVtt2PeEuLQ4DIZDcJWHeScYFsyfdDnJgF5tW0by5wKxep9dH1lf2sjsNOhnCYVedATziElanZL7Wp/XGvOZnHN6D8x5b2nXBaCSMvd3vMXjX3cOYLqd2/Ob/cwWFIna3eTeJxWKgN8QIEzhbwpj+Dcau5/G6GfqtiM/YS+wm5zGNFc3kOB3N5y/wwSsUgahhAtWZJhLYE9MEDUBI1ctoIKF23loi95nZDFhGdvyW0AnnNjXDKFXPkG9Bamorqn5QQJOsJ71FdlYf5hIigysjp5ZU3q+9HzDur7/ez0c9j/GA4W046SspxU7GUsIAMzXPf6VMODgTEsxiylgcpSMKVbqgmpI879mSVT9cVnd4F8F119BkmRSZTao9UcDky5VnZtXFUoKk4412UrvOqGW2iboUVnhbUnnKSjIqG8C2VMyJ2SCKEoPwqdho5QivjUX3xeRlgOpLvRhBuU2u+KWM=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
