apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgABMM4Gfo5bvxPBn5AXJJnTwwbTOvoTX+peZFL+Mv0oMyttERO4usEQCPAqcVlVJtzwhH4zjgNTCEHMiFK+fOc0TRvxMrntmoWaZbxuA289ReU3ZBloPeHLO2MoO3BJ3PYSkOHKc48GVg4XEVJp+Lju/BODVPLRCycfR9ACyKfA1vokz1qxgG38q8aoS/3NfGaRZGNIDYREo6FNySPU+8W3HQOGLIANFWpzUNTxLyW0lbOKr+oW/ln5RSrCGP33dujDftE17aGXi3rww8caap3eTyENuKHXumDCHBApiiGcZchOEwJGaLtznw2Wj4wd4x9VqWSKbAgYu8OUK9PYqLUlBgPGuJE61j6OBuY+QP8hcvpU/v/odbaBuEA3Fbf669xGiZh2arM8KqptTL2IWoZ+DJ5b+OPJ6RxsQVyJ7L7m9mBA0izYeyCm3VHIyQ53Lzh1AjtKPIvru0pZuyAd9bLEaMISv+GUtAA0ws63AzZYWzLvcH2qheAQqyo6ZHswAC843RV9t3xow2hzpQGN4pbWVwkYNC72m0oSoPLmhDQNFXh2B2cS7WNbRH6RE1k1NmvqLvCNnxJLMQm4PsCdqEFXkY4PPxWzsQOAC3tqG7UtdezfTlA9A3yC1pthr/0XAMg7v6ZBW7mVWBHE3yNStowhOCaO00bZnXiqZRKtl5p4BLUg8iEgUyNk+yKHcoUrgVCmnj8=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
