apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDPOZrJMni1adxgJHY7OReJQrBA8UY/DvM2GRVkL3Irh8Ge4hGa3WEuBbUC9v4/vZz0akIJ0L6XEKzpp7NKeWyGfSy04FflipJdu0uXigbtgeRP+XZFymdve3E1OJ4KMyZrH4YjLxt1/mt4P2N2ybTZaiBLkW5+kIV9A+Keyk26dtkDeJbTW2dEUMFSLFjwibHrVL5fuyZv/Dd/Oh8IwJVspJH3CK9ITU/+L0KtgcQ7kdpSQdZml3p/Y22keTHB70MahOn4LODPv43Vj3GFv0juIIvbRfqGJBp5AjUOlMe3UgTCqWGrt7alVB8ajoCMz823gKzTIiMIM0oQhHeIWiYcgSO1mrj6anMMcsLXDbef7/E/7awtdskDMDDiWTsrsnoIHNBKm3+M2lcYYYyt4Ssm6ZEsInkr/O8W5rVGnQRhkbPjVQTXJ9gTVRB+PjMOcE4ARD14bQUFqYpigxOtTvKiQYVmAl8AjDbKZFcM6yMEV9XmdVZmoyKECQA5KGYGQqQY+4XhCjLB3tNG32s9Zp8tVVqEz8YtT4Od7QPujlP1zSm1FtF0tJmCDfXC+2Z3rL/1pTbntt75IIjwUKcvymw1SGT4WQZ9D6oCOtYJ8xs7UMz5ayYzTddSYDpOCgykWM3qEv7Ch9GaMfKrMZKnSQ6FZ4cdAgSyyVQ4ymGrxbM4NhW/fJQMuGmwQMYkknNqRF0h6Tc=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
