apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBpPc568vl/wLcr8CUunRNLR+/VWxl8klfBurc4Tse6HLVGWdUsEOd0oOY0pfxwq1zOvUbWH2A6tGirlas7aL2il/5sTt1eP+jdkhm07yJVyoEYPYH72vK+V7XW0Mh+QPaxb6nXbsk4D+QWbNTvJ7b6vXXjr7UD+D8OAYqCEJnnoB0hhhBYq1mztVu10D0tzCnsREB0CbMutYvdT4s/2MpOD4UJcvuAPVoUqgcWwhMH56VT7wOZB2lbff4lAasSPWv2OOO6VkMHd7Sb0TPrrxyuEYEtJqEYmUApHEEWOz3XH6inCaK4HfhKvl8lI4OjbWk1jWVJVykgWYmQlDAti/k/htaQM+zFsexaJ60NdkzSrJjE23fT/f1+rIPSTetYzL7w0oySBZ6Xs60tpOQQihVR/7pPnR/YcxSuY+EMRiXeelENsmC1XYx4virFhQYLoJVqNlNrcAwOIyC9TgGB8kSw/5JboUq+r2mMuiMMBhaK0zy4nBwxinTYum/JKffj96QxdPzLvqKej0gqwZyiuOZLKHKCOHD7lVpPbbp5+LhQIZgqy5nRdY6tkF4QRovPN4CjasUr+TQSN/O6hhK+ETCOlRGINAuvrEZaTSFuOt3+BTSQENw9lKhf6ppVf+GLhdOl/sx3Ka++bUts2jKpLk4kjE+NHnTrLPhjFEWwBPl7MBqz1VuUJLhdhEORXCe0Y/IM5A0=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
