apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCh+mf0ImNUZV3nDV6k50Qi+7E4ECaI8+18R3XrVcvlWM8Q6u2PZZM8VjCOjF6IyIVmiZMix/ePMUyN263Ql51FD/1W+19UQTzJStQmJ6KwKvXZ0KTujLvYUuETL1F/q0P8AYnEe/0Mj7g4zOBYU7SU1tD7Ng6Yzq3vfAWz4yPP9k1B5vQsQ9IlwFxEcmhI0Grthq6T+SXQBhpjbQCBuJgj7SgusFU4RcrOIOLfLTwqwRUIeFGCPQ4FKwJAyXa4i/66LE+ltEO768NFzly+UcoznIXZJCLlzT5Rdlfo9dZngjbBDuccQ6sdzqYi7x4X9w+xPDmAqzDeXaNNrP8s0Cva/jNOaq04oO/eyDozLxWHU678Uq+xgxwWUfgdChu9rR0jQtF9gVpQKAkK+45yArzbrf4jdWuBwDEmEP8A3txpeBY8ShtQIFR58QZIYQrkFNGi7aRnu9csnnghIW5Zbaz3T7IXPuOTQ7trVxp4vzaWN+1+6yHwYsGOcyS9WroTTn/Yqh4bSPaGnO2FbYVZYc/F6QIO0Ktr8UQ8JXjdG33wwJ57AiJreXRrce2M0pMJ+rLn1CxeMFFaZbpEbnCN0rWVpR8TRo30OAHlecWBPoIX59uI41g/LuVrxWcwJY+YL8U9jApqB+0q4qopXO+9/kopI3CHPST/6117xEjB3YokZxJPuKC1f44j+g0t4BLqyEEQ2ps=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
