apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCn/6ER2mLkd8cKN/uYbBUByiwe/83cjn9vki/BSrF/IHYrO3brsy6r56NW62S4AR3pB8+us15k4z0B9j/cgrxRhw3tou61mI3ihZklDtmpdNR1xefDL4430FU6VUNEs+M092f9FSwXxuXuuCYHr7I+mKsmWquDShZjvB1doH7rqxu33vyv0sZWZVsKGyHAvJO7diitRhC1nj3S4Ft/iyUfw3+zgIys21i8IMAf0gdM4Vje3dqDPGBlbBQqwDKOj4nDwAzB2yZbrh5O4Zji6qzVT18+oeKO4KCTw4dfMnkY3Vk+DoRcI59PPkB2WHhsdk23x17s1IV3wRto3klLACd53WzofEmLW3fwONk1ippzDFFlCnOP/RyG123RWuzK5+9BsXkp/+pWxOEuwl80flBlxQhkOYbPCF/fmWbBJZ0K+tEi9/zGw3eOQqCRLc2eZUNlSzqGFy/LDh5oj2FRGgd6Z5emTJkVIWVSrJETBtn/quichElhTcPRFQFjE3InDWzYsi4KSRw5td34wFduSRxCU2z1KNqKLFtGrwY6T8mKFyQbNYn2uLIOgKlhume0YX/j0e6Ba/siPBHULwg/Vpl5XDjpc5O03EYcDdb6Y1KkQIsKdDS60T+bKnmlUkQKCTEf+ICsC9ytjjOkjxV3R2mcPpD916EZzHkECU1JunrKhLBbN/Z/5TGZGUVSPpv0Br9eSMc=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
