apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB1A1so7xtMylDeqMvsZizDwMXK09Zluw08YqQjUtX4y8TTTjYn7CyIA4BSUyBYRjMISUy8WuGprYFyKz5/a5bg03Me/Hh8J9uVAjuKxw+gPzReCuc2bTSiGrONZMMWC3VwAnByqjAnNVl21lnQNQUd6UStJbJNAUb1beapH6yj1KuOtRVK0dGSPiJisccwDL3pCXAVYldB60KhW3JieVAJ6sbanCzC4sphj9HjwFI+5BcZ3tU1PnbFzH5Ch7YNGIUjiFOhNkP/sgrvgfGqtfomkbq1sNaoId+7HMA44JZvUm3p3t+/pw2klQVT/iatMnyYvu5Uzb6vw4MoWLcDDh3bc9OBG26Uh6/8hhcsFjAsFT14ecivWLq9t14XpN47aMCh6x/PC1fpjBbPWlEvC/Gy47LopJ+UcObVwhTGGqd+ufmKGqu2B/lPBVK+NFgBcC4U+3U+nA5CK87CtjnqskaYr1ZqV45vBtX0GBMsBB+TEOMMZyJGJFxhYiz2Pzo8YBJCF7FNurgpovRbENOL/qtUnUCRWFWHAFnJVnUHekN+VYNedpEcH+pchF0eTKNY0uYSn1u0n6JnjthMAUNR71KXDrfh5v1bswaPNiMkEInF193OzXHTl2mZI9XjM8H3RnMUcWFLr+gJPM+pUjMAClJs/TzlQHVYaP69SqWv0oyntZWq2fthwJJCyLv5Ubqm0HixJ7o=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
