apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAcdJDv9dLVLK9KE+4Z/qEKy6k2lZ2I6Vs2gvP6wnx+11uG1obnUSvl8ucx4lYMne6ruCGrOTlThdk8EZNTINUNgcl4NqA3P6Y5p3jwCK/AlemcFq0Z9UAxiFkmdGdOGqot9qDBQRmiOjN+BAipBXOo+zMpJyIRgKvDiNwk0R53IJlZBAD5BGbFR+GKZw01sNWPXFHUfecMtfLdQG3T/geb4QigQoo3CAgPhAPVIjClzmDriE2/ZFeWlNgqmQi+VpA2KFpVp3aRG5rWsRiM+mQaJxUxUIjS8vSc396oEwxaBumO87wNt08jmLQBlHwptLEQI0OW2pAn2tawNZqYhPFxsA9nhg7TKig2PRR244rLg6FZYNo92/eiCip/AsCS2jTfq/c5IDusURM/vXplWI/mGTmcTEoUFOGOhq70mjTiGIpC9pG2dnAEk3SKA776KoXt5oYkm6I1VW08d8zxK5rsI0lqQhvVmfIwU6vZYRRcLd9ce6NgAGdhR+2MLZzYrukkQKlAFMEXEQUVgt5fyrWyyp+zOSqNW0lPgZ1n5mHiwCmlNxnf5yRO5eL8wLXOEgLb5wsEFhgeuvwDY9U1sV+kgrV1DBAcKtGbF1vR+rxDuHVF7jFWRyXxtRPNlFF1KdmKfNvl3yaLhkF4OCtLaG/KMVXvnGUphl1QfYtz/wumAKZ9IcVb+FPSDkTGg1T5Bw+9FPs=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
