apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBuuCqXNnYvQeDQA7xIn0rQgJXJnKKZLe9KVxfMNY2lIluhoe7pnbNB5q2t4x6OmAVCAUS9ZTQlcXNX33PxoPuOnScAb63Vs3oyi/ZrVkg7ckdcfiT2GE1gXjBJFRym6g3JxKLmPpnTnbRKT0K753NaMDxWuZFqUOwDU+0SCN1n0Ja5QlUZAUMgyqR98+qhrOK4y2CKthwEK1SlKOvzs+u/cQVw2pXqM2o9CKigL78eYPrI01dkOBiLQasHP0L7YEYs9KrY/4ojM+0md77IxE6ccnaS9MtcvbVIu+02MZL9lrMDC/M5VBBXNtU/bsLnN5zAAmsDbkEZ4A/cqyGwiEskyYkaPuIb4E54RHRWas6D5CBcL4oXQDBb249ayuvfcKCEvuihqy0kK6F4NfIwmOuyyMTOdPTN+TdnRh2ZTwdq0nqZ6M83l1NDIgCN/a2SiUJgzyxH2L4XHlubftokJn6vS6j44SVHdyoZIAwaIYBK9PfsCxxlUCFago2RFqSh5+p3EzbYJVn/KkV7ublOu8pr8xZBljEjojAGvKW3oJcbonk1EAs4qdMM7M7BJHUwa/1xXRsQHSNyPz6yjek8+thOMsuZLX5F2VoQhcbiH8uKSE/bnC2nPDQ/ToZJZ28RbpUuLie/FYj7qmRhQOWyMEWiXf01yMTmeKdN4fwSWuQRWzJoWil1vlo2fcqyyevYAEQNjMA=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
