apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCyrkmteWJhtCMys1SvjnqdRLkAu0XecT93DJMDrzKxVN0jK/F6d5paUDpgpQlC/Mk+mEq1RZM2NEk90G7BExlroU5Dvve+D6BYzGEtWgvYpL8skxe9lnmQNa3hpHmA+Y7CSRZan3saKPO8YCyoRUt/l5TtPSubC/W40ov2xtbK3wTxzrwzzfpLVT8d7nALNBwPMBVwJuPlaZfn2hWO69Rt2lnKcYu8FoUgWuWYYU9zPZKDTNeL9gj0uCqBIYNQ1BBFfz8iGtISp8krdJPGUa8zIACej5EOY6bTE/oKJDrEonuPd1mX/TN4VPCG4Hhuzop1qvL5t12gs727f/Y7vM0NLjsWBhHtolwM4vgf4PIg5xM72myU8raAxmN5qIhwBEzWuMqrk4R6IQUSwDEQR0B5U5QMRotD9uD9+lmN6OwcVyjmh5u5PyOVvNmIP03HFM5zZ0t+zsX6QtaTFikvTaQFGgF8+L7PzmO88qhbcAoSmzYa24gJcE1i9Gt4B/vRyGukFrRuu868fnkOlhhNeO3FsVSyURzx+HcwoDamZP9eAu59fHkF7XrTYr5yYZR0/aMM9cqaEVs0rQMvIOQBouwrSY2US+pb+CE0n1sz7nPnHA65IWIsptM9C37wyuMyQOXPhEWMP/Ilk3oWEdYEXB3BMmzQtV2pNSaEWKI2eIZjFiN7tTgWS+ZSfGHVlYNCeiYcgUY=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
