apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCq7jxSKgp226VJ6FTn7JYe+a8M8ayIWTEFF223Cc8hRv59cOn+3DtNJpFtcpvggs/hh7VTtqiiphVSby0e+WWeFl4PwUkJi32gR1WRFBF/ulC+z+bwKItrwhJT0b7jkDlCv4p91x2NdjtKDR5MFtCW2uSEgOcYbfpK4FQq+LWF0nXe4BoAT+i2XUI7CMn+VtqB+f6BnjzwQVAFFXALWa2T+ronLRPoy+u2cIoLnJJMAENYphf2CPxH80j8bFDg9ljFvr7Hj9QpnPPes6cScbLFHXdOFqFAZyk7vGNbnebtD3l/YcZmasseuH5/psz3xauZoPMQEdipukFhsXtONYYoZb3Wusq+AWXuOH5fBKQlTDbxkEu4HsApTBziAvInxBw2ZrnQ4PR31UwVMEVvs9CuOoT2SbNIDt5tkGKx4y6aIyB6oSmf7K0KaA9gV6Wjx5ehDRLmAJzBynrcgeMiqnAtpBoS9IoRv1xGNuOrWjoLbPeeeo7g53dt8kQKA/Zr0xPJzDI6YmP6EauimrmSSm7C0ztoNs+jUnPgxPDkxh6c//UGBjkAn5etUw0vyOJP9kls/ZrnBCh4/wIfgfrV0PyritE2XLhNNSQ742EHF9N6J+lswUBYxAX5krU2aH3fBl+1cu/kaUY6y6sh1sC+rJ8vnVdNLIAo4ivOGCF2Uu59P++8KJHvr5mBRd7cBU/WHXIR8iQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
