apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAimFimAzQgTH153g0lo4Ve+gAbgURZfKJXlKQfEqyRDRHUvuoBgkTC1ni6Lq06bwukjHVX0duVeo9KAmEU44y0t48yn4zk2Bh9Voc163khleoZ8FxBQSjgdkA8ormOdyNociPZqGHTrY4HPZx2R5/zlumD6zF2FFezTb9ATIGBYUTJQm42VemTyQW5V72cwIemK3MVUVZJr+MOv31qn9Efz8gN4FU8zRBdVhEXAmFUSx4oUs0jE/eU5cYAypej2ShMTxrN6Tj2XGHS/iW7wUUk5vBSn2ccIn/jGjGhstiqmQ1iffQ7uOkaCLjECpCGdd0aw64Qsx58L/RKNf5m9xGGpaxvY1x2zSD8CcTdkRx3sYTblSrzQjgPNbDBqbrOUnErOZPia/e13r+9RHrb5Y43n0/AsAVutemzrvItH71s+bqpI5dp9RAtKBhNKmUV2+j3sZ8OPpKBMxzWiaPkkdsFHvEBteAY03tx1D59sZvwpWtPvKSlaguXI5X33f/m3IUjy4kVsHOy4YCasts9CNl8YyiPhCMyOxT230K130/JlxT6a57y4Wo4YTKYEBUHyPVe6xHOp/IzXir9fOGZ5X8NGHGy+n5F1fo5BxHbCTlidBdU2Mp1wb/cvT0g8WixRHUJNQEFQ+KBcO9XHQHdEM4LJxYWyLl4nwCgZsPW6lL0rNqcx7G5VdoSALHQW61ncBo0RLA=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
