apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBZVY0h0pqtRoSkce+6hnCPKG8DuTtUIunjBax6b8VMgsw1LGAyDVkhgQxSHX+Qx4Xzk+bSBR3hK1/5j+orQAeg4y7XQtWZR+jzP4yCc3yrg4YDPETrWfCSTRhMLl5T3cL1XCrxFjCzS4S4DluPXhCsj06X7NJDutCsoqOvFypTsX1U3QCVt5vhKnu1mnoL4YUg8W/YKo8yTcR4Qiw9TTicA3mr8KOJC97QlRNozSzI+yHdTHYhLMXDrdcl4kcM/iNbshC0DyVE3F4z1K+QYK2vJo2L1q/XfBEK+jIr9CJB9SYWn3gmOfN49zHr76kzTY3cMuNexYUHskgDrbEgj31ZxlQgW0mXhnNHa9b45gU6mmAkgu28L2Ht0+Ry2gkW+Y3lOKyBKYAi6cNEBb7hc3gPZvntZWNd5pV0Bf9mHlwv44wBlk5TVdRlWQH0XQaoOIin74Q96fqaqH2ufQZCg//TpSNvopSbGu94mB4jcDv5LPNLxBoNJ4adm8gVRldwTOgZJ/Cfh7kIXUTyfsgxcoObAlPDCzbFI86vu5EnHag3dej1MubzaP+i/dtkdpu3+kINl3xOoPHD49rGg4R2AR8PyvJzb2ia5DVKzKGGD5zAZqyYyLdpF5urmTQ6XucOTM18AAXkvM77NtHRG+8UTUsb90xgoOdZwJySRGCMVsWnvV3RQNApFZjA6eyFHesRVZYcDfk=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
