apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCEblvhF8ulkJeaoOnqYQ1gV+fXhFXOOSlqo29IK4vccIVd2ltuWSd9SHMS+ZyEsTuOdvu1FZkiZUrZrUWyaUiskxpjt/JgqNP6jHpbDgvnLikNBSlaRXgox1VqQdtp7IMeKNJC8CaJJZdEGxDYiBitgp9wkoWI8R4PNUCRKirujRf3/YNUmQgOLvTBK+XaP5GXWWEoL/bkEavR4sLElLEGztyQ7dbx4oH+SrzZ/Dnz73BO4IEF7YIWd6qOWX6z5r9kENbrVNowln5Z4q1XIvwe2AOYfxDS+oQXiHBrUUOwNWOqTldAllr7VfdOkBDKSaapK6KBbrEtmmyn1jfYkPzioFlL+UweVZhrlYecXSyLk2M/8R/vY7mYXP48u2nF2XK0zYM7PuivkxW6C9l39Vg9HK2omq9KD81c9cuEz6hck1JuHrXQk5xZDe4JOuXNsluvdZA4B80QBL1CuA7vqrQdHtySXzt53g1nL9+UKBnib1n1YZhJGmwav1V2XY+W0nt6HcNEAUTipRCfbN+v4rIUlIQx4FrDtQ+hYETdg1e9uPENUbgawR55trMnNZi7HfPulLtDloKE0Usg/l5fwabnF0a+s4i1vTxgIXQu0nf/29znOMacDAkb92WnYI4kXyjbm8Rr1gbYf0QM43qKb18qf+x7S9FSnH0von7igOr6cBKA71gVAccvYUPvyOCDxawvKGY=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
