apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAyo3U/G/YrrbpWOl/X8CYRz6aCDokzOcQkcqXrJiOtVVo+Gg2zW/aCkx4wHw4sm3g7HXOC06WTYo49nGL9D/qQPelQn4OY26q1tsKoNdqHNaED9TgD5ebNn1VY9YcXIhw6sJUBRSpkTtM0iRNkQLh/D9OVazRN0FHGo4tNz2wixqT55AajOqv1hVPJb3C0eITZAjGdVVNydKlqBWs1/4DnqpqphOBmokYLceMMjCEuigs4PqzzucPT+B6lDb0P4KSwCPOolQt7VHcKqJ+GBtrmU0F6dTc44a16kRUx7tGndMcEOiV2IyjAwLhpYnoHoI4aDAKVVAydSciMk5rR5X1AVq+xM1vbbhycUCCK83ylrLZj65yFCe5KVt3EJcRY7bxXf/7k8o9ScbqOZaAZDaMIjXUhgEnmGscmCdwgdg4kbD2dblnN6KsjS53EuOMX/keEZcKEOgF1O0hMeegbJ8WAfWWvvT8Q1jELH3N5xul5EMMTe3uJG5CPCTqCVyKafxISZoYsVujukkSUZSAbzYVQJ2XFqYkuATprb/gUKvCXhIATlibYwjJCSRYYVSBk5rOutYFP5KvXPqqjnTMPYHOhf1fdHzrD4N3KysmeHrB9qtseVn3x3kXgDTOzC6gZrobFeYu8S11LOfi7A/bqJ9hjdKjYCQ5OnMh8ASPLoWpv9XXA5KUIiPZcLN/A9TDZ+3ULZcY=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
