apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAnBxsAGnx7pgyqMUxAm6/YYRm2uNlj3X1ZjI1VMyihxijPfuBLye1ttoV+sOV3ForWwzlZqDuBHWx5rirVFy8WanofjsqXOUG6jyLI1MIgCWitduZddCwV0BPRVFMqUwlc1GZLJQw6OtIESWJFkmm62/m9IH8uNPYY2tz3xglPoypy01mgxWcnFfW0IpQ/IrEH/kUh2QPi7skusMx+hWeO0TijgBrrbkpS7Gl/oPtCca8qvx4hfgbW11gI5wLKxnAzPIr8PvoPOjRAMA58/9gA7K3Uq+t/d3JSO/IOc/du/i7quGT1mS65r4CL6YW77RqM2jWiDqL2Ady7rsndzAkT/zOfY3vFp04oqW525tUBnY9vSRiG8jbxkiot0b0qJXY9D9CrmUHfGs1EI/gd/qPKxSGvTIsUG1bI3breIfTt3cutlbu39tJcmeoHMSzif6HDxoSSENz2dnnSwOno16EhCsim/SLpXSzlYd/eZUUFRrrzwIX3leKU8GEQN0AsHdI+rqRb5qHU7QyboBEXVJZByT4MqbaDPiKEB0Kruxteo/0zE6fkjWuy6of04q3VgcZu2jYn6rfhBKNgwOP8D9DqlVOqPnplVwZRDFTvaGURdDZdZKVCb5qUQ9hIELREh5mC3fy+mfTCp46fBVHOEHwvpVrlmKxmav4VvyC9FxXo2lmkEpHUYcmOQvLAA2clF4NIRfQ=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
