apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBamkBpeFjRnEFpgUN29BIQ8Hnivi7uLZjjsWtc/j1rvuZ4yhk7D4oQSvrU42/hOa8lqi3mdSLncD4AomviLySewPcRlYkV2JbzXDrHiZaL6dNPyDKp4CjokghYcH6AggUd1hoUCIQmrVDUqeqRcV5ZcnCaKkxJvZ8yS7BO7eYmxPhAgeoka61jUNgs4WV5IpEwQcp54RFvGbsMlYH70WaXSP0AszaNJrfRTIjOvihHlguN2YiVmPCoKXWzluEUtyqvjUGZpBDdWNCB4qjw343S8OV7m+FInWhQFpZ9WPuQ6pp4gsyb+yy0J/wBtPL0x1OmoPsA2K5hJlVZzXJiSmccTvBqroLpPV0YE7MZwXufJBSyKi3rvG1L37U0WPsJ/G5wzlEm9WsPDppIWy8iQimdKsd+KgJXs7gNaTuFbSMvmK5MtqGyzFVdyDt7XId7AJDoj2x/L8H6rh8fJapGJjwAOy6gZ/CNMuuScCj+BrxkdYjeXud0YWf/STUHFcdQrO4OoLPN5oUDlbtjNKOcRDqhaN9uqzP28pJvqrlWudZK9tzgV20/BnHm8R2idkAmc7ZqLNlVBnCNZ7Wd7HD7xFeiMR9OxspfH082Fuzoggl7FYaiYUh/w5lkULg1i01XpRcxx8FRpL6ojxJ4DHuKopT9v+0P5NFs6emgKND6DKi3eLL7yjTw/qxTbftp+SNwbVN/e+A=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
