apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDbFw9db0/0t7FfItMrjZqamQMT9cmky+fpUziVHAv8kv+YYj+7CndAUfYYdSpkr/ssSUsN7xKZe0Ch0uhY2KTlv01oGdEvyQdS2R/cRxrc84UkcBLycWtwivKvr7mCIFpNeniJkkZcAJk0YMdRu2Q/rbB7nFTGhAltmqW03a9okmhruLX1Kjx3jL36vuJ3dKQBHrTCsemUskmGfidSuTEvyb1g1joB3mtIDClHVY+LVQvm2zuCSgJMTFn9CN9b0OV6zTLpO0wIZk9NVexiKayyYpdcMdg/853IVQawz5DxAnYH4FAXyr+H5uFuSVP3W4y2krAozfH1pHBdyh/FxaahU35yGvuuMAB7/eJ5iqJGLo+Z65DTrjygbeehQKYKHT7CXrt/IAPZB1ti+ExN2e0WIj7WKnWuvYV5nQWzg2QAAT0AXxST1keBraAj2AlaDTIeKLwlwBUOqK8PHV+6ViQEeGwYFdK0RP5qDm1elRl8mQfRpgJ01ADvW9BvIyPaWhw+aN9j8kCoeJlEhMGNNKe8xJtUcwSLiTL7Ac1YnFDzQCoJBtOqSgk1y9cbUn1qFhSvsmsXYOE7CybevyLHIY1XQ+lNxhLDeB2hyzBGp2vO4kwE2Ft1qdodKbb/wOGmWrGEQRIJf08+0nKcOtVAeLTIrNsfpx/1Eetvpy4JRH72mKdqIjgGgX89DPCCmvYAnQTV0Xs=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
