apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCaOZQ0IYR1FZdyMpu0LaAStm589sINEk3yMfabWBbvK5O8lOi+R/RnboD/dXHFl/I7iudCmxv12uW6z2SH+2Vse/AEYwTiz68+DtjOsbDEkOU01KffYfLNaa3KcZNIAc5NPzg4umsJG08Eh3QA7dRIuFeKqWDIERmtaQvAwsr72/XZwRpLbU+JCFYWN0R8xSyErqnRwt73YcG9hHxurP1d3TRxTE4O0bMflmKbMxb5jDDb0/1P2gsS800VzSYqJ9QUx8BXUriSmNlTfvIdhtPEvYy4zmaDu9BxFPIxnrKS5dxsJk4hK5StZhTNLqtxtN5e2LDRWAYMPByVYQHEehUufGbfUBhbC5uBxq0YdS3co8Ed44IIeNe9WZU41HtZmI4YzCCbRfijUldEtxSdZJnX6uvNaLJGV6D1pp/RwH/tUcYnNowukWd+g1vRlQCBU0CICk9LMovUXk5fcOriUZ5QVYWXeXIxX5Dk+OayPZNDxHXcwcuuWiw3wjrEOOh+FDVOY0sssesneuqrF3GmE/sLzDKdFiBYWzDpUDrzeetpNCI04/KeWtcCnYc0qXdn/KrZmXIaIYRAIP+MmzvIoCcYnmDkavEV9Qt30PIrKvmVxOY32lehrGAls0vsIFiAHPd+f8xi7pBEZcY6EEaOjbnKVJ0PMwCwhXB693hvQg0laWoSOOTzSNQX1louDPhjPIAl0oc=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
