apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBqOertU02od7PrHjqGPhdIDmZ/aDsjtyC/DOZglQ322kciWGPS8ywUkpkNzrd42lCBhq1KPdEU7OcSBR5eDpuhHMHiS2uIp20ih+DxNs79H8Zl04ZQhTOqk66W4XkWxctjS0kdPHzBrAR4PLcEhsxwPAYJWR3IYUB2/UTwtaGAWXvAbY5koacR4LtC4e261XMU2V3oMOVyI6PejNoGjmCzvmDDMNANtG36LfPJzV2MmtGYCmv611+0XOhRTkTQdUcdeyrousF2/yAbH/DRcCLF8PFNfGbrna1WnU/6b4lbcyh4O7fduanGPhpk5AllcAgInehd7zD1NkFr5rL0/cOIlgzQCENvWtdkh6bT/9/+sgeJOqOX6PMHcxugvAC5AwzNIjE125JAarDn+8GBhQBz3WCyUc24VHKdgd6co7rAklujUTCr2Zsd94oxwbAZxHFz76gpFIE8Ee0oHtv7+KiYyqskNZa1XFda2wuJuqnI63RorFwEuV18ofHayvTleKdBTQ2+RfSDB5NUgy8/+QyyM33F0aTIsCCXmjhiP9OS6tuceIsM6kH4O1AJ207PJzfMfQ7R6Rt9IHj1fxll+ngEny9XvAvM8G/SVequB9VxdzcM+oNin0gzAqTtALQd1YOjAPUs/zEZkBcT/brZFeHZgorilB+0eitH3TOhxojZT9P/DLN7rsoL1551ADBUwQsl8FY=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi-svc
      namespace: cicd
    type: Opaque
status: {}
