apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-prod-go-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCfPPmyv0+EeEUb6PI5O3nWHmfY5adVpVwZckaAR8ASzFNCFlSlb2uVAIPB7iNzuVVX7I7rFbUf8J4+O16jQSbpDx16B7/LCvPqpJsSqnjcwesPlQdVTFQ7AsND6O3axOp18qSLNGpfKGiJdWT/IJqcRVKHxei1zVebCfayIw5KKS9/lPGpkVL2Zsv6ing7PHStTHDi44fgO6VkYY6ouPh5fswWTuuOTvk4e0jBfX4Nm7NJmaAFRQUbkBjnoy+SN/r+wHMQdojwbYsmy8Czd0L2ab4kLtcem4rj3+//57XPB7bvZydMCTEvcMJ8paqA5M+3zvke0A1c3hkerDFI2HDVyGkqhLWMvUCwu1Q6Ivq3q44rtJvdepe4EioD1ZqFWi3rUln06fkDbLUoj6+LgcvPpUc7sYpbvcVooOsCU+sGuOl9/tumwMB7aBqIUfZSTTFgIchcvanS1EHLqMjIrDlXG+BTjl04/VQgEkXA/sgr5rKP/goYCuMRYgavRV1J8mFdiF4uoYy2838vVfdstLBnmDNocowpcHvlAVjCYxIDl0vdEyYfUUuWXNxCfNFl894win8kfG0WveO2UkCUjRmLkUqlMX4Gc2WOY3jspBRSJqUHxpmXv9onCYdrHtyxePt4LKmf8hnSVX1/RO+NhWB8jROT12dx2h0hczN0v69C7SbxnwFaBQh/HdCYtowsC4msM64=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-prod-go-svc
      namespace: cicd
    type: Opaque
status: {}
