apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-prod-go-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCn9lzrB3H4psb+WVskXrYbqJ1hqdLRP8d6qP/ESHsQsP7DcyJb84M0rfiWu37vhE3u1MnWYeRVHQc+iBkxAwv6ksnbvy5+8/y/U/QsKaATempOi4Bzn5F38i+oQpISgp5ULOPR2fuqltZfqZiyGrH0oTfbCbzUNF4t9kihL+LXjuO5OtKkVuo4ONPso8GnkGNWVcK5oHKT/fFzPcsv/QUFeD5VOs0uzn8yhOPCz05ET/qWDZwHlgJXPzNplZ6nPXTN1Y09ifsETBAmMhzii+GSudBZ+bnPuojWGY1CN+E+873sP4AQsFAYRTq/7Hy7ZLRpnFalZx6bzGF0H6Jqr6BAahyLt4wI3dBG7TMmo5P7YcWKGGWRc8EsY3/VERfS4MKDHzcsJofgPTfEQ0O8A4t6W6Lp9dqIFotDmNNcpOExMiJU1ohL5XUNljpnfzJVWR2dNxqzKR7iDefrXbNZxumt2xEZnyt6S4ctamXAdx6JJ15XUpC+6AHgy0gZ9zjIqg9fE2/dsreW1l6mUgnMGMnqNLFf3ICAUkv76++3wfrmNgWFTJd3uzlDZLHCZneds8YhvNl7T3l4jWXArnctlRaTEzGmwv+yzVj5D1kib30oUsrjCkxWFEaxvQRGDtaTH4+Y88nf/nO8q9p4FjidL4avPuGk9O/J2yjkt5s/VNxoY9oei1p/GiY6xTmJohQLOb+vf8Q=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-prod-go-svc
      namespace: cicd
    type: Opaque
status: {}
