apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-prod-go-svc
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBdD1dlqlHMMi4sJZxKdjwf+xuVqgsK+FXaqlWoX7g4c6mjVEVW6jtaAqLFrBJsZ9lXKwsOg0UySCgvPT7u4M5RY7sjpCjPHFeIGOZGjUrqemWebbgBN2y4o0c6QmNUSDlwOw8BILOfSSWU5QHAPY44why1DqrsxmHppuyaZfcRTaHvVgwtF0pNmuxu/Nesvqy3G2w9Ti6zELl8JBSkym1mIHEOrtVQ2DjTeSWrXwFcFHjcXgprVZjPbHK+3CrK79Sod8FIplVufE5LIX6ajG+U7/rT6xFj/GgxI2XHUVszp83V0ojRBUXlIXFUxXfN6LXuAg1xmTs09R4qyclsfNNQH4S4w5B6yklyDgxufM4UZHt88BMyoLxUQqtO/zAtegnWpAm5M1K+wClwQgvLEFqHQkTuqmqIVzKcWPcbqZeVDjzEPiVo3QC0vAo8njoU+ZyKugZ7WLgUXe3jEa60KU5Z5yNk0Zj82WJY9dleaJd0fzMp7k/fBhGe+e7xd5s2I9WhIjmOqVrW+ylMZDm0vIcew7Wp8denda/JCT3PnTiLWcJmdG4tsd2fQLFerQhYwlJo4gdMQNrJJ9f705LskhklkKwMBxwq4kcs1yTq1sVML7Mpx1h5r4A6KjrZdhkOLI4pcWm3gxwZy5z79b32txcJGuVrG9YFNCkFTwYuDd1vEVozBIEfHk1UCASrLuyLKYub9z8=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-prod-go-svc
      namespace: cicd
    type: Opaque
status: {}
