apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-svc
  name: go-svc
  namespace: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-svc
  template:
    metadata:
      labels:
        app: go-svc
    spec:
      containers:
      - image: quay.io/cbanavik/taxi:0.1
        name: go-svc
        ports:
        - containerPort: 80
