apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: http
    app.kubernetes.io/part-of: backend
  name: http
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: http
      app.kubernetes.io/part-of: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: http
        app.kubernetes.io/part-of: backend
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: Always
        name: http
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
