apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: http
    app.kubernetes.io/part-of: backend
  name: http
  namespace: prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: http
    app.kubernetes.io/part-of: backend
status:
  loadBalancer: {}
