apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  resourceExclusions: |
    - apiGroups:
      - "tekton.dev"
      kinds:
      - "TaskRun"
      - "PipelineRun"
      clusters:
      - "*"
  server:
    route:
      enabled: true