apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-svc
  namespace: stage
  labels:
    app: go-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-svc
  template:
    metadata:
      labels:
        app: go-svc
    spec:
      containers:
      - name: go-svc
        image: quay.io/cbanavik/taxi:chetan-rns-patch-1-08b8ad1923a8b4dafba8968adf4aba17083dd627
        ports:
        - containerPort: 80
