apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret-taxi-svc
  namespace: chetan-cicd
spec:
  encryptedData:
    webhook-secret-key: AgBSc0ZucMi3kZ+h0bpLMZYtO9YJTIfm5l6skuwj8mIH6CSRhTHINIulbHDV/IYLe0ufAnBwsu3swbgxqf5x9DO5F4NpcdDI4VjhnruibCZQtFYx8KRKSm3C/v8gY5vu2A18DjIHdK3y7a6exArplA60ewy9GMh4frM5rCz+FlHoghmT8Q79pMk4Y5Wg1JaWp32VNpY+UmEX+/RPh4QpvSZClPpgHPIy8mtS43x3imc6CsLubjDU5f7Eo4oB/zmoRgO0unR8IZlj9T2DS9PYskNO/hCMYUrM5eIEDQqVe8+CMTVszIc1Tp7Z/nVjT1X91gkXjQt2mk3tUa9QawriHSrPV26UauOSxiAms9IeeAU0vU9byQY9uDpunOSQKNb/8EhRXEBhWeXUMk/OGo0EUbiagsyxjHHZrFsmPyqJ4xVvWveCSFpJgp9nVQ/q1dNMostAJd/GJ6WI5jHuJhTrMsQPYwSQYzrRv4KMs343Ocn7PdEx3HpQbRC8Z4coA9dntT1X+c9jd1C9cxTVj7E6APpZ0srjQBSivm7Kadw1UlHNz8SS0s5GGxC10zyOZwo9JjqcgxxjMEMtw7G3F9S0kq5cU/DPtQRc0VUNjOwhmIF+QbB42nNmi9SSmaT7cEvw4GMLcyx1YzgKOoTwZs7ZuHyIW9T7qQKpNJm6JTVEtxuQmGxfal+bkv/ejAl+12Xz/UFQvIE=
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret-taxi-svc
      namespace: chetan-cicd
    type: Opaque
status: {}
