apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: chetan-cicd
spec:
  encryptedData:
    webhook-secret-key: AgASlJcNbmUaG6e4GEJuRzL8eNOECaYCd2C0xDEVcSuB0t0h/81ulCJT05d5FTImLbvrwpxtul8AteG8vEOY3avH/6M3OG84gOan+i6kvrSg5gQYuy0+v0QjjRPOO7yZGuMhqCVMxZmqBnoFUJ82hqxDMI2rSWQJ9bf+BmFugEv7Jrmd8hTZO1PGtjvfkKvDMC98h2XYCdeZbvP1ZDGB2OHLpDxFm9tgve6IpHmGc98evRMlETp1MPnyTotGz5OTKDAaVYFtGNEGZ/2j6rMIWZuA8FXRuJfzpFyE2nO48yKCJKUmfTgwcao+INTETxuwZdQvG1XA9icHiZ+BA1DCKjeVdKOO4P+bHK5yab5ciGJIdb+GL2mrzIhZxYm5hWLJ+qgFHsK/G6WlSZFylw7RAPb+znyAeZ2lT5jphco6LmSjy9aNNi7mARLNKOVaEtkJCRk1SMDuef9dwqB4KVZ15cvoooNIGDxtyvx1JRKE8iIN73quiH53L4DYmOaQQz4AjxqfRrxLdD9MfOQ77iDCfUkEkjKWXvS1v3w95QUAUbcwF/tBiTTbskXZWUiDC4rl9cGRbJLAX68lBJqZOUELseJoMl7s4ZY0qusVfmePRMPXu/yZ06kR3OpcuC1AgswFqwK3WGKxxyVuMcqSADjtS3brRBGa19Ok+N1ZwCepzgqWrtAhMavG17sL7qFDMWLTKHh1nwE=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: chetan-cicd
    type: Opaque
status: {}
