apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: chetan-cicd
spec:
  encryptedData:
    webhook-secret-key: AgCAm53ACWxI9N8iTfldbC0qn+1Tji8vHO8FxJeY8OMYg8wdH6Ecg+EI0z9iABTV+8s1P6B59rPnS7ZZzVFDwDLgCbLsORR98lTm9MDW9e7uM3B8T2r6HYT6haVXaPhWRl1RgcihNoGnNRKG1cZdcibqIV46zNMyDCa7FX/aTqXEYuc6J4ixEJ3NQHIzBy/iYea7PBRXSyNvAjxoQyB3+jMFXO7DoNrJgm37FWmhzlqL2ZeJIAPYbow04kVNS047dBIJOet7CTPgC0FjA6OU73iMVBU2RQvnFS0wLSbPPkq1zxk6NihaKy+kgnANz5oaQAYCRIvPKxAH8uPTpj78Cp0GunlC1eh85ODQm/wWpk98VuZi3ljF7sRvm9iVD02w3iZmOGOSTg795Yjfm0jGXCnB/iLQI94TFh5WPnE4iZPnhgUI8QJIO0IJLxkqFa7QscrGr/QI5tOWlva9CvwA4y1/UyT74IP++zoOpFXTTr97eMxgF1eZSLsW9J4tLPw6Ok8gPPp2um4Vod+gjMnZY1xHmBouu09UEwrNwYIKMB1FQKtKAVnrHJ+94V8T8ZqeBvYe7g9gPedDIksAxGVgkWhB6rUbMPYd/TNQEC70phRohrmDHHAk4osW9vTthrrR7Pn4/TGtJE2XMLI/AFeTcKvwfhp0eQZnnWFh6qJoj73a6NubJXN965gBsoBmd5geDWzPc+E=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: chetan-cicd
    type: Opaque
status: {}
