apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: deploy-from-source-task
  namespace: cicd
spec:
  params:
  - default: none
    description: If true run a server-side dryrun.
    name: DRYRUN
    type: string
  resources:
    inputs:
    - name: source
      type: git
  steps:
  - image: quay.io/redhat-developer/k8s-kubectl
    name: run-kubectl
    resources: {}
    script: "#!/bin/sh\nis_argocd=false\nargo_path=\"config/argocd\"\ncicd_path=\"config/cicd\"\nclient=kubectl\nif
      [ -d ${argo_path} ]\nthen\n   printf \"Apply $(basename ${argo_path}) applications\\n\"\n
      \  if [ \"$client\" != \"\" ];then $client apply --dry-run=$(inputs.params.DRYRUN)
      -k \"${argo_path}/config\"; fi\n   is_argocd=true\nfi\nprintf \"Apply $(basename
      ${cicd_path}) environment\\n\"\nif [ \"$client\" != \"\" ];then $client apply
      --dry-run=$(inputs.params.DRYRUN) -k \"${cicd_path}/overlays\"; fi\nfor dir
      in $(ls -d environments/*/)\ndo\n   \tif ! $is_argocd\n   \tthen\n\t   printf
      \"Apply $(basename ${dir}) environment\\n\"\n       env_path=\"${dir}env/overlays\"\n
      \      if [ \"$client\" != \"\" ];then $client apply --dry-run=$(inputs.params.DRYRUN)
      -k $env_path; fi\n   \telse\n       if [ -d \"${dir}apps\" ]\n       then\n
      \          for app in $(ls -d ${dir}apps/*/)\n           do\n            \tprintf
      \"Apply $(basename ${app}) application\\n\"\n            \tif [ \"$client\"
      != \"\" ];then $client apply --dry-run=$(inputs.params.DRYRUN) -k $app; fi\n
      \          done\n       else \n        \tprintf \"Apply $(basename ${dir}) environment\\n\"\n
      \           env_path=\"${dir}env/overlays\"\n            if [ \"$client\" !=
      \"\" ];then $client apply --dry-run=$(inputs.params.DRYRUN) -k $env_path; fi\n
      \      fi\n   \tfi\ndone"
    workingDir: /workspace/source
