apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-svc
  name: go-svc
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-svc
  template:
    metadata:
      labels:
        app: go-svc
    spec:
      containers:
      - image: quay.io/cbanavik/taxi:chetan-rns-patch-1-1005be975da88ea3f4982a9ce255cb9497565d53
        name: go-svc
        ports:
        - containerPort: 80
