apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-svc
  name: go-svc
  namespace: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-svc
  template:
    metadata:
      labels:
        app: go-svc
    spec:
      containers:
      - image: quay.io/cbanavik/taxi:chetan-rns-patch-1-1-2cfe26339199da06e6fc67fe91b1ca3c604b8ee1
        name: go-svc
        ports:
        - containerPort: 80
