apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-svc
  name: go-svc
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-svc
  template:
    metadata:
      labels:
        app: go-svc
    spec:
      containers:
      - image: quay.io/cbanavik/taxi:chetan-rns-patch-1-593713c376dd4fbca5956cb357a88bdff51ab623
        name: go-svc
        ports:
        - containerPort: 80
