apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-svc
  name: go-svc
  namespace: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-svc
  template:
    metadata:
      labels:
        app: go-svc
    spec:
      containers:
      - image: quay.io/cbanavik/taxi:chetan-rns-patch-1-ab5e73b66dbe5ecbd28efa28fce47a56ebf71625
        name: go-svc
        ports:
        - containerPort: 80
