kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: set-gitlab-status
spec:
  tasks:
  - name: set-pending-status
    taskRef:
      name: github-set-status
    params:
    - name: REPO_FULL_NAME
      value: cbanavik%2Fgo-server
    - name: SHA
      value: bb819f27fa45e160a321fe2e4248ef332f3d728b
    - name: DESCRIPTION
      value: "Build has started"
    - name: STATE
      value: pending
    - name: TARGET_URL
      value: https://tekton/dashboard/taskrun/log
    - name: API_PATH_PREFIX
      value: "/api/v4"
    - name: GITHUB_HOST_URL
      value: "gitlab.com"
  - name: sleep
    runAfter:
    - set-pending-status
    taskSpec:
      steps:
      - name: sleep
        image: ubuntu
        command: ["sleep","10"]
  finally:
  - name: set-final-status
    taskRef:
      name: github-set-status
    params:
    - name: REPO_FULL_NAME
      value: cbanavik%2Fgo-server
    - name: SHA
      value: bb819f27fa45e160a321fe2e4248ef332f3d728b
    - name: DESCRIPTION
      value: "Build has started"
    - name: STATE
      value: "$(tasks.sleep.status)"
    - name: TARGET_URL
      value: https://tekton/dashboard/taskrun/log
    - name: API_PATH_PREFIX
      value: "/api/v4"
    - name: GITHUB_HOST_URL
      value: "gitlab.com"