apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: commit-status-tracker-git-secret
  namespace: cicd
spec:
  encryptedData:
    token: AgBY0LP0EeRoljqdO1dy1OuEm7zOJ22dVKtm68VLc8iq52r/caikeL3QQ1cUnozaDyzFlDvSm7Z/CFRdGzoXq/+tsm+Swg7LehiIlSlF8ugbOIgiJA0AH81/hpj7ZCQAgSLQPpM1tiRyh2tz0918zeOgkhMU9pSbwvIPr/Eh8k+UfoZwQcXs2KniR+9P9zOIYgTrdco28QdvcH1YM/xhDp0uW0UnZxY2udQLB4gEOw085SSv4aemHajixY8hWXKFiUqNXmwhR49IaCbnBaJTr9Q+HWUNmtKLAKZdVMx1C+RCOyBmsiPf2X6NpHhlOcQTP6PA3aVb3Q+FH4x5p82iCEay2qU/X4gE1nGF7bIqebJCDAz5XYWDNxCR53iDe7TXmrU33LW5sKtcLVAYDOLNcWkA1g8DFwowDxdAEhkTegRyRalVKz00YsaommO1m6Z3Q7NbW1LaHLyWAS1ZGPTsVaaq8IiICuaav8/XMgm/glWR3zdViVVNWkHybGSNpEimYQ4+T9g3AHWnx3BIkIot+4FPisEBWb8Ys/utxIQyRiSH1cvkmJ3YuNNGOy7lwkkhi9x+OYyHYgVCgWxWirsYc3CZVLui5mXX1v9I6LzM8e9EL0jXiQ8BQ4LwJyDR+OOkiIQ8+wUoch2FkL15WsRDT2M/fvDw4B4tKKwn9Yf2FAkYi+LBx3XgldzTjT69ZLkP+ivBydWxX0su/csD4DzubxvlHRXSG3CGn28tg1Uc6wH53w1QdeqiSGTd
  template:
    metadata:
      creationTimestamp: null
      name: commit-status-tracker-git-secret
      namespace: cicd
    type: Opaque
status: {}
