apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgB7nJkxezpNhVC4yvGPJgT2D7+jaWNwQewq/taxnEkvIroetd41l+5XvOUO9y8scc7rRyGil+QvnqKmvUGkfcEC1UZWSoOvk+uJtidvfLdOjvhr2t7itRw8X3rQuVk4+HJs2YDH6l13lzooo+3TNx6icWC3CEE2BWf0sfb82l18o8bjLwa0q3Qptic4IgHZrxraGg6ehB0JfT5Su1efWdN5YebmR/7vjMUatLCTodq1xK0eYFLvsiPRlYkZ9Dlffwzl8mTDL1ypCjV4v4nPav1+tSW432YNd6Pmem8g3OMCxUzCaNWoUtPo2ombHgqKTcbB15WsUzBt6U9/KvIwgRPtv5V66+NAP59fqu826UJ+zz6fpSUffeZrk28EOJEv4QNYTFnA6xNU5l6a915oL5NtVkY9mvf0vpGR8A7mdlHn5UkxDvT8DwkD0cMa/ZE/+E0OIW4qUVheZfhViY+wpl8Wk872NSpSg9qIXipzUFR3suo6tqPPw6WsAX52C5AQZF07Bp68z/g1M/BuenD5vWIYMPED3kdnX/8xBTYTpUlD0C7GUYhdR/rX7jUXii0I6TbcTHSSM4kkuej/PPsIyYc2wlg/vDDVnbSZ8qFgno2G7WmTSur2kyDIEaZ905Fc3ehU/ZUFVGIB3Go2hqOwec9deUju4bOgTcrWb5qNfJDgQVZTqNJdPH4XG+SmQXQ3q176ai+worF3NyiP5CexU+4NAm8L3acwDg06cSkaSUcazdlJ5V6JaJP5xbGDDvSbCAp1kA960gtyNF5DVtNwSBpyHQNBlEVYg4oKC1Z3pkaWK7By9HsEIFU1KD5abpOkCfHtpJHFzflXiHk2iCOsL32e4BYPOQt0f5O9AUzFUmrwuIBkTx+g7nHfCEv5CwA2ySDcv9S8GnmL2dQGv6YtMnyGKqA/Leba+v/GBxIczrjCRVbu49Si7sNNnm2FQvw5JmQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
