apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgC6xlXofUebYtnLiD5WTB5CDZxw6DXc07qkZFgM2wueRKq/M7V82g7lIxNjczQXQo9ZGtujl5EiDjxtHRwfmt1MBPhkJeYAVGJ43XTTlbB6LJbKGKjbTLW4BJ4JObwR9p6gZl3wa5u0rvSAmxA+cALTjA1kEU7rrD2vLnQzI8L0pjLIHd+RpXJX5yHvGKj9kuytJsf6/MEF6oJHpiy+mrzf0GvrRhq57U1x5lMYuZlGMWYZClFOeQqjjgJ+/adud2SJITv+GCkW/lgNpO2vmP30ieOfwRb9aNGJi5nw3uExvQCi+Rdn98EBzPzIaGMao3XTTPrU+bOQ5U+/KEy2ZArmNuWVobvV4UWkNKMPgCqb1/UETFC0Sl+v2R8aa9+ZzCjrYJNS4h8i8kLGa7SBMeET4iUwg/UXFaBjdm1sbV6OsM8CYBnuopS4pVCl3G4lWfrcJ3xCFFnifEJQMh1EgWuwGuZRhUdtRm0JpB/mJCLb88924PY165TrZ0+xQ1tkx3pCirm+efWupC1EkLLIHG2c45GNB6oH/9LUxBu+iZC6MCk8mWc7cwb2LjyHChwEG6W5nzpoS+zPodc7Ex9RQ+VcbDaMxsMhSXzSHhARwuKQDtAIIg420jta6c8v27+UIj4Epwdth2yuONeqexcwrYh+Oo/pE4ba3zBq9QTC8JC0q6VgmM29vBt6n8i21lHRlDpokd3MaWjetSEITvqhtTb9e7zB2GcXp8+rX0FYswSSF4X80WZkcWbmUkQmLNVBfRcSFkfPsBW96A2VK5O61IEIifR2Fhm8L6HR2GG084yT7+Br4kpJDMa8xHJydz76LRzGEsMPI+xisMoGuYI67yy3hiTThl0WhAu8/odrSxj2CUga/E8gpcimqgCOf1hXTHacPZjxZgovniKyH2JCZP/JOsizogG+4srnYWqWox7xdj48ol5l7H4ZY6Ge6Bpaf7U=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
