apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBnhD9Ip7zBOTppZQmNP4wqTjY1niT7cqCWbMr/Vz2Vt3b9NRBwaMC+Tox7tSAqr1f0EEAsgPAjAdBSsvjfiviUs2So0S8Ajz1TKeP+V3YiJzQ8Z5QXEYlkqzyMTgoicyHssa8bxUIpz7iysyngJarJp8BgRIRNxmCPILN8v6+n+u5s7cPsHoL1BLTkjHjiaiUjX14QNY4gitSJACDq/B8qkQ0FCWJxg1YID707GERxnatH7WmK40htK8QSO5iQ9SAcUPClrFt4oNTznjfKOiE7duy0Wty/J2D5tarNkk7Vh711llbGfdl/RIJM4i8Kx9Obe3wCVcxSgkuhN+z9UHnatys90UgSV5p4Wg430Rj41wajhCsM9c8iCmfqVR3ymlgR7KgYbz6hXD2hy6JSuLudZt98FTubkdM1FsZ2BcLd4KCq8Z4k8oWPZk7l9gZS+ZJR+hV8jLRkjTCAWL4TQvCkMOIGyIYIwAYSrBSbWselBQvqUF5xvh/XKbOWdK/2QU5WSOmq0rq/2UmpwPsLSkDndTNTZBo0qfDfqTQrErCXZFzFzeZAOgX8IcX8AKXqubK+DiThF6G/tb1fEa8kOiulfE+aaaDVN4FGeNfi9ro6FRY3lQIZhoo1obY6r37plQMv05DUzjAMnQaHP4LuQTZEm5sSQC8Beri1WDCJi1X6L4KZ2kaVEtgMbBguaurEYguTKnpOuTGZwT/QbDvyG3kcI4lKRTrKgS1q/mKJ/BbNtGMg16/XNIk7iUW5rkf6j2ZN+S/GNyJAY/et7qfyTidEGVrapGmMXzSi9dfm/LIk9Vrim5SSEiERpYpChOnqj93y+MGCETjD9G0yHGya8XB9go4/IQGpWqYbOkgTo4+qcE5yOTgu82xcUjBHXZiGmrIfXLdRJ/z5GXHRNRrUVSUl2NTQq/hdMhMj2xxBw/9ELFGRMS3e/CX7psxRmQJtZoSQrn2sjDFQ9QR1fJYiiIte3bK4KWZknKaL7tTBrXAwcPOTTDZO9NWHhv+8A5+obGYhRHWIOIM488Ia6O4HKdcMzgb5SkOFfN+sQSZYvKaeMRdCc0dvccHluLZSexeDPux1bJJmx496OBEaXEVBixBcx6vB
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
