apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAZRvMAZTL0IgYrPONaHIA1RVcySdrbPJQZFgIqKoUTp0JE6Ap9Pk3vP3yE7JB2zMtXTUEI9pDBo8vgAsBVhgsbnOwsiIgKzho53WKXBPUrWSqoZSEbpLgs4JC072oY5NmWWmsZaA/qWGiYxsnFlx/gd3VSswMRgqT/kS1nASsz244pNe2RkziUm3XSu832KKkL4j0TPpSGarz5eSMbKJNpZIdSlNYHyzVwFYglbmAK0ZymunxuaKBYtVAIsw40fxrMeq4fGYlNZyPP10Qkfq5sl4AM82i+QsQ6NMe1fA332h2RmFuv5FYynjjYXAXRLivOlQHT0n3/L1v0ttrVHRdriQUKrSB975BUN3ZkJwTKsi6YC7n6w2v+eqg91Tljb+9OBqGmlmfDGgj78zfg26Fkkt9ovRI15PCorUgJxO0I1Uba0s19EdXpv6/VPyrM32u8BAtQko2adFWEp/9PSrdQUN0JVOJjcPZNEor+PI+agvjRBT1IT9bftj7EuLooxqkRJWx4BxFZqz4oubusd8IDqexw2M1j8ptua+o3IpzHcNmYWNNzzB1S3/QHGzbX2npCDfD68emAiW6hxjgU51djqQE1oCOCjKpbg91VZQ4QPdXQ6hVGLuY7yagNlCXSmPGmZLgtGKDoQ/KB9EPcFCVnY1I9L6klDaxoLD9jyMmX5jsir1W+B896dilXQTTw9g3/z/jx5OBQ0clO+GGKVO37qIL3/h5iLS3n4Xn4JaoRn4Dc1Wc8Ay1eGEKJGU/1SfcHAqbFiqTwDUVTGeirXx3HVMuPsN9cqDaeFQExDLCZ5X/ltQWPl7TXNXOtrS7T3qiW1+xp7r+TpcrsRScK6kanODXnHE6FZC2ky3hgJrHxW+d6ulixjNjpzXGJa4l640/sO/AimmLGFxtMqiDbr2lctHmpcAi/xwPRXOL5d8rtNE+pAnSnFBv12JIpf8Htkcc=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
