apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBeqwVxWnCORncJ4/CBTsJ08Oyx5a9/WrAo/QpaTZswVkZzwJ5ChUxinYlXGCixq/qr0E5cHTtSO1pU+s3cmLukpVk0u1EuI45L/blTiKnhIBFK0j1X3/fxuJeZk+BQ8TEd2FQ2kUNWCfBIwaPIwZiuwpPbCTQ01/HRM7dvCe5kSngdAmqAtucvtnYrMqf76TO/Ofqmpo7M8gqxL7V3QIXQjdwysnu4Sth9osOywROccJm+gRc8o27r64x7yXvNHLo7Ac1o5UBj48I6qau/1o9HsLkycknq34qa970HmKq9HvkKgfTnPweS/y5skqhWgoKFSXCTFemgD6q5TLR6m+c1IrX+6Mb/nH96qpZSDCacX1q1Lc2R58nJGrnNAh5N+mVE7PjVTzrxcMxpLPALHe9OWAK8/T3jSXIjT0U4wR52lQwsTFZE6vigT9Wk5OHpREoiS5dRt4elCMepdf2DT9H2AQr2L0hM5sHXcwwDMi1x/7V7YHCCnj/e+QkWZA8t/vIrIvHNNOYuqe9VFQjEP1DTrkQZ1IL2X8Ay4nEs25ElsECLlKWddbf2sS2y5OnE/iV+UMXIrW5+OCAWctoRBhwcTQMRqurxP9Rkdq2g1RKQHMSfdv28rn+ejyGPQPjyGSEiuId98tdL7dke403pqGOFg4KrExr9UU9wjTYO1LIHt4oU3Jr86wpdLGEs4DEmwhYqd0El1GTUEf1C5zBz81fQxg5njustbr33AXshRVpEqtDnIUiTio/PSzJDPF14wrWOyvS46XcP7XUEVeh6t0Y/LwkmN3Nf7MZAIl4rfpluqiYXlp787JJhH/3ZM0Lo/3RgZTx/hzFLnemtMHfCMgWVctHCgKISoVEx2/lzUtFVeOd5Sh8Ycxf0230JWBs9sWHmYwAXYlWbMqw5bYF0tHtP7yILh95rvnpWsSVzVuYoSNNeA1Eove5UaDXzltMfxF4=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
