apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgB5k7CFXBeRdrkMRjpfAfpf/7o3Slvc62L3nQ6ygxBkO7feC/yseVmTYf6Mp+C0t1AKfyZyekB0mhD8TV0I3gWmDhsxv1yMcuQ2VCDWGdpjKH8MnBkwpRIr14mDRIZbQb6L/K98qsu2zUwEWKdXTIp3IXirNhqJW4JDiGck5bSmbaqQDSB5hH0gcBimS04pUqNbd/OCgbJfKUyPqLAwWEaDgTlsrQ4EvTUvulDr3BayBsSwaGpGc5tjIy4Rc/GzurPTIXxcmITbsMvQuB4QvBfnyVeAeBsJmvNvz9JEFgXeO22Mdm8qXwuszgWsRtJ597xFjQGomo+b4RaNrT9b2PTaBOHl0h/8BcVy62UyThbbHfbu8AHbktRcH0ULNiLo69CwuNv5MnZHhs9A5oWGuh2gftM9XyGHQvZag7IUEZ3ZMFM/bHM20cioD8O+TPET4BN1HMbhUTxTVEQyxzosk544m4OxOeQD0gQ4Hcuool9a4c/BlmWFxz1uriWcdHJ1p1rTKu3Yw4fhG9woX3fZqZt961EwZciC0GmccYpMBTtrjNX03YRO/JleavnL4hOrXxbS7JlgNikSGOF4FuO1E+4BEQ+Wmbli4T1fXtKGQLXIkF1hqWNaDubbYU64d3EYfEUJEq4jaCRTm0nfzo2cXXI5DG4LuxgIl8/4X/jWYycppUnoG1+zaY5NH1FFtxvftl+mQtNKTNWsZ50c7bdNP41nWRypwKhD9SvTz0EFiNFAalPqCNyQxxtfyJApjShb2Z6YJfPNilBFSK/QiUn8ohvbT7E7GiP4xvHab24cgQrXYyi/zNSChJ+uubq330mJYURk3zMgmYBLLWtlvpZt8eZlYUCXk0Arx06UPfN17SfVLmnJHUkRaXCIOOO7LX3hmEvy2fApQf1XG33OLCC+dta6mIIo5q8GTKjKZzwq6cb6N80Ej7LVXezGenAS2KeDXrE=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
