apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCGBIif9skLWD6IVKiD2vQqiOFcEGK2daJgxAZ3jcW9AzDoQc84SgyUdvcsugAdUui9e3FbjJ/SWR0jd0ZzV06kgivfIniZr2N2CRzEFqV1XlTYherlnqqX5CwC/KnAoxCBzgoclqEdNEuLuHwg9EY5fuxGU9IAX38ZiNRkfoFOaqqGpT/TdqE1X/DQEqIsibWCGl5xEqGD8LK49375NKGno5xir3tuwF3ANQTwAKKKVSHf9hCzsBvUtQNToEWE/ZfcgsGmaRHCXxVJMi+3qb4/+M/QDzhUzyMYzxVBLUDBk+uqi5Czkkdk/sEDmCJoysWJawyR19zbjoRNXMeNT6UuOK3HO7LPb/+vOCQeyKAcAj6dnKDm+1VeBeoquXAGz0JIK2cmD74lHHLVtx+lT6jvAmSZ6OOCOmxG6xWRXIwVIhqej/H+cgmEhti9KEhIDLiSALwMz5ic07RcSTSSc3r0WhCk4lojkFOcCwZZdzNWr3CXG1efPnVutS5EZt8cn4PVZshsANgM0QIQIyJyqNZ+X8Bk7tpl4+pS9IDx4HkiPj0Lla8PAxlorHqB0pZA/h63IyT8wPrZpQWwiW5UzZmTS1SdsnjFo+KRmx5BhhPpgHhkEdcVJuszVctYrsuIQGho1ZmQXyg6wXFGeE6KLeBJ7gvKVgJojvgEgyrZ5fixW+zDl5Wlh4oP994ixnYu4XOECRE6RVkK0P18f0ZoXg1yjw7VDv03beAzmcqoDNasac3TGTtdy/DKBucOIYUhmjZiPbdrXv+LhlaVZ93iEWHerSSxRPBW65RObdXMcmB+nOxfsAZHYf76U9QDhvLX89+SgIYWu1IPhN6dVu9Lahfjk5MkhM2aeFx6bRFi5BpGMCOubvPYOb6Mx1YD055fmpmPykiW9WttOkbrVDh+PH+mGAAAe2hjGbeLAYBKad0qFRI6nIJ7p7O+bf47o/JUgKALF7t/40Ra6Q/mIWGpLti5BtQ0bgEIQbfNnZMCl/lOsP87raseaeBxZLAwpBcV206w6waDYdzjzyPRbKvWe08YTXAVRE3zI7jKhGuPziEg+GneHfnbti5TetY+Pl3kBYsABm22An5u+VjR3DDPjpllF55u
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
