apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCTcKuANJ+BdkfTsynNYzaFmCsnQhMzckldOglfR3Y1g7pgb/EB/gpfFoIUdUonFDG6A6mBEn64ka1v6Ov06O++7aiWJ+nKZudtFD+GDU48gErR/6c1Q9HyhvbUUqbL/I6TcZzd3/MUx+ufURuLfFbNKo4m0rdeZGSTiqPIzqp7jDU2mBCYYeAOresMy7tT0PePa6zfa0tQQ9MuAMZKT2CNIgxFLezS9jKn2C21JzcHFTOmM+lJbS9JJiKur1DJZcyWkQULNVo0U/02bVtHcluEy2T2fy72ArS+B7PCm+KuH1/GscIIgqCMlaBcOI950owWKULpTeXePKrbOJnr7Bkg4Dg/3T9/QmVxYzzlTu52L/jjYi/UF3mc2MLOoIXkL2qJaXufoPcK7zmVY8OYc4yUUykYgYE6UyAPeiBSigpnsGldaAU0f5Keh6DO3QmSSLnTV8jweXUGQWU8HZNySc/V+Bg7XEG9CBqJ6hMGSDRhXU/mkBxkD0H0saI55178W08r6fmkuououbPAXBACykAaUctgptttgj2r3eOv8xQXcp3MKDdJjcLgqnDQFGCIJBMatKwvb/0/P9/fJYrYimmWAt5Bxh/7hIvfLiDS9QvQb8qWaebe0SB44Q4yexmcfaWQmqUaZU4eWyCe37NNVlktPKPmC6o8zchVDlQrn6uigTgbN7rDIlqlYiappiYAsX7v1CceXrrhQSWRemIn7NV0Jpop3TKr28tboJGB/ZjQmCmqbOgMsQt5i6agOcE/ICgny4fNQJ/IMPYVkcLiRqlw2v7f5lgXq9hVRiWsV0Ut8DOlkQzj1K3TE34zzGFfHAvVZDBIwbZjOliFOO60GBNi7bS+Oe4fWjt8qroIcUsF2/bIACDIsndO9y9DmbZ070mY5sHcX3hNilBzrvbxslMY53DSSWAB0UW1KAy/Ri+q0Xy0ElXj7KhY0DDWXqbBxIA=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
