apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBRQ6OnXvbwxB8aFnviQ16aOsq9PSJCAzgApV24bUBSpUZJBqPkN/RX7MJ8IuybXIIykGYRzOdHAGJ4OdBsuGvye21U1an4iwPdYLZeF/jE2EGyxYjaalWp7h96xgsvlGi4ZlyC1Ak7nc/U3ET0+3AupC9gcoTz8gUBSm9Zd9RpCOV5Af9wAal9UxJIAeEXM3N/KZ+oWTUlTXcbD8Ey5pRvJYCA4lpLOvxl5oxq5fIY7uTkAiS+3ra1PkP+SQVvboIHUWEZmqEG/b9yK7NYCetMuSYJcsore54bnfSK1v/OpjLwOYjfrMqhcou00JTbXyBQOieIN+1YGABzmR0NITSBs8gZIGNFCAnvEMWIg6yUYhkw39oJbDC0kBGRVxA2Sq8FYPnjaAXKKJzpk/A80uH0rHNy26gUhgwFNIpoNpxeifJ39I7LP7+NWZt0usrqnC8T+bMRAWpPuGfUtH5nGg2SMwUYH1VDokDGg+KYk9DUTmUtuCWdxoV8E0kDmibC3JIQR9iNx1xsa9M4jToR+qnOtEjs/9Gb+0PL14qU8oWX0tSsr/mPphJuwDlNcKhaOadh/7E9l8jBw81msNJ8bMitbalg1Ei5L08hw1w2DxxO0e8DcZR3H4fm+4F4nFEWncWPcWuJVU73ygJ4Xti9rvUglp4K/FulWKt8zema7i0SG1XuOwLgnJDa/A3DWA1+fogLQSEg4QXieyi7MzsYWOKA/nnrvwBGquQVM1utVICP9zyS58B7WQVsfO4lL51rgldVTB71+2LMI4Hjq+4ggC1TLKuHE9sgE/riw7MB3Afksz28vPiKWiDy2KFxS5ts0+HPRbiwtD7yJVA17Rnt+Jk6gSHAacTc2hV3rZ5JTMyBhffziVCNt3G8XsKn/woFu0fV0fT2jWQx6nb15G7ndMv86mmxUF7d9WvbeBK7HHPcSYHkRK8sHz2aFa3A+Q+R2e00G4VJbEnVTl8Opk2l/oMmYO3Cka/QK1j3u6qbwuQ8qg5MQFQND8IgTOvPR8I29k/AZsvDUPZzW/Qiz778Z0XehGhOeD83Xj2sKxjOCo1qkLruW4yAFtmOy2nozv7e8dpMCqhlKgGF8F2lc4LeGmLvuLvy
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
