apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAUnSghNf9GSRcO2a7islgNgNcgQ2n+2oHjJwfFB+PEbFeowjxUXS2L3LXWecR0Uuo1rTluNGsEC9XPgU5AXAUgu2cwPHihDCZqAbZhC0JNf9k59jwTQPehNsj1j12ONiw5zItSr9HLnisuu3tTpX469RJLg7RabEz+O4XTADlqmNWS6PZLRfYyxG2fXJ6v8Wv62d71Np9r6DxcMJfLqwqOoj2sDxlK2SP92Pxteb4HsChvk4FSahEhHb7MLrb0J+M76GmFKUvvxZWwgf/boMLrExb8kRPp3RwHoXszKMe8RdzCwuVymDReLgbWxYaHUgc+Zpw+42l2mX2t/iJDdjkXO2lFyB6OB+zYIBeP2YhsyefFMU6WVIIxoZOcRr0B5jgYIAHas/tHX2yVYIY7djgeaSFGNwGD4pUQizr37iP7I3m1HR1rAJ+RSaMURyMXn5xz4h5homHF9h1Woo6l+FQ7161xICkz2suIRl1pjpn2AZciG4zcXcc4xBBlYRlrz9ZkuFkYwexTiegbLwiHZA5Gm6d1OBRkwX+gSuRzW0CZjC4w2MEAHx+Sp/sTM8EGx0JDLob6ktdMjynGEPLb5n80mGEgxpHxz3dL03F4as+IvASf9wodIe412lC2jG7Sc/2vdHCZmdhkV3+cZjAjKu85Uy7TiGzO0H6nr/263k2VStNNlVqwkqBZlKG324GcccXcnWDvbqDtpW4e9UDsfCgeEIjtBiOa3JbW2fJ/WCXxsazzTQz4mMIUuSJAzax2hslzhterolG3PsEYQE5phBj00VerqDefBi6FgszvTP9KpBSMbrEEgOC8anBElVKx3oNaROvvw9ha1Wl/0533fCZEgCtJ5EK7C67nQwhpv2iao5JvMW8mufnLm+XoBdwOLeD56bscrSa4cX17IavMcyAgpbB4Lpx8OqapKpPrZrrSbmu5xZzP/z665XJUzHwyB7sGjTU+Lz0UrqQY9D6Cg5kY7F76jRfh5eg1Kw6YsOVRYLnBHOp1IEMrPz4bBuL8KBAyCRO4ErjlPXE/O6NL4eCnIrWfiWLeqLa8Bx5Q76vx2Qjgo7Bw+jw8YxvEyRG3wiKxRvO/94ESMeG3uBSmlHl83KtI
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
