apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBy7zkrDIgHsiA1eaAbJW4Km11JEuHNNwdMDR1Vm7zvYbswa2A+SAjjUOxb7rsJvjnqzEwKiChf7a5R6APyEGLfiePNzdc/wsp38MIGlljHEocms0yX7Bm8QdNfplAjxAPfGLiC3ioQKcjDF1WCbKq5xx9tlIfHKpXQi7HjHKtVxsqgV2Zpq/j1SDa0h4lrdofe5psYWLEQ5S/VkoUec5vnnDjEdQZEccAeqL6acfTzFPkBGQDu5ah4Vz/pnc3Li8I8tDu8rXmgIu36VNR7RVv3Rp13PXBpl0cdwDSTMMB5hX4VweEIPhRmgDsO0u9+q4fzIlVS/Tr36kFkfywdf++n8W8feQXMEFetjRx8I5XCQ2lGkwOdYGEEsQ3QkbmJkZ3E3BxkxNgRZF/BKf/2jaxwma2u9XFRa/md7HPNVFkq172akDmT7MrLVQoRF3sSKsFSGcGRD1j57UeXXY8kY5HRypWmC1+fSO7msOBp4JUxaw3gUjmg/1OO6XXX3GJf9fDZFyJ8IODFxr8J+FEBvOqMwqlGHUMCN7cAg3Rq157dkzbkKTtLHnXzq4g8sq+5bW2IePZw7tKVD7/Rw0qfHOXeiS8GGbGoDDVTPbbwEFHFAw26fjMFsySfxaKjWR3nRXob9KB+I458E+yvptjvBz5gPJFZ8jM1dxO2DDOTg5F1Y70G63B2+7r+oRw1RhpcxlM5bHasrCXaqy67qJdH+VOcXL7fkXHP8K2ggb8sd9WuopquCr3sUe8cerw+DLODHhOmv8aY9e1+bFjAsxYg4isS12aID1QYNr5us0IPpBXz0bd3x0lR+um0uiXiDjsacGG36atLXo1mifC4PlIJ3G1Xpec8X6fpLoAK/Dsj9AJaaWhEoTAb5JQChGWuDu/SqAByjV2S66tvqDWGjtH0ABTXlJoFhmr4i+6NM6UjUVm+7V2mlh0isZzj9xeYWl3tCZ4=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
