apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAxyI/o69GGlU+8w7HUYHcLgcXl/b1aMv+iq2ADsO2XofLRl+6HBfFgsJ+pJW2dKCjquSn9sSiEq95bDZ0FSaajFZ4NabSiqHVB7DxtR1RpUgzjEQLNStUbquZ6Ft4z2BHqX7nMGKdrj9cuBx0lS3JkMDiSbl5DuS4H8F8kWZLBTs1tl/GaGleTUN+GlMdiejkCaFuRHeJMfzNpB5azxiScKziGX8z3n3ZtxKHFeEukpk8ngXKY+vrhI//lhKRJFx85PJCGwuE5keDYwqbreNf+yH0jla8OMimgu9BgR+zjdDI0VpiP4VnmO3twbvDgvQ8WRqGz4xOHKPBao0LhOwwKN528X/4ICeEXWQpuhIA9fkRlVV5oCE0a1UYXPZCqLpjNrb1Nz2QC6psqLZxNUAXUNgytTgdbchB9Byw1E4J/W5V0WhoXNDq1tCoMkVkDNfwtiVvB8L+x04fZAfC8SnlMoBdz6lIMZD7LqSqHqAbfnsl3yomm7PlTRQPcQo5cWRPYfi1M9OY2UPu1WDCspT7ODgaNakfEbZPysox8lSw4e19xfE8Lh1VWyyjTpQ3LQndUVMzzYBZr9WAvYZWHDxvNWPPo0OlJEyYarWRgD3MB6wt+rgQxhtIyvK8m+BmqNRiv+JJSKVmVma07D79X+EeSS2Klf9f3Q3hPZnyhEhmxxU1PzreFFWQjoUJ5kaQjdFhwJGcLAZ/r9DT9LxE7CJWkmwJ2HpM+VoBlgFPcweaUItzmNulrDcWYyhIYEyR/qpNzBoAMVFW5daHNJbS23XaVBPS7aNvr7rWZBCRktRpj3FKpeR8WcOCl0j9P/geDWR/BMgsWZbRZhPcw0n/WAP775EjPvwe5MPFOHrBYF8aTe5cLw1uj45LeF+4Lp/mo9cHUOk2NXfxjlPZdg0c1qjxY9bfOMiDkDc0FU807XwuG3N0oapf/Lg3iGdHmMeHsKKw=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
