apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgC9mgs7Y1r+JqHUYNHXWIDLnzqf/7up3aHrTFdaT2CeUZyrMmEkO6WaYLnx/pceYYy8C64qT7pisdpMlT9zttDNlo22mMCLtPj8wwjFgyYKijvHX81VbXysnBpcwagO/UeHUBbpiAEbES2PweXXhR2LOA0Bme/H4O/gnehpSFmYDnNmPVLTe7N+eT+JPt6in1cS8t9TOaO3MiDQEGAk9Rc5xhw+EJztnVnAGsYFR1slcRGIPrwZM4DtQlge2uatAfQ17nv1oUfGaVlmqF2uHfMUhieZkUny8y1bt1KC413AdT9sy+W34tDg3qwb92MxpzasqdQx2TWv7MlKA6nSumQPr+3uINzvG9oeTMWIf3RCrQFYUTJajOymrxhGn5kEFUNr380CLGxoJoIrp5Q3kthPyxzL5Db0Y0VeLj+N2NLh4XbNhjUgqHDDcHnqsPp0LgRg4uSIAUbFKXUy5b7EHZWZbLHjvUg9Edbbrue8k3LmbzjOjb/zrQdoLuVRB5rewjMlZwo/knRL9tXSOi3Jc5rWm9U12mPKXh0YP5bWJ11MJVizqAmtpuhUGm0FU0j6M+RlVplu8RE4m+1KeT9rf4u6HOoAtwqSFYfFLtAAfBbZHauIPCeNmpFvjEV+NaB0JdR+H6Y0qABTSDMmQm84tdoSWrMxRkble+43nL9BCcSgSSKvT8JkTNoYqs3rBzrWmwAyaB339ggx+jGL2Mf2MN3XVewu2EnIODVolrqNovnlX2rEWU7t7yx1IZBBB2+sa61M1z2svLg8mFOEbi0pOo3vJVZ6fT5AExeL9m4Np3Q9OyOccM/LQ6eC7BChinDap2bB8GEdgE5CwbrNQNXWgq+ZGV7e5TIBkvfj7A2OIqcrdmVNkyjbMiOg20WnI7PEl6O/hfmTZkxa6PEi1wWyobb8AC4tid3pd2xfhEfqRreTx0t3LCv6OUaCwk8Qhc8Q6uQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
