apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCfAUwcPTQPrUICDaAbHM/+RQDpePCtgAmsx2cWmxjIYS7wkWh+J1F/VcPvbYNl5JWeSqOHQ9kQ3aSI77pSqN4S/sVJhkQtA3E4jrduyL7jQwupY1V/KBmHdXFQZkBCQVUuiFB19vyxaJUsSef2NJG8fVa9k/Vi4mXg878vXSPiZxm+4LJ3/VXHRoj/GTQqt0gp9vvqFnBfS5tM+X3bwf0TuCNVIBL4ofJAEr5hbwzmsX8bgzDibxj8Xy07h5g4NpmR6L/7IWwrh9sjxnLBoUk7TaZIxuPNgdzHrsVIphe30XErMI/v0Mh5Rl/wuqOb3Q2hakWiAt2qu+7zNOuB0Z2HsSVwf02Y8lVdzCqj5xKIPxmNk4BCoeWgGzbNMyM1C1LNo8jaeEn/Jt5d0cwWM3X+rMJ4bC605PTPUVjZqJuwgI22sX+CNzSvyB1HZgjqNOMQybVuX0Bb5Xk+JWOmFR83v6mWLrtWQljzIfTUeIIAj07kmc8PZhgibJWzxZ3oOXWN67guJ6nmstIHs46WtM4gR6jf/h1nBrB7DEbndPMA8eWYdFkgtSuvg6x+o18l1QvzD0AXF42eUKtWX7s4WXxoVaJjQlUamWGT5736yg7SQa6Ir7KSJNG4ctBtm12SEW9SIWLqBk2vN16jrgdWMztL7fbea+jKAjeL4sLFRK+avQ8+l++mwlVxN2FaYZkjjgmJY1Cl4laH/Q45U3JYj6eZNPBh5JHs8Umad/L4E2e2S8CH70dZXbdsn+7nVzxtS8tbcXClDIBz2rx/39LBArAWScMwDbE+0P3m6lT8z3iv0739tiqiQY7vty2VtjUqP6CmdTNHlo3yQpM50yNyGsZpi0auEcYRi6G+nvBa+wTrgiTn/pqGiB2XxVzrhpJw5+sq3yyikTvpqFV/RSNlhpapsRk8kZLg9nU92AM5vrpsvJocCkZX7mGD2zmDKaKCbLs=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
