apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBH92vSU1D06LTriVe8U6ag27ZkWjFAS9mdU4aP4UNzyENNAdYW2M/935TQ9KFuTj92ZwDmw5KeFEg4Ilw/QN1SRG2U6YsHK8vp34wrRUOPpXE5cBWKHGo2SjVd5aajDxrpYbjS5r4R8cQONhzvbFKXJ9nVzxt2YGqlD0Lj8jUdA/HwERBzScqj6OdSj6pkYjQiHVIC4vFY8ZvS6wIKfApfUix1gb4g230ncbaL/Ah1m3/D6pgCVd8iUZYRiTpRj8JWw6/hc/ep1Vvcldga+PKGwxtlb2fsTZisVh3EiM2lBqi39VVD2HpCPIMWVZN+oyk7E7FQPt90NMO7kXzcdib8pLQHJg/PLA8C2qUFkn+Nu9Uw5yJevLndRfPKiEsV9dzQsnscXT2DpF2ohVSCk/h0xit7U/WNIOA0D6KcLmH+lg5df/6ZuBxj/1FLGyHTpn2Z0v5UhUwXGdI24vKSCZElxBJOz0Y3bllquy+94IzTSuaQpNfhTVeHe5Z79fRokMkBXe/YOar5yOV2MEIUeb3E6ieT9PtM0mYZLz/3QG9mbjTCbbSRui89ku0Gjx15H2xB74F4sAjy2wMNHDxSXitZJrNrmP9h5aQTnlGsFLo/i1UvXSri2kmNgSfzkKcixSOXB5tQn46WoSPsjJxnvDQqDLZYorBzVHXXTYbPui8ISQVQkrFCSpD3vn4GCXE/ZyRVYzG+1809CTWtjNx7aaETq4DF9tSjCud1RS9cy6FRMLQCdHSRJbxwa4zg/g1Naaab100siprnxK5U4NJixC2B9Pr0YXBxd+gYlxgiEiKC8SFZFZTnbH1Wh5Fn6cyIKCcrq5rpqrY+oaQltXVgcqO67Nxz6KWfPGzs6cv5VCRwd8sKa1Xq28+ggqjgOLFfraeZND4XP4FMYzNH5S8Ju6hurYJz4h+2Its6PXWDrQqPEVhKFmUy5rbD8SRQsn6MHJwyay4NDx+cbtew9mnbdCi9XsydmXf6Mt9HwpCjMSzP9FtPQTz4MJp+HwYrg8i3SkYB7hVZUJYBj7qokzpmvYIBtNm+jPynGoHUwfkHY+x81vCqWZkrF1NzgkVgmHbXgs/vUtAeQuYyPI4y8FOlF4Z0XbA4
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
