apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgB2VVduRkR1rHASUu5+pEqeqyQCsfDNc0bO/g+kohG3qs1kC6Uj5WYeIqqaiVSVAd90vjF0HpbUpvb1ET/M/fUPoz/MASz8yXrknGwlzthGm3K9jpMRVC7KjT0ndlSy6vUPke65s0KitE3IBXmQVoaaJLL+Xh9oUpqIicWZp5fTAbRxJA+VGhhbpEMP/vJp3vaOPF8wct3tOrCTquKGPr8HCeavzsYZmIPoM+DwtTlgbp0k21U8ALAib3bTcgAKMdvSE90wHQRwtAcfkgu+y+fMvGr3VYsLvT4NzJWoolwb4MOeylgYRlfj+hrZAq1hFUVJS1d4gd0ecVJPFFbzeEivaDbc0Y6V7/ud74wiTTuN9ifAUN33EjJYJkgJxS91NE6SOr8LXiwMLcXrkhK31YU9IbvN2C7EMC/XH1R9f1ZhVnfiPInU5Ei5Ya0npOo9TXadzQcRmKQbxLIqvXQu7XnUj1rv3INao3Nw4Rc0uv3TiI870UOtsIfHDeEiW7o0Ts/BUlMvYICQ77ZB9UJ45jYZYyB6VPK9foc/G+yLTQeqaE27MCtpWmhsSOSQip5opPplkt6ZInqHb5WO5KrERQ5dRSt1suhd+/p1ZFLfVwPxVcsyuKKLblbk4Jg6tkLTHIKG+gtYHcT7jgXvDVuvO0+P7gI+iTChYvaJYEOUQ/rIm8/3LtaVGKGuszvM3pXXTxRQLHmvU8psNTdN5DvBzxDOlTVWQQteTSbbR2ZpzLG1vDqYn20NhIUoKkgB0RkUkS/nm5Sm9ojdudY2DWLbmMMQH0ZfB43vMUQGQJSlGSmMzEzxUxgW+1XfMp0tnyt7hRFFndjJIlwvjw523E3q4EPeILCBzuIUNqs6lVPCPE2USv7iq4hngVpC+ysxyAFAa3OZJpwZ5VNSlJzTSCfUmgLmfDxWN4SH52gBKYdc8FCdo+cNa/iHk5mRv639OLcwApo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
