apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAqwyk1L3dyYdp3hUaF8AeI2Ndz1KTQaa5kuFso0HPv2jkC0/1rZjDqfzzaGe2amHM66FtalAha7maRpZ3oO1l3PJw+p2n3TBDmD2jb3z/hCwhc2GQVgwOERv/V5KpGv6rKA3Xy8EHWzQ3TuGCmL2b3QZa6m1rSAkloBdiZxRXnr1cM7hCn3MWlBFtymgcm8qkyQwBqKknckyrv9+17E911XREwPC30YHAxQHoYpDQUNBYt//VIULTUIbQKWm2pGy6i/pVvgVCXgWgFVabqdcqB6aBsZ2v+RvAXe937AlIyEl+w0qXB5VsMDjnqaDD33kzOiRmlVIn4dUjL/U9fFrNW2LK2BK8q//G5NR2WrwzI+apQGu+k5+6TCtCTpFwTDs6MjUoGiX4y8zjCPLiNi/g+yU+TFEy0sLVrpQNWKP/KlfonJ1h5dzyno6DGwVN+eiMAbQgRvEk9eRZqSJ42D5HwTGsbsPgj5OwQ/I70vHWm8LZDbQz7JD7ztYcAPbuDoo3RxKbF1wZ/t8RyAIw8OzE5edMhuBm8xvONnIX5DaSmvj3NXGA06skDd/7NwBl3KCB39eYJtkNRl809ztjd5YBkD5KfxgBPvb2KWH9VF8922708P/NojNjyHL8Vmy2mEAlH4xHqshJSOIZ7v99g9qIzTyCMtXOVFdtWPOTAD0uZTahcJ1+JzwdaaQGMHl5loLlFRO8jLQxmJtSu8cK+Nd2T1K6mY639bee5vrtTkHo66fQAA6wiLFj8eeP/ok5Ya770MB9aPOTagpYiDgpnQxgiPxzNxa52JGs49KOWncyhGNbsTBQ1QFrRVdsG00jj2vkzPkcXNgmPkOKaj8bDIlvTtSq8w6Tp4TO49hSEeanfOjSxvyy6uArvOl10XnZIWvrLKRD+ynEiShwKzMNBTrHe/SQrOrkSQhooROXBez6yD2yeK7gcAC4onbYPYMePFHQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
