apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBGCBjSX/IHnyAj7lNSu/MbxW8Ttdcag21cTXM+wC4mUmhFJ690Cjbmo+tA9BrdDLHBnnmSKa+Oosi9HG2TBl1ozAiQnd4rgdd6AY871ftMzo3pHZU6323SEK0HdMB68LPtymRQzCu7IqsnNe1L7bQF7sX53Ai8YbvCjPpy9oVqUZMb5ckJZ/Q2Xi0PHQZcHWyJWnNY3GGQJKhNHhMu0XvRqrQWJG4Cd3lAgempk4TBwQUtox2x6ijUDSn+nskbe7O4nMbmeMmLI1fszr+WCWfk0njCNeRFcbze1XKj8Gg5CLgFUje45XKoYT1sNEX6sizVRCHA/t3m6S/A4vT8+R2WcUaCmNEBCJMdN5NgaUsObKi8mQ8a28Q8MXhJugAdgIl0l5pN/7rwM6lrV0fr0dYGSJYy4HbJWqU7Xu10i1FLSww3eizq5GN3iqgH7tYCXnDRXulVVtg5q0qcGXOXUGvxihxP+ExMIxOQLA5Wys1EItlwiFQsV/X04Iy8CmCtDk9XqFOmUjemO5TVhVsnb1hkv2RkCJjRzUgjgQZNRrcMHsvozm+Mwt2NuxZL03TuRHc/2G7Y6N9Gx3Ct5h6HS2ddPyQyj8b3/VOAuR3inGyJzHFlpHmiBrrjWDEbizpmh/h3STnFpF3mNq2EwEbgqDv/5P00QFzJ2ZYnd4qstYS2Gx04F+x6RtmJBjP7yMVHwDGPFIwmuv4pqWBhC8Jn34o155tZE71WP82nc7aoGu0aVEc3qA5Bs87Zzh0YHFzu8mrHYX+hky48SaA3NutIpglRcS4U6idj73Rejl2QAwx3hYdt+JVDu6a53B5Fc/j+4l1WGiEqXpdQ6n+kjCHdd9VNjDvkoUKKVOx08Y0YnVfp2143fEevtPzSDjhda6CFQti3BE60td8WK/H8qfsKTkZJH+Nl4lh8e4cv4ocUg5HOZM+e/ger7F+ALZPDZZFJZTY=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
