apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBBr5kSeE31hr/9ZajnQ11v7PaHXvhel59wy1gxrpXG0FOBpkX56T10jkYnHPPEJqUdfz2l/cvGQLDi6WoaeviQbi+/qu058/kqftfatW58FX6jq/jRneakIvYRDiYANhUiYqepd8RuE9asCq2AFdiFvlNJR+PkQ6qN3ROfflHy8oOUT/ii2nbZJMqxdkypsYsiijYEKpj5jKkC00S4guHPMtdNr/sX7c6OAuJuFB7m/yQypY6ViyoW7J8hLwbO/MFJBfjpjABqNIvMg3XXXZCDXgTpXJ8pQQg3/hKPVdMMSEfeJwjihY4s4e50PxMJ6ky7qfKBWb70n0KFK9VNZRPAH2D9iuYAnctHN+uQz4HPGvoo85kEYFaen+Qi7DjHZAgwRCzXwWkt8SeecFC/7sPmSoFJxEKEONkRVLqkNI8FXRRPIsPIKX3O8XHprHaQNDj/WRf3FHf/KPnz7WFYgVNlvxUFPpqM+uYJu35bJ2hpLhEffiHIrHtCUaEzW0hQOFjvOaf5PW16P2BFz8OkiGXnzMtkgec5b0MFywA9GCXkMpE3PAetihzKNuXRU/d1a64nhemZfV/Z28b8jdYhUiuyyDNOtzUTPEA3uDyDV//2NR9PLE0M/zMomqLqAzSm6tzfdnNE3bGvYKPzewm78zBrywGN13zubyAdCkpaOpobGB8uIonfEavcb5/fpM1vbBOxyexf+SHgij04XfcKZrRuGgOueNG9km0EiwHwWB66kKerap/ra8SudD+Zao8gX2PvdD58ZRouWWvmeAS5aqWjDDN6oaJTdmu7zpGvNJgW29uSFWq10SB0J9guMQcJoj5GZeK0oWSaxiQY0H11IQTlbPKU4I1jvGnneE527wWPiyFxGxXane0AAjS1uDOsHGvn/TxuOIXeWxYA6cHqjvxrDYbUy7V5HazadkiO+FrH/VOFiNbTKdem965gcSQRGQaPjTsZH4AwG/GxQG6ISQOA4pu8D4kkDzpW4T8vwYO5f56LTRX3Lif2bWTo8LyOmFsCQV34RRYZEbv82cM7aL6/KuvBGsiwqtTpRuQEbVld5CU8OFT5XUxHXdaBNV+3X3YUVIQ0dXpIK/8FsYwaSNoak7Lf
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
