apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA4pK8tDDhOtlCOCiOH7rUKAEALDF+59QqAMt7cJPc42kI2XTjsM+L9RcbOEWFQkUDvT97lXx67t82C3fl0yyCz3GlPoueP+7ZWQazNL4cztGJ9OTSACq6qMtuBmJmEZccb9LsaLdU9tLF1U94j0c9zdhGUw63NQzXRoLdfMHJ7x4eBVL6Qz8qZAH28a4htrpQOo1nf1iC11UOxarAhyFRvNrGZnUddjNfdkxk4EoHb+plwEiiTUaLHT3X1RZ19UBOhhnzm7AH3Xy7WG/YNBO8I8J9qASfYCHmZBhKQRw/TD9h35FSGuwqkGAUWqFtuzi2DaXyx/sXwDQd4LqIwaakaa14spO5zMmq0ns3EhrnUQTw76HmcqN6KYNpc2IQXt06USJP/Xcnv6U9Y6E1IkuPwGLNrx2PivMivDxhxFBwErLmHZFfGklgL/leVYtNJUi3qkgxnDH8QL7Vj7DdRpzxparMp6Yn66PsqKVjqvjlOOFcLkN5xkRHiFhrXoN8Vqic9YzwPlLn2z5zdhr1sKhAwJFMKWH0IdUpBd1DRS1SHd1Ft60WXhmvOMsAiyi+anq85Nf46d+Y7JB/lXXrhZgKx6lggWN7617apTZTvSYraHB8unFgY4FX9mXPJlWa5HjWgFZITQua+49/zuWJ9iJ3SrFh9K3+jX98iWE75Ly/nYjtDoVCAlBz5KUEjwMKts6FinH0KVZzHoj8t+GLJR77dk1HoGyl8FYQynHLQbhiJtAFYiox+gc2Krh+a9X3mODs2e8VMiWp/aBSC+93yFAJYHSLiqUO8zMZM6+jdPOYFWp//Jx3zq2+ZcDVqT/Af5T57AK+xSEDHfroU8SLSWLvHcoP3unSdjxmK/n4jT1C4n7/SwCk3lXQLnaKvuPTsn/rlPFVRSFPrkGwMhSW0GQff+IbqvbIDTW4k4haJZYgrd5BA4/89tDrIeF+cn5ViOxeQxQX3kqhC4tfe7Jsx6yvhhnF/xjWebnrlXPJ65wrnuGNHchgJeazllR7ia4ZQa4t56wYAq2dyu7SGmiPs4IFVCd98gMqSUZJDpbdUmLRQKgsaaLVHWN7KSHzHR/mJ/wlqJ2MfNQjxeBxclsBYlkyIssZV
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
