apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBNlnt2kztsbiKBruepQaajPMnXeyvp6v3d5u8t46Mci+U1Rk6DQakp500T8mf170dAEoCXSYWE9h+pHieKh76GrU58DopmeRSdPrkBLBgRU9YsHRvkT76DyOwSfjPq9B+nhxu5b9cDOOfhoyzmn9ZaNxDnWZ5+wb+28ypu6xrvFYLsAANDLa2jlEWOD6yHtGDdMVp40Hj3VyUkxjyxKnIQruSjiF+Zl0oBXqgIok5B/pjmzCkclG2bpJbkgStepKwBL8B5vM8Xn76i38XzJwErcCVX9eOJcCO/B2IlEQFYY/5SATCv0y3uve2PZ35PxQ5Uzv9gSZDKb2AytUcKPYvyVKgKZuml7DGFUUaR/6VaJajPNPVdQUxPPIVIUcma3wUasbRbOzgZYBi7Q4itJ7JkAczfDXuH1fzBzF0r5s2ItM8ONRnXACjIpjq3zH0fgFC84as2OKM10l00acZV5cf6qQhN59hE2TIkRMCd08/yckx1s/wQBskR0SHKJ91jad1qIN8eSAfQzd2SsPJErW2ZAUBkiWz8kH8PUDjwcSwBqwE1sCTFegNdFaAJlKJYBXmJGAmw8TC/5JIISK8Xz/8+lJ8zogJgDtaHuayJ0fVh/TEm/F5m9quvRzQJjRvu26W9+UKADjz6JV9WPacX4WPT9W2do/TCkrK1luCcIBuanPHaZky2ZLOc2PZtnH1XP6LqssQjNY++BerL6RBrGBwHvMlnQ4OkduZoUz5RJZ0pVydbgaRDVqTRxtlPX61a3Pb/3QaKDpBoSkaU1PFoJm6OmfsEzl1Y/NTE4JiDqjrWp8Oq09KiJ8nogxeSKw3m7S+fxVD890hEtyEmyLnnQcbHv89cHs8WWy7/1hNIUgfygTs4Nrk45PONJW561FMJZ8y3zrmPNmDWv6YB7+WtTOEJkRrgGerOWuHVZbzCU7MElMe7aB1/vTAtNAXcoTNtiE4Vwha+oO5sCijYHsjeffkYT/WgLs/sbSPrAh6f4A5AIl2rtdtjJ3YtwQf16LIOP5gSWM3Y0/FHQ31yWL79gtA2cXIwq+6LNRVfK6JMDarRV+DoR3W68FaVfgk+fcDA7CN5uWqI3TMVjpu+aMvUdUBqJdAl
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
