apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBC9T33kvShZbo9ri9rdIeXnXuRkF9tLyHMpRHpbBXbtma2MLutSsXxLuMqz4UrzTp9WgyeoBLu5r+PIyH1AUtjvGh9+yPGVhDeJpxkM0fNNWl6HoGljfwoir8oocUBgdZlp5btOpGqWCw+BEjuPfGNKYhKxZWp6fW2ipmG99DXJbUjVLX73VJPpnDjZkTlc/nnPlKD5aAKURGiP2+RRulzkWIn6bV0+bS6MxrFaYYV3p0ZtUfa4aASArlXNB4c6H5QKKB3FFhs6B9aJHHyyJhu18yO8q6D0MK5dGizD1bAYF/wleYB+A5SgsM4I+AX+TV+WhX3vui18vysEZClyktwdtl6xWoPs3HxdC3iShxK6+F4vTmt3uCx7uYxIoTB3b8D3uFx74n7InobLOCGx9n5f7/TLKlddU5BGONSoLyKsxj9PfSlOvPMhQw9NTNf5r92Xvod59TxywOGuOrUUz0CZCS5DBaR29Fh34vSplz1Xeb6ewi6A1EIzbXHiZQ65H2swwHIgD+zBIdA2VwClYozOjIGBOkZKacRMT/4QT+ywyS3c5OHxwMEOw8I6TVIJ8xxDceXreltHEm9visMacwucn4/YTcbl+5oSNQrFC0IQeZxDkuRzNMViS75sYoePBLQOFdda6YxnfLerC3sbeIAxJR6pnQhUL5yGOJ438Z4DbuEXJdQaGUYTaqK2rwWxT6s9iS79+MP3dQCVrBKg1dvFFwDSsL0ikjVMxRLKmsr9xHIup7u9gdpYAnzy5pzxjIVwljxA9KHTXJO3Coa+v7YDf8eyM2y4QXDk4tQBpsInCoSH7NWnyg7CMTWxKkRQZlY9HARaZma+/syHJY+gH0uOfbI/pXLctlt6qjuLu1kfTEU4XMRyfOFiGveujj0acaH9RKlnLJcEBdGmc0b+CB7nc1FtlbeX8I7YsCbZ+23IUuNXv+6Sgc4XYddvmc0fv6/NbfAoVWdR5Ev/W8M/WtPOTUwS274sxoljHhc4MuZ76vdKnlVL0tJqIfXRgibJz+F4Gnchx8hGJZHieOrPC2RMhS+jIVMdgw8Krm/uRGxXjdv5Lr/AVzM+NRkummOUbo0I8dV5ZbrrIvOaOdMAcPv6a/a
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
