apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAFlz7SaAnxz2nvpbv/wVFIHHA3VmTuJHD8EEt8a+xYdFMH7X4vk9bxEQRJhoJ/j5GmpKQZROOcuDeh+AxevIIPz8eTsqSyLpJEAP5y/dpzepKjpV5PqE3RZWkmXxvty45KyOvXLOUE2OHOwlHN7xWsF9NlJjD7q6nbMaXnd7Xv6au+M+9IZtBGELSdpOzHI7LZXECnuw+l3eDi8nT/gnaAam2uwlysX4jG5uf759XrGe2ZZihNE0VsEo4AM9c1ZHGbNEVOcfViC1tpbFMM3BJNwaARAF62/GQbBgkEtV3BDM8wKB9D7gnWDRlOq5Wg1TFDHq3KUeLKiQ177Xlu5r5OrsKpWMC3oHmOJOwQD1RU0xNxtWeSI7W1BVMbxiVSrdgqeTO6jdXL2iOTlpEdOWP7J/pKJ/iWtAdaI83snLNOQH5eD5ASt33hXmYlyTgJJwHsfh31KlDbYStOzWavsHXa0tRPiyejVXI90WSpiGR6M4yeDfemfi4sP8AwSb96b/EbM7r09cszF1dbcsmQJResk4rSl5iFVhQ0jOnTT2n72ajjlCdI6DHuK2EaeiVGZPtyuuhsjFGi3/uW7t4ncxvUktpkkr1dGxosi5RUovuCbM0pFEMS6TQO+7YmNmirvG2ZbQZXJNzmlwydSMQvpBttvf4SvTMH0Fp62TcTp2FB6Qm8UohU3qcRjDanN22fwuXVNqnayYQTmw7tJc/quzMRInpkBMFECfGc6ZB6F3KYm4K/d+AQQyFEiUh0N38Z1S1prnCkzKaWWbjsQlTJnuD2xbc1fZ/lE/B8futYQtc9XrwHnB2o20rvvid7khph22wBQJa8vc0sKtaN4yUZQfyIFclzz2poZ3wIHsUhwMfGa8brpYaBe3jLgLpmcuSxlZsu220my2N6MjDBiUhlqqfBgdxMQLZrX5LiHuf1a2j7kB5I0jabueJVkAIU5Eay6bw=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
