apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCO2cYP/TE7e3Yf7N6QiKtB2m50l5DReKMB3RqSMrU13lRKaTE4KuO2fztv/jSgfCGZvASuE1D395N54Tz9pEAKzD9I0o3vXLlO8kcM5mFaceCb21PkXcR66jTrXvENG90nU2EWo4xBV8ww4jcddgvVEcQmZroWm8KzY+xovij+CEvQ+bfONkh7dH7cuLzKwhNJ7Ex/P5XGXLzZ+e0/uqRZQkjhmYYQr+9tTdoeWUvd5/4ZGea6+b+xxpx3+Dcd/QbV4e51lDwQDOLmemaMjYHOv1Nu8rx3oaKXHQiCOVG/TvsbzFjxofxfGZQpDbh1LWbvLMkSJMjyAi3rn9Q4aJcWwWnBsBYAEqLfvK2v/+gOvI5voBMj4bWrxPy42TQuRkp8mdcRA2iQPmL50g6wo1QVmK5fWriWRiIhkTz7g+pG38NSWHo3aXD1cOuDy1PFjikTrahwCLmowHp6AmeVmjMhRpyJRSJNgPKCI5GFiIFGaNYLa9wryMYEiEc8W2wEmb+GXClPHciaE7cmjYuweZ9Z11XScJGIU5OFIVphdPfKqw+CAn/k97zn//0JUjyCgsbK2dcNBftsUlvlxwXRFJz59pMwZmGXg7jn9S4R2NaiJRKaBZbxmOaXIvNxICiRBtNRmPYEty4S5CGF1v8QjnlPw8yAekHrhW4oyxjqVlmsErWWYdq+L0HgYgHQAHMOeIxNQ7Yq13R4Q8zYnFLlWl4SvkAvDfgSyG1THHkwk0xmq4S0fDZl5QyklvrM59fJ7VtpGQxdgu+/VzDO6l7wxVYShVQ5pLVuAvSfzKQ03BAkx/laiVdDbJcVtalyWGQ767okezrxWbr/nc1GdX7ra1OBtgTgv5jgg7g2QindPWOsuJetfbJIfE3uFgzrEPNLYSVm/xgvxX8a3lcsNF/DxDpCtCDEfa6bfYLnnUhf0X4hmXEo1IwBROX0OrhWsa5h8Lo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
