apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCJsbfVbbWfkJCmT3K//94c5zjroHduPJLLkRpk8tMOnd9UFU+atXtviuUCdezYypZvaQO6laTDb2Jaa8lS50kPCjgsyWhSdbn+5TWHDgfZQddMhH+8Ow4UWaGdmk1DxbX+qKH70LoMx8K6RML8dT5MdByA8Ffz02Cr5iP3+HlqQEEg7AX7i3ffiEBIzwJUEeKoOumlevWILtBZV8g3v2rmHFU18rqS9x8quIUVbatm5rsu/0TRLE+EzTmMOnq8sjmR1KOuVCvPNyG/k2uTgbKZoNrIqCiKBMpnrQWVv82BkzVrcUWl0rhS2a28J1u0zgghXPbimHezoHc0oTtex5SdD1PMpYwdsEwx79nw7e2c4cQuYDs891+aWkoeRWDlb4ac6ZvMyjTld1lclrYd+pev4qsC2C8+f5mYSKp6A8wmrl1kcOg286BGAFlnVs0ep0WWXxo6/xpC7TPT3bxmGKPuaHXBbP/Q2ODVNSmw66lb8gJt4SF7mOuQZuItjxiTKgQ1HB8R3s9R7aawLYmrDG0qCukHFuVnux7Py6ZTc9iwS+u0tzNTA1jxk9A58eu+LoewksbRAd1GftndCfRZG0wWE6MRVvNpAHRNn0ldacxRMEDFOTPSNz1euCUBa0pZh+ARnOZfSLlsE8EQ1GU2KkkFzZNMrZUbrXbRtFIwkC4H0wcfriRGw9rI2IBmU0NquOv40X6qjj9iCRULmdoYduDfoCvylfEdxEZuKDuSXEVZQeSazUm/gsq8pgw70q5zKB/ENmlQcD/tRQMz0n6W5Sm/Zg6sLxRGnsatXrGc1v/XEEh69pYkrehXOlhrEbYAlNoYIFPl8ISa2XaPEbZOPQPMy3fnk2i2Cv8wU7IOGxb9kK6rYkxPxcr2sj7kfwMm0IiK8bFMz1rzvLi2fI9B6MLlcHql4th4M181pAccMTsi67eOnMCalqI+DL4vwnCVKHkswL15XGeweI21H2mgWtGgC1UibS40zMe0SdOstXXWK4P6E5Js1klZsg9bdqRLY4hAbe/qWwjQOYlTnS95emIiuJLgX8aUjuRlwbSoU1zhX8vexFxoypKGT0BdlKUuZwn3Hi/e0Z8dg/2k14DlUDCmcL9C
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
