apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBQqoEB5xmPH2iNe1UDI0uf+BmPW4BKvPdZ1KzoXlYkg6p64aEhX1A1T7TfrCIXgKj5iTAliyhJuN/i+IFrD6/K4R2CNajo40H39ew+7S8jsVSDoEvomI1UoANey2e6cm95Y5KxVFOUIt9ZslhBHJNFWomlT/QVszxpbWX7J3d2aRucSp/YPdb3aQGh+8DoBatVouoe4NphXocyFnUru8rgPoLmjiGjDNX3uqX/VXKuKOeC/u2XrGt2muabpbWjcHK0HzcMHB2X58Z3XqfcNArpEQ3pnP2kQbQTVPfxlCAdAE6osZJ7ZxHFxEw+d4KirK4gsbVZjV0jdnj0LJH8BxLYsrBFvUdYoMMz+T3TfYpKLhT6LKKMW8kK5M1qt6kmdYZAERugoAyCq9DT6n2HCaega5q2g07pJDzyihY6DAY4Zvqx4Wxxh0FYNKVSaXEk0lGjR5J+m43axKR+tffT+ZIC1QKmJBphcpDkVV8ivwWnAzCthEkfgPvW8wZHvRmhTWH370yVdSfuKy10eL9aPVEcuFWNkFHdAtWByNiXzCf0epFeDK8TG8ffX3GJS3wQd4GHn3C7zcqr64AmuCSVxuh+rBXAN5OgOs88rDpcFLsFPHEl3ZC2yWGKJM7cmLQvecmNQ19oJchEHKjzzWSjdfRFySj/JuBNAFspkddxsQPDBP3lTxEJTMGd2BjgTYJOiHTM49svnlosckmTRKZ0BUjmD8axUdTA740fDQKoQVojiQaihr3zbV7D4e2jMtjI7J5CXo2iDlRC5M6e7Shn/mWsbA7jOQ6x2fgrF1Re/R/2gR3UZhhCwYaDEX4s2RkMmdf5nezfzww/S1bHi7r/7zcPXDKVTISXNEbnXNpBIqJZOMYp8Q61TH7fY3sb+hNNAL1lwGKjVHMRu7kNdYRAtp4EJHtTafagUAyUqTgn5TQxE+Z4/Z8f/C4BmA9dauzawQE=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
