apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCDtz8yL5TRs5g+zQA23zQMNJAVvu/hwXp4xjCZgk71d28/eCmdjnd3jRE/fE6MqQ04ShxjNvSY65YtX24kUp1a9JvjPH10FS65ybHTtXrK7x+MgrcpMPDN909eVvLAfAA/n+77PnDouKgxJAQOYKtNxBATNDw4uW7zUQNbFfWyodOrA1e9iXkUukJ2AUe5y2ZfZlWjqq/prmlO017xkbevXYcYCqzXPuoZIchSs5IdcmMosGOwgf7RaFsooxSejVymDThXzNBxOOT8WlGzwINpYy6umBVETji3N+Tm4IdmhwTGL5hzrRJu6kxg9vWOOiZPUBTOYX14KuipKMpTFoq2OXbjaWsmCMP/tqh8JfCZCTGArD+3FK+9mkIZsBUFjVe4NLoi4v7nrMRSJ/q+vFtvwOo4yzQMIjnYwHiztoO5b8g1n9YJHZRHIQXF0isFwnYJJMuLVkizNzzrOHV2md+a6zOJ6aHBSM0AMqJThTXvzXg9O0aDWRV8iQllAwA9UWdge0wl7+GlPRRyl6XcWDlshD7IgyxcL0iVY9e/aj+qtl5rKSuikQHdT8ElQ15Fagj0EN/JklIQd5kJ1dsswiZf6r6UAkp8kATM3WjhkvjDslm6fL78CbhGuvC6ilBg/eIT7Qf6NDuxaoKjMvsv/DZzMjNzkEBFbJthrkLdSA1H0PIHE5wBPAyM40EmLf/dGE45WVQUJWiZIhlRg8y0yZ1BbFrLiKBItqHdpKXly6xfozzJkavHa6NnZdgt7kXY/98jiGfYQ2h2siG3hnadMmTL0fj0QVoVQJZDeDeCcqJzNhodmei8TZKgv3l3OV0AcDEURXpJ8f4UljwS58KMbMsSRU0OmRne4fAFL4MZXBVtjBdenkphRndV8C8FnNqCxcotBhOhhM9NmXtwrdmJ1P5tGoVzR00nGE9p50u6yhg+ixqxw5zKu/rn/Toh6BcweZI=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
