apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAT4ylPIqLh0ZXKrQ9qfRMUXX1B1Rie+k3ywH6avXPNvtUK7SyWPvxQTvcy5pBVYkH2/dUeZjW26F6U1nDkYFumAeE7IWjwYhpWfujzcrbbGhtviyBxg1ZleZqHqE1WzBkVEEI9R1LXX++PGVKtknCI2e64wDsxgVfxl0wit6XbPHYWSQVh/9j7GbSekajpIne9oQ12yfgAspThLeqEUvqkiZzZbENoFGHbQrY2iAjr4QSwPgLxvAWIUyxilXaCsKMzis7+mfn1L6wLfRqvHoMW6peYq4UcYmsrGL8RwEoa4K/F1TH/AzTVDX4v4tg+Y1U/9TRwq3P7w6KVq4oXCb0pzHUsijFegLqAR0zwJvIUFa6cJO4/OvClq5ggTL9yghbD1E8HsDm95HmCgbAFyuVx0ryu1Q/3ikEQtZJ1h0Pfybc2ATq/+NF7a12DwfqfpDETkaD+jdTMl48R7PWh7fKOP6zAQsQlePfhMw0hTZtp/66KKJNJ34DnVvuQEZd2nrGcn89WRrwhhVrI7DN3b47vqj3618Iqhk7aXbPvxfFpkldvbqB0vkZ+eAiuD6QSreapw82MkybECTq8l8U/2MiEIUkEL5/RtFKlCuh/jXlk2UQNmWfp3GubCi/c2W1cfX7qSdmsWIigRwrx4dNDKx1wLEPshdMHVcZ4PUpH0TU1RLjQZfml6ra8UgqNEfKwM+80Orp3GbZg3GB4ZDkn1uwuEQK8aCEKazPW4gPvvjmt/1vQ6kIGkwrZ060pLoMYDrNYHiiuqAK6tNUWkco7rNuzM9IKxdcZ2w8TKpELTxewtSUkkQGD+xVqQrqIimY9cC+y8Vt1J+Lv+gq3PKp37ARTCWAeSj9kkqiwS+bL6+z1E4DrzNdu8DOUu4UO8goqylgvxkIDlGsy6hp7xzjyq+Hm2puIEL2X6R18xomSryAQCWbD706FupmuuEUDse7VgP8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
