apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAulxw5p7asmqIsRBx82ufHFAxDpu5HcO/l/kd7bZHUsiw9yGie+ZbZn7Jz79hQVaDjgAuFv/ifRF03AruoPFnnBiRZyFhDrHtfKf8L30dQ/oarPb72yHMFHDTlOGM1suRvKJH4h2wVLdq0XArfP23oJtrIHY2JHP707c3lQwAizN6IflhuFOBJy4K3LlpXMCrR8TiKAhM396/SzIxamMrUnQKgFqkN6pLSyAC7Iq1mnVMfAcO3vq2o2D1WmgsCYpy/VQKBQl0sGoHrhG35X9RsHqsF0U5dJuRzoNVLTMq2zWXfmq+LxH/RHeTA5+/HX2MTCjfMvblTXx5R8hK89Rt73gDHtBTGhBO3XHubJtZdbMAqVsHUx9r4kJsIqce8Gpyo/xt55mtZspLoKKGJHYj+B7l77ukiTIfDFSWKVjvOcIk37TeJGCn05aVlAcOoHyB7BtGiehjat4PJiglidKw2JD2pni9pN3GEHjby34jy314L6g+OJW+o89SUpCyHPX552WN4FlV5OqoCazFgYvojD2cMn8JOeJFcrILRZRK8XD5MllwlyWs7W8XDdddrDUV08XoTe60EoHbqgh8sFuccVFpLi/ENN6qL/CzPUOXb4q9eW5CiWBLGD7K28scNBTRv3Lk79EtFczbmaas33I0hrFfbaq8Ca1xUn1vEBL5ToRctASdsqe4IBR+7gqwn7iAcwkiTesNG9Vy/WJM+JKT7gArZQfxG05Q/hHWL+CGPsKowsih4KI1cXXlM6lQkO9bnBp6c2fsjzWlTppV8n2gliYvbhVeebAN5YdaHAo+KDui6FD0Ueguxh8fU1W2qvRW0QhJtFIM7F+Xq7g95mv9ED7ow4B2XiGZr7PwioMlImUAKYG1VWgI7Y5BueY4rEgKMR+5o1eLPpM+Z7zP2JTrrSaGVnLkaFjUxpSLK37L6qxx+mvo210a57WpsTZm0Rio=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
