apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCZt7s1YCxr3KpaNJcDrK67jKR6vMHrEPKdYGxMeYxPAuS9dArxqcZdrNNvTkZBJzK5OlGdE7Qmv95OQ/jGXq9AUjVb81SKLketApEOHoCV691A+XH+5WdUdtUlqzBx2DDpUdRjjt5pWxn82RJMk61C5uxEHQdJ8iBaQ4nK9+EtWPCFuQ8FhFh19AwQ9rhk2zD70C49JFKBsq7yzv/anyPnXSyY5KIPw2FngBR23et0h6a+YKx48Y+mH8e8GbCfCGgBQEZ2QSXECPc5KCI+/TwQbvQrdDxdlnob1Ag1x1PkTR/6wmmUk47zbo8UY4Zcm3ZQx9p5bnnTQ4l4kK6pzuT5Pk3exNDXcd/53PX1Er0ZJLK+s9VhZmBP6MROwDklSne+HWGY8Xw7TZZRHSLPxMBdfcD2ykIzw/UPWgrmqTyYVuSkng3FhhriX44HJ/m5XFYxeW+LAvE4+Bo4wSeR86fdgH1QmDHhqC+NKAGwb1zYDvj0J/tj3bxo47RotEfRvTT0sl5TfqyoQLpLk3hkDxRi7c36FdSHY+s34t1n/XR1cLUakbnjnZnsvrj+9SF6fhNdmBpOabqOF1gJ0ClIS7Mr6MR5uq2HafduR8992X4MQchxNgNlKRulx7/yJ3u7aLzxc9kx4MMJnXO9/I6TMtfydr5Ey0KzfXzlm9wMuVWfe/MsqPoxzLkSkF/EMNYmuuiPE/UnISxWaG8JT+79XCCnkjDgBllINaQMmBR4OWMmg6cBwKpTywZDCo1SEaMs3nPyLpEuTPHRCT6w7SYQfGgDcSsNUqrr/JMqLN7vfHwc9YUKPpXksHLFBlA/A7V16OMTMn/fun/hN/cTc2qazsHipYY5r7x/00S2mDbuKreTLLjaKCWTU4cW3cHm3PGlxTPO+K5viS0OwMWVFgKYBO5rVT1wzpaWqIbpXFu+NnH52igRurGhabjtGjgzc9sHnTc=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
