apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAToKLcuYc7qqNgwDs+HNIE1+fKD3miKAryRBI7XUa3JfK1CCUCyDrzucnonbZS7liVWHIAOksLqczE5NKYXhGJCsQkCVNIuW2P24HsAUJlnOMrUywl3pit4xRVG4DeBNhFFQsBvz0nVmVz27uMYKgNV+SQKkEqlqhp9ROwfb3OmmZ8LNLN+4rDnYa+mcUbpJWJadvofOPdrgTrLdBIfqdyBlGSt8K333nx3qsbqH4/IRJAWh3e6Z17Z5hyIrCU67/JrYMb4vWpo2xtnuQtMQkS+IQgxtnQVxhaoyYHBCaF0AXzcSKW4FmsQ58XtD4FB7iaLn5hbj/45mtuXem2Nw+i3PnTO+9qzfPaFjLQegtmrxhBuMqjLGREkTIZoZxvA8z61UTHi/TkLNa6RVWif1R1baK4fIcdbX+gF1y8hZ8zH5o0u3EBxKxOz2KIEZVDlDUbIm8onL/li/eO3tA9MDxiyUolZPd/BYbJP+uk9cyMgrJOGjMmXMB2hDdaFh/+7uCvshg+emJGLlxO0i0eNaPi0w9GIKCmwOAnw8zLKQAZHoBvOVoyE3mBGqYfT50zqYu85OzjQZAP4eK8Rzi4FmA0Mnez5pgu02FpUEsJB2TWHmv9WHtMhIXaQ55rYSpoeuoYQuXrMRs4FSUaTjVwO/o2PdU4dlM69v7FurvoNplDGKOLUvdCvoOq8IrsGPgRQ7qkBUSxgaxg8/gMeruJAypwzRkOz+DHK61mebo2RAN82Kf1N/N1aFVqF6v+Df7VjxyEYa/eEtMhiNvlzDxVSMRdEwOpWsbWDKjlmQ0Wz+WGQkHqObGU5Kn82W/x1PKJ1I9EB6kYEBgHLRPWc3f53bXmBEaLOeDxJkAr3jX1+9SZgjIW+yOU0EtSZ/x2HL7DvWANYRK5GAHS5rais9dGExbEkhrssvdDuHBgQ23P/6+9VQSW89xO0cWVc0Z/HoJ0v9I=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
