apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBFjxGDay1byIiPnB7E0khM7bE52e3CS1WmzuNGmoLDxkKLfGYDe55JjlQiKJF3jEjAFnlsAXTlmoIvt1ZQJlyucqRB6Pr5DmhmheIOirCLJnKBlcATPcoZEA1kae+zwk/fyyYygFb08VTiKUh9Q5i1bDE8bQq9EzJbk15iyJR3vrWNLwqr0mOBWwQhx0SjrE2rKo0FfiZerwpyFWpk8dU0OdlkMp96oNW3sbg1XXSXMS8HrFV1WhGCO7icsZJ14kVrvBBWPIXQtVohoAFDQipwXqJS7JtcKu9VutYrfaKcbLJ7goHVNxOg3U1k8JZuWE2gdzTH5MPjVbSj6gQpDW8I9G13FiV7E36Fk+QjgQ8jIRksniS34RpeF7Qlt7m0fEd5QoaQg62sjASzXrhOrwnM7tMg97DcJgIozyHyA2O43thht4yBU74CnjM8oDZykj3Efb65C1iFqBVfqpkhD0iiwSJ4K2oDmM0yxStY9s/7ZYKCjcxUyVc+bTNJunskFt3rsUHjK+rp1C+EPIRlKo2tR24AgOW/YP3xqnWhmdsGba8LxHZA0WPHMZJ/jkRXdDUpv3BFlsCl2MiC3oUBgwF+iiDz88aodKZZXWOhT5NCc+oGVBSmGw2nJ6292gW9Y2FuS+UPmP1pDwhiLJTHh4K9mr74l6iq/9ngeSBmQ5facdA18sDOIctowk0GQ3hwdt3OAg+mCOKp92mQgfIB8p5qxwkP0t+VR5xDvBb8a6nNQ18/0r9a5PlKaOrf282um7Y50GV2Kam+pAyqcgJ/JdvabXmFbuCFsN2cbonEANFyz9YnPLWA4yESu1VT0WPz/e9BdFEWYT7QTy8jWpl8IMGL/5E6KbmNWhoCYRDlsfLDX2jaYjIJ2v6rdVuFWS2jNlytsGARo/EdB0ywlV4H+6yIs+fS6pKMSv2GOWfzsHe7ta4UqHuJcNifFdYm8tvdpxJ44BZApBOaWzi7/aX4GXtMIwRRDNaYvdpy4/WE3f1YI+LQpxbovym12RF4Y2Bl+Y9VrGAvCWkZXr9m1L85PT6VIFWdxq0VSikV8gJaYOqLef/MHqh+1eA953cUJeix3NwGc1T6dvS4NTSE6lV7c5taRZ1O
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
