apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCrBVRt7DAoRrrxXb22F/dtKjACUBGBEQKRiPe+l2fTKzD/Pr50QMir5eh77Rmb7rC0YQZRRe2LgsJJg6OYoKy/8GJA1L2dXDqDvkmS8vO5x5J6kkYZVhY7tB+IzhqRz49EanCJx54ZVh/du9eig4JsHu6f6eFW/Ii+vJs6i0vGSHwCFK0IWME37moZYKTMPolJkobkJfnbKW+GdFN42YzATrqSnQbySEk3pyrLfAhx9qVraLlGw2gmSa5LeR6RJpwuJBzVIbDHu2Te5KJ1U6rTuH3gVs/vLg3ZgKF/bgSGgh++qUVfD77CujBzzRpF+N0wjVteU8znCC//votbSuxc/TtDZxD/di4FCR5u9cZ/zioGgKd+bCQEMPh5PnmmUm19iVJSsH7Cbg/QVgP21JnApIBmlgvcS4IRy19pyT2BNttkGj5KpEU5RREs45Nih2c0FKL9psHOxKOmRIglvAW4ZHv1cSlkWrx1yeXooUoDvPCtJ1HhQMw1ZsVGozsoAhHC1gaGTFlMdQopxyuxYM6vOfNGwD8tDraEM5IjLbF5VeIgHMSzFJf+SV+x+XHew5cYK6Wa36cCNokOVxKfKQXW1km1CsILUSuydCyARSv3yDNtcy0oHXSdVElBMdaUa3Hi1UNtHkFkPxHpw+cz9NdVqOKOJFHNtEMyLw76lV07X8wLEoJsSAuItCK9H+1c7H8WMZ2Sl9epJipJ4usyr1+vPUcZPtUstgUTr+P0sDyPNehIy6sCtMQslrxrZnV97xg05Tce4AOs7lq7KRFRSM7Kk05BQHF4wU4nU0hYW/nXc8BPxBsXe+463yQV8Dy7Wvfe9Gp41uIhVctqDqsvbXiuwCrrr8IgxgGUyZ38Jl/nflcS2zRoVGt2AATa5FPyy/6pz8hyvCjjaFFB8d1CfEroOwc+t/udUIidM3fU+q/CGeErYZdwq9cB0V+XZFOk+p8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
