apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgDLQJMYtsERMaL6ieoZtiVRVH79D7tkSx1F6f4xMoIpPOe1H2UKGRbXJ3BQuoYCnn0T+ohCwct2LG0fiBZYTQgwpWhxPY0RXR93k82ECnHtqoQ8LQS74W+EbJj41vw44d12eifCdAzKtsv1a4CowRTQE57Marbz4ZFc1gvyiFP9vV4Bj4+DO015k3tq0rBdX2sfK5cAGSzea4IGo2OVIEks5IM05tm/W/6y87k4ApEsmfDxCOJ1zsB9sWfGFiO5NXdqgA7vmF5kIbLvv6mukQvHKCFPjmvsAxTaNhtUkXu+NLMQRnDTROkh06SJ5NJVgw9u/C7UcBRjvlflrL7wbY9/uG48MmzdAa4wI+7m/SPxMggH1gYvy0YhPvUHRYkTRXFf1L3zslm3luvTmZiewKgAE2vTd7mX7Rt1D2GEQR4maoC27WNFWdvwsufHKhXc9Y7FGraWiN2ShcnmT/mN/RSIP/n2trDtn73mZfoph/gfftVLX8iCGIjrCkTMZM4Y8qX6/GP+7j7aqJaYU0GHwgwPTPpkn+Ztp1GTLm5N9MBpLSIMVJmFoUV8zdt97bM327JH3qDGSxk0yAOp2L49rF2YU36w4vccC5zFG+sui70OhuUk+os6xQ16jpCEqE6t+unG7BbCp91Oq8VlHgHhqmQUOsXCp3/B83Z5Phu3TJR3vo+c+LyZMREY1CjLHkkdOeZwTG0sgCp9WaNZJJP+3xJ7BuCvFTXQuQUA6UPol+cWjRD9nKddxgGSKqStwnNB27DSzQrK03rFASH0DN++XwS/ewHAznnMPjl7wLGvsAAvZtkYVXcxEop4TMz9NLKFbBtXwPYrThTpBArnSOw1vSlnAZy2Cx25Typ8Bb/16Rbn5wwIoUbYRtvFnOXyal2zSQWubPwmbin8Oy1IpkyJcHOVnK9tPaUfy/4St8S5XKoG/4iUd6leu264n7p0rBI0LA2rYdwQaIsbk6HMmbrVf5BB9wQL+PQdUBJd4ZsX9GvQEHH/oKe7Yd36MxYEnTE473kjq/T/tOlY0qpq76/2UP6evDE9ltWUhMlsclCbFalSOISl03uDh+kL4mLNjH2qXd+S5qItgWq9qtBAu9DW6lYVQ6Ac
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
