apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBANa8kWTeQKkiyfn/EPmYAHywuyqIpujYSwKgGnmAZLIxjABmmQyOG1jTgHJKNUFehl+UVfo/lv3rDuIeT+fjRhEfsJVdmQ3Pj1ghfBP2LWU+35zDFa80ZRMQeQq79HOhRkwmbO9wxkcwTdrYB5zbOgiymobCRX/IfX2Yb+SBYB2sVzvHWnFRQHJLL7TXdVYNoA+hZdja+/lN5Ott6lGdTxYrZfrhB5QRu1a6obvENloRtYfQDMA4XGJbgFBrUvqUxCvR1oGelrL6fNfdEl1RjQiM6fbfmidOuquNjQzJ3QytQHQ98VoZzMuhQ3OODY2KF/h+ZXGfl/dzyhRKvPoIOIYQJg3FbQt1qzPR8iS7qIS9OtLtTPIGPnEV2RAW+VQkQ+lUrJTOIPOCPvbVTRgK5A78VUqYyR3LVpBf/YvwyADrQYzGOP5R71h2O4V5UJyKyur6bFTbXrWUyyH4lPcdYZDt2+XIKaqAC5sic9R/IND+ReDs6s07N+l4lfGCZI/9Yum+nV2wPSCMKDA3oLq9GXiix9xamV1lVXVsNcZo0dRVEwPHRDO2DMxH6M0yIUJyEjVzU2hOcwqlIkmYCH2juPEgycdwIIkvkGX/499HmqM1NSHMYjSrt4yfQAdetIY2gYeqMdt9xHgXVCOhYCCkneqBMQCptyt8Jgp2yvQfQbuPxwUvrHJQaUMZ26L5pazYl1aiGQFqZatTbOfJ0oKAtaG80+IrKYrIbKU7qr6fx2JWHaIxF5ktR3283DhiSivlVSeCF8+Oc35vk7KJ8jKNTVkYbGNawaxDI7Z5j1ekzKKmrUXdeERGyJvwKCqMbHIC1bUFWwG3kyr09oGlxUBDCGPml/NdlViuyTEOI6bZO3IaXg9EhFAxMuTEM1QU8rXBv/yzMnAt/qdWzxQrr87/NYv3HCFZ+UOG6VGT1hO3jfLMWoq50kNnDGLO/8j3V+N8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
