apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBwIajGPNfrLdKYBc9Jf8tnfyx41ovlqYO6+vbavyjGiVpbAhOHSS10eI3IrElZDQzsAh3pW8xgAfbUj8+lKIFIRe2pc+XFIHt4n9BNFaGcwj8RpPRosPQwvEeyms5OI5/HjsI/VyyQ7MtiRWU/GEri5paGLWz3Vi1jCPzIQiXgFl60paJp8VaCiPsA9li1AEmGP1t16ohw/VRXVR6YK6cdOoIcWOp/TXZ8keKeIDCT6uSAun9/pSagvr4lJ8DcYLk6AxWEQgYjUK01fi70+5ODfVzW96ZAB8GGoW41kVXRipqu7wTm1Vq/uQ+fTEMO59GV+ptGxWcye55AJxEQ4ZcBoWHaYbbXc7o5f75sz069a+Xk2aw2hewP0hGSuy6oFUG8L5uoG9M5oyO5/2oZum3NT2EaPvXODQwFRvC2Axi1pAZQ71JWjlaAd8u6LouDH759ePPuMIp9U1F6mN6+4LcR3SwbQGfsgHHGov5QSlUwk4SK1lsvuRI/YrOzwsSF4I1orLuNAObxRcr7sV9ekbidfv0yKG3G1U+pWodVrMj3k0n2XGSnyLMrSBzDWwirxDKvjlnBZox2cbNf7QQ9iadbOYHzXIDY6eudoW+Y+5FI78dSkx/q4t6K+HWJBH4uCCcfpAt66knpzw63//LQZWFGoRBr5+pys0vSQdP3bcGsTUcGZrxwpUBgVbQTBK8itq1E2/aWmvwCUFEl94vj7rTHwnDTnM4XIlscKENwqtxPphwMH/sUHLaCmhcL9BtVr9l85ImuB8gnQoN8fHa9jXjxaWu0UbxmRV8b0Mlu0e+07uULrLfLzBmkbvSNNCmbDJzIWam7Nyh4Qt3RbaCBgvjMZqi37iMPCghkhKvTTWzGi2QCHO6ckGt3hTqdhiZjYT09K3Y8f2Qc9FaxDsXP1p5gFKadQO0sM6v8BjbRV9Umf4juWPWa2br0itg5XHOmFeg=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
