apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBWtztbfUkr7DwY4RRcfLnq2qdNI/FWW8APWpNu+j4NEykzfNIYPD8eJSBhY+atI46iQJIYWGhKNM6ANvaoclbDO9nVSdXM9wKAAirlDmVyMM4ZmP26yvnybAfJKVx35A5kXZH6hQ+8QQiEkU3bMfOZhwdHcL7oJonPbWCw+4Ga4S/ACv3T+1+x+bVwj+l4TtING/WtNO5OnVcPCqbKeqHI8uFRkFT3SJBLFcAtq9qJg7pMHkz12DCtzB9RyWhvy0XF4Mr2Ht+sS0g2pmIpRKUsX5Drd9kDD2qVppljHXedB64ErspmKci1tvDyfzUo6uZs7WBO3A7PVIrOyET4opBRXaTs7/7BEWAdSP9kAe0x4eRBiFFNxcXB6v8emSu/FVOA4pQdaEl0wt8c/WPRsNfHfCNw/9W/PFNI/JpovhimhJ2+yCOY+dErAyWNLQczD/8H+LsewlKSTUVZrPCWqd0G6ubKvNm1O0NTtWfm501nKFvZztJxsDwJp2DuVMz56gT3bZxJ+TVJalCZ5Y3S5xzxCxoYeA+LmkA0op9jkhaNYN4jMt+1scLRjmmgalvn2E86UFk2MS/lojxF5AqXtExRWFgAmc9fvQlPfsAHwSlczt0NxHYGYsfayG0xUK4Vr3kFhw58PgiyegjY2GgN96m4OTgeoRFVsF39vt4A/ftvSILfvpVu0ozHE2WmzyXcaSq3jXkVxmVn4AgIuroKMuTejiBp2lqCaQcWaoVBOu3NJMSMDQ+mqMC154cmZKDnwzVgWNzHnx+fWbjWKsS4dsGDgxahaAwf3cTpBXS90LW5RWCiXjmcjRk2K5dj2e6oIEtp8VzX7iWWxwbxyMp1u8o6LkGG5Y1aCDmZShdscVDMvO7uOfLtUjdnzXi8dGz3B1xrN/huDh/tFsaCYOUm93byCI+mMqnCBnXmCW29/JhZOML5if/cugy7xej74H3clow/r3G1qV7ID7DhmblhS/VKhXEtLf5ChMAv5AONYG0BBt2d5ueYmSWsB4NfIlTZOXtIvXi13dle3Dl/l1ENwHozpqzfmu82KFqXCJgCWPoyUASNolNFiwjpxvXH2TK2ysN+UM5sxMjEyBtOggiz7NBDR4wN
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
