apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAVV4xANM5Ntsr9+gBA9yg/YNOufifxvsKtu/ZOOMxAj9u2bHW7fAqNVvCFqKc3sGCAcYMaTBjgRlYpNwkXf4x9ynjcE7WudASoGmoiJm2vZuNKllyqsnLwHn1o+N5hK1uERh8xuI5CiMNQTdS6ixVDDpJCH+AKY509RNKy3NsDsuwbTWdCMvgUik3RBacnVaoazuoYnS0hPmQwS/XEx1pC54VBA+0YKmhYlSNCaUr6jP+wVPwNDtBCoDNf+s41YV4xtBJ9o+VkkhjX9FPZ3+lWPb84CXe4VZPk2EdLed4C5t/08BYFwhIYJwEI3tACtluM+JBW2F6AUYVaOp9E+QMvqPuE88QRKL781TwgQMA+sXTHXsENpT28FBMJ166VsLAfW6I5E7pG3GvjfgJVwxj9SYFzb6Et+e66T0QqrUCg3TKAN/DlmbA1WFSrJ/4eYlrqwYnZXdjvUvwus/1v3iB0mVpVoukIapjfwA9Ljr4pXKGTcEMHkDXPMfQVa47+f2R8ZRS0M4Tt1ABAeXHFaetxlPvozHUYpsy2Nl6wUP4CB6lRGbujlp9wC1CTmJQ5eYIGnrRwP3W9wS6MJM0l7uzC1een5RvnuKfk142Hhk0S4pJgI3MU5lKQcnwcW37k6CrjwsXx0scnDOTLg+K8m16US/hFlujNlZl723NLe/FEizFmcHtLOw37D70QKL8rehd5NJrpbaTetApJS29KMcUxqhsmWaAKNZBQvDUs+AtRAqDD98nKjD1192VfYNmT2pb5RN3d4AKDGEd1loA/hAtWiJkDgi5rn48PVEA9/NTCIjF3O5GMxtzAFeE5bGcOT91p3Qc3X1jXDSco7V3YQHsq0AVgu05SNt7qsUdwJm8ieLOXR681WChKw/I1VGgA76g/mJnlxOeTSpB4AYCgqBQTaFvL0jbWkLQlWBxz1PYppEN8g+HDWmPVjr5JAICt6G0=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
