apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgA14fmBACHvCQZ8ZF8tr3GYMAyknWi36QXkdFuL9klQIOE1it9I52ol+xl1F/8I+5lqf0wvYiT9cfqj7/zPHGkXLqQOLU4UV/9TsBYetWvUsR7pYusXNR4VFaMLc6DBXCw/R9kMMH7cXNaOM/uBLGRRIA8CJ5IqT/c+1LUVRoMH4hq82M0SYNfJOqtMI6h5kXvA6CCxafwBRFpP/vFTYxKaQNzcGxjluKw2DjbXxJgtREVJaFHVbX83KWKpyioGpvvsf83ZZRa+GdnK35Aee7Yw6BTvua9htvYkQlrbZAnPxctT1l99ZRP8K7pTEz2RLS2hY8WKOHn7E5K0TD1D3GbOCkRxYhj3T8NRjw74lbKTdpHs0OAFCBza/dtfKe7gWWjeLnmqdf3qHu8qwuApnRPO0Y7UHLvBr3kSctJTKp15YA0m8dx3KRlzeN1ImJ6Nr4y+5+73+t13qfmLVUQSOLbur+ubH2tqhDFO/3w0mmP/6Zc+XP/nITIMjIPvbVfx3TFQhJweN1UMCu9YVjuaxzEOK2yDPGrgQQ1mudURB7ku+YgwfBWsm8Eeb88R6xB9ql2X+hys41WKnL+7IsntH7qIAsqlr29Anyy/tWhp7hy17hzHTG4qPX/HKGi0k4ip00RZrr96bx4/l6OOCJ8fX5NaV6FgDDsWyJCoYlxrIuwxNH3se1e9ZJ9OfOX7dixEqLi+QyF8Dn7TY45FqpSZ7H7facsVnjf3MH3Nl6jnC5h3uNUMuK1dhFJ57iVB7q2WFAhOXo37/b/Nd3O09hkQQrt3SCuiuR5Jt7b/2R+mfBA662a3M5lQdfdEOdolvMC48dhwrG1lICByf80OIP7dcILCXzSiHTII6lytwdjSIckmjAAPEOE7GeoccHkqEtIP8qoQBe8B+rGnNzKtHy1c3LcvGPGxm7fSVkGwLlvqYujYFInCALk2p6BQYJTa7Yo4Z8U=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
