apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgAwMwT1wQXkMBg0F9LO7+qEbA9WvVTw1IBZTjEGbDDeSpw3ZLiPieh9ZuBDtOqEddBsTqkYoU1Cbl91Kn8rt9uSOPAF2hVw3DR29095T+yPy3GIxLfySzcdd+3YHKFfJLqbBUGOV+1IYcK1XtX+MZz44mexsqvU3Bs5rCpTm7pgZ9dLoULgq85FZSS+7MDESaGHicctShwxLZIvIeWG/QIm4Kkr1wak2HJIX+3w8IJsthBmrMu+HaYnt4QkgX7/dKtb2sgWjqwKN3+PmKpbUhnNhzmunb1MRqew9NogoP7IeNOU/JuGWxqJJdifhdLeUkN2XLuKwlnfqB6RkWNZGJn0lUgH7HXFvlkQDm5/RGgXvZlMsDaRWlK7RFJm1VWYmS5E4y9X3DuLIvwUbnIG4lQ3xrV9A9/KAd3gh+5vzq6qSWHXfjBpGvW+f0Zjhs05BJCT+8O8/zUOBwEWRUh8seFVfbxpbQ8VR7lh4eRk6qQ7By6Po3Yakl27/IuHel22yLrTq++o+4cV0jCSIRdahhFjSYPURw0U2HrWpGWvPfb8TnTCnyVMcd2xXPTnoT/G5VVsNBAMT/xVY5q0vtBn/yTmrkD9cKKLhhbqO7C6A4YPrxL2Zfyku1NzeOYKuFBJ23AXiTTGSEdTwWfoUfeTjfgYIRmrJoMClva/JGUCP1hd+bfv6oKjKfjehBhmZVemGpMyb5T+5BmLA5/rPR2Kua1inh1I7qDAephHuZJWxyopNxCTRa+nKifwp2UGxdea4TqXcVW62dQDxcYprOKKANJPVApXFP4b/azHVzxopo3fX9GpK1ibNvdryQLoRj6q1zKN24/dfxq3sMAmlFDeuwaLwUrcg7z2FGOEmibGMffsx8Vr89O9nhKRup3MWo1A7MDOVlIXxuGshIWSnSp+VXSt75ujtGoOD5PGbol/XKH2tzs71K6XaP+fNxmo5/+dMJ4=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
