apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgC15pHyG0ZCxeIBLqEW+x58dUMsA5RNEEeBuCvREv+NDVtXoNgAYhFc3rWl181bYh1L7VeSewlN17N8+yDjffRE/aLCrnms5dqyCA/yjrRQSM3dnnPC2yMqr4fYVPCOU0SuL3ypO1leXfSge+PPSLz2ZCFcbwc9b6OEpFhKuRs5hUCRM9OEoN+/aZsiMHf8BejWZ4KVz1cdOQr+qzLKnkYaYvuN3s5woY5Blil0x5lruP+QhhdYgnxNtA4YjgyG5iDEkCgN/S3A8ws7XjKhaoeVwlBNKFH3DgtTEY47yKx0e3uh3HS/fb+iOpS3FlI2RpEE5Ut6TIGuk8tuCcmQO+N0pghr+m96zjYugwCT/5REs1skYUDaoY1PRGdO5csOZKSgFwIXrgcSEN+y62hKBkiqv63Ucdt09mD7Ci1wuf5XXLHXFjhZ3o9b7JUfN5Us/wuvzXb7Fd9sGvnDREByay9JiZ/6xtMh3LV6gDK0l4flhozzMNZ5GQAiW/vx55GaDPkRkDnnlMLN0Nx7tITZB9ijJ+sFIT3eVqAKik62ul0btS4jFAXZOIYfpNFXqH0fcpDnwPCeTK1S+IyChPu7zymHcU75s6zmle52HbIEdJdzfAlaVJMdUrROErLG8JcWxCD0fX8ebVObA3s6RX2xUwmRIzAiF0jdr7mEbhWkFvi+8mZAgoKWPNqkowg/NNL2aPWeki21erbA79wHqyc3hNAxAzxqmqq3L+/x1iRhEAPsCn0Cb4QQ5pXKoWJmO6DkBPXw5F4FaUmLDuYLU11Q9pWatJJX5hw7dKAys8tDOwfZPVTzQaFXvhkSBIKtEyUADogTTPMjdPLPvKwjxZtjj1XkdOsRIcAaHE/sFICAT2X1uEs91LD7uFkSXBL2VJhPoJe2Kxf43DRYyX5hbLxOZbItXDgx+uq+isqiKcoMMhj43gcR25QdfWPjd4H+pdCp2K0=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
