apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCqaalktbMwEEzRzeBkOWKcU2gpU+bN8TKimG5NAyr+4T5MxgnCTxEFXLzm8wEERb7uBnSN4sVjuEORydHSoBRxRnMNyFFp1ojLANxbrfB9tkLlaMBMPp5HNMr2UDIBxZkWmUnxiY+ZhMf4qEbFPqkhkj68TT3YiAjnWDmCTokQ/0r0oivr1ljJJnrH8DtWaYrgR6TLrnICYFIS4Q+7c+R8w6Q1haXF/EVxH0xPvSWRlBs4/9B06lNba1bfDpNDazbi3X8hQbsWTUu0BQAmGUGu7RnV/PqwWw5tBvRVrrNB5+m0jh+Q0TGXdCW/A7hotTsOAzOiOdAECaos44BbuomU2AWkcU87LTQD/59ulUVAzxxPs3GjhvoAwzq/iZtijhQ9HMmmbbsNLXGnpsfNwMdUE8zU679ddYDnfsGa18H6LbKlICXiWi908IVV/rOkX2iYFDoXSKEbanKO6a72pMisxF2MnVmrA5DPCz648JYjocMQMhcdtbWEM9+ZAnf0pLruRqpY0Xv6WnmENLqZIBbO0MxNiN76O5ra3Y5gceO9NLD9egZfmKSYwARx8+BXTsLoC79aspxWiUFlk34uBcFvtlwub+o/5ULHjH9ikbtFgT9wT1yXtQDUrTHk8yKapq2+G1pIgO+iScMvxGPKC0Nf9T6NODnwpEcrv/0NB1zGlOEj42TzyOWttNrd2RJcAhC1HDXyO8dm14BHip/zGtdJZqC8Gi+VA5fjbtKK8HrZkW521or4uQI1
    username: AgB7zSLAsSnw+Ar3lB7g+/xMwKMnaxwlL/sbAH6T/qHnzjpLm4mjUGQ6iKOi7Qubu9aTG9ZDSJk37EvpwcRoCTsM7aJwmtbqzIa2VkdT0dXFzkUJImrJvhoBPOBFJPkWtq4zo/lULe3rLo6G1kasRfI9qytT4LrfiSouDhCxwezs3XtBnplZhPZB56ragdbMjhBZBTUM5r2Fjg2Z/C+TzoM8WmLpgd9om2m/L2fvLHJFWM4x57DlCu2yUXjGYDde05c3NRRfsQIWLeEbpCDmv27WwbCaHhBdg+8Aoj4ZZg5Hhe1YM4S6YZBzwe2l0ZgnFMFkG7HUPXg9klsjdmC1RdnZVPTfegHi04Am0lyGrqbR0z6SPBS1KlZ4EsDPL/47JpSt/gaXNhoTKVc2fLSv7RXjkmmgHSPk6T9EYXHjOmNyusTvB2lafeCQ//c2PoD5Rnda5fV1QaRhSAQLUyFXNldJF+74hxRppKy2Arzeg+rTPXwAzAk93d4G6+Yn4mx/xfq/Iz/FozKmO6/l7izDsDEH/V16+75/PofWj6jYXiG3SgpoR83VYu5KMDFKIE6FJwwojPzUcWbWaMY5sNzko/Jirs4QJjclHB/W8u/MI89KGyrS6SDamkIA40hmQSP7RHutObfSdo80v0DLu0MfV6Aiwe7nK76gmI394S034igCKdZp0Zmr/OLu0G1IT6lP4d6iFZ+m6PE=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
