apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAIQZeplxpo98zCaIE3uMStTXH2S3ISVVOj85jPZvcU93VVKKcLWHSkv7qoTcef2bzErhRUKZxUMREPbDlcG05G+rH7OL4aODs/E4AfBOtjujBA5pwtuMnauRRdbJUS7lRBIVyREFJ1En8knaMzpLlRhNgZaqCF841ok72e7iuKhJg8VBfFsb6sGcjHWKnltl97jZKZO6AbJBKsHNwze/tdJ3jluoNJ0d/IACHa24/vtFNCfJDUIF/3/ZoTJKJ6MVBVes/T2K9Dr4/4chilYslDBEqWoiTmgR3mjyOb4tcaSjoN8Hv/xOBpDYV5ztlVSLyrMbPKmQkNlgdJoEqoRKNkxA7s/h9dIX7OWYMARP90XT/YxxPhkY70qSZlBIFFT8o2wyhjCHLJbnLqzETY/Snm0n2edVAtvrneUx7mu6DPRuMw0/bpZ8q2HrasNMpBlUaXDJLLn5pyp3HYupKRVf5T0iXATx5DElJcVQ2mUTgIoAvn7pVwqZVjWnf+d0VBwcsOP0viW/1s+EQYnqps15KxSnuQE+aOv2/Yl7nH8+WIklBxnYlZBYv7Juh3bsOd9AXJeobgcMqdBid3R3uBt+xkMWW8jD6O6G7HPyigvTOAclSRD14CcNXWwy0SQh105iN1oI4C+GSDQaVSsxxVoUC8XV3i/XEbM6+5iDl4VQAZvu808kswtEtDZm5bwlCs9olbqIT4Q9YTlWlCQBPZNGqi0hGajauKLERIbvsfFz3M2nZxfirBFvdH
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
