apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCXYVSRvL0SMVevF4gvtMcIz7cxAJBqu+lUmo/px9U5NiXqV7eKIlJJi1J5OcFyIsC4zdOx6O/cVdDqLOE83GVg0HHhwdNp6qkGgKS7SVw7AMIHXPUpLcfn0NmtYKEOB0uo0uTzQzhhjlZji773i+wtaleeaDHKono4hNWZ2iHWd3kJ4Sc5blN9iRRZevbI8A2syJyHsVh91eAJhlisyQfniUgfC5oEt+WuIbfNFCJZqxAHtin2s6RT2cm0jUkfQxUb2aLr0A4FgxvU3Df4L7NrqtytKXLmQz0JA87AJhZ8KhG9u5CKQX5yIhXxl/tKwDuTJ+KWv+NksEkEw2bg/3gQtiBweEKock6Y6oxZ0Tn1ltQvWkAOb+QpCZwAUDDk34eBJB6/tuL1CEcY3JyUlrFEcvbjINCZ/4H4wS08oWWFLYarHr2LIdQyk9xlb9pBeUo803w07V3a3+9sfnfpFBWaPlVdY7lB5zW9kos7q1nyeTcqeOLVhY3zBAim+bV4YzIAi8ujVbzMHK+JOojA1coTOwieCb0+coNu+p9+Z66ZpivBYOxLu6p94bNdCDOxKHxnjD0jpDjdEuQrktetEwqOTUsq0KDS3Ga0JwtoO8xs4fkmrQz3c05uTlL1KqIia2mdWS9eV62YXBJdRac1jLz1NN7F6BuTnP1cLQU4gD/0unct0j93WAuKifyzhxkJJQF1mfNACgFKGnqHOEw6oE2tnuvgX8T9s4Z7R755PZp9WqYik/bXYF21
    username: AgAy69UKp3dcUNBlWut62l8ZfodPPw0sYBnHQ6aUhe7x48VogeWSJZ6p+9JetuNG+NQMw12Ro5Fzcqpjfklg3A7tCQcdy6Qo8BO2XrVrQ6mbbR+Yr1vkuOd5c1TWqTVim7S6EHDB5byRZAvMwyP9ykJSsJKpGRoWIZMlLbLEAAWOJaVy55lU86F97VGoHFE/Wcc34hDPNnQk+YI1z826lVkmnyksIAHh29SkucH1Mok8Glzx17l7kgYHoImTWlTQoFZrcUGSyU20106xb5elRZV8KXrKFkagUE3zyed9+ZYy4x2QcQFeUU38ELTwwqCDLts31looV3dliqKacHTFKxaKIdbKaF1W8DTHTAOVPWJDHbCLq4BWpoaoWGKFNvw6niifQQB3u21Zt1jajYRa2BBWaAs6ysXM3bJhL1Z/3YvMkkt4slxzSDzmJQaew1HnCKqC/Mm9fzxH0vE8qQMoi5RQ2FuQeQlJfI6X8u9R43KvEPkp71GQ0Wb6hz44QSsheTKSuxlyYpCKD+Wm1yDYB4OwYmWfdrPQaV3V6sa/RIh8CvJiEHRgpZDPMAHWOBU1W7T+X861igKORZyeuU12G7/7T0GstkP2Ga7r5X3KDBcnzbSjnoy0sSh5S2W6EMI0VYgkEPDpsnUTJa0YYGE8jjynPo19o5hpwyU1C78UfA0aZj8ioAnVBvSDa7SNV8wqs29lRrus+o8=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
