apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgCWWCKubbpbmnXD9F3ZeyEPLdgvEqOgJQrm/8dBn8qgO8OCHUiJUGdGAWhFefF0XVFaGGH313+bQloG4vC3hvO0uaxGeaaFPATCtZGpsLNoB2V674wdZMw4VTtBFUsiNERDYfjy9x4eXuiqiNFo2ZU7sYuSVdD2sKBgeB5CzrdVH+eXwdenZGiT2N/cUxlhmpqHdnBT6YAsAX8xNDi22j+5y7ILq6tIJzHJituqvXR4KpnHcCdWO8RIFCqyhuDICOOxjyvhUeJFimOu5cT3R6QaU5w3naelWYDLNtlY6OOCX0F2YRN/CoFH6vD6ESIWPRtAhvOoW7HzCEqaUxT7h/eeMvjOywllgsbZ/CQA1xg1HJT9tj6ox33zaEeMeSci6O2T61n9xQlsxQgmMnQiE6nFQHNvHa9iJVn3M4chydGFZ+lVzX8LmzOBXz8qmVXiKkijByfrBHSSEgWTdeSzOtHkv/KO6G6cqDJhlVshJzvhAm4eQZcRgA2oqmj8WR8DRE0SQkmtAGSxEgRoO1+b5NqkBvbQqhcfjr9TkhQ7Sx3GyNGkTZUPYU+U67k/FBtUBez9Cg7oDafKAgl5L+t6TuJ43Js/M5hfH7j+rs1atMobA2b8DHvG2LURePgr53xjr5XqbYLoDpSTcS9fwx7Kv66UeQl9tbZgPLqyhGa14LnON3QOKiX55/b3NuJnNv7CmFz1XW7XIXTS1Uu7gXgt4TX3euJvuXiKp33EomGzH78fmY2qKZe/NVq1
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
