apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAqiHxqmcdk2CaiQm8oYjzaK9YD+nRGt82TqWkO8jllXzSghUXRVSHC2GLg7uW5SZRyNxV15FYWZqo3eVrudbwKzi6KkZ6J31eXOFdDGU/HkDLbKsZGnHOayv4Qrg/jCsWyeyKocYCgMxE/50DO02VbPgSUJdsqBxsKIgpZjp+U6elXK/yCryNfyy6RDuyBQpJSuQcXpFK5p5CZsXWiHN74JQAJbytLGxHBCIt1bpnXVm44+1Mc8sdnWphkucSlcjuirNVNFrKrHE+VJM+63BlYYjVpZtkPfeH+kYR84NyfkPH3iEnWsKI97HAndIvhj9V+TwAv69iqCZyQlcJSnQpjY1YF3wXJkJTCEBdovPvguodK4xONWlpAmC3tRNAGiopmhxXNR4MeJLyMp6U2isWo5XIL6ySZMfElukoP0qrnUmV/deQMGiZVMqUwFVGI7GzSMGORqdjCbRWO43QtCQH0avLP5swefDvBH+Ur3WeRDRU2p8SYwqvnCU0YGKiL/g03nBuhDNNSSIdIy6Cqbutn+TcCPJ2l0P/VCuL4uFqw3n9h+KwhAS7agO47JDIe2F6zMv1vy2cMbtrOw2pMTJGNIaUnIpn6t4ACVYfNLny5eePAFeBqeHRY8vUhpigLVHUAtFmXW+EjOEw+KQvuXRs++l1PP5SbPuw0KJF3oaQ7MlXmCR4DUIsJ1c6YeWEM9XRayZ3BtQrBjJPT/Bis5HOqyC6DWjYggy502D6694uFdtgKDw2Y/yrW
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
