apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgBMzvOPQ5C+lwoRgrBjO3e9EzWQfzukiIOLYYOJ8zQuAliHUlSyHA95Trf8KTlOgfgIVg/9zFjX78DQw7fDkTcXnQd816T2WtWmicEedkEcYqzEO+oc+hI/ZWE4MlHK6z4Bzm5tPJdY6zgnbI9g4O98Ic/maPmDICJjakilMxo/Sg1uk616pnKdsE50aa99f2cht5Yu6HuDL36OnL5nbHYDR6FRCbpRpN9FIYVG3m+X8W+u2vZfdeOBTLWSNcSqNylJVOA9+peU/71Rqk9Z+/byww2ABws7HroBT/CwWuW/0HzMQQSN+3yHtVGjS9kal7mtZU/tjCocxq/Eb1o8rLPBIUrD8vKZoKEfw6vs2/gZg/innxBtLDWS5rCsEnGPx/i7zkV6hj/wI3u7Ul1oHqY/uMrdG5IQ0o79+GL7auxVYSWTUQ7tlbd6XGDTMfO4ahhDafBRtr6X/xcKtf1dRATKWPanArW+pzm6Eo1WOLr27UiYNtzghl9QJtX0kPX/yc8HNaF44nYCBdLuA2RgXw8qqmaKsnUj1jDX2ocdcVylU4LQt/42DYhQ2a52z5QlXMwzbk33qhl69iK7F5pNvRyx2hfaRbU0EnPMk9HclHAI9ym2cmO4pQck895PU0C1ZSeA0BVfmXIaiQ1N86jMcepOAm28Wvy6MRA4Ng4CcvYWmmU7iCxy8Jw2eMo5uqQbPJgRTvBKEfQ4vjiBZTxJn6nZC5ywpx1eEdmgPclsaoK8QamTvI+JBXeT
    username: AgB4HWOXt7q9ZL7F3JhutrNbgUv/VGsUKXnqGvzBS6Rp6r2Os1XjMLZBjaw+Lw/Q/2YsX3ZJ/VKrD/W1oS4Nqla3q5v4PVNx1c44jIzteTM6Z1svdFqa0jAJeFrBEQLkrdCSWysLgdfM2oVFR9IZtvXG5ScZjnjCJcBKavjeG+t7EVrPrtYTz0+QGWZQMlVktvrXiW8ZtCE4nz+OSBMte6BAFwizTlOimtejQv6CGSfU3JaSfxR5RM6a+GxyCAX68KH9uNtpp1eztacW9qt8899iOP6IX2z8VrLRKpBqCdNPtDK59wlU/obuxS+nTwRozm5YKvSZjLTRCu375OtxTnTnPGb0nsjYnu6Ufy7GYkB+PycOu3wEvJcEudMTIj4oQ8LllQMyVCVhP8lt/hEARYApzYy3bbaAuwkTYi3JIZJpY/pHv396sAL1O5XNhQrmDS/u7g0jqZKmaFMfMwHr2wAtGOEGYJ2voY/RmUOnY0lOYGDLVBkM3BgCBxXpEkyDAWTcGqs86m1N3xm1rS3iLGNl355IWZNQDj1g2E3RoU2LBytBwBJqsreOm5Uafbrt6NcRPddn/7c1W2UhsUlb6NpwuFTcE7TP+rzjGaNq7/K/o9lLe11K/eELh7l1ovrHtHRlxgJQrWNdJlQFLOuxz/gXqXnE4Oa9VQRKBdIczE+RAm2fIXbBDBTytl08sHfJTifIxqcv3jE=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
