apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgA9NurDzVWb85L36HBEav9JtSAffRvIOfSS5Ej67zfTJ5bbiwemfZ/RA9nlTr5yRdAO1uuaHp+i96i7uQpix5HD185Cy+Y5lA+ZGA4kw2WxBGmoVOTuf+JSM2tvL8g1jYWCILPnfIAzzGA4O1SCsga/0at4OHPjT5l80CPC6dasFX0Ivb/6pNFby2gOwL0QTmnTcoIc4Jle7eT20hucEXpmXnZaUEwbhkZofOuClgddKqFJK/NkVXya/O4Jmzv4+dbf1J42HPj8cvTX+MgeJjDZv8mscm3krlRA1fe3vEFW172Ty385+RuSm+50QcVb37rS0noEdzCWfPIeaf5i4WvTHCauH47lgM/rYA+6xwy81BEySQnw/A6P0zpfJQRMz3Ziwvd46pdor/7CQ/WgUrCB+undG69m5PZ3xYmTC29/IkjvtjFikNvBAJlnTQgrxq8pDfqB66UuLoMRAHgSs6B/he2BRPrgUbMeOXhtumzQELK/OViJsUJeq5gdcGcN7/iHtyi/haki6om68MCOw5PK0cuC2tA+9BgoA5WoqZmeFXTahD5pVwzDaZCDpuuwMTNfv1BFWJuN9J8sQNSd5WioxNdiy+mZGq5E37UziNFZORaZR53quuLMdLixa4kFfwPSgkXAG4zR+qVkyLlZI0/P5xaF3K2cXVT/l8NVlRypUHjIra7aYYi4bawPq3INwxTjyZwAgtdiPzb1edoOlDsYzbf6Xxue8cNNWyBQ/4jIWxY2G7aCNZLh
    username: AgAO6x+CdyQQDdbkP5pzeNTofy5yJjfxQRawKS1RB7p5Ob3ffcl/NGAlGCTzf9gFGPiAFePbdXmp59VWOyBjg+TynO6qlM6o56zkn65nRWfc75VIYxE9QT/wpWazc7AnlM8fiBe1KUTGEAYNYjuXUSm/4FqvaTEGDmLb7Yj9Ufw9T6iB3VMDsqdNoRpGWR2FrVNb7lzu4R82NPWrwt3iSYZloa24+mYLRjkYL/HrIzOKOzlzjFJUP36dPs43VNa3DY7dA1aDuK+sJ8wA6VEGSwciP7Aj6hzlDrIp7fAZXMkCowKL63eOKzY+bCrk1DuUGWEb2QTkmQ5rhnUl2SEA66d3dMg3qJRfpt0IJc8jCvAygFVcnIYqpMW8WbU24qyA0JMoJLuFNVuM/rBMDzk79kog2yzyXIMbOAs4wFYEcuE35Ycv8TbpdTybHcZu45fkTndH0srNkz2oyKvlSfOv1uPkPwZYpGBOnfm2ZK/gaz9f72nZl+i43lgiFPTUqbJwGfwb7M0ooKpE9IJdeEz7Z7QkvNypCdoOsMh1E/Rz4PPzNeYTcL08P5FWFKiidGJJVY+Y+RBMs89jCcL5p32MBsU99vGtVg9VPu2neMPA3ruK8/LDkUH5Mj2EDeoyfJ1cflnXWmKETP/MsuLVwabeaItcu2UkkleKX3SMianeT1r3W4YT74iJ1hR7/v88EiW2wCVX7ixgKnI=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
