apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAysZTsI9wTIuD2t+FhsmDo8wxw0NwF5bcOapGAA+xxi0flVRjTJ2s0FgoL1+UGKkeGn5iMl8o7CBI3ldHWKKfi/Iz2bKrMGxo8zhi+U91+nJxzR3HoQawx2hVrfray/iMhPfrArbxKb72tMJg9FXU/+W15PQHvpJx8JUtgR15TGY/EVGCEWECJs6T3o2gdtFuzExtE/iuFWRjXPA5y5S8qpw+eVLY/yXX3t5OAPOufCmTvjTDIOrZc6x/DRrNDOWAnORAA3wp4aKD8uYTZXj69prCpAGEMuencFG/lssQecXJKv9OFVlfm8PN51/sJoAXZK1MD93M9YadhLEAt9CxW3U+Cs/LGSwURTImaHrK8Xf6i+sFmGhDobn+KBYfDeyQ6ByZmwBDenWACww5cpoF5CUavXAHyCh1KJF1dbKxF7GfdX8HVMlsqviIj1wASTFLt5plAAe421tPHmXc3ap6FmUY+ajc09ukNcNIrHSI34RLhr7tGL3XGi4FmRf0WqISEgsW/Jc4RZm7qQjQV/+yMoymAyLPgWzHZJDYD+mfzb1CLmnnc9VaBMdtOP3rFAEHM/4t5AlITDa5kc75d8n4w0+GR+43fCa32PBD+zODAbwIBgx05LMqDCVth9wnQkZPq8i5PUJDIRAj86jjuEGI0yiwvFNrvgLm45ooVHzHxMHEhregFA3VZ5MgMRyvRwjO14bzNO9pRbxNdRq5Ko82hwN7i2g/uI/lVN8Ur2nPf4UYx/qRMBj2o
    username: AgBUqRYv93/1f73+rIMAWstcxWiEWNEXhLFYgUXvyj4unonSr4N6P1znqnwXlY1JMW6SGcwMbKUNvX16ld2P6MchmZZOWl2Tj0gInprfGno0H0zAJfoEp1iZlNNih6YgG0T/JoZP8GDjyIwwv/tHnGTppF5owo4mTEXRDSgnQlelqrQfLiF7pxMqbKOtfH37S5CTxMjcpfPPfNcFaKaXskDE47XH+lXjqqDtTV1we4GsB58Yc9KnQFK3qoeI+cItk5Rg+7YJsLhhGrhb3gUWOWL0M0MCsU8HYzrsItlgD98vrYh/Mw1HNpAmbVbvtCXYGZuQsjDgm+WwCQmTVaQGKseZAEtgts0bYZrumRz5w2dCyxq+F20smzxSaHDIN5dXjJ5GixfZKGvHl5/2648CCZdPH9+Re9qWer1IfK+46Zxm9FjyEm/M1HM9hyNA2XWJU9BN2a2TCxrg7GEuHn/Yg/KA+2dWvqGkYRURb7mCCNvFBY60piv/k1UehYAbiTcO1NRpLLAo7cS8MIFqK2GQ9aRBQs5HnPllX/sOzMzbLAGp7VOTrWyPvpY2nfEwy/ztizWotbJY4GTUvtOECHQpETOuAoGTxKvKF+4u92FafBghRfLhVs6Sv5z5x2e5wNi4JvOwUAThAsBiL9ApZUKc0Jh9STISVvHNeras/NWR3qwsrY7gZ29/5Bz2OWp19m5XOychsB9t7vA=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
