apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgBHO0l9vT++AEJlFu6RGA3o4XHhohRrwQHqCjct/KD0IcpX/IaC7Qxru3AZQi3CMoJZ38OD8KZMKdd3yxStmK6cphUFEJhSoqOpm9fdEhg+/BYg2kX9I+scgkZTlVG6PgzZzzxXh7dxBO32Kmmz6PSPSV8buFeG+Qm2j2sYgqrBpQqrfuR4y7EWLwUDlhVtiFg1HGl3kW13y6L7FMD01U3V1ua/FRbEBVph84fkzGDcPmT6Yf2m6M99Zt/HxQFD56T8LOIBQHpgCDta3IJSQfdRnDNR26NUERZXM1kXilbRGy4xr5zrVwi+VC/Gh3a4uNWVf9Z8x8WP8laJyQbXL4/GdkWOvft4Sly3hc53DsB39ZFXTQVKvst1bEkMp+hQWETozoYfjdBGzlWKTOm6ut5G3dxr+8C+gcnnrqOCcQLKexjBzqNLzN5GCu0Yk4PAY7miXyO2cTqlXTDHuyZTtym72V3gm7K7Sq6ykzqwLF7u8M2rIKyxXceMtCsbYfcNHq8XMrpqme+YQjiT81egyQP9b7GXG1Wi9HU/MJBpG0lsiJUGnSBFnIVKZ78FhA5JBxmeplI8WBHckDfSszr4hDxNsu0+KXWk3uuBuJD3f5sOcJxaZok8uwrBcSU5nk7e0FNe975hgxRh7udKSfrC60dzMLFT+BMX6gZTFhRAtBwuW4lbKFTzBMaKMSqQYMQBl17nB7dLtTBAXmYodmp5S0J6MpG79zbdIzLxz8bWNryVMj73/iaCLut5
    username: AgBvfL0SziYxSS2sDXGkdhEcY4NRtXcjkIUaa0dQoWvbHE30ho3YnRoB8TpOsdMlcYhVGfEG8g6JPJu/cigJbWIvatB06qsKBFXlUKZODAF6es/8sKwgkFSkVpDEE5ULrqb7I5tCCAUGPVEqbaPtX1GsxRX9cEyRP34uth4bvG5IwXtYUK0OV/H3ndFnbc5usLP59LeodWfXxRXLdL8RYoawrnlJlAbu37dLT4rNDxxpR/BT+cVDydyoBFG9oUl7NqieDHFqepwgEzJzi0wKwGXFhY/Z0F92goKJxivv9UAauLWymWWmdCgLvAepouz7nxvhmwF9cDoTjZ6XrGE4ILBMgnYor5xhIaJ0vX/WkTE55EqYoHsMCuTvAxeQ+RxD5jpFsbR33qFqQmGYNeiSm1E2/Bh6vw/bTwLW5oLFQTkdBUejqZ0znTk4RD6opdUt+oiuHMOYoH9dboXuLt8cat4Cv70q6hzFzRjlwOCEKSBvfMw6LcEnYi/c5TMmV7MokQ7jqrY7mIlG3yiCQ4rakzfDQjvYEwtAF+FJt7BwcxRFYfOSo9rgxQfeFMTsi6cHXjNB7ktv00GliiYIWeMAy2yV17MgcrJPMeU+QrwONIFqdHk65tUPPide4Gud/rgel2+ZO4lxQju+mgOibFl9V5o97Dbg2kCha2gnNnMTScZzO4AActz0AKLBJ7nrhCxyYbqy0TP7uOw=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
