apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCSHTpzCDpS70obt8ahM1vqP4ycAFY84c1QdfYQbxVTuZZofDRAwdzp+/WMkU60hnkFhqwqwGrRvwX8bFc4okhIe2V+hBmFh5H5la7FAVixcrBgA3DF+s+6ulMftg2ii9tBcW8UTaycepsjPZe/Xc/royecQgnrZP5YoP7/OjaYKJR1mb6PV5Fs7pwmM3jnTbTOq+bjNkRGnNUsX5yUlqZ5AW/G4wnRfEqyLVae/vl1V8fQ6PBcliaZ8rhReVRTcR+z/OtKrlHrUGZ+F70r/HNRNOfhDr43N8rN6WS/SnelXHQgOXr15qdattXH1onBrFb/wrlysmcksntyskM93tpIY8AmaidHpTr1S4eJdEbgbqYXfQvnyGtP8mjnAW9R1MEs9wL7Bv4WxvicAUECVz2qzROFM+bdL3TkS+VbyJODIFp4PTVUhdUsyGYLm606JSjYi56abePwAL1RkT99T4zFjPn0FK2rrGXKTjFRNHTBOWJaLAXbNSjDNCPFPToCxFGpnAbhyjKhBl/MGSW21v0K0py+eYJVA4UIRjt0LJXKxYeCelcMSDi3ohEkxDpk/NAh0/B1SL0VkoYwSEBVA+THVrlJ9WUAkhyqHzaDTwwDt/AbdkgLNjGd+Nt3LKK6Lk0+x20rvpP6v3gtZto0GnkF9nFtZTm7VYr/bua5sCaFM9CH8drPZGr+xne55RGaGckRaqs970rppAVwupmMYfG7ip8K1m44dEyZvznZ9zqgmPJYx4YQdzMf
    username: AgCRqGfZEGs31EvK1NKrYfi0jhuD3rb7dv/gGVV/zqb+aFj+aZJK+lGtxYL3GsNENTrV7rE7ssVU/RGO7/rwy08vL4ZuY8GOmAAx4MOIHwBjGhon7tCyCn2m7g14FDL6rv3ZekNcWrnxTT8vogJcBwWuXSMPpugX4LEZUm7wD+q+X/MY1SBkYdXg/8oGr8qhXEOAFLzx+RQwgh5KfA0bkjx/dNvzgQhZXtJjIdsiwq/fy+Hbhaend76XHyNpsfozFVYghTCtxRhRvPpR/LcUzoewoA0bBxREyTt0d1bvvQPQ2ZEW+LwxU8ghEIpLj9NPSj0wlDHhVfJhQXr5nhrT3dygPtnYQgmnlG5gISf970TK7GgzMX/U7pEhha1jR24ini/+GSCNq0HC3OmZ2LDpKZ86U7LTUJVLwXFaw16X39GC7gRXrrAawbcxboUGxqPb1RMQXq85bCn2DbBvJJvVCcmNtmazrGTIEsPCjn8fX0SOQdPetVfOMY2wumCpUmniX7wVjpN/gvAZ6Io7Ere375Rj2w8fRXLAGWZ2wyBiXWZbdLZLrvbfxvFnUTuEf9VjN7ofEMGOqqBbUmo5fmJkXpReVq5Ueu969tZGZ1w4RKAkUNoHf9tTlx5MuJ+OxNniVtLSQoFk+0aU5+00pjEQz5zPgoTZNF7QIkMddvgOZ9Wbl2rBRHxs9o3li8+2ZQKRA300MJKM0gA=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
