apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgA1CnnZXP3KyLD2NYFEGsay1hx1wFU3uTHB8UALkFBmHzHYIXp7dXDbphX/7e4seU8VVLu0aP4pjLlSu/6yq8Wx9h6Eg037zRiXl0YurL6x81cv+Tp9UDZQuUa3B1ljYUjl0YSqQuZaQav840B8HoMq5Xz3sWxHQ5bzMg7D/N1IIKdhNjY0lmS+mTl2svgk+5TbbCcrcQWIm+NrU595oqsj6noX9ycQWLtjeKDj+FNOU16AKjQCAffBq4EQ773yhxZCeNJ+gcmpOgH+oy0jxKf/ShC3jVSCDgWza2JokQYjXsUh6Hz5kz5aMuVP0o1GxtNsSRzur6V4tMKP/bHiqBE78ikoijoASRdZAIowyVY5HUROa59hx6saRFTUFgOorrmbOp+vTXvy2rONEnFV+ZzW7w8nH/vToM6vov/L0Wr+fR19eaD5strYlpZFleMAlhxTIDOXC1t+3gz9BgFQDcFeOyUT03PwryiBndVlLatcU4YJIqfBANpRxagUmmXT2SP7w+Cwkw5RIzivbKb2n2Xh4EV1nJFyHlcO9IG4b36MLmZN7Fl2oSqny+L9IlO0LJ98GH4HXSu/kNFpQHoJux4OgwWWj5QJdTFJYCT7XSoNiw1a7i7f9Tjd/IAKSL5TrvpkTlBpeZge1lFDky7twxrrzY2kwAzMQe6+sRfSepjsT8HaMhRHoZrvVTxTKynJ0wObzM9XVovYMk3UOeu8ymwQciFrpewPPATDV3CcNaRGYKy9BXEvmzsf
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
