apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCKYS885GriOuWzhM+n+ORvIq13mcsbwGth0xsIkpgJ460O58u4zQcxpfFKM4ved9fKPjivJlWn0wKg7tqSX8JaDuMHVQ4PwNLMJEYoJHJYArF8Ef7ZwbcefmLk+go6+GOaY/rsATRFv1xLrUSNEnrCXywNV4cqebZ4xiwXd4ojoDtj8LrjOXsj7qdWRBJGrFqmgJJyampg7KOTQJxF0SVgSbPceraochXmW9hYLweGur56nTeBscBCLPt5GQzukY9xKcCUL+wWOyuPeEEVpJsk8zhsD+8RKiGWRWyzuH04M6V16Lp4WipEaHkyZ4SuKPgNtdSsygEKQuisTLBs2gJDA0GfFzIiJ71O4V1BYYf+2jgnwdiZYo9vSo5iSHHfj7Vgc9l8b3hdl8Pf642NyfZwduGTNHfcCQTUB/xMx72f0GOLrC4orRaBPRSAOn1NDAuBcROWaiQhEO4l4By2qtN+C/G/TLtPT2auwjR5k8nitvxkZCV+EdbK/BDc7U8Eq+YXqhdLMqS9d+6d9NZxfIequjijDeEXsdV8enuD5rxrSK5Gdu9h76D22QzlQS0AjBCoIZfno9WVmEDiDmp+cviCEDn6LDAxektcM/0zKUmT7gNjxNiIz/0JkxHT7p8lMRr5gFav789Txqyk//tsSLEWmZsmp4YPSjDqvm1rf30MRJrN66xX2FdefX9w6VR80N1YtbBBPj14Wi/84iKrUpwckUIIm72Vp9UWOqERbjkw3gxB+m/yksuf
    username: AgBVavO+nRj2ITkBRblpgBQKzrJ+LtTmtO5I5qn/Geub0dF8p7uTMfPruG9ID5KzajqILwNQ+wGiyMYg0ZzckeF8kNnUlXdCorSyrjQjvn34BFQXEO+XZ40vycrkEpLrePHzC2z05kSxhTGbELX1KD9ZIaikn09EKHBLeNx4bmaBwuWC53XW3YMnKf6yZ0tqOPAd20nMtJUkH6vLeOQUuWAp5jkNIYOSabTe4yrVW5YMHID58OQAH2ABEly6ggZBpROOjqyYALcgrArtTJ7TWgHsqCIEfv4xMeC76OYZqDBwxZY1VbHu4WPmFLxGl556GXRBik17E/OxXs52fMZ3mo9N6bt6w1hpOPBhWWfP1qOXy6DwoNerJv+j+0yDPmKhO6HqaIKSES2it9lpdI6amHsODdpO+jVB5ioMwjK0m7isLaxjBVrz1Uqpk1MmdvdOzpSqucA0TG1RtJfEQ0G5nqzfD1O7fKsp6wFxydDjcoOGLPpi4p87nkaxtBWvmTWQ84Z2Sraxyy5n9KHK1JLoew9TEqU87x8btacUXRDwoa5+wEZlySw1ePHTg/yMnfNFSh7PIbndp4GdQVwmO1MnV4TLcO2VbOh6cJ7BEQake59pppHXQZ2+7XZ/TVA5fhEzzaXnlux8fmWqZw+VOSf6g2ztPVuTBtnYO54SySg1sKz9g9w3fw06qXyI6yzRKseB3avIKpPxYNE=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
