apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAZYMx6HnR3O/EwP6QgeREnYVEGSTwAjL6T46/1d7kvASErHw+Ow/6IG65MMg1fgrMxZFCDTB1eMaHreuOH7bhs/y6Y1ZtB6IqK7WgkIQwNTuzfgk6pwCY03hzvyKKs4ob2SKoinuhQ7XpUA8IgRnIJheSL6mMjspFYeoQSDeSEoLXwR6u9zUthfBHx2nMopkHCvUjsaxEszKbhch/FZ7mKvj66GpeD+Os6llqS5WyAPua0rv/pRrlTvPyngbX5DrycOv26hoqH7ZpHWOSVmg8Jr623+KPowsMEVbCN9CaQ19jjOB+bF/3qSUCR3TfQTT223/AaGMZpgEBExO0YfcNwu7jHfTVEEyhDKQRNBMRHi8q61q0C+n6YvHnBI7obG7mLWbQxxMgjfZ05SgauYKzdaZ8MsVwjoc8YEcbRQSX5R9GJ+8gsfKeJjrNISEGqix7ZdWVhrMQr5SMwEk+waggKfBczBFv+ZUHAlqAnczt58bMnw8brOwGGh6EckSZ13p6GzGsklw0olOasCQ9MySmmaeekzUfw/Mh3B66CmsS7XPMqoDS08e3qWIuEmgE9KUMBXs81XRbYsfD3QvYvZEI+TzbAo+u/eoXhm9+NwfJ+d1DS01GDSz3EA+1mfPuE065+eKoGTvGJbFjrdXBWyN+e5EtfDgYxEYJ+ZMFJKoH3XYWQYAfEDK9WyaB2P2a0xkfucaKvG5ktj6DSTNnZok4VOrrrDbT7UsiYgZiva8G4PdY+zpHchu5x
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
