apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgBl+W1rXynLkja9HgKsLrVa2yHII6MS01c0bZCdicAVzpG/Saxbqb0SsJzTD5A5GASYgMmefIsyHUaw+WU+xBnxm2o2uGexhFZ+4JWENfCJeDI+AxPCis+1ZLm4Nq0wAJdEu9n8fovSe4/FcmyBZ0RoDKC+/n+314ZzsxFjQm/wsX7gq4IIa+SwSl2SAleJNqZT7ZPvte93/vP0eqAdKt1CZ2nlFr0KBrguGPBbKKNBh1t2J+inEj3Wl3K7MNrJ02YjHAukXQKMOqH00KXILZNeTCm7lQaRY7RzdoYXCPTq+5Mol1PlE9rFYAidvRNcaevUlgFT6FxspvQ52Rw2fHVwhQuHeEWeJv77gpQVMzcX7QInPpaQCRlIZfH2k4QpFLIcJb1TL+MRvH2SazAJpH1/MQnyDpBwlZaaH+sAZsERfH9kVD79MxVxUlb7xq8p67NkRlnYvIUuUJ6fx+s84XBxXtbX1Yys4lF0nnEDS5gMx42fCrBlOO5yZptAGa1RYr95nEmhS9nnZCcoMXZbAL3fp2e5V3gz66BTS01JwT6FXfO47RbJe6971MjEShmalBswunkNrwr5GYTBPJaPOld12V25PSFpPuj+fwZR5K/CgoXWDCW3ZntvZ13oakmN69Vxp22lpIAoT07XX4S56WlwVMDomRmTWWG0TLfnGT1D+Gde9MsRDELJ3grigAkIPWhWXNv1Ar9Sq3zx1xD7xIN5QAcMcjKLbEI85VGaj+F+3JZGpRTZ+sDn
    username: AgBWTwd89gXqClMWs0i0y+uHuIdd1wseKDd1OvzbS3OO3wBZvF90aFJ6qXRzXG/2xd6OZ1aeRckNs0Fj/jR4iCtS4G/KO/CB4JcZDrjm6dEWC7vAO877tlg2PQpePlFlO5Co1WhPFOgAF9aUF9olhr4EuczhshxYYjg2WmNnTizH0MtceodJ1fcl9GCqJ82vkIVK42dwGqrsq+M55U3RNGtmOd85TpQ8xm3L/PCoy5xgs7L2DqQ51nCFYeMLWg0yip0cCrWguIOePodAoooKctxN4j26n8Jo3b5B5kzZVLrvNzajddhA/5+v4epIUpW7dlNG84f61OfG4zzyfuCGl4ZgbnAcJORmzNa4hwzB4TTCIn9nE3eCSXnvxx9n/1L0vZTaTOFX54KI0+nL2Qm8ZBDebN11M9YcZEoF38uLnSKzn51I8hao96LgDJ4rPzBhBSBTD3qu2Bkq7Qw2QCT7Q6eQ1KCBpaIkmMvkzKGszfiDzsCHvsIdSZpBJYF9GBlMf2pFKtsLgQKHmZtOociOXLUSqs1NcFIpIpXiHpNcL2BiXOD/FMEZptu/PKBFBakHVbGCAViW19d6HOMvLz0eGU5+0gOzDDPcNIESUEMR8QTeSoMqvxhsUe5LpssXTpB/9X1y7DSoalGugEB9ll0P4Wvz2K50/Oq+UpEgxt7HouVqMN08kUkbAu4cv9eltA/pt3m5Io3KB4k=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
