apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgC3pnJCTT/rDLRXVNTvG5+t36DK7rn9wI652UP/Sek8aGNO9FSPkNZbjQlOf7+iulsIOG/dXg3Nqf3cC6NKlrX9kmwIo1ENBOEh6t5ZDKxWjY4K4lw+Q56blBm0CZoj94atS4aiEu2RxDiCHAdVGwKNkemhSj0yYyGl0Qqwy9cYKEbsKlBDNuguQhnKQvi2OjOrcF3g6S0Pn+8iznoMxYe6PsDOipQZmKodbyi7a8IejwfCJl3yw9lg70IgT/sYl+u0G0NWouO+POXoAS6ggY2Zk4xy3BtztmOpOSH/GBmX4EiyNXiudlko7aT62l55w6YuVmrPNU1cKKgt470ok2Z9ycvZOTxy5cTDT96r+udLMMz6ESpTjkkcibBGKg7HH+L073JIxCAJXOqZsU6GOOuWWb6M1NTnuYWBZHvEswlna7FTKxXvwodiGuUgeQ0KJxjCpwYNgNx2yVb1EY+5TcCUIMbiZEYXU1l7QoPh/7q15oIzqVF+urHamyGgLoNPBx2zd/OeCaO47LzE/hnND9z3Ro0h74t0qm4IYmVrfYTbIiRebszN2B4Ney3we66NxK212iO3J7nHOMDnHzladlhIpFfGWjY2tg/zpi6/OfhNH/UAnUE9p8L4+gxiKoUEaLfRd26MHTA6sOP74ULW5NgA29P3cUWn1vi0E8OKH6LsELY5b08fd9tZhTyRplwB/lk++ayuMVsNBKtjeUeQ/ixIrMsu+Qk9+bRqAtdxf3NjmpKJBI2a48Xg
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
