apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAcSFVeBtpmwPrKqFzXPXvh6J+NJ4aimPKLcs22TrAwwxBfOErwP+lON/i69izbagilheYc9lqrUz4EEI4ns7pkyFmTZXzQTKrWKGQ0GbJ1zYUcexW69I9eym2j/HeBvVTvRwQmHf4VHRybLYYqZWpx1e9y8hjXBfREgxBxRMjhK2YtBfsmhQKqQA9w76ABanPLsOj+tGo0cMHBU8EJ8+EA51B9zWNoA7lWzDwhuY+iQNJPn76eNAS1gH3SCKbM/R/xq+U1R4SgosxLuI4iz6GWnb9hfdczqIRvEGFBGVbkXADsbwI7hFZO1eIgTaP5JZ2uU3/sjgliOZ1cKS4OJNU6f1FxPNxGrn0oJ+MYT43/1sIPhdCL2o9Foh1baBqaAYe0G1mdJGC7LWkEVbluWvh7c//JLTlQJxgcHRvkYIJAECFR4UisRrf9CyvWM1/pWLXReFr/P2c+A3nm6OpRgQ6hMpsEbFoFDDAe6YH/MIRXzfR+lanrJ+bNsGfxPm/73iR6LDkJ0430KnwLxdpJyFqnadNjcHCTMpPQQH3W6w8HpGcBZCQVjroeVObzRgUy/kc0GgAjZLvPA/tsz6A/sVi2UoPv4UqPlGuB3/NJo9Y3w2MUegO08tKWtmQib1aIu8AxAW7WnM3D0Q7aBqpx1jhuhsImBAiG0lhSJWEtPNY/DqVtXeBxO+53actsPLPBRWvmbnP1X5UpQSPi/vMFfDIO5QHSYuv8lPp6XiVTf38yvQrqJfDqS/WN
    username: AgCE+ju7ZBSMn++Om/zAAZ64Syv585J2m9M4HINclnpCF6tBAgt8GAyWmvt57dPFkjdtRNuFlulMmRBKvFC1te7RmLKU4XcASNjtQBwwN6TXer18WHIFb/dpie7JHKBTO5Re7wu3lIuuv3NONvzwRXSxYV+QF4IzyWQor3ZF+L/sY/uYIC9h5kNU8Ugu4A9d8ypKj5oIG7g2527/JnVKPrNU2tbfJ06mFSIcEvyfF+f+WeBHN6jPbTOwzuVH7p6sdCJp1go6kmQkZFTFiZSW/bCxnOGBLrTZ33jiE0Ec93i07zc9Egf8VmcPLtfwgVNveUIUJXm1SH+EgCkK1FOoazeh351sOFsbS+ebS6xgPtReB3f2HVie348ZtUJdQjdLMf57fXqqPZXTuBLLzR3MEZotrx9kDszUEFNZOPPFJdLeXbOj4zE4cdaxhbC8zS1o9PwaCAAl0nbwDGuPEtkFilnsx9ar+/2epKr4rN9jB/V2JROHW9F5ot6QIFKhavxdt2AotQVeWSvfJOVBw2NeKkk1bUt3mSNwFK2ndCpNjXIGfelbRIv+TwD5Fyq3SG8V6lZ44dIXeGl4FPLww96ZLz30WTkBII6Rk0MRFY7v0lM3449uNELIcQApl5HIMGuMSxpOeJm5TbgoNze/H4E8cU3u1hvfn6Y1ns8BhMXfOzl6emNJdl0zplDbH8fyYbmC7yfrZLPQ9Rw=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
