apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAi1p6sH6szjtI1/cema2hQ21nc6SmZckwVsaa3hQfYnC0x/GJ7MoXInpuBXAGGBU/GrHfhTV3a7EOc+YfeJIQeMD8X8ul/KCII/fK9cTBDxXrUmkplgAUkQUe+MfJQh4FzJlAyo1Mpi1MZjYV/SFt18xrUr5kcCJX05lqTphNeRNkym26AXlmALXCQn7xl7Ocq1blfasqbhUf2OEnpc1P3A9kHk42yYEzlVYVdvWaTsqAp0zck4+BEu6t337MDcek3i5BjPwJ3a3IO45tn/ymwoVlVeu9A1yHzRAl//eyVOmApXhgZtiLAM9VDe5IOIMrn4ccpMWl21kJNuMkCNLV3Ve99LGHrCIRKlWsVQ5DN9Wllo2V0BiHl1R1sJ7HSYauYYKDmPMzfBbkWMO5Fguz5WWwGuSulzcjoiJ0WBH5CxKsbcOEIRQI+ww0HwF8M0NlFrx9rXCaDmgYFLfxXl/787OL+YMIUOH3w+O5u0TEECOyOFDFg/yAmcj5v9QgLLBpH9KIbGw2RL/5IK9LeyUDvBt0F8SzILOA2ErcioyJ8WtJCDXjw2eHuAlovIbBMYyqqFbxtYtNYjHWnS8JnlQTFI3B5MwquB95k3tAKf5vkpjBHCI1Ot5M7djSB95bKUJhfFjm3yw7cDuH4+QiXdFUpxmDfcb/k2NpUaL69kLM9lWwwNqkUcuLtguaGOouqBMCZIJhMLHsVe88OYoWuUMnJhGgIxoX16m/z9yvDSWpzYumlrjVoLxrS
    username: AgCEy6GPOA8sbrEiN5SlcH9NZNdl5nOJyGHILqdTSO2t7tmkIcIY+zmnPElx8QOTnu2SmiA1XfTuZkUN98FyLlvVg5VOILWyxRF1RvlxqD6tvdDf1CVVsWFm3WcCcbuhfvrH96RgcVK0P9JF3JJTlDMeGUtqFcTNHPl8RjJk0QU2H5pqJfR10X4u0iHb8CE5+3hltQeWtOFiuOyR4jHbglvtxbjSvHCVOs2yG1gWnXz0adBMHXuOO6Q4PgBSaIF/JvXv4qhfwuII9mBWBGvyjYDkqrqcFOhYly+IMxulEv0fVifgsX0DD5kE2X7uGcr9F7tAp45MFw494AiyR/XwIXo3gXj/pkIRIaLPrFa5cPXu7VRXOgHdN5V/nRJRxHpFQMvbD2H1jfODqnQAetb0l12otgjt+vsvKSWeMRX7z2PaZ3zRnP8Ul0AXuTk9D/d80JFQOJ2xsQYQDYRfT3+3Q4LuBpq5BtWvPV5e6m8w+HOKU+zxRxnPKuJ2xcUcG/PJX4Z5smqcht1sXljPAbf52ShxP4iaXPF4MIaZlOY5Z/c0dXRdZlgWXryI2Wp4ahHsa3ks/k2a7f9P/RUve+f1I0RCQioXcuCk2fPl5O+FezA25n4KdZQiinBXRtCAiFuGh4URwsFblTtUF4NX9FdoaB9RL6S3HeYf+AUy6Uzy5dUCs4E5ubCOnFmPXSuUxRrtngyjWDXH9SU=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
