apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAe4HwKKfX4W3L0Dkbce3sTfmLNnwjbXmRKAzAK8LTMdKsFj/7k43oO4HQAvn2q71DYqnj+ctjOJ6lzGb1FqdzxplhH9YCRS9F38FZsZmjUA91vbSiVrI+yOkS+FzQmO0b1pAdNi5/oUM3rtbByjVfed8HgOCyEKkSknZvQHvDM7jIZT9+vZT+RH3p0EUTiSfNOvn3W3ceaIrOTpou0UVynWqWVkbARXN+UJqBmTjrtThigVE+elgvcEhJsdk9PAlhAKr0IooDWtIt3XMWdrERArK5xKRFdMsNAR8DtTbpM4vuvubK+uikCjbi44vtBtYInBkd5docI/AdJEMLEwc+kFHvko73kzG6cO5QwiLVa5S4lBjaSEwj8HZHSunYNr2Mum7QGzEq1WI4UOABLWPjkKSZfS48BecqU22hQRDPo0KxgvIYIxlM6LSU54nvDl6Bc42oVEp7hrZIpWah5FuHFHyxA8Yxi571Lh0fzfNwJhi/MrvXRHGPUNDvPJZdnHjL8DBIHrbAMpr070jRvlMYj8j39nflK2R6eo6gpP8TP5mRZsePuvppsjuQYnh+DmzGL+A1NhVe8pYXOzIcb6Y4khXrZYR8f4veQGla0OBFCmN2fuU5WZdcjtLD3rRVkcShUJAr214wdlCatHsuv3gwvGk3wROQePQKjqA93WNGX3PB50hsNnViOReWQc84oNri3Dm1xAYVMFWzzPR2AvqSQX0g4LGaO0XYaZhSRj4U12yWP04Lz8eCT
    username: AgAgz5m0UstCVGLcpjrARjnq1AI7izO37VoPar8MeyFr/ztU5L0mI7B+j2/aEFKPnBer0Ck0fdPHmI/AOd+EpSAFvJ6AkVhgLTz6I4AmbaXVaF+3nt3Iwr25PK54sv6LFID493umTqWXmr5oOdl/VxOG5cXWXmqgFy0DzA3dmNaBV9XlYvaxxTxC/Pn1P3fwKT70L9piXKZEWPBi8juK+awwh0tSyUM4MlGa63bHQnD/fF9OrEUv3gCAmC0q7VjT0d3Sw3yHah7kG1ClU/vhkX8eCCr9v6bQm6Z3yjlpBl4QorwtC2z7Jmhejdd1RRTlHnCnL06oslm4XPt4tN4KBebiqNPXMLJcA8ofoq+x0+/z8a1iMLLdDzjQlMMKaIz0iC4vxPn5zybwQh8wurxGNj5f3FuTO2DbfRCYzvOzWNv4ZBgtWs5uW7wEDhJRRf9rWNiUM8aG38d4p8m7cAe4rC+tsUPhx+D35quor4bnwZuav2nBIZ0je4d3j2PafJznxVnSYxCVFNmxkQ1oLLQmYHQyqPhA7Pk1aIl+s8RrMtSsGZ4aofODG3Osy+2fhWe2T1FbrMurFhpw6e/KbosrtDF02qGdAGD6KHYxkemDG206LfdKvYHjtJXgl7a1Lb7wrpwR9qHbpO3PeyzLFCifvtKK7tzcDN1IAzklXS8eQgkfQf8Bxt+6a9vo0/KQPiHkQ2FhVjsKjBU=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
