apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCge1KqSwH3xRUR6Ys8G8fSZkHk46nI9uWP/gvHpNgDMqYGcpX+wjoTEPxKe7HrcqkDPyucf7zrhGyRXAdPmodAG48l6jeErze6bC8I2F1GeKleghdFNn8dKz0EficcR6th8Buv7ATaCsuMp3KEDSS8jhfLgc5sMN7VvInbZTxLM1eaqqefasGONf0gfZNrbYVHptOKRcjXIHTyArB98oAW7rG/uUQV1kMJgQdIfgsxRMjmmK1AwrG+Hyt2ty0W33Ib6p5U9gqRhXd0WFJ+oH38fMBAMT6USp3R34feoxiYJELtX1iZAMU7hss55qOZ1yB1krxckMGI/YM8CKmuQHIuwinXEetJvWpYeIgwle1HH7Bi4sKuydH2sUz6vhLH7unROsRKxvdsUi41Q/Z2S9w5CQLH1NmZ1qbH6bpOGyglrVAVUuUJ/75nkALoi7ByNfStr6NHiXCcuh4nyaLZ8WxNaVGRzvaTks775N4aWB67u1UU7NqBogi6qLaddtryCFEyKmFGcRXZoOHNT7PJ/bCWE/mo+3ocPqJPIONk+fCuQawnEen/nQ1EXqNdAciEzetw8OaymF6RjlM/r9jwRiRLoIgoi5Rb5aF9qJj73EYX70oWOUx7DgxmaD2z0NcLg0PYCr8VALIb3a+0pZtCWpNkKJ9A8M2JOyNdVf/R2NhbOmLwoQDjsBRxLIWxUvSFRiz65Wpze7l4QI4Qr2XKvPB/yX2vTCdovEbSFkBdP98CUc1vTgGAeFC+
    username: AgCS7gh20VW2zJ8lJppsDfl2z8qVlIzSBYFCQxYKGg/TYWrT4fKbRWizSQNeswaeXZiPtKRMqHGY3jsXQL4lWtWvl5d7P9tDXG9fdcNzGzI/fMet/PboyLM/EHHSDBeymZnUwGxGdkg3SwEFRw0sDkFH/WP81XrXH8N4/VOOismx8Xg08HjVbrPaCxZsU7ttr0XQ0ge3mCHsGRL3TBkFz/CNTnAfCL96yySC09Od0Vx589AIHZGuoEgCjpXdV+KZGwoMJ47QKCUpz/eCl6tdGWh9VqA1a9DVawemM7MFRpFgOzuq+Q1BuYhFjt7IVE3e5LCCvcDxothm4vspSpvZJjBgs4PXlciKLRuNWrFswSo5KyNCeNPBk91XKU5lUGe5OaJ6MZ7FT2wK81CdwjF1CFov8V8f4d0bjOaUdAq7Cmmkox3vW0QcBfOt3pdIPdr8sfSqF6RXlXT9jCIh/I4c8QyQBln+r01omPQDS+bjuFuRxvcKOl9DnBcpD7i0QcK17yz4+E6h8RuuBO5fVtIIEOnlzfBHoY+mVPJoudnZ9XS9mqhvnydrD+vdGLj5UoRLyd2A/eYsQSvS8GJ1fxmEwHFu426E1NEm13iQojVaDUzzSn58FK24POD1f8r5zSbisuebVj8yi0Cor8M4Vb+7j6uaPN8bQKLJ/hH6mItDdXqm553nM1PNWczNUkQdwcPz6uAkFjSdApM=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
