apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgBnXO3QA3eIQ/AyKW1LRG6d6zjFDnZFniBW/6gc+t8E7QrXgjTJAqAgXiiBrz22ng/4Sswo6DWw9lmyfXfuKnwqpv0kK7hP0rtFvWUtFQkBDPJrl32hZt9sp4A/XEYBty2P4ChCL++T/sA0wOciVcompPJqM3jwVoSNZlcsgMyRHAS0nFEgKF8plvgQg2qtLzN1ssI3+t32C9srIMsIlrfNo/nh2Y15iDZGkrhLlKDjitpssL0qa/awgn12IIDmb0xd6K5gplHqcCHMWdktxnIincBQLkQWk5ccKbCA63IU8jYLwZgB3zasxyBYAMHfDaK8oTDmjNjsG+UZhm0fyMsBZvNQU2iO9ELpLxJ2IIib5v30piT1Svbd2HW+ymSatlZEMb8lUjte3R2l+yRcfc97AfkJ/0V3ssW7tczTdSUECWHlegjSGZ1OrTtedF6Gep7NAmKSH/REjXp6mkfFirW2Ke6Sw3BpBb2Ug2dle4hN1OSiLUHktTJaf5es5igLmIj4jE3GzgygE57e2jMwYYPHV7/soiERgdSG54ApG1S8ES9vdAg9uunGpnlo3VFR2UlcwsFoQeHsVNfym5SeJr/0yQ9IeoDbU7IRKWfwKmo5iUkY4U2JEh6r2rbO8Ck7DKZ+esXG8T1rcA/2jW2BoQAGtkfBTORcHbMPn6L8/DIYuM+8YKNyqrkiW+ZpZEZMRk2zCVRlidbbxRKZajDQaXNIgv/FfI9jXLLntg00VOn1B2Dv2YWCKtG9
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
