apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgA06fPowesPSTa6TKFNXP7Z/WVmydJT/5GfVB4wZRujcKP4mhugBw2nA1eM6RBwn85SL4rEPe8AYkDL2Md6NCF2L+w9jH26aVy043ameuxwOSO9sSOewm4mJ/x8O2mruZFMQTmKr9BcoDmw2MdAcCgEappMjtuyioIctDCH1gICTqf5ZUMS8OnnnyKKDYiCK+kGf856jREpzJ5o3+Zy8sYqhz3bXAQtsEA9GoO1H6ul5mFxACvLMoyFtJeA47cfsFT4qNYPuYoc6ZUjVFxTupyvJNXhEAokCPBu74EBISAExZd+Uks3jOYfrEAjmRrnziHY5aBE0TI3rUJbRn2Ph2A+l5/rFViA3XyzYUcsf5ksbJd+KannVQgXrQKvoz58kZYEJzj1zvsuqDcY1NS/B9KA8JO/WaP3mjWo39YRz5cRXn4lrjJsjstngaDpZE4GhmErbVjnz3zRhbTBEJEOSGrMo9HGjLBL72JZXZXG+jZoXPSTjdf8bbdf3vgT9Ev4XDC8KjgkjgzU6JvCCXm6uflsz8KjWiUoV3+sOx38nmYpti+I4lRNx8u3qoKSCMaCz2YDIj0/6RnYpWFrCWp8wkm6wgdA9qyoW+vjFxDlB8sYdZlv1JnILK0hE0aiTRY5PxtMTQIe9pdqf+WH29+fMNpcHjQ8rROyxQA2kk4/D/kR9zUWThsvF2i/bw0t4sXY9tvsX5Aq1QTdgGrOsegR0JKkBWWuBaQ2spccupBJ+NXZHwzCF4eoYEhJ
    username: AgCKA0xkDwY7znHvWW8PU/J8y7GSe4PZHCJBkFzxolI4kkf+z4phFUlkHhnH5St0mWk3cxzC5VQ4ZoWckm9EK9aZx9m46NN5rrmACQWPIE2OCey2zkr66epTVLAOmdDzI3IzakHcR2zPSUj/c6U5+ATPhLiQ3gYpnCKi1wfPsm7sswkxZI17x8a2i/u6dJ5jEiM8cNHievCGVg+bc8j8fo8IN5e6XLofWwJcCYiMnWGaP7uJoPH4vbcJfM5AKQU/x0kdStogBjw9vN1tJb0J91c8+1m9z+c81ls9fsNYOQTogpwFTwGh3Ji4gY52nDBOokl8OiX9fHGeqyee+QgYXA5g6E9WBcw97cfy5B5GZsN+14NWYvBp53201C9ez+sSunOH0xkE90W4dhKV8fxeU7/9uk4yMvVECmQGfgk+bnZ2oFThTT+7ed48XYlh2u334p/Fea+Qa3FXUgiZFzSbqanYIWhPn9gc6XdpIbW75/GNMJRCVd8+PL8HEJ3Nu4jNhxZyyIcakbs8qjXEfOwSTbkNDa984qr5sflYsnnZMfLNkMs865kltgPj5wwbhQ51dGUETLPXmcMPwnx4L2iFsgyRxprh6/VmyDDx/v7tyZ1414JDS40285aQExyPuzZlWLEVQrZo5DgcvvHweH26Tvz2nh6hN0rvRbJ/h/6ZF+YiYson2fIqmjF3R5qTtjMTgoS+xNJEjxg=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
