apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgB9uN+CBIh1zEfkBW03/JgM7vRosFahy7efn2cKkBXpNrPS+EO5u+vyglucalKPa1TplbT/k4HskRh69a9ydMtOYlTtYdDSb4aX/3WKDI1aWF5O/QfkZMA7JdWQPjDWaZl6PF9LqQiky0rSwsdHtgBl3XC5bX1yXQvjXIUaiecAdhWcnWW7SZ55pNTKCt5lziLaMWViTQW7JSDu7MkiPVAX/cQj0SRKYp07l2FKSmNhDYwB4tYbKPlclaHHMA6B1l/pcaN7tynKFgPgGLHQ0/CQSacmyqGbQVkfhNKM/7WwL319otyZn5X/iuKKNn5Q7pnd7AlnaCxzI2tI9fOaFKrA4+DPpjLWsnARnJHGAI0IqeOpbFPnJX4IBKxmoWJz8k+r1XUE0/QSTT5w0aoAMsgERaPUQiya6pwmX4uDO3Pei/xTsyRA1Tsi2Dy3ngVVp1+rLyGNaIgBjSNEX9kxum8AJSRaLRGlhZ4Cw2dk0c3ebCTKCUEXFLJKB2PFLbDYozBaO6Ho+tWagS3hfbxP969KPwJpbS4XfqQvBvhGvw1w6grwRJTy0/AOl5rBH/ZGk6P5p5/xv4rkRzbsQRqPUEFph/l+P32+3VCUOfIZPVvnnWSeQ3jtdcohOmzxUJ2ww7W3t8DkRSsNe0hNoHEDJd2hDRM2RrmblqWRkT1obWylIcDdfkWuQc12aUPY+au4zUTEpKijIpwD6kJ1JNgO9py4hpa1T9gvVfwSdEUuHuFb2gELsyRPQ1jX
    username: AgCSgPVVdXvbKg9mCB8TxlCCm6KFwVK+9qV9zTlngap8In2RIF4jE/1CBxWUrtGVRCdmWIoU+gNKNuqFH7s9U4osmR+qsqULflQx77v2hRyoEA90hFCmDMI2lJMrL+raNXix0N9ncwd4kCBe7a5G3oExDdoz1MjiM2vE+jAmNZeBtmQsZ+6k7u2xKllyi0rY5eN39oSxCYq469oSI0HHfYdjBaRq+TJR3tb5EFu39/Mm5HbnrRJG7QDzY5SYmICOMaDQ3aC512G1RHs/5qOgg2JFE+G1G9d2PnpYcxbE+rqwSp02w/SwsCN4YAFw6Jr9q2j9lSCiSqBJrn3a3UFk57anXl975H6xzHgvuXDKUAWsei/t3ng+nbyxofZLDatK0l7EHmX8rp35j30roFAZMfO6miAeLOV49T7TJFpdN9q4Oex9hWsGPsElsfdbjiaocaf1kRSXTDj5vBlonE0n+xFo0LFmZjUMnppviFotkK+TCpdX4vj9bd6S+GZJeQTmIdrsBNZHypOYVTmwWzHEURihudhzB8oigbCQWahovkf72f5wosgAc3sYiwTGPZiNXn+7OLbBG/WhGBBEtMgM1veH4PGXv0O08EW2y/+SD6/rPiKDC1A3YIrhoet4lfJ6z97cCbsmCTUoLhkSs7yBZmHIXV+F/ZSCAcoYO8IJs2Sb3DnM/cOpCBD/mxCExJ7leZnB/qyoMOg=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
