apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgBnmDwJ/V9IIq7olsX7BiW6HQeJFKUiD1J8ZGRueF5I2innQvYthl+3ZvwRPWJ9awMi3GG44zetQAntI4l6CHSyiOXdWVz90RvMt2/9YUGBjC1oO2yr+KjW42+FoM6DNQUserlIKFjHRl0+mi3mQF7tcbQdhIqtHG5lbNKgxB1uplwb39gCU39V/kAOBzA7gEVOUxqH+oaQJxKFbpNk0Qz7Ue5kUI7/3Ajn3li5gLJnLFoIRMDRqf1jMKQfW53jn9CDdYE61oPgxIt+p9zDxNJyuEjYc2AwgWTuxtrp0GUixwCyY25qWbsX96frQNGaf3mtxYO6tp+yc3+QfY7N+/bPkD9uz6NYzU1p8WDKCf+/sh0ocLV8DuFgKFD4DND+9SrEoLlnepe0czIkw+o66Vo2FW07NQVtCNymiqOKIzdinH9pXt5MXKRo5aW00U+AH9HeeIrYDKEQU4pGlxPlZOeQ1DD12cuwf1ljN6Dm8A9E+NB/FhQfjXL1J2viBml8WSsBztzgItWn+kTM4sxfrLCsqLf5HkJgd80RQDZiAMzuzqFeS1455962laT9B2JucUjFK3y6InJNn2dTZBItq2mA3M+ZXKh6QNPR/yxb1mSClI+BaW1y3hDZUc8eMRISJs0i0JiiNIreAd3dmQvfi2puDnCbD7cSHBMBxWjLliItHNuvF9MwAO992e/Kcz6X8Et+FB/5xMRwyYyzfXRm9f3Y/SIWw7CBsMIBIY6YZGySbwH/ciXDFnjD
    username: AgBWnOFMKK2bpFIs40LM20fu4EtlfYPbPA6d2BTmCHOTuPGciGHthxgeV7qtkUZBM44XUNOuowJuO7a/RjgGPo6LyyR5BJSQ9j+wqXYbChvG9x2wT4y4jdLmjdZpnopIRILbk5rd+Raxd1PeX+OwMC0ou0QsQ+6v3OH1LSgntAQ3moU/CgPXyT85hYx4hABkegI6oLJS7F3TXnRy30xlfQ3oMaXNLo6KYgaQT3gxLzg5Mo3CqB5aPfhpFopDbYKEwihsRwAa3+d8aMP1ZXR/oHnYAFiprMgGzUIIu1YRQdF4F9NLlD5ClJAQqw/DAHM4LCuqVOtPypWLebUAU/BIO/sSZio8Nhwg9yPVeJa+k4tbk4dihC/V5T3nvfLviSXWDZ1cVBcUK3lQ/Zm/e5liwc4Z0IJufokwjDZyhxxA/gtlgW0aQA9+vWUKTd49MQ8T8xyYnuH8g+UoxtrLN2m077xRsdGZGq4NcBgQ6QQhmUrp77XSjhDrGafrTIxV0RqNKOKf4RstaoIyoiGir83L7Pj4l2rezQz4wk6cmf8FdvfjK60pKInNlpsZkvOm3N65832xGm6Sd219jxXtfsHNw+GgyKg2E7hep1tRXx8QDCVGC6/ZOgUhnCn8xNEyzEdgRw89G/zSQPpHdVzzvpPZmYm4OR27imRZ4nC5TFL1I1Iwm0lAtdQoj66eOPZDwYvq5v4TRQ7//Hs=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
