apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgA1n/9hBlUJMRLsr3QFUsY/pRYjkzdgWxn4+tKEnK2T3/XXd+4BIj11shgQEJ8T3Mf/f4R8JsJhNiHnfoOGEX8J63Ik0fwFdJFdCLBHxRAGGIzUdGSRbkkAf2XJGeWzcOVBy9IWLEhX0kKQzHP7VdUgdtYtBI7AlQetXiBcujN5iIgaXPDCF4E1PG8gvE4Sbt3jCTZhllnPrzMsv/og0zT4UDtrXgY4tJD0sUtjYJDUmhmqwK/xFtx2bZdXxxspjHuZPTtrOFcN7q3yDObZ2/oCZPjxzt94MNJsB9Mvpjcd0XzyZQZfh7bqzbrnoANQim07+Sj5t1xNdDfnMOxzibRu/rvaKMapV22TJjTVlwJbNfzk7oNj+HqmEdfL4r6vQsk2iNi/mBbz/GUdYJftmHpsY0gSzr5kFTXR4v7UiDtAWWFWvK6Ynsvw+QBXIoWKitYIaeNL5IZySLsZNVhrLUX4yB/jzDxf/nCMHAbRQVKoI0ocAha9WHTnksC8A+kjYOS8oCp+4KPNpNcqNbayM09SpD5+xMv1Iy1dQlhMt4alh6z6YuWLhx6yP0K2x4toKfVf1RQTdPpQIOCUIp/YNBaHBfAB6/T/X/+8inK+PD3ZkaKua1wGqK3xR3HmHZPA2T6M2uU9rvuu1TFeboPou2lmrQDGPm8hIf51IJdovK7UmjL3jVl7CAIb65LTz9ul1ymsLF8f82NAwCWoP1zYJVSnhgJiUQ2+19wKdEQK/wJPB5kzgRKYfiiu
    username: AgBnCmm5F1vrfcc+6h34h82VwmgikHi9YTrGVGCgGmAGO3+Fh93J7KakLe+Xw2Av+55ao9Fol0jRjfjjtwy4GcswrnK28m+NjGOwuEg52CEIABanVt2nEuEiprVHUoz8p8TX4Z0gtVVl3S1K4ca85A7n80fffBZ7tAFLejMgV9B6t3nGTjvIFPC4qCiXIYeLMTkBRScCQ4zQx7xbpH1vXKNmNrEBli0fQ6XQBxCgBcXgvMVgbn0iyyFHr9D2nOo0nAzojgzKoKKOkv9uSx/BwgjEt7E3Fg5yZKvnpwZ8f7E7uGyA/L0SipukeFpsJF6SRMi5RRTdsrxXlfs1S6ONzlR7UWsLDLzheG3qJo349/qT0eJQO91+nIROdX48qmxg08TBdQGxgqfCogbBnT4/5S7OvqcerazHYa9hdrV8HXQAKuOh9rtAzlOOV5JYcuS6hjNZxPLwDK0K1j3YwoH0huo+FHVGYJKg+PIwBtbKQeubmXyfNbSrsu6oKPzZD4uXlkteZ6olYJSSBB5sXZISfNikmairbwNx3x+vyHVijN/Wy/tCUhQCSVI4LzfxtDObta1O04xb3Jldk5r4aIzwVpsVytFexpzMDsGZ9Q26UVOK6CUKkV+SwsehefythQ7hdzZgHag/dPrLhteX3PZE06rzh1T9C0iWhD4LvDYFkTtL6bqrapHejP6NUbHQDhrjlhh7of2DvXg=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
