apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAyMFoEP193cUqmCzJ678CZ8cmu0iIHYTU41Izejmrv2oRwaskCLAnrsOHWsMfDs+xZmwDkDTs75tIINcbRCxTOyReMwD5wDkCz2U7N5LJv3BFd/No6HpNeUMdQdFwjFLPUrbqdtfjs2w8p+7Fia7aHjaC+NOzZnSB4lsBGVGZ7i3dVEFaAy3ixp9rhdAvgBNECm4MNs2BrbGvhinBpKOEg431nfgZ9/n4LLFgqE6L1P2wH/QlYHNby+idc2RiuOOo0aVFmSZVpLUMG4lJKohUbxzKXeRWGrwxQDFo+j6ctCtwmCZN1Aa8iPrEQU/BPCYMj3aO/HyIlL467nGfwe5bNmUFnPsHstdwYeKWuPEq9fydPwW0sTLkv+E81RgNq3SjoNMPignmR1QWgDG0X7et7s92g0RHcs7wvZiLX/fcd00k6Cd+C60O/jIWyAPLHs+5VORd9fJyssKHQwgbE+5E5DY+zpaYNnTunPiewB3WlDe3Gg+JBara9g12YKw+zI6GsuszXMOWMarF6ENsisESJOEVUMyRUkRpY711nrik9P14plnY+FcPnpqE+hzYrWXTMh3LihLq6TbbOUPnf0T2eLiPp6ArPk7hZKyCl2UNmIvOrKPtGtKwjFMny2C6hJZRNYOjjx7ECYHnaSUJgyVdVBDAQLKQUorOlo7DG4wW7kn9X6EnvIPU4n89kE/UmXjDsu1ThTLf6CafSCxxXyfM+qG0SEImQIo036zuAGLM2pAvTepwqQ1In
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
