apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgAw4CwKulAHRPe/tGncAXeY3xOQm/yBTZxwSKSLKvSxjygCMjX/eNoWFn6IMlc4TpsjHsdV9BUuBpfeYgiu7o/GyYb1DLgWMGmpFPEAUhB1Gtysz4DSEDzq3fQ8YnOpUY430qdKnGWMQFMvDs5ey8D8l77CMZGPWLXhG2QzE93tS39sj1FqbzMX2u1oUT0MUMpwJleO/cPZ+bwBb2e53ZfaLogn5CNMyM9ht7xwVypyECbiNKEEnIrLkVVdzcwUXcJxMMqw4Ck5aWi6awdXHWuQzRmz+U09BZG3qSChXosD0KOxuhpUoUUxPL7DNIcCFynBt4z2CQqj1SplClHo+qn6tz1Vfagobz+p00smC2ijjAHX2rUgp9uNdwyD8dGlRGrPV3WzHXHzCl0UgGAkvq9hwO7D4dth2Js30HZoWfw33w1FHSjLEw2EfjDkLFlJY1afpSb20UrRK87jTfhWHm6tgo61QuhqWaYtsfk5T5p/OaQlYNqBTKvThnOT3WrcrGX11ldlOMMeueGsaBrkLJv5haHAVOamqDhb/Ct1psMLxeJWJEVnLXlF7WJMpeDAV+613AoKLG7iTCbEnE6/0wW1fU8nKfTyhnRCm75koUXnJL59lilazV49VhUyZTINvdWsaiH7qgCLztnSlYdxSZGFxWnqeSXIj8enj1ADhaR17dYGe4OL7LrBul7cm7uzx8JHtMGszRsFrfPqoqvXx7uHtIeXRwxOk5lY4xIgPu4vrE1ALvlutjZw
    username: AgC3vD5/ZUaz7oKd7sSuwR9FTmw/NhIVuHGsSN+fhSB7F6OwZTMbrwoGLywlTLAqq2XWxjXCzPfiETbQt4Y+t7uoXv6nYzhPN3B8w9gpV/7o37gfiQ4vA1Mm2xb5GvL4NSojJXr3QUaC3tMu2DD0Wib3NwJUNhQMJYocieUlLw5hnNqXPrxBZlz5Ag6SqurLXHAQW/NofbSaKMCFCiHVxzNTCACFxTPQQi9EKn3D6ZOKkF8VpCBMmRKFP3ub/eKDN6+SmhjI1ReuWp4nkwyg1EmDLyLDdHWkp6jgkwQAhd/xI0V8IYzGRbvflwrAauMQbJCEoBLwYUTsN0sQRqV+BzmTyQZYdyKes88C3hPBMmBgyojWaHIOiC2BlXzGzLdD+dWJ3WT+eH/ZTfdh0QexcWHAqQEDYUUeuD8G4qnvF9PBZu9riU/zvlDUaPC1s2dgDqGV39enO+l5FMxqMWhm93S7i37HyQ6TXE/4rM9OaYR+II1V5CVaI54K1FFu8Dhme2hMLdtyyrFCjz3LLeZNnFTe2t7inJaaJBxYwFtWHw94PQnhp9bFIaneg8dx/ZVrQyZvbabSrB54amCgHjM1weZ/yg3yrrZA5XozBfmwXGn0rbdgokoNbg2A4TGlRML82vMK+Tm/RrI5owkhsUrk/5NhOkgXajHcLqOpwuh2+3ngYiWWlY8Z63XtxpZQtG02K2rw+4gxh9I=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
