apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgCKtPC2Uwhx/x0Q0ou76a8iHdyNSGIwWJbN2sZcT59zODk1XJO/3H+7vmvVXwPO5cBppuoxZgqF/uwPSlPzeqDuZpxGrIGr+6yvKMrwKbgliBEHvCbO40mP0ePcNZrramJ7Ih1L+ipaqwIuKME/5ZR/wlH9umJCQ5ul4bwR0sWQYBqGWKPgoP1TgA+N3nIhQbOwAY8kltNcMJmtv9r55XaU2U4q5Ege5RkYpyUN5ji7ra6UdYJCOzrUB7LLFP5eMAeiQO1rXQc/bhQ7oPDjLbLFvKg7vweuAtEq9Z5q5oZlT/yrHlW7dbM10MawZqa/kIWxCwVlHwh+Kq/TPnRZUymlWJpzWlPKglo6UZtRmYTbKvZCB4xTzhGevpLHsdAmPx4IeDLKiGdcwa/qUyH07cEoJoVLih69x49r9BMJDgoGl/UCUBHDmMU+geuLcYITc6wioG839CQ20HErrv2J7QOJYEBJGBIBtQbb5cbTafnMZZUiv/JfgchuAcUW4YkVX3W1Fmh6Pq0JdgekW1eLStuWygLmdkILrLSkUpw+IgonosEAZh7eBdxn8hSvIkxKsnAoyhEWVTxAAsju0t4u62jFd0pJPNXF/i1X+8H0ZHYBC4om5+9/umhhyHeFnoMC+iPnjbWmVG/3OAzZu7SNyl/uXwg4V+zkl14emyNexoyqhP3KM/LfZTgz3fzqaobemd0pFosy4ClmpOQhuStmVxwt9UDjZ8NHCTy96/FnU7PAPaNOwlvDi+RI
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
