apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBusygwm8mz+TUY0QadvfE+G3Rl9sOVcMnc2jm2eX1E9kpPzrHoGe0Jq1nC6NvVu5pboNU8ruJGQOfHnDAVt4zy6KuPnz+lzlYk09ZVVTXvi47KckXMXKy+5AsT9ivsUdI5aRU7aTA5ak05YzsPCv5UhICD0Mp57sYKWo3OP5MgbiH14SK9q+fqY5OOA033TjfdejDSxoQCrqv1idYPfbkjjoARxbPnVJBJRECYfgglyDm9KT40JAKMnk3TR0XICefC32fshB74TsP02UcnOicVPs4OhhIKxZdmaWSgyGHBVXKXRpe1ZmrNQFdOM2W9LHcM9CFLyxr523PtKpBIdT29/TfSuWxUVz7bcEnW3ncvI/JuAdBA+yahbgpJzYA/+jwG3S6cqB5qVwAwMn44pYI57aWKBASyj+lyPs5mEIRd9qnLZDpiDDVh7jouynRt0M0OO9U4VD8qmHqo1yF8vw5oEOEGNMbK8fW8o4exeZAW3aIIFXG+z59VGZin2Em8JnY3db8U0aRIj5rleLz2EX/FxnL2xeYOqNptzAClXFNWYG07aUlM971oRC8qnZK8B1mChwLHwQP/rB8Q1MOA56wm0y6B+omUWL50Shken8raruEWCHEEOl03m5NsupKp5X7EekIFhnTY4rvOgSgRNoo4fzJ0E843b8cOn+z/Ub6SqkIMnfXozYgjDm9nh6g91JxGqnZEFgWUd61bS0DlRFZYwn0kHA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
