apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAig0R5bnm/LI1NfdW45R41WWH1mNrMAVsMUq88oyl5JcBpCE75bjBxghIbgIgPXE3pyJmonjC10nMaX4eRnGtvjp9yQ6iO5YAVRxlhcPE8dhUG5EBW1XR306jQ/jy2GGD4H3UyMtL/Ka8TZfLuM64sj71q8dxR7+7oAoX1tEygbi7Ophz/Mxt8j8VG6s89bRi0TjJ4tsx/UiC5rijio/evV5OLy8OzeCslhvSmLRjBmtL2jBZnZw8FJ4gtzrWYS3JAdVFSG2ngD3yUFLiIhFIH9OtQjlvKlvgHdW39PWy80TB3Eaq+1AUaTzGbeav9jzW1gcw+bIr7sKSnoZ/PJoJwlEfsKAj31noytm2lVHWsTJIdZLbHlm3LWv6dX39Vu+9TZhB0/bvWvJtWRmL/AXnFDESgHH8CuIEzdx4azB9OQ4bsTMR0Qe7+xdTwMyGG1oKL8JoURCgWkTvlmeKYXs0ObrQCIWWeeZeGfHmw4M/R5TbIuTJVqWde6364n2AzW3392SZgPDl31RrF/+7LXQ2FhPiFhH88Ynlrb9sp5IIEsjQy+T/UZW2ITNgC4bNJ8UaqBFN8C1d276PFLFiIT9D+/F6plLc9GvmbJOYy07LD4B/8YJ6hPxXwZBTuXVyiPErOaKirIyE9S2D8RqvkOgiLH7AZ5N8jHIAh3pkGA3YPnS1qy/1eHjE3qkrANBtJWzgzIM7M0vjwr6XNABGonfhyEir2Mg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
