apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCeP6PYZePWzj2Vgk1LBBK/IDAIGwswyeaA8DcKe3OJogJyQ1IOA9haz3nivFIPEP+2ZdUjHaKyplIVVDGzNJd2iL3L/L+4XNe+etW/C6dG78VCvC2D3Nnb0obwbioHZFJ/aHwys3s3NxYxMtMM6g1Ps5S/7AkXe7cFRQMLVDN9reyeKmzY6AHPD40h7Oyzmyn9yWbFO7GJGnqZ+4O5yVn/wKe514c3VNulmM/VgnQVdAku9sjiJzqqIbP8ruFU/4AZCMFxMioPfV2FzdNjSTqRnOcAsAvEcZI1jgF2Xz+ZDgs6iXfcCy78Uj/iHEK7MbH6aRpA6MQj7ioVBnXtnYxniyY/3Xs8C4ZOGoJS8o//bVJn8U+ZlHcDPPy7O1cgBbHa1rmr6r4w+QleIA069xdIgbHhBmK5FEJWnjM+mCAhtMaQ2iaENOQiraNrM+KSFGSkQP6SJ+32wXwcUhQN26PfGUn6UaRX5OhYwJb4rupFaX9eOrPOtx61/eMOijmPxTgU7ET9VN5JGgH/ImxdZHcGRJoOA913TKPzHqOLi9HXDUUg+B/1zKBdx6EEzQiC3qGC2joS3g9FxVtEB8oqSt7797RS0mAHFGc0bsBZZrgptMXPP8U7B4rWYRMFPdYD1ljb7aT4WIyg4dfwN90zAnfohIZh2sK1kylbQsvjReBXdQRGlt4VIjgTcLa4Jfg/evkJ/xc=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
