apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBsBLT4RzGXB/3KLsb6Mehdun88hiAkuH+VdjLFqre7D5C18BrGE80maFlpA0JBQ9UfpHDA8dOT1+wS3Q3VfjYjQBDCY3qeeBsP432LgeVtsnR831uGEW9Bkk5rPosrXDmqdwv99N6evFZ81/XzFUbET8RoyiTh9U0glfq0SBdHFI/StomZgC4XrFcN84xT2fAJX4ZEL0TzHOq9mJWwemquqSfkkS5gYrp3I2m/iXVfv8tb9qphCUMXgvY+evXWL8h57oO+HU7qB7bRtfLVqy2aNakbFGmZacMkeeCj4kM4B6iwf8wCd4NwMyxICSbKE/xOZawyii+S9TFkEMqy3jd3QfOiVzKvEtkomexVBZDonvdrbkRt7zEo+xlaIWVOM8eNkTURT39+0VZ+F7QfNMS0+FepnxuBi9oPQAV/1lBr7cGsfqk6sa3qLkjX3nO6/bMSlq5Ds66eSoXm2zici2ECWPKRqzfYbu1fx912Ms2QFRBgWKTlsv4Im+o3+C3F9FAoFtaDWQJ3j/pKh/+4Tp4GclXwHWhh8W8JOya4HcvN5taH/mRjYbDZpMmmkMynL9gIoN2jszYrjLYFxm0dWQZYdDZt+AZ4FJ6zmXcoDvqtqPwA1iukXViWug3MMpg+G3gqPeJroLnTsUden5kKkuoffxIgZeCLsbddgOYdldcwPQDB0A86YpJgrQxNU3gNUAnhjT0=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
