apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgARg0hgWHY1aTG3bubZ77iPuIjdTO7Jkj6aMz3yUX25zun8JaWu5fA7f1qKMQWjqP94hzko+RuV5sVXCbMYECsMp5KMxnbyqUV97mLUE7iPkX6BkzLjsI+DTS06RPNA8TVMBEvv6NhcMLrG/PTb5egloBn1Mz4Ioat3J/8OcWgQusl+K6qnWSKeuIcwNzKAbZruEdNBzYbvvyc6o1kAIoMq8bb1vjKgcUpZcL0E+fH6UMLT+tC27leEIhAPjNeEqmWToUF9E+32fqr0P0dOykYReaRXkNdcy7RFNYS84qPuPZRkGSQ8TDy7UU4kyNIX53V/M1NjYQr8x0g2lQwIMuhje4XqnSxmeqW7it89McXcWF/ECsrD1DLEy4DTmZltR2nFLygADvY5zt2jWKmqaH6qeNVcb5CgVRiHfy0Hle3EamTX/jljsknG4uzsuipP6uv5dhaRtz79feG8fA+3N2fBqM+m2YyIkeN58Y1HIMxwaJE5dL6EeYNgBeW6bO/PcU0JBHe1nYPV+J/NyaGcQgmn+WzpZyaTCX9l3jwVk4q5Eav6VBCc67AcZQTLaJDcc6y1c7FBHJ4pT1OXskX4w8xFDSp3cUPDgcHL3iGfcyNIoNa+gHzo/cnXkF0Pi46UEjcn+BiE+BsDH6ogJmfG+iifRtZwUNouVNqM/migqZIgcuaACyrDTFM0V4FVz29NMpGTdXlVmwzVjhx9YmOHTRFd6O9/AA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
