apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAg3CFv0k+rQTEoOCsrCQe6M6YPrh04ybuWULrCOH0z3kDZHXJyZMXqEBm8TRgzLiZiSdSEidf9K4nzdjm3GbTUBgkIGyuwG+JdVGhniK1K7TBCNOfATcK3iYPRTWP16vPE0sbGNL/s2k40ONZMHOyQNfizzNKE3eTTsr7YyhrrcqlW+Yz9fFQJYL2e09plaPgyoXkPl544XVjJpwviNUIk9lIjZ7lab7CQAt7rEV31CDvIXdVjfwzkjH8DYhvh+E68tFdhUo1MQdmzK6nwUodmp/BC3aO3alcyLvWk1fKkLIiNJZQ0DCNl4bDDHLj9KycDVLyPHvNH5pF/vj8TkdImWTvW5M9mgadlSdhFVJL0G7LlE/ED+J60ZzUrIkNE4P3hs1sjKNbidaFqMuQISe+6ppxPRABdgwS/MAvFwX5eE8Rfu/G4rinrtSgXfp+sX58i9HyyDY+w4FiLx+JoOfC6/K5+WKfn8WY673i5dr3FRXRbmKqo2BjJe3YyVMWRxcNRj/HaLPMeWo+rllA7427qM+r+mZMzWHzTR5DciD77ElYmxAMjAmQpOt/llAGLNg0nJSkuwoniRV3quLfZHQfLaXRF2POiUu1aLwNvbInN3182mxOLf92cO6k6nE05uvV3xyMWieBKSHuYffPQ+fDq4pE5OoyH7i9ACvLy9iTUWVTRRM3KD4NGYn6e9AWYkl3GRqk=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
