apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBYrhJtP1FcLy37f4uZ8mTiazn6xhU9XbMREE7HHmQUz2ruDGgHyAslUKMuc3u+LWucIaCWybMjkKjtCXMc199h3Im7kyg4Tu/cldW50zCgbsVj8iyN2FQmMG43lbCAS8NZgDPU8D7ySPaFXGbvKLfGYP3jJtBW5FO+vlks2o8LV3aTjeBLWofPyWVf1dzyHN0PPCQUx/4y12sQDEH3ghHDmWx/vedy9OwfeTLLogNTgWm1Jwv3nLlg2JrpmvyHTukKLdV5QCHbuV+z9Eb40OZz82esMJRVhQJnDclJxONDt/KpSfw8PLcLjyWnWe6ULVV6XMmy9cNKug7wF+CZNhvmxaU4Ffz8GccrIMzqysgPWiJdkuX1M8FKTVrpxNuKZ6Uxjwmc0eIJ/ptUAG8t6JAdL73GUm5oOWVg/kccl7UCEcjxEgX1zY3B6qTWxWIQFqtb4qSzwnG8iJsFivGgBl7P7AVHsMtcCrgkaYJ8TQj6G4Ucc3kt2s6QcuoU0FAQYNpsYmwjpMpADFwJbAjUwdbANZ2fZFzDgtwEmTRmGAHuKw/0W5oBcDDSSAIW6eYCrwch5ms1Mkdiczx3pzW6EYf9/GsrBLt+ucU6T8ZhqQ4axqBE+UW9mL/Iy8WuWuS1bhqYCI1X9HikHJBFvsjNo+fc/OVDn7zz/I8H2Gzmk8d3THdeucus7wlBlmlr7K2W9WVJInLXJdEBu66FgRDRvxl/N5ziog==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
