apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDI/fn7wuGfm0yy439KVGDJ8veTnUVoBnGTmqphvz1E+OHiXWqPXoP1xbfZeMM6RkIdgKqJcyz24JcvtVwE0+EkKIjxHiAFaDEtBhvJbn6+hmAdVwgXpGrCbV7RKpaUCas+rE2GWzNrdfStXCtr763qP4XTfwzhtAuDlMnOTcCCx7BziJip6lxb72jW0xvU9AvRiOeHreXnGuhokUenoRM0O6VNIqjKMRcGuCq1e/KkJ4I9hlJU8qB6G2oHgCozV30NV24pW3c4fkN3fcK4FWNYCuVbfQYOddh+5oFJNnU8SG7gM5PWQ/03ZnM2o1AHlQyOpWBxR0YMAv0SJJ5iZGTQQ8wlsHeMrZRzAdZfUUbbOpBStFyx69AdSi4zWCxhFLKE6Tmt4sKhD/I1qsTR9MiECLQWzV5tJhi2A+XUE2AbAH0sjFvTCkUndzwpaTjHUWaekUNYLdZoOT5wvaoSYfLO7DomMvYxclbHT5uQJNjl8GkGay7Wh6Tt4i2OrmUcLJWTvWBw8hbEXjdYmqCQ5uCopDHptdLN+shIsFoDnKOMRYBC+5r8oBbCEprtWdKeyXVE+eJSeoXn0AJzp1xdF08GjwQRS0GMXeeVUid08JNIfHTXSa12cPUcGr+Tib+hnoXR1wTbuIzi9jHrHwXeMFKo3tdsAaQYE+qNhx9lKN9j/fsik16PRb1GzR4KViTHHx2ydcBPzL3UhC3HOJ1Q0N2rw+ZRMw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
