apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBfllSCzd3/Aw8GOl4OuUa3G2GammSHweaS5F6Kc7URZuNM7VKvqKGA1Y+mJQqb5v1/ZaERjaAHJBEn+66T/+8U/1DPabdLO80gPmwzj7g8/FJf3Mghp4UVRafayk2/AlhSsNcU9SAF0bE2FB7/0rI12sHbYZVJ8BZa7oyLJKtwTB8gw467/xRNfWY+EglpqkEZv0jk23SOG1T+3LcXg7ZP2Y8T6OnSyjynaFHLfda1UDktuXDG22MA4Bs5c8QTkKQP/IyqAAQ7GeYnh+kYnbnCKt59QKfS+RVgNqA2YVSKvelfu9xO6yL2pAT8WTMP5cF4X6RGfOHiGuZVNpDt2eURQdsRX0zQOdUUbt5FTk8ha4VoXjF7JQCWj3SEH4RQ696K5j473mzvIeAw71pc8McrGBTP12OInQ9LfPZupvoBMZiywqN8BYCtH4QZchkQCQMY5EVOpmHn5Q0i5WOdarPKO7zLW755YZPCYMpAnzeWi5Kk4pb1dZ0zsjfbxn6neM1WHYyHf5I9hS9ZbQEG6YagEcqaYXVRlq+cAe7tfpox6WK+p3ScmwiYdA94lZVugznS4GfSY4VBEPL5lfU55uZan5gRHz0VQuoSWBB/4jpeTXEhuhbLtncUGRJ+e6O4hknIUDr1WdB5bDEIC7lsdvetmz+QOEO8Ne/xvEBB3SujeC6WEVjMNZI7WEl+eXs2BH24NtnOSIkm44C8EG2ktC0552UqxA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
