apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB8WIqedjs/hKOkYw8GEzcgCCMJLR9eC8i8eWbZyOxDf8nwXhlSRnkuOacM7/8/Qw+++AzdJV6rGPbnEhvgI6YhSvnx57fY2KA9Wl3J9IkV/El4CYOm+6oXN+rRA5YPGE5fu0Ul/OQi90dB1WxDh84UmDfmVXkqGOwKFxzW0zxMIalEzYa0g3wyhidk2Li+8gpC9YdZVXSygsArsMroNesvNitMDs4q9Qvn5O7kCADC96iHNf/ZAu3FezmOENkdqXJ0IiOaQ1m5juvLFO/Cqq44sc126ufKLqialCxEShgv5r/FjJ6NHef+k2zHpljsfNkSAmwFs6lX88LctnOPyj+U5Q1Y53NSpS+/JbTlcYlSFPQhLpY+1jGdFZsaCZLwYspChQLorcgACe8KNcW9Ku5R0bikbQpuYCuj6CTChJksQqFbadxkAlouypKZ7R9WB4jmqnmDiCnJG0DLWzDVjHbsiuh0stXhg6ThVvopmrR5e701+4bKPEyy0n2JK51H7CTflHUar9l4g1FSrRkWTJXTeP3ZpOAH8UhGjpbaJH1iR1JNRp9iDbrN4aRsoqZixhSzWeBmEAj29csoU2ow3hW42T/nih1E6rkgZHqX1P10BCmoN2hPCImP10jA3jhQKaO3iodCi3hWekT92JP5zjx5CQPPue2GDRhZwdcb8eONTBzJ/ZhyvUHLpXgkIX8Ke58MBzo0rdEZB5tZcMvNDZa6zDRCSw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
