apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCNB/0hDBVAXIFC5YM5RQT4eCeaLoxjfBzn4bAFmSC0loYHSEJgDEKxC7dT4O1nsE25jUDWgx0MdplZ7LdHeGgjAQKzUV5eUFO8ve8++APzuQStkQZXBOOueWA8dYHgZJMWx2syuPlO0+6gXoNIBMpi3dvIIVW9FSKy0ZQ6wBMU8PVpdddNGbBujHdEzDP3kIRASa63un3HqtJXVLDuZ/uNdSrk6Kehwhv4qn+jsi/r9UzuRT23qxnNuNrp6kKGIuUoC+EQ42nm+b/q2BZOzaexijyVnhljcBk3TqrgzKKhxiXHuLUSzH2WO+S/l1YiS4+6eCv/aHJBTHx1Dp0fIrBRnz5Sz7690IxWEphDbMNDRt2s157aTGwbwxIma+zajPz/Rb2vqvrxQVqqywUGvrPqaOCf4bq5mbXwu4EDaPLJAg/FI9+0nYk1NMsRUfkGXcZ5dxz8sJrkpe8Pu6kWQju+wI00ZGGEFfNf96ftJwbqsHK7MQFfdN057wgloseEvOw3pIIF4E8aaHykCSH4uMphtWODpLHQ9BBfaW/LWg3U8igyJPwAWXeVfkuJH6ggTMiwhrE/bLDhQMGcuw5OqHeWYmqjK+4fwjcmoIvjBay5ba4XxLaDlKpKCfomqDxjysBfAkksEa0USO2s4oZuCcdEK+dub3LwvxTC/O4674KdxshWROcJku8klEvwbLFcnLNxIbiYtpJs0nkx1n2m6lFNmKs9rg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
