apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC7eof1rRAHchQgR1jKLpGptE6aBsuneDjFCpRTib8fSfAjWBuZV4UX2TsaLGrgA2mneOqFEvO6VWpVB08VaVVh1OaxiFoVEg5GIFA3qkLXo5lZdVldbl+VLLz6GB3/54cePA0bq73TN6piA2GadIbw0Kxt4g9ujQ89TbpBMOtq7oaziXij8LSt1g4XW4RYbnHgEVMQ8/zrnksSo2UGk0c1or4fCK34kGo/xfPPVXKuDkVxedQS9mtC7xLLRu63YQ4jYbEoIMr0uGU88DwYg4D+qxRcmnXrzFL5/oUR/Ppx/sgWR4dWktIkN+S0E1Hgg5IHquHZ1rA0G2u43vXZlc9YD2nzcxc4Kk/cx1YEUJsz/9GgrcmtnBbWhYzmoRCVqtsFTDyy4xMb8RxE3y+QJIxz5rh6mnZBtVhskt8QPBiPRcPfolqsmNTLqz2kP1VYT0PSFQD576Z5Ax0wdH3vP1CX7dyj2saReCpAtCT/wM3+CW4m+BgQ51Iwbz86Mv3Y+AVKZJTkLVVek5bEpQPfeEI6v7BAV+1TU54iTVKWulc/MTy9BkC2DPs4e2zBVdYVfb2taSbG5T7GkniNeqkPAX7CjXYlEYXd7Ob/lKn1E/3ebIAV6HYTj+9he/zcR0cHbKeICA0XP4mvoW1QgNiY19MubdHmQrA603SjDZhI6+0KDRnyzkVLqbn81Ov/+B3owv+nIQA=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
