apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCS7JuWt/e5V54eQnmwSd9J7XxXYApqfh+xaghsZAod+LFCHFV3zmBGuvG2mOCiji65X1ozCH9/1h/87yjemjo0iJsmOijSF1+YI+qTyeHb93z/y174IBfruPvOEoZarFV0tSzQeOByo9qjuTDkES1abgkec7UBkMov8jEV+XwX+QCPyfeo1oT65HnFfN+uOH8SGbE1SeHiyLALEhzDwl06Zqi7P2hkR/xCQstwwsPANt6dhavqNatARtItrowiWTSbh+jbIpNufRj7yl5R88yeJFenIt0xLjDKI4d/f3kaQKenP+a5fsECeE/dnBbd4eDthYT0MY/V3jMSFC3fzfy8k3nrCOqDdr7I6NQTa7Ijn496iHT4I6xqTuGWH8kXZ3QqZrUTWtSxVQiy6bCNylZj6ZnNbWIeSyTgs8LNoPKStmBaylfc9ZmaVUbVr7unj4eAJJMSz6aXzYb+xEa0FocQUPhaNEBOJvWRhWDsA4V0De3moT4BJvagk4xnc6pmHH3qfQLE4BHx6oVnOn/O3XYvaEcf0TvGz5i9I1us/f76ixyMBC9CRYQ0Df0wbMwBUG1VlIpOSvhRCZpiVnBe/9PM3n+arD6elEy+pDDlgQWRZmI6tNZ1zP6lrRsEknj6zCj4fva0XfYnqs17Bpx79AIkXoeBkPi52B08ur5JvYXinTcQZb1HnDSIcHvLxbIbzakgbgNjx1YFjVGGB7cem2LsLX58tA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
