apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB0/foF4xY/iWtzCAsRmRuJn6ywbbhbcE4JMXD7KxkYzH2WgsH4CgKDikNZszyXy0fP7M4AwWIqdlFzthLdTITsmMvyCQtsfw3UuhTOafzFKLgNZ9GIGkrbIuFC2W21IkjSyqB9aR7O5nQhsWXi7/23CWqwvzFMA5Ph0LkFQDi0C9OUyEMRR+ukvOdTHB5lvbMCKKMn+KU5bQcSYYYNuzOOqGxFMBGEpEhGEz2IFjidKnSV/Cskdk8daci6NL8Sv3tmLDYic2rosPCB1yHP5tw/Nfc4qTsMlCGeB8XtNQOqXI3JcycUShHMKD9EeAJkb3txjcDAgoydaSwI/d0y90vLaOb9IToZ0tMcoX/7qYn2koWg5Yygr/vZNo9Auc1OGYuZoJsyuuPoCkM2ODMxTVi3u5RVt7OvL9NR3GQhMY+0NFZRxnb5H08OD5MEcMLAAW9VxS8/Iy5KOX5FYnpjDNWFz6IVbQGAOAj+0oE0t8npkoxnf6Kw5+ZecwbHFBQCJUVS7F5OobBGBcNEAnb7VARTzRtqFS2V55E04Ih8xOlfJnjlt+0Q7ZnQrc8LG7liQTro0lgSN48/up0AOEp/mTeIeU80Ohg4MOMTajBlGWwGIDtGLkZkLB/YCZcnpUDNaW/JIQPs+yOJs9v+Kfm07eQ+6a9svNr42IgOPGOMucMkD2VJE+Dl/nKpIzRD+n/BLu9V1fg=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
