apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA44cBeSvOdT3oqL2syvDN6AGgskn6co0nm8Fx3L159o3wv82I7KSgBzPFBHOhSDpqlb2USnHV83jvx47LCXdWjAmNn+t59Kt5bMPQunzeviALoMiVKc7H4U9Vwryo0ILvJ2tWINxTUR2sBnPw98uK/BeKz4eGkxJ6Gg0KoTovszBPSvtlvPZHj8ugiAZiyYebejMK7UI5oOFbJeiQYL9X4QD0u7fynrzhfgTaTwiZy2Sri6VbWyQsSMc7JRcVj6uYlEAUlxwwfkyP4WPBxLAMe7KuIFi/sQPmUUrUK15niyano5RU9H0xqQhNdl2hNaNcdwhh9BerUGUha4HXl/D7bdjN5mTvGSyiEY1gnhH+zDirdgsZtfcZNCAGKjUsn/6D3u0oa1mMJ4LjKZ4oCU383t3zHW6pqNQDCpszsg37XwDeujseU6ddMLDdWg7Hg4Da2XCf5ZqTZdFHMCQmjPOyf230p03Vbt26HVEhNZqD68vh+0rnDd2HuY2x+QfY1pLwsDiOgzM5HXgJ7jvWIiyPKObnprT00ChSNMamnbS9nDoBaZtXCtifZ7sS81No+kZ5tdmn1GZS5kuVRo4dUAITekHOS57zHAyfhn4XQW0XTEiTya4t/bbS9aZSA5k3WzB7emSpBVYmBCYZuHdhxaNLAcvhbzkgRn/MjE3T85rMR9EHJU3AnhbevVdlrKGqqRFVxCt7/rleYWECVzx2u778ffrXMzQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
