apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA0ppd7PLT/2w1BUY53gzDkpKO0B/j4Vzn3rmr65Wu8Li1mVVjRZ7hcexqhYlR+KULNl0eU9QpXiVPChf2zL0cl7FniaSeZWia4QExAdFWXmy3T/6CBnPM9jXSWlphxZldmtmhhUko23ZI4Gy8hfNGgkYGmRQqdrk/RrKEHzIKaMgcZhuinSh+DBz0zYedHT5pNJcD/kKCnwjPYGTj/SBh02LwGtXW68i5A58K9qXEftkeULO1kpHKRNP19lm44NRHOr2yaZC97r/FEoVrFiqgvruUeK2mR3CF3bFBDPvDZpZBpcoFfniY/M9XQNcHSwkdqR4yhPdPb+w+8I9YnrJdmAVjp5DCcNZq9dhCrT/HZsfE0OoT3IFWW41rTvcTyPY92193WhQLdN8hM5XlmB5WmbkaR5CrRVjfo4NYgZYA1nIgqT+yvdB9LGAuGmqLjlrNynRJNXb9W1LZatYhDi9C69EqyKi4+RokLsZSnTisDnvBrMcwnI5ZVr5odhcG9qoW1iPsLk0CX/q5+4XjMI3lMq8i54nTaCqRmqwhjuOk7E/tubdzVGgBfYMiljh3BY5QN2Msh3Ur7PqE4HXmLNCv30/k9bc3WTNiwPI6eZC9j3wZHkckpXwWN7wKR3WoGDuY4f48t8h97/piGai63GXI2tuCk4IoSLFmaGQCVc3HGdk8C33Ypynl7hYTtGg/I5txwOD4=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
