apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB5PKNqmbvVQAJqIjGOybVGBdXCoCFdp4boVAhj0+3h8/Ea63PLvZHZlC12i2ItzuSQNLCwRpgtyuRfaNCea3PYAqgS+9T5ZBMZJnz9aaPZqRcSfLudJtXgVRGl11nbTOIS2RWL75tVI49lhO9HnzE13e3Eg0GzrFH2J5yKUsDa7Dr1rSNO8Pi75hmHSb2ctgIDej3HFn7WvWGFBTTRFkwnexXYQlyayIuFHgvL2ZEDZq7M4sHI57varQfqyZxxymRNWX6mYd/A1rLnuISXqOwXK5YwcIeOQ5k7vYxyiqXwUthqGV+mW06RWiUt4/BKvG1QWD3baCb1/jSAc10gtdh0FU/AaEjGXZip9F/ArY+/lmQovM9W+u0pJOMDJfTN3fFcZAalRDjG0DhhicWAMgkH030ZRx1JQpgBTME24QiNV6KO7j8AqnzEybYr8Af5CHaiMu1w9G48uY1PfgEbfs2VrF16BRe6LK8+KDl2hbZLyReaQ476QfBJ78PAOkkO80dg0q4Cuguka4JKmol3lvTigqqCZVyC+nZ/ZQtTQ946cffKLjmn8/FMNTv2o+0W8Vxc6SOfYw1zh3lQ2ME6VxWsl68AMSbV6IiYIkMJAULgat+ckLwQdC9KsqAeB2PGCxKiBGyLYctLi5/bY0FO3+1aEf4z+1xcpNsFO556QZ6X8QhADVUGLLOPl98yOykJRrh/JLU=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
