apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBv3PUHNNCLdbPVIBP9e4E/qhoDG5K/kC0MuUf6AlH63QxQt1ScUNpfo82tfrPHUwqzXtVSivvLZX4Mu+n5cYyJXnYEgaLTzkc+jrqymHVadq90sNGi0XC9OZvh3smUpCv4Vl6bXEBgmLWxB/w8764XorU/t2aKDq77/aipKO+ZBFX73hMP9jRXWygmpPSGf9OTd/3syTcIpnRLdazP1IgIEt5ooifP771GwqsEaD5Noi6OCvvt4GFOqEgEz6G8+DrvLbsjKW924NmnIDP2WfXcrzIXSTmutRvIlthwTOgTMpX9ldM6tNkevJdtnWaGmd2jJMMv89AcMzFpghrutAawEFWYo3CQfk3mUAA0MRiA+OXehwTGhBVuM2IKaUzlx9SXSkgnDKARpraLBBW0eCfRgcTqNLBVAUzhd60TgokUx2PDr2Yi3Ngp+8jMAvVlCt8JlxbnVUKECq7OOrT2CASJbD9cIEnvNSsz7ixSOFT2LzdWQC6ULYL02rPH4muLQvW6rNw3i3IA2f/ghHKVjvUiDxu6k/OfMIwN8yuHN4vcnP25ecaG7LEvo1S1j8wSLP5/P75QaGVmtSYMmYbZZEZ82lF+4Rz37zIBYU0W5ynl9nd/aTOWuKIRRai47eo4CvvXTqyAUftX9BmNw623A6/gBhK9p6rP68xq5yeC6JR++fO1GYfCoI0N43rUmx38icSfPns=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
