apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAeiMH6i5ITIdlwdw7EhJ7Asq21rNqQXeWNn3/QaA9wZkD+mQcdmSOldvjp1UbEfeX6AlsYLT0LVPH9ZPt7XcvHKlKqruo+QTKNFMwpSUIhS+jfzBs3TQ4eXTLXxFpG/Vp5Ic12MOGNyb1UABYX0DEcGIJGm175wUbLbFZppJO9wSVudEakflPjN+gj+koRNCXEAK448bZ7b47OJVk3hei4VsQv5nyh3OEmbXpRW7QCWuQbjLDck5I16m0fxDe7HDHIY+YPJ4TMaHGxOrMX/xjBDURQilAtK8ylqu8/kQcwocPBkiPTK9bINaLR6dCEPUT/bWucp60WlLB0PnaSWksPiIuQvZ1UUVODD5WR1h6asVFcNZrTLIgjVvIsdtHfvu9Qkyl1SFWHs2NQeILTxeAFN/NGiXucQQOUaOpBdh6kbklOW7vTyV0OCKiQ3ZI2U8M/mgGXsrrAO293yfflves4bssL+53JaA7aMq1fwEa5DGYo3E/Y/PFzg32V9V3/jO6m6mdbdP9tRGah19VwX6wYZLKEmsEwOtUb9nq+spLNHRQjO5GAfcR3PViDgEMCbz8KPYTlVmhybKROVJ8DxchyxiMuiYGsThZAXtsR+F/H1OLUpKOyDTY4oQqCD58JpMAp7ebdscB+9wS8V/idKLyH7XuYop0Rm/OrAOMla/fCN1nyfuVowCYIb8fmnkzRaWSMbMPYZi9LsSQK5eu0X64QOs/V/Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
