apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAWCRdOtzrYnAbVE2E+/vWFSwpb9XJ6wtp8vZCegxe4qy0XriS3GSQy182I0fvhVbeffE/yskEnJn1WbMG74Hlyh5O6cwAiKYny2tfHw9VHw5iwwUFPuWGYnJJsdYySh0FiD903SI4JrnMVd8GDm9VwFZlyYt4x93L2M/hL7fvBA5X3KKkcZ5kn8t/ZD6urK+X4dPrf33jEgZyGwyCfj+g4+UQqDv3LWm4MIEzzrv5RQTOKC8olySKPsmY+im1na3zQ7m68HoK/k1uKkMk4qE/Hi8JmpOzldP4w2cJHPrtbDYS4mzS1tWlQ2HYg2QcWFTWlGUDxkMGXpUuYsUoZTWAWA+Qf0XF+zqBUFkMO/SzIhXr8/7NP5kUUou0LtxYJ7E+4yotmSQ30liAc9/PciDZN2h1jBSdYbhd1cWs+RPRoxQqFNbC8CopCZs8gQIyBl5A58qWrHiuxKKqEdOVI9jyLY7sAei/h45c3RYG/EvCyA7BbdyKfVtvQrS5r6JKLWYX/5c1zBbJOLGy+Th7to+89JC1lXXHd2nwQjeMuUPClHFqY6niVrnTze+WXUJw15KxRRmT6/JNdZZmhkKENbnNh2MCHHPUA2WV3pY7CViQJBWXQZd7uyQB63II3yEEukqNPykj70A4R3+vjxi7ooKQ3iJIOgAYn+mG22Kj443EZWvJLA2GO6OwazAOGdiSnjAQcxcJh4btacANOY0K34by7lteW6w==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
