apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA4ZWIwVKQntFTSAk8DtknSesrdxvL3gbFG7+Js/kzb/aW+GmBADDzeKBXWHIw7j46aJo6DV83od388BdPCU129QeoCLGZAO+92dhNtKM0pMje8Rczx+Y0S8jG6kG5kgLOIlmuBiG0YkkchCUv+YUcRWEUa8fuc2EROJpM2VPRs//ecwL5UU60ZURJG/ValZ4hVv+qcnRK29idVYD7uUewGCfViLhI3+q32/16E7UqnIoAPhB/oNf6wq5rpbDTbMXSsy1KTfVNxnAtoJr6mcan3Ug9/joLTQFrvWQcsgSUBPp+8LpF+3ULZa60UgOI952gDtV0q8/MvRjw7M8H6ErzkVrxLP+iXf9cH2jtlp2uXIg2mTEkcKwSnytQPldEsolFMZKqwWXf0feqxKk1mtgs1lo1gMZgq9PtEdP7BsmRl/1sG+0fwpjDOPejpxezYj6uxS011acqVFVlgNg1Oaor8SqGaEJ1lm6/2SV7F93chd6ZVZpABWzkeJWm1uRPnfU6tsxsTbJ2ELcp4YZ8aF8Op+wSPaSr2r7CNq+K9ZPSbJB7TMP/RxPfS3Mpfmla6k1Xc7X390OTL7SE7nBTojKUWrQj/jVX3gchIMrqdRUwQD9kt0tzBxU5paecEiA+rBxITPjf0cnKwEu7DbKd1zGoKZ1Z7ViOa/TSk8x5AKdodaQhAiwlS2k4lpcHlFwW+PfrfP/4=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
