apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA0iPcLgXFqFq6E49rwwdJKFifzJbRJ91mDmLWXM9ZpdCnq+8E93voZXTnubUIplcCwuCL9DxvM+Q+IkVPWdD2dgBEU1Wgdh/XEULp5KkbJdiLYxI5iOJLIUGXJCH9AeXimxvtUxo2NH61DsZoR99eG4c75tVy4hkuIbVD4mOA9bMHB184AX1bWGkpy5t03NOQcGBEB8+xHgrVbgUNoF6DHXUTP7cAtkJOJ81plrABUF3X1Hwdi8ZC4/e/gCi8OlhVSGaweQJrMeelTWEGxOlhQ/P539kFPwDQ9kEk21KstV7/4EeW32LVd/M9F5sROXoE3U7F7T1OA0XAieNdIxnHsHh/iQcRlclAS9a/nzY9bTirZuvs2pty+5x05mSKDgVCOeM0X/uxV+oJ8FqKiatnchHjN573tccqkdRdt6A2oZLzWG6xjDWG+UnvecIsobj3Emuqk34Y/DRC/FJJx35XAW2hb6Kh5qpKHSem/KjKlH6cOCK7erc9Ky05Ue5vQ7hwmfpgFhMWnY2mxGhw7Hx2z72wez10VVc3QwRJO151z5Pikt6aPF+1pT0mDLUQyvlFeVLeJLssGQ+UqP9iPc7N0YIx4E8gCY/dOlTGKaGzcwL5WHeWJsGPj9E1h7GM2F/21tCL+UZGrJEVJqOJDL0YYFTY3k6ZDHOZuD2rpB74e6oPDqPBlNjRAre6IvQ48rN9IunbxnP9vUCb+wNFXh9D9hxTsBQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
