apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgArk8mUIAmUjHn6q1f3A1kK9/pHn7HPzRhemfxcZevseJKR9WPe3MNliFQ6IptXOwHB/z5tLVviuFqohT2Lj7MSXDhPLEhVloY5z3tUd4qoP/dxcTiqvODGKNuyOf2AuPAuCxiAOWEk1g8kFPB6eEHUr2J1aWHFEojslI2l+KNMY2LizLoK1X9nwa7OLXnMXgKoNqG4Tgr9CdcyILnuz92Nds5d58caJ8LLPhOzXKgbg6RAQ5MH/1HP0+MT66BgCr1JEe2Si++dGhfTdoCA7E0L5HTEWP+r0HghumzjdvlWGbT4pDzSxQ2r5LjllnCYVhIVG+RBiWNZ9JJpDvHEN6Ho8cQQOL16fGM0icsaZuRE1//YaNBhfBQZMJcALLrh7mLi+317yIjNN/2SwWE1H2cRLDdH12Zin5odFQhuLKJIe4BhHO+hwPYcT4TomvXmHQwvRyVa4BRrFxXQoYfLnYLqkhZNMAu9wGoDPDUWtCJt3/BxA/0hzPit+1wecN8JW2b8fVKdy60GSEVHAZdREZotSRZcPFQsOd1VjL0TVFYEU3OgjU9ht9KN3JVygz4LBZyOckX+HrYhkCEHKvnsLDcEf+DHfauzxWD8e74ohXHOwkWphhVLWXbU6cvOdAWDt9QdsSBPVAGsPZtnLfDDbvMo0YfeyjiY2qfQNDoWQMIvXxsCH6R7xxT8+koUSZeFbUyEbteTXQxXIKz2t1HmI26XMtixxQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
