apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBbglxg1N26rgD7tCBNccm6vHndy6UNFmk1IJh5zXmBBq2eAgvPYzlFbOblwvjkQGUUw2KE4tuagMSAbKO32wOURWd4m9nXs88Z8PCE4fB5nkIo6muO3+JDm53jbBbxjXcvFF22ibW6HM7rVvygqiL6G1R7CsOA8q3UYyhfJ3tkK+RRKTPPjtPj6zcV3xaGRMZ4Qea9EtIzwhPh9gDtF6qyCHkjZSwy0k7XNojgVVLdiSOyEz+6SoOIfQ1YSTELL0BioTYRnDFLpke1bOygB0tctAEReHrg+dHpGnMsBm/QxSA+slxgeZJiN3x5uCrKl+ZRbRnhbIG2sYTSAKcdhAA/L0YMwltObjSw83f6tGsiTP8wXFiTTnhBOZdaCWjwp+X4JniRdCJZj0x76GkEsjP2+qBYcFCMRq3vdSGfnoSTgf8/mJf0Y+uUe1UFvAsiuadtQF5ZNp560X0+lIttVeZwB091SoAgkSfW/xAScuiWNjfNR8f56W0lxii6f1as4PFTS1WUHe6VzE9SHHSUmuNfiPd1q6k/zTcbtZlA5agF5+K5Qjo3Fs5Dc8F+ekpOHpUdXDfg0psepqWBsEMWtWZ8poFRSaBZYvQjLyMHk4HZQSAIZWIsu+xGdPfJ5dqKL1zszjn12dfe5Fme+01Ob+C/zHVZDOIk5XgGeh+PJtp4UZFjs2YspxFHbQsA3CF9t24QsQo=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
