apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBqvMhn4rCGq9LhgTgmJGxceG68lGEITTdBdKMgdAj088leK56uq7T+eB0CNR4f1QclwIf5W92fdukor5mzYyMAe7j4sSAt7sIjZt1lM+tVVj2mRaMWY/N2Z3sApsFI3wndIJY/SrUhdWaXs9DEMmmqcEmH0/Sz+x9eHgGmBaxnXpj5iAnEoolZ5gOaCBL6gEtDJbkhICGObWX1XyVTOEl78MaYB2bFXJ6K0Mp1CB4Aix6ulyXrL4dSrg/AsA/EpeVe0l6cfW8hx6dGhOP67av4oAmbu6YMevjPsu1eXk6EH/InGZ8y1YErrBnUnHhdwMI6pfpV0WgHtNxaHQtLsFAss6DxPtRuOJa/USiH6msvQbkBBgzVVO8qzStgIfqaeBot1AH9wB2qNGVJHIU/E8DTxavyqmzk/OxW9cobGJYl/K4IlFwFNUkn2MxugXxFL7kT+oSBxw39X7XR7m7IhfvS9c6SbXw/I1AquYyijOmMLRWaMmkvWNDXvJ1jgUKdJJZcAOX2opqKNWXdji7pIhvBsVyi0hGW42WyP9vivf51vXUepzV/piNwMtOxvUesE8dZrFNfbU4yXpZEJ/e+M09GmBIxkGwnvUPb/l05niPx7blmsj88y/l2PzFKuWU95Dz08nyAX8vR2oxDZoPPFxAu1x5vWiEUMBrb/HCyo73Zqhcxq5NWg2ivvEOKSnwN02ezNmZmrIhD4Nn6Xybj1nuksI0NiQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
