apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCs3pPtpUXqSqwh7G58aYoK+YR8d61C7NWECKyCL4+Kqp46pw6Guq7AD0tucNxhVuuCOPs8YGnjXNTw2fZB7d8npbT4wqfeYt0C0nDYIITIF6O5tUERLWAqt/zDeStpIop97AxJTmdPtmY0STtdK1BBFPVyVbSL4lizknd1jVSOwemJkFzE21BOfwhP5AzDAfDZrZosmt4f9I1d3R1b721YllhbgTf5rpRqOjCU5BIczNaqujCYD0A7Bl0pxil1ZGGFy2hIl1O8UfasCZQ0pTnv9vY646BWj0QMv+Agnt7baj3677JaJyD3qOEM3rW2eAOZkP0L1zsHH6QrzgRr6OW5uNcQZEJDrUcRZEcOscqYabhusQNXUQRZ6mkBaq1WGpaIe3Wnu5EwdAABIVDFuS4U7P/VHLIwmLUEKJb405sbgnl1iB0vOYY/eDFsZ8+9XE6OiMzgl6DF0gIyue97I/cHqUIOYbUWxgVHK2JEeHDb+dAHGFk8qIyKo93+KeANJ5XEgW0InytEj1QhxJLI1RhXPHhsg3eWeXbRIF9bFJpmzbcK21f5qJpeXfo5Cu9ty/lRvUpPeM0u5JMegYlKj1aqQSFcP9RYSDLrMXwy3xEO1uEBqyPGSfCJrQd3SIDkA/E3UIklvCEpRXMEfm6KofV/CQIc+IT5bCSd356R+6X4LZIpu8bBuqmVa58WbqU+M2qNk2A=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
