apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCFmIKXgXz5s/zoY6OpNhftyGHlzZX+9OB5wMEw6dHLMID843Jg0XtwrMkEU8s6M0ZJX8H6MSDjz5U6k4itHGIN4rQoGnR5n2PM5uL5t9oWMisWE7taaUw0MBbDtnQc8tYMa9wkvu+j/5eXxYoQGxRxqi63/0m4DKhecAOYhO1HkMhMX+0sZk95J58vNs9iVLzppY3Febt1tk+q6inA+EWOO90uoF9JUxaXt/DWsaUjmt5lHtE7LVfE1SvJ+cMHOB3iwnleTBmKe3B/hcKOpuMfExodW0AemJYy+TtTd+m87nvXpy0920Ts0uAY0xwb+9b59eUg+fklpsTQXB0qidS1iqjGhBdKz/gwLCPgK353IZPjuCYJOjkqpk0xj/+RX2n6D3R4JWyqZ0zolaKdyk3tr+9qLcfXMnOfQwgovOPqwMm7E5dzSqCxzfY8KmRVC8vi7nVOu0TnjZdKCyU7uQNcJqG/fjTQtQSgJewlhAPhe78NwSkyV8WIHChvbp4ki0OcVLcIJgQzapUcdGer5x3e3ICQcdvH1Dzqi9OR2IbBQGbJJRu/2w5vmSskbCVFPbmcZjUcSfHtXasZWzCIsBa1lcWpr7puRXRgg26bMdhNnGe3usAaFmtSF4jTZjuEgzEfzkWUGwX0FhYhIs1Ra9NgJGed5zIkoUPTin8cL8bPE61Jdz4+hEMHJAKmxujA7tdc1lH923lNqsZ9yPiu+UBrwQCniw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
