apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBbEypRaCJVB2pjnkHHHu589k7wvT0+jgr+j/gQ6CldeTUPKprQKZkpEg0k19P7sfP2L2svfxgyTmonAjCvg1dESmP2yTOWqyDML5GFmh0zwm8/F37XSx3lyVUeQnu6qgO6dL8Lwi2oSWEbTMwv0BXLYdc7AXzws/p635W8rDnE01/2eZjzKYRQAHT8/144yM0TrhwM3j76BdKazlCXExXxA1gjk187v3xzHciIY3RvBKKwPQ0kGTKEGAyo5kLdsl21RI0Lb6IPWi+xtKWdDCamEjmovsi1AwOvwvYHGmYT842+p6WD12IdzXAz4FBsavSFaQwdn6UoUFYsK8MZkGFd+lMIT2ILkpmpkn/kp3jcuwoh+KXSOrPAB11fSzs+F0eVk551FrvjjNv9htrJ0QKnlLE6W/nrd7ks25ezTTA8qsLT3KvpqcBXwSbQW2jNNpbvzbTL39gOrPno+jQ77jvSCNK+3f2dIn3nvCVS2zk/Cf9fLMgJAvTK8YRHYcsjfoRduyNjLqsz9FJtwfNB3/ypy0i+mHZTu2dM5S1pBTRsw3FPhFCWATsrbrdeJDfFCsAavdWIJimG1+87wW9Z58Dmjju7aM09zyHGSMu7XRKI8T5fkKR3p01ITf/cylikxoHhjuY+MpyveTmVGEyIPUs/HMTnm7vctlufu8Tjo9fOJlxTA+TCpxLhcrvSnrs1f0rmnmQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
