apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCeSdtVF/TuHtantShJWYSyWueJPiSC8fKMCP6VgTLCrXcFU6Ra1unLRb2KoTrOwkWvwn5K14RTdEfmRF6npu7gCoMQUFlnWmP+P+00lYilNuKXJGNSR35ecpLOeUCsLnNenIl2ck4x0f6Tn7grz5YLg8jlPrIc0pqXRTlShIZmYELkIM/Ngw8IQHIfNjE37CvFxUeeRfAHD2Iv65viLa/0JyoVWX0rZKjhbpHWuRMeAN9YqNdW0waze0z9UJV2NeSqCoa0A2dFt02Dc174bNOS2qlJfQ0N9PyijEWPwTEI3OTfPd4rTMQecPb0hG/1XWrdXZ6e34i5eEib3I1kgrFtwK31Sr4RDWgS6AvysWzwafrlxFVBh3+tdyve1/aMwYNQ8AXg1RMrMz28RNq0n+AwRxMokK4dfORu+2xwDRrmpvTT3R0VgPIrnWpDyvWk3OOkaD/E6k4JQUVsDBxEOhXtv/4jjk8/npX3bBwWoOAYtGwSpSd23jzkW0fUv6tj6V0roay/HdLksof2nfYCwfXPlW/u1N01YKxCdv2gp6IXMG5PF4dP7h/e2jX0Y/0Sy+x16/aFY96EEZEfg4c+NnRkKpBDnC1fkyj4wivpilsMhdFdlGrdW2gCFmBNvsQrPJG7MveQPVbBv3mG42Rg123I9uBaQiu5jbJZcE8B03PofOfc6X5SCrqO62QhGpzU3wFl3Rcjjp8R8CIXjgpAb4ZRHIoTqg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
