apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAafmxBHMhO83cO4gnbgQIguRXjE4yDS4sgXYSzt4I57GqxDvaEWJERdjBdtEYZU30U6RKjByaDgJu7CDieog/BmaZxQRRO8C+nIxr1EUAn7qVcbusfPi+yvlWUr9yXGcAWmhymzinjPCiTKeYnwhBeU6/skVkEgiRNp7YBDD0LXGsSd/5P1LWt3HN58gxUTEGAkhH0E96zpf+4B4d3aXcmoEm81yLViypjipWGIhFRDxXquDgAKEOabvXi/UlJshILeut4srbM62QwwC7cyS9WnVfmlkneQnyl6xfpejcwwT4el3RYYJsWr4+Y6ZUGnJRdJhcRYmOJYl3vytjrxqZKDYQjOgXD5Z7NNyZO/9r+RYFYVreK2P0OSXTRCiypMDVAIhALkZWEouzUo2dupYf1iiuX8FOA3r0X00rxdvSX7Dof0fGRMNpMn33gJaJ/BhFp2uetPvdkGB4DmdJDu+DNmAnmgOzVe/Km/toOPu732aLtUwQtTD0eQS8ecMPUgRa4+2sHsq/y2XqhFSREDvGIFjwMK6kXUIQKb8zCbUdm+6I3CP+p9f+ly+AXG+heX4fW9FTN8bW3pYUD00M7hxJUHJbI0YUU91acWdUE3WYDLBQ/77BsgP7eUlNm+CjQtz6YEORtLt1Vu6slvd9h0pdjO405D3pFvvNksHWbqVz10aB9aZYMqNg0dftB5KIGfrMdkhk=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
