apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCHlqf8StYRcWDW/P9TUlUdj8rTpAUAtlmZsnPqzAkSaKKpwa8BUqX/db196RizwFeUvH8JI0t6G+0d7e+B54PrNsNhc5dyhtDncelAb9yPDjbS8YxKCnWoJ1sAG/bCDkvi89kwudjWEedPjc5HRYUbSO6L7VhBR6vcxvNITvpul4YZ2lVa9Tq9CKCuZVkufIlrwKkiqaA7exM3Sh6K3iXVG3TSyIn2u0oaOZEjPmgdGoyFTPq6z0QF4vHyLwRMo75KIyMWFESpZe1HS2vdQ63cfueyE5y9Ezg0084zB6bpgi9tv663lvS4fdr/ND76lY8fue12SnPfmVEi33si5jg4/QLnEjUFvvUSj4Mf27g1ZryjKHS8XjPT3Ld8Uy6+xYUbiRB3vAlobCZWh7tNGBQm3NYXjaKfnHqmfAGfHYnPdzV7jwGF/2CqstrVFlsIlFGRfmj5tOSjSDBSuQr/acPGCIogFbqWqv9P2NCQMGQX+lmiUSdIlbM4rhBzrMIINt8mQ6y7NEEr50h8s7Q4awdHlaH3cWOgowlHvblEXoNPUFKQ8pNtjcDXOw6aEnBuW/rY9MDKUwJbIntoWr7TS3P5aoZMix0F7R7dNJ8Wat6RBKqy9TSSYBWTPgqkrzmdAaAxjKMOzcDrcJ8GSRmDS/HqgwPSRP7HPKZXBd8jAAVWGLuFxUQf5SOW4bNSvimKGkUV2qzWkPjDbB9erhyQS2pej/OGjQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
