apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCMlnmZ/uy9I2KJbnDwiqGgdEvyBnnVb+Wrw6VKvp+ugN1g/7Ynt+cGQ4sqiaSLIWc0GLuXCq1ehvPN4/7It4IBaWRbvl+ZdJt7Cxba3ifhdKQCRIdtQ7G4tCZryJDvI7cpmuh7IsWfMOHIlpABCwKDvzQVdwDNeds7TfBI8lmi/cN22gmllMp0JyxpNDenKuHseY4MV6SSnz4zU2S7zdL3EgK29NHRf+Cz7/XTOW7isC7zklt9LtIZD+Nv1oaYJugQZHxgm5iUq7qG14JU3JoA5u7L4oxGL3gkU7JGG+ieIluol6Qhsc7wWscV6c2h3+UmJtnNHipd/rAk04ZrFh9JvYErKBmoOmwScJyzNT146tkqpOGBlwHiUlfnhnF9ehcvHGK6THMARLgR6xv8wtd9YAZQDMn4VCWSjOOSeKdxIcITgBRCuITGWcDi2dX/aho7kzPhU2oRumFEcDXOMBfJ9Db5R/m475030UrPQ3Bgu8jIj3HUKUt6d/0Qzr5zWoXEQ8Dj1Xhl00bdw9Y/53ewIU9CQ9PW/o1gJeuq3byDjM59W1FePeO0PaqHCqSPSqMik6TNqIBnOceFUkNH2Z2QQH5zVtDyKmSj7lXQDXSpfVqGlnVdzCdZjMH38I1xbaNDB1g6Q5jaWkMdN/gJMuzS7418FLwjvXcLr0TZ6PsdT0o6nsauuGTzD2Su8vXoki2uft9ELuJyo56jhYITwJ/BW74W7g==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
