apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAn2GVQjhPq9gR+m/KekdvxySvuZ9wq+s9Bj1x0FfQDJYZXDYiYAta+5KtOqVbL9XB0UJvWaTwYL6+2pcnu/57n8dd3xaWwfcKWH9gR80EmtAFViIyZKd72LLIveqllaXRv3oLgPQjItErLQwPmAX1bVWRPava4xBQTT4ou4rdIsBa4i3MVg61CUkdIMSheW99H8+/CMHWczn2wnjyXGa+iw/CewEuuBi6JAa3ZkE6XE1muVnoGn7h1mWktWv709qXDSAQ4gGgh3/95Sej0IVuW16mtW4Jw09n9DevHd88oj0YK0ooDvCbct2AFeUkK7uuex5iUz5bkbqgDIpbXZULt6lIJEj9goeIJZ+a4XIPjBdYYLoNL/Tq7oCq7tw8Sto6esnd+mJ+bpNvR6OUS7Sh3BsEI2FwvrZ7RRrThc1afYuOP1XOHxUkaJDqH7rKQGUOEDnvthdE0lvyKtLZzn/RisBE2x3vO08vM13HGn+++fcp2TRcutiSqyPANMSMicel47Zz2HOP8aihSXoO6fcDvN74x9RXXQD1inKXpF6ROhZGw4bXMCUwrZl+Z4YA9g/rQztQteIFHqZ9nHo4vyD/8JkK+bgt3M5tovWDoxOvyTZmktPI2JQdGJym9CdRUijf/ovMSBIlsTr8qKyBLXg4QFvJS5sOuO2tz9Oqd6gTIoZDrBEEX7x18o0sBj1RkOJe36D/S9pZ3AHMYHkehgBrJ3I3L0g==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
