apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC9bd5AZIgD6Agk3CZTQu+0JOynH2ukl8zCgVHYqessN0pGJY/L6/emCjTLRA/4Y0jPwuNK610WiQNEQkYK31qF1BAWb/Rz3vSI+zBYbT5YVQavVQECMiaCl6uOCwmp19O1p00EPrpXpAiTYoGJ1BRRqwt0Se7kTCKoimxX1l8KjX1pQzhr/5Rd9buTFDlPAKOkDchzhCvPIXy6c3cBy4SJA4uxZUznig4It5inINeJmoFFx4cow/Vg1vIJSjsrzRnRBgnX4WxYB1CkhaLHu2atpWMSlX/GvntjC4b7u75ErLCcUk/kd7mWWeDj4QnC8BP9yuog/Dr29qmB7SUUJVPAMEL56/reoPSezbnf+EQh2DPfM8b5kcK6XjKd19HzVoW1RP4eYX6zl6PJPeuNrWJQhJxShYSQUJvY/Qx3NTD+csQYSvLmCgZZ4jGeHlRfpLwGakgV0GQWl24Xe+oz/QUdZoae2sDS7dzEwv9PTfafalhZ4EYVoWTxtjxN0G8XdtipYeMPeUCRZIfEi4ybDWjYqdhP5nNc20ZS/fDR8R7syShUdd5QLfbGd0IYnOChbht+xq+vIazyjSDXt7RZFo1wSdqg/Zq0WFXNeLuJb0f4qDIAC87/qvFwfJs5RQBBEys/7IzxCtvXm6q0NtVLthzpWuAjIHUlQUUqAXKOtDsLHsQhrYJAySRNQ8TorQkpMpRaOlI=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
