apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBPsvpEJ4zjio+xBP0s8BrPtz46newx/Lk5SLkKfYun5yF8mD6CSt4sBku+HH02tFUjfYCB2qHG5u/Mq4nMK9Jpa9k7N/HLrGm8sx5dIKx4kzUWBYsv4zbBpYK3KIgTclTGgV/szDes4/UVJvbYdDn0hIoELlDXUe2Ef2l7mujbiiNKC9fnhQ85Mix9PMWm6WRsDxqSOkeZFkfHZBIYdr+Vm1qARcyBay/FTEdsuzSZawW2fsR2K9fOwpLH6z67drCoZ6kKYqz/Cn0DaIIgKSF2T1+DBnH4b2YiHGqXTcI/AwkcbUtpcrYMUT8crRtnc06hCNXOxH5sdz6m/CxS76Kumm2dNaMFR8TvuKy3No40gHqO2iZUwvTNHhX6lf9EN40R7Gp+B5Wt2+A8t4Lu+1tmLZPdYvchajGkBZZnk3ZYRxpVi9jj95PcWKSauXDxtBQECGZg/SK2vFlvtsrw/8cv47wB0hK/zEFO12at9MaNlq886nqKxPA7W5CTv6ZI6L7EQdFH0tUe8fbJRgs1AmP2h91Aeqm9P1Y4iZJjXr+Iy8kzGBzAKomijswQ5qhuGoV8SEHgoYn7JJRYhopdzRpq4yZxeZrND3e/06VtDq9TGnnObiaGv3aykMjhRAuM3QlHc+uCe/R4SZVB1kfZJjUgDWbbooqZ8Y+V8/0EEcta2ja8lGUOz+DFuUvlWwaVjZ3ki5Q=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
