apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCa4pf3JEZvmfflQEX8nGLaf1KwT4+8V20EehU/kVenqXR/rMtqTMz2nzH5aQtGHlCOsUQ/pSntY/qBn1wMhnFgMUY/E/bXKdoWcEhnPl+QmstyQGtJ2HRH5yBdbWcYa0roVfsAfJhLmTw/x/NK7ABzCPs9PIVCOE9XPFvGHXt8Bcl3nScxVSC1IXXVCaDU4gdr/H8p48tYF6O1z0ELl5OROMXww6cZKMhsAOmgbenZIK7kbPy4dnQRQVi/ukufbZyg6A5g5NikiaD6PID3bJ8SGE29EEHV5cv4ngAcLlGlaPLxdSkujL665j9EE34uqKi8Vv2tcbke0OmN9O+gK55EU0DX+kwXnxfGtkX7i6trBRTWQFqJ8Z58OQkwQhLOKs/9eoqTB3Cd2ZWnNK+Uw3c5MIl95lJxtdhTsoOazQdSauk10rdcPffXZDSlRcihyxzoGVBBhdaoLXnLvjlDajdsMOgBf6zclaqIDnuVFqziv4dNKotUau24gXJd3laOtcto/WGAElHmzAYGkc1SJTUCTHbf6Y/L4LyIS7eJzaw3zOu+c1q6ET60Dm+4DUmFmKAWx8tcfx1Oz3M1Mi2npykGtrEP+T3Jq5jbaofwpqXwD7Iv7ymKnd0TI7afkFbHjjUgjv5KkN4aZnCeC6DCbYVxMdYV66V33NrFTiK5DMvgXEIMHlXjr7NInnl6r6vLDp08nzHyJnamEL7wbDNCZR748AZkTQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
