apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDBTtL6RS9XqyTtZS0ma+3mcKCnK8InsUzt2myo5w4r4id453rODiJ3HlJNiLi3xyROW8GhvsVER4eQHhNitZB4MrqP7EFibSpDpe3xX+zb13YWnl0cyBwCJ3y1IMF61fKC9xsiIZYG/D/nXPtWB7hQl0NNvgGeCOHkyqNnG8ZmlACUMSxM6P6je+5FuEHkpNYnHL7VxkMFGIGO/jC4KJ6WvhlPqNzUq0s1ssg5eDGyXZ+ZKD/IGScQvdxzGOnL1+XNllQiU8tUfLxljaxO/IILfCrRdXQxPZo7uyHPNWoPcxVCD+bwmcJk5Rs7Kvycc1mz96R7HultIMqSEzwTuJUNy03Xw5B7UGPPlE9vHzao1mKZwc4hnMx0Mfby5Rz3NjhJuWzBytYiuVx2s4q9qkK0/PK/CxtoeHX2nTEe0sF0EM3x/INQLz06m0+tYj9sNMKjF2JS1y/ZWSe6rx/50Mh5ncwFfMb7efa3t9PuopVI6oLAW5+HJz2qLcwt3CL++ZUcuBht44Atkih2196w0oSAgIZbQzK6PiazjADTsIpayjDoEXl9m2hap5MZnLCEVwyTwmbNL0UOsqxg1KtjRneFsD+L9/srovGxoIs04WujSjP0vNfkOJLrCRPk2BCOsSXfeLjbs2aNPmSYuICqMTvJYpTlLTuCHW4aycq6JLmA805Yhlzoonf9esmPAAVjQGUVOjs=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
