apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBtQF1gXJVeJvXbfqDTxtC2BlnsFZORkKhkQpqBEOdyNcLiPL30K56jLSGGCGhQLSj+VBlJPRb/kNEI/6A2DcS85X81pkDpGQUwG0mx1yh4cKL0+RQlpeuSGozMkEPx7nNRhcWCFxvWQa5R914n1J7caGlDGk/IaxsjR8b9kzIPW9rxNXGXmR1Mm7DT0F3+LJ6tYi4YBodGxR5nSabq+D0CqIDqrWl7JR9By9ZaVKrxllvQWb6uQAM62NgOImoRyvEm+yIZDXOWdEfMeqcy+Q+xzVrhIFTIF4UbohZ+XrzYWsJEKzJJPBiWbVPJHTFD46HxL6RTnc+GYo263hOmwHtkA3H2ka3BjJQ795KYbMYH2xPhDfH2sDycMGwx+V81rGEsN1ZDOTJzNftlpKXKrQtRc7xAX/RWA4wLOWoe6AkQBTxA+qCW+jIJ87tnq6ha36PhqezAftnKA8Ni0P7QKpdFheMHzXQPOVI9kpO+G3+HRo/o0gaGd7oXkOWhbgpydxqaEodrKIU7/2wZQ3jHN6SGAFBq38itNxnjJ5bxC2Of/3flkG0p48BMseyrqAGfaRvkZ+j2YrbvjjQQLmo1l4KjTlABuDtN6hxx1JuKLFnSNCm0bqcoaJj/dWUsFQV9ov2THVFY4oDq2xjBHKLPowRfjJsfHSRjE1y8BiQ+CEmYwcs1MU+SRo+/fa7i2/2iIElt9SQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
