apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCtqQUy+c9cRfao7v6eKS9HuROzKHaSd2N2Kua9sran2xGOK8Ca2Sl71IeLTg18RGaeQdyuR9XwHBow17j9Vc3cQUshJ/T5jfTmtlx+NApbmKz9yqDm4GAJXibIngkMwH+yTUpLdIdF/Nwd7E5xwixu3oY/59yScp7hcrhz8TItRK0X+m1nPDqoHS8kJJ2SwSEmI2Qz7WiROSAB0Rqw2kac3YqinmkF+F4siy1RhmfGVj+LkXELpXizy5tYLnaMX0B0XbDiVXql8eldk8K24xkADhiQ6GSJrHTCfYW5NURC0yfe1YDpH40OZi4nxCZFEAUHl35Fk8nDztZJdimAfJu0XX+bAkHBsg8diKtLx7whlp+lBS5CrL8RiaMUjgb+skT1ARHZG7g2z4cAs8xWvZeX7IW/zJRFsSlD1GL/oTQ7Eh8ehGnyOP7nRhA6wMuChtOdf0hlFF1vhMTuifbjhvMJjg6dTz5wkkTyrW/bYHWo/3jN/0cvFUMTBShPCJVYN/NolwoUvmiIsucgQEcRaAi5yFjophvwQozJP3jE+KYIGpo39c9WWhGcTPwQ6XndqtoumLG8PyW4viUgvwLKz5NqRIp/YRxN4LbagOCZAmf+buccB8jz49WVlqHk0DVm3m+us5vOaEvzwfSejf9/bYgoo3Qvpqh7uGA4Ey98YbVIL8UkMU4pxiR6I6WDobh3US7ZQyw=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
