apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC5jGURHERueMM3LYIo1EKCcmP5Pme8txw/2WvzwN9DnAAuZfg7+yN10N1jNHCEtivxcfFuBAtNYo2xMXTdUWfmy1jAwlMeP5UP1pFLqMoiKDDmYVMR6LyOlfzbj5dnRqJEWS1WSCo0vWM2ZZ0SUK37Aogf+yd3kdyfJ37Yw2ewdy8PpHE8yDdouBaWdcfW3F8xxqtmYP2Jg9WVSFFiIRdedpGSGXOrhQjyGFgf5rmKWV1xFsYQTwbtE3yFYNp02lu4En8hkJIbJXu2lnpVTDv2kJ3Nr4WNxLfuXG7iDxUyFOEt/P5MiEys1x9dXi9Ie8XfTrudYi/xEN66/Mo+NQlFfXjxoJlLX8FJaAD0YEW58fMGpAJS1CMF0zSeSsR/xDs5aIm6urIDm1itAAdtuXjZwFBdxxenmL7JqmKPNN8N636on0nABNXi3s0DZRezU3EI6O1ZYnOKRYZY+u6pH8v2Cj2mbcQkCZ+zi8Qj7clU5OnNoF7Sm+WvM6qo+rh2KVd5Km3RcvkZHBLuMRxvtmKSy6vX6YE4xTkeIaaDRxnq0f7/RpVl1PuyqW+HdY1Vqtn5kBHi0ZT6mb417wTXTsqZVUbsBhmW4pTXP5UupW/rA6KR5jIf3B3cWnA1rrweYsUi5nXRtHAK6Vz7OUGvPaETZCfyN7Fhai1XKeFo9BI2iEtLyJCv/uI57Zc1KaQyilVXEGw=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
