apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAkAfZjaGSGNycu/C/exrNh9Xi4xWnu9/tlgelHKhLPsnTmhFzqP+HHF4vQHGC105IdO8Yjp6VF2j6ByeDz8MggXdkVGhE8gNYop3pA+9osUQliuri0AV1IR/KQsUgySJG3oDXGnxtsL0nG1DfsvyU2MXkCgaS4iYhR++rhG3ngs/CrpOv2qY/kCIHZx0YihqP8t+TRgmep6bLsFNI3K+WtyGal/19CoeTUPiBaerX9Hk8J9Jo5Lyu2soaqKD6iVdihFRdWmDgtntVhvkFzMalXR6RBVnfCDZq49QVzxWprntvcl6+NJAswgUqatnct2JNoTeMTFsx/v0aqu3t30DhAWh8hhR90W3WRm3YeaPYUnZ8POCu8U/6eK+doSgYTjN7kCLCFcoT48UHCu0GcQ/r5HmvbVDLrV1MdBd0i/WPdmp9ByXBZrE8Y1M48pezAlJJCLdGoeLVI5siKh8q5l4I6TrjiYn4EaQKe14vspPHkiIhRj9zjO7+LvOCHig0vDItjRJa8SatNnsgWVYM8GMuQAKH4celN/uvWGz9GgnoPiO+O7txRzpfQ+hRATwLH82Gvig35g2nfYMZGC5graAUazXBcnsqQVkyKIrzbTL6MaTc2UwkmIc2mwf3dL52TBQ3K9LK5mbi03vdj4FY4zli2gVQtzNRNkqVOjv6KEymKkj6T33MGYtCrqcybx/RwFAicC7OuiOM6maBwMIHTl+bMxEZ5RQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
