apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCrXjqYEj4CI8tp3Jlwwtibm3PKE5JzUOvIXwPXhGrbJfAS9aHKPg31zzSdSrwXHqFasBCwghIjV3dwQeXjwwsXj8XjuTn29pVzFgUFVkIu3vG1T4Np8V5huDwa79Q+j77zsGqNocEiZFYmR5m8AgcyiubTWfkgKocsNTijxEAESWslNszZRUvbG+tGE68PCXdNXmKVNpLY5TwrjZRjSCIvtjv2sDifagSpGQuvbVLnZuizYEjNt6KdJ1TXrwmuzlqs7aYmSBwrd6ISULYZwY51l5ArdVXVY7hMSM3KNC3BGrhVrdstwbUd7ylqgJAoHFA+I396ArLJO0VUx+n95UTzjXgsd6wddwliu5thtgz2/pIyGJqVPzFP8hvY1s3nRzZ9U1hhjXpi1YKf6stsz05E15FI8QcdzxrXn0NidCCBIQBf/VKj0uNFQ5cSWm4sjWpOcQL//Aa0AJpgKGUD8PxbtvTTDIX/7N6eUPpTRpTxEgfV+nDXtYIovaYVB1m0GSB54WsKjC0weT42F8aA7l2cTs/e+w02AWY0vMJ/pwAQ5mrM19OGnaKAcLlurWu9AInBJ5FLU2cObNr82ak0c4FQJjWl1HkDIYur1YvoGFiTy+QPxsuN3Vt0c9wjxTGI5ponEQz+rx9FVm48aA0XQN9caKKbXXimFrrgRfWvdjfv0Tqyee8yfjP7BbSsykEXA85qfuc=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
