apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCF7rTH+9SqoxQ2oR/3uQp+YNs6CBDFYeqkqkngPJuom2CNhQhejDl4BxHXZwKQYfuAuM3MkI/MSqgCNWXM1IxDmJuqQfqjkJ1Bg9wskjtqM/hfPeJafS7isivPsz1JdauoKs65RFviDOHYYElhW4WRMwFHJSvrB4O/3HcmSop9ZTq4Vcycqmtjiunw3D6Ro/kksU0ByIPA/wXHkrhvSXai7d5st3EYw0ytNlZjPfNoP/SyPEvJNb0CxZNqhxS7HkuggdA5PtRbSYUCps30Cvd10GaUO9UEfiz9IKTZkHURaQWGsCFt7EbxlHm/vpYemb9umvvwHuFogkKng5n/RmSyo2xkpADRvyh8Bo++nLzPhbDSMpdlURSczXde3EXATOPYhe8ASlNiISkU0S1dGHclsRvENid49WlFuR1ywlbYayOsIDSUcHHxA/sfsOXAhSg4pYBIwuC2YNUyrdzaodKUSPfHS0sg8fIEM2El935IOxlnLQdSvG0fXE15BppL8D5DUdHN+R5C/pW3F+B2VhyyjmOQXZ72hNVydb2JmCZsuluEHQG4ErYwrPgIG0MvG2tkd8ysXPfHBtrMgIAc7Oix1NfK4XVMVq0jIgbhHoBWpXzIhu+8xVuZe3t+fK3C+zceYCbOamQxa/bvALhsSCz37hYzMIZiIQdTpN3v2zzLtTRvVdDNc1dAKo8CFAws1PhKgwA=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
