apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCQmNP1rVylQpx1KKt223xMUSjLMJlOXKTd7YE5/iYd5JNezAMDi+wXBh58NgUtsQNgYurSD9rCNa3bv1dxEB6NbVQ5Rx5EGPebrPlkTwqiBKIbDJkMsyx5n0DKfpfIO3pg7GoP3+OWYPa8VhaP7U7rrV+0WfYP7eSMfsjdx4eHUcX9JRdNbcS/DZQWSKpOzzax7DTjKcpCqFg6Vy7fAviuQoOllpp2dGoqbVCvoILlqhnhn4v7Lylnz2+W/DIqrbbqhkO7KwnSedMuf6LF0SITTt+et/sJP35oG8fhxXWi4Ju0AN0k2g/hm06/sWWRNHo4VOuf6LmbPvgt4Ch0v+z8PSTUdQCJQSnsag4Un+ZpAAI21YpzGaB5By4ZxhMkxK2Y1UxuPwjdgIuWits4m6sseLibeBi0lSGKm7oUrgeXfxgGOztSJh8nlHH+8MGlgBL+l7sGU5TFYasNrnqmIIqrVm7lKV62StiAZNX9aHH/qdIhVyVK0D/4EtH0FOj0w0Ueslp4AF0IPYNKXPbexCzGsEgg0gKcN8ZVUbrEKr7y2vQn42To6zcUysn4ECNYFhJC9xDKQBkaA4fJwW7oA/EhmiVLqCJ+SQnwU9AhZt7NocBpMC4Aq7T+ejOJq2W76dTBy3l1hkIikI/U/amWYNWlHAssFftuF9Vjob0J08AebV1wvw+E6/S7+zLkgf+yPRe312OFpJYQctZpxSARCYGzhwt5cg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
