apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDJqKF8UHW1nLiGf0IGkdNHgHMBnd2NRKsXA6xV29mng8K7KNpnzRri3v4I2C7uF4EbxLevs5ZQwsDNb/yNTrk7tAilik06E0Psvj2mYZesyJvwl9VmgFdR39rupiLROws4YIgGxOfhzR9IcdZ2TYdm/TG1ivQRAUuOdUluW8Gz+MoU8iNJvfm3yijz4nrUr63N4dYIVUZanGir1mjwqo/lHCJehJlfCH9gFjC8Ji5QvSUL2mzkSRbBG4FpM/lEPUuH7Qax8d2sYfUODwTlCescjPmd6WtA1H96OklWcmj4vP7uleDJ7I29LJCteGRz8elT8HE6+QZgf8CzH0/WvyvZayssyvk87eQWdKrLK1QJs5k4ej7zEELSqIdT41O+ugpW58cewCz8Sn0XyhBkYwC+Wbzs5HgysQDmBRnmcDDBAi5Ac4xPAvkwpkaj4ivXG4NTUUKntMkP3+QMFsK91YTG1TLh5C7PMAf+IobmINBHX4NsD06oPhPS5LpIUcYMCnnBAShoppGYSly40skatGpIDG5Wsxtw8OPiaaJ50/E7JwC1cpHpcCtrFqWP3hEZUVBUyHsOUt0SmC1MoESxV0W8C0dMa76LUPZ6qV+qrCZUSdPU8I5wX4WFXtezxYJg6OIzhKDHyzcrg7caynIvq7rKsXe0P+/kxlVu6mPl+z+j53IRTG6r6NULFtjJuwIKpV7+KwRIAjS2osaeJt+Esf9+RStD/w==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
