apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA2LlL7R+8H6X+oGUhwfZUtvfogtX0vApsxchGfF5fcUHlxkzJ+YDy2MOpgGUeV8oTCs+Kx9L4C3VL19Uv6Wz0D7u1e5ehSSNCyOdFuuZbJR6l+KG288MZI2Fn7vS+WczLJYPkYCcZBVoza4/K1Pgc+eC4YBxUj08TNWc2iEDebdiYtusndAWti5KCC+lnKYsCwE9TZZw/qq/Yec9s5WMLG9pwhrUapyZGsqB9TDth/ly5Ow0TqtsXYgN/Oc8yGWhrmgIkKff/9VL1c3a4H8Npq7VSWy47ahAZOJBSn/8sx8QH+P0sxa7gBECy9n+dvJa+RmTq6A0aA78VwcDKRaMwaqoQyZOeV+ruPW8wkKqRuewERCwiu+iChdZeCYR+280VouMr62SVuLLwCBwU3YSSFPoVv6+7yq0GiI7Iicnv7dnRjlGEoRFh9/nPxQbvlx4qTN2rD4Xdq6W0ul4pUlsPiGDYFqODhbhW/v9Thg7776FUVtDVBZ6PV0DpDBSutphROUibuTcmnfbMuuXn7JKWEaVwkZOi8m7x7/SuXB4+Agz2+D3Wpm6Xc4mvwUPanl5I345mmljnKNJKfwFRKtYyCSJIYIO7ynkvHgRLsGorONEcT3mOdC1Hm11Wt+r5ilzK1lrDH9AYwe+WFVKyVQ5sYGZ1oaq7qLYw8cJFc4WflvoViAr0XfMgeV2VEE6tS3dhCSHSpcMv20gmenSlmP+gl0pJTzQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
