apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDE1RriW9P6S2S4W5+Tot7dlU623HkDs6STSmd48glTMhMF486wLkKXyJhtANBi8dBR623q6XbRHtKoePEIl6Q/F8Ruqkj4JYzDh/261UBxtrHMPggfKH1AwjpHNTztCK67UP/BUBHQTz/2cU97yQaAbu6t4J1v5y2Ccc3E8BznxBBuyfS9gxRpogt/Zrt494LVVivMyp4QL2xCFSj50VQkt9kiWTuvSwinOb9vr2F5biFtVqJ+KBzvl1D1HHiJomBAeZdQghbUvlUdAGh+Bd94+XIPJURE4Sa825aq2oPY99ROeQMg2b3vtWihyQi1VQXK7EffknowwFlD8QjhZ3IqO0W5eBRmpJK8u3VctIkeghtghfofDTiLAILbc2+rrHZyOtoqhXD6JE4Vb4zc0oXNRQ5fvyNl79jWN83IaMKnzNQByPhOt3FpkqL78COyn8rJy7pBGkjA+/yHcHbAE6Luk2s/nXSNFfcvfm3EO4zhEt33iRt/05ylwBqUaxc68UjPCLqtcMpfXLAGYoZnMMEvFh7v9gjn+GB2rPX7pv6pfoHBJzK4MFA0tNB0q5oWFHzx1DepGvUGDAnQaZLWJYcE9mmoNzN3PTjGM8eD0GDGozMAuuCy1zoWvS2Qci2jppjrqRiVKPYlVfnoCz6Z9T0S++LjoDqnTLpXDAq7A29+TDzcIReMnGpH4Z6pg7+X/XErsM1Zu8ZR8DSlr+m7jnH+PE4yww==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
