apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCFWa25P0kTjPoaDSdcJBDyj/7o8yzBDeVIcpdG9urKmogmZUxqitL3QW4UhSvPAQoBjjoNqdLmkhrS9uL5GDSJxj3Kn7yFoU+92tJ95xishgHg9woZubOw5ZO3fgU0taJOzYBSOlac7BowTNETrJJDQUKRdHydK1kxpHZsHGSIRXeWrJF6UF229OQGzm35eg1WCCx335sd53iELlvNVX1ZHkkU6/kREpvvlkO/GCmAKeqOTBkGWqjS90IhCFbpQJqpQSyoWRNFqxGdy1y1rTQXDI629nDH3k2fA96qHZqTg0UC9aQsR5PVyRIUrnv1R6Q6QHwWcpQcQDP+oFZ3QJmG96QKzcitbHS3IepkEASZC2ZrnFJXNPxuOn6Zoy1g2J5odGLFCUyzeCBXxYG/QVsj1PEgR8G4QEbE3PZeRM2Q+0q8i0249rXerEb2DZYm6stvuOsYiSNWl4jfaUIsNQcb2W5Ot6lHCYoFndiXilYpDzUXwPTL02bZx9ZbvKhqt57vRQ2RUdNAxJGWQQhPAcXVIm6RYPyPH3+FkRq7GlEzHG/bFelsCMsyWbKDlppl9bW3qLgsnmJnVKq1HIaACsEFUyHyxAvEs82h9jHPRJZK1cN/L3f7PMV3RNVsEF8ZnySMtJAhUZm14TnlpmyCwJiyiqFqDYo+XiYkN0A3jJ0j1lKcwPvCI3YFJ71+OepzLZBKn1H3nH9MBVDRu5bvHaDXJj0oAg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
