apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBr6GdQ6UIJBPiZ7Z6k53JElvu6b3DB8KLNrt1tR9GzOc5CGr/0b0c3TlxFnICEQSbV0NsyuRpsilbtlS9No8h5dEPcH7IWIEC6QEq7Mx6RFDLBgUjnj2bB1WzEaOAoaG/5mi9crhe9cTShZY0lhFDBoEgwi3dxXZ7y0iOy2Odsy3GFVzc8H53mBedvr5ZkIIJTDzfwQq8KHGBWCQAsDXnDnKOZuL3BpkUI+1By62bukkCMEOwpkqpOryxnE6uT0+RpE2FlVwuLlt2j/l+jIyBMm9vu5X4x5t3ziuAZCTk81nRUiMcdzaYcFWldZNxRwV5yopICZ0xKJtrhB2slqp/9dnBMTkiuw0vX0UkAIZ1L8qmwHQSBbV2KQ9/ABa/NMAfmnAhD+85iGTbxzbC/TfRPGYVGLPaDfWxsaYZQfS6jNSGMRA+6QRjoRRjdGp7sC33YajSbHazY8juPVxrDsdNxcjv9D+XhT7i6JBodroahipqX9XA5Ce+KOxpnw/kCPpYaGECb/zVHhkgaT+2L0qaEh2Nuxxpye5cpNrpK99IrX7awe0X7Go/SXlg5MsEuc4P6KBp2lBj0TOjRANGSDU2kIwRlbijrIKI+mGPgCrxzCXOf6nYLnaiU0ITzgH/gmIUHej43eezWJtGAW4A/AihujQwywjKC3QvXlPRpke8VX/ly0FmFw/FV0tZ/COMZOhzN6ziD0CpfnEDSI4HfSRNL879Izg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
