apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB0/EmNl4LGzkVuHUzsOgln3CgO1XWXe6KqVyqzoqPApYkjBFP4Uwp6vz91YCcJSMB70MRY+i4SpClEfk/1l0JPZyzQvwzdA1bkPCf8krHWswy0D5+euyW0XVis6ruvx5y6i9mGK/s3LKBtI1BAT+5sMMgXR8zkDbFckhwgXSV/mEB4y9Un8EyVW9fOwd71O3G5TpRwDA4HzKpQN1vxQog6Elm43c5lA/lDjCZ5aWA7RjTEuzNTLoznQ0sD+xqKOEMMsZYfZOvLgepK3h+BJ4CyDSPgL8Tyb54MhwySBI2agpdVzX7z8Q9Qi6jzISYGLOc7U/dqBk9OU4ghxf/Y2QHHWamkK2nHgdym9jj+ZI/JXtXVCBnbbtHfcD1vXdFHZro7qiuSv0BKrl/3fn+sJq0S4CfdbCUZwXIefVjhi7FdK6tjtzJdMn25Mv4qEcZayf2pOvHG+uMgnx13qnRlJWBDQuEjs2t47FdvhCGDILkTpXD0R06n9gyGlILLpXnlbZAabf1jIJQBQoLY6rjv9TCyILX/VPOnpsulNh5qAnU4Vl/9U3vVjhmc3vDpcAWXDDBejEfzysc5jzfWI/i03O1Gk83DBQ+Mn22708rGPFtYlC1PZBCLzNvAABzb09hY0/ED03vmy+XQByBkMFdnn/blE5zinna8KrfXMSX6rRc2kVpnvBgIBkDAwPbZbNmJ+sWnOrE=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
