apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCu0GxPFOiPB+x/mLzyX32yPiUi/EvoSLK/hSu/dH1ef3F+jngnTJKHcWxrVBKGl9P3/LzZ8cpkB7uuWmbM1zFOdYGQzh2tby7lrySqOcKudXgxm2ZfGHQzIRZrx6T7XooyqeeI3w426R03S2UqgeyyvVseM6dP/2MrUxXQ0rjechyn/696Ufsv7kw2+nnVqAlYOY1X3I0JzawfjjlhrSdlgkVsmORkzHZuZ6k6BoGK8Xkedug0f8c4c17vBqT+XAfMispr9FyLYqn1+/VVwOsgUgHKIS45iAS/YFsNP4OYZNAqNn1yHJgYt5lI87SUl4Rz4yVibP18ptNHDRfonHPkj92nuYZTctyYAcS7x/wjIgjO9o4weFECgRMgzmdCJGdc/IRAieWuxNZAjkFu2j1/nIRm908MSj+INE6n2aWWe3W6bAdLRUfGf7teE1EU+oNXWStEiyr+rzk0WCk5xXf/hOgBPyvwquiPP29Q+9qZJqR2z5TSMkwExfvmVOULfIl4IRGDtu4QFJhdBlM9H/XlmB9OdXP0wDjRY+CVyh8cqP7r4InBakgpRyisSDz3uto8oKzAIVxdYAlwSJNYvr7t/Dod54EMcPz4K4F3GCM8quH7floTG/Bv08eVDHEFGSxnCvWlRGX24ANP2csDmJrOzzn159avkOgRtgmkUwMOLT1Hay+j+4Rfldu6RYVPH+Ubcpk=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
