apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCtVDC2NuTkh2p4hDS0lDNKqS5tfkMFriZxJypLvOiTdUQBrhA7jnWRzUrwzfzuQJ+9AGED4tSYcVmR+4x+f9InNdqCpleF2YR50iSt7WBNFxKWlNdMLOQm0deLRm2GkVIBB2CHtYCGN53dYdHKblkVQ5zcfhoa2H/wKQKeIPKiLos8FwrRbWbsdTa6wwQAEh/rq/rFub/F0McaA95kgo8gOZW9o+QuqVmKzREjKU3JjvM+1XwI53gfWG3NppW+EB47p8EjbIIgjShE+8GYRb8tfOMoezgOD882mvoFLsgUhpVBRtkAG5dnwLuGxMM9n6O766KGtooK+uAglmoK0tIznHAKCiy+h2gyBoJAhFktOyBuJNTzA3Uv3k5J4iVGA8xJkL8DFzXSF611U/3yUlp+lJQ+e2robSb8hJe7kxdRt+SeGESD4d3XAclX3+hwITbY/oFPoiZ4lXdK+srCQ+GoIHxaVnni7lpDL+UInKk0uepZm/pr/u/nFnMGLJ3vdwgXkcW5LnEzDLiW0hXW092XIsyWKuAISHjvZlZ1Suym/e5RdtouPnulJ0vMEdnQVe45Wld036od+Nj9+PQiPEdDR/bK53qePlMKsIlJMZ7Q/7543BjTyhCqX9b8yzJCJ/Cs1wRKm2dy/I8dfOPR21qybG6jSh3XZzqa0RkVpoOVsTkZmG3P9UradFmxhgH1uoIhUQPpIoYmPxFs1yrDoAaSaOacMw==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
