apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB3zb1k363C/CeSbWgDaN7yVLLw8LZnHmQafN1z1WyUoMWA5ELp4pbZTPqjRxs6HEV7l6JAxEbYqQ0OEhnpdLkcVpmyhLycVQxwprjGd0gT6OelVG2CzFliPixppalyvampPQa513AIKKwowOEKuEpzUnUtt5m+Kd8KOEjjxGm3E2ssD8AVzeXVtU2Anxv14ypCZSn3/9oTgmcfOQBI5mmobo2WhzD3f7ZdotiEmN1Zi2Wt4UU4ZAAoY1HVDjzwueFGR+/tX2f6woEwzJoV/Vvn9UDixT/B0YOhvOl9UW1s24vZYnnxENxVuSVCKEpen+GJU/vP35Wjb/NyxidcWMv234CGuWCHLcFxalvn46Y/W5Z9CEcgc0/X9AzQ55AQQGD0vKi2beNA+EzVcwF9AoZBaTfjnd44UxRpN1kLJfrUtuera8b1oRf5+pBFI/8ifFReN0VY9bvCWjP0idOxDM5mcwFbDjjdCmVFI05p2XsP0igauigTS6Pti1/z9jTrkfNfpKKfgZokf1QxNdL+gWBD3izAhLg5jGULfYpRXVS1mHdjyfQv6YLJ0TdQr4HMYwMEeQF/jSpEXCtnNkTKedG3SzuTWywDxw3jMXkg/f3d+pbklR5jsJ5A1l66zmj6r2cNjxstbjnJ9aZTDdb0K211X4bD6SBTDDtBYfB2WNW3tPNQZMfcc5zISNYmPvb99hfoCe+Goax0exvnL1v4NXfmarG9Ag==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
