apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBleeMdJLvQ0qBaE0ZhNI5LyJcN4dAPEfiFV6nIjGghJfPcKqA3picDvdYjRbG01cxRysQzq/0DhWkZj89FSosOpiC9utqLAX1gZub3YINf0Ds8BtgVLj6wRfZffb7k1iO8nMYGQ/z3Eozb7V3Ya6WHXACFRPWo2r5f38WfCH9WyZbUDRUozoXW0fLw18Jr7Icml0CY2yU38ntKpnsdI8UEZTU8RNK6vObCvSQkTQskFVbEcoXQsTu2TA7reZ0BhTbCbFEs+OGWWqNnOx1R7Lst6+di7k2beICVCHPX5yHsl6+sLLlJLwHbvg8bL9kEO5ZCB9Z0fpe0C/V5qVLnhuNeAOOLddKMEmxYW1Rx6XUtr7zp7VHcbVAjP+JI+wW8dtDnPxyuUDGvVeVF7NAvUJ4/0XYDKdF8wsLfHeiH63DB1WsspyIl3Vw5y46sjj0D2LhW/PFx3ixhiG5q3z2thpmnHO+lu9N5TA3IcV5fqZw3A6NSC2HZxY9uOnzZaSOMieM71FykpeNwB6ZVufGLh80rwfg8oLuZPi3c6xEaAdy39aLAY8/P6u78mOz40kjQ8mwPWYEtLOkpuuyb7CW/Q2E7gl5WsiQrYE+8H7wiKoTkAmcSFAA4dkkOJJlDVHbd4LCRPI7uBQ67ae2wwnvcheVTgwLVu3GNtIT+l3hByyjsWOKymMjymKIDC6Z7IAQiwgEjc19fZDq73FVVGIbJU70aHIMVdA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
