apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCgzJQtpuQIv7ESCYnGlB9G8Wq9DMAC1YOHe8h4zpuxYG670HropQbN4uBcAC2JngyuLXYDBCEdkzMWvxo+VqAZEzzh1KlldqM8rA7Tu9LjEk66ylgP0o7F5U/wqL/LdQnvf/4LnHZT8FcIN8oDF60mkFmTyrDxgsUNQBPkSL0o9xAziTeRzZe7PxNG6VAKK0HL6ela1wfLt0VcoiHQQbTU6r1ZiuWL3n8/DaLQRLXcpWj/R9v8fItd6PYVkIk1J+2TbK0FYM1/EHoTHqhgjoiS7yKy6I1RsO8PnjJu2vhD3laNBZrFcpkyXib9j6AUu+w1kqTjM1NrYyxQ72yAFk8BwBNzXuqfn8UAn0gT/cOkhqvsqRTzUnodEg1WJcjqmRpd+oREpK2T0Dde8zrozU28VVyBTVu+iV7RfZqylVuae4XdLONKoNq/QHbZYUrzZ89pb+GYhZCETenEVKYmnHFRzkaMDWs8T85r5lX+pyyVsby/9UGcj1craZp7EGjq9BrsLdgj7l9q6hWN0hT4CHl2dhqjeMBU5SGNpVqEViY9bbQTyUZWGfPwBaqFw1V2aoiC7jO8J9Xxl7msAJC1fg06Vld2D8MbljtW/lONqO3RwC7W2x4qtNNasATuqzFiOTxKM7lpqg58ePuISP7qFTWXpfZzrHLG/1honDrJ9Ehk4mlN7JSZAJXplFO4q2zoEayWVNxPbX9Qn0l1luPMrfjqDKBgxw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
