apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCZBO9RHzgbmiNlw3xtfKGE5udydpSbQUT6W0xa9HJw2awSSG51OQz6lGDwXlHEq7FmiflI/gEuNAJaMbRZmh+Jtj0AXCYoiUWSo2Y10q7JqACIU/glxE5m0ftzFlRUMx5LVHY7D3RalkcB/igKAm+OvMav/jnmdb7XBxMw/TBZ76EaZyv9YBTN9Zj8SO+kWyFi6JrHaYDurndEIDz54ISDGPZGiEi70ylHbsxlf4WkVle2Z2DD47zGUNnuRSx2C7VD5MJ1eyNH7iv+/KeWwzxbS9Rj+kUwQjXJGJNryrXtbpSAewZFdokHHLrJzX+c61mCQGlAs1FzbIFCiNJmg/sDBorUlsQgMNoE9bA40vY70rgg05GRybNp4zxw1T/2z3xLnmfCQC9uT5YS1kGdOLSA8sAjX0SEEaNbnpYsqQ1pIC01bmXEtg9rjVLq3oQU2vaxnvAEQ6ApXsgLbhnkpe5iDlq6MHsMaeEX9oLxquYclVTgB7r3Ji3bXfegN/441uIbknkAqOaAv9xSWw8CnILI7STMOdXzHnAGlndu0QE6/K1VreRNvqzdOWWDz/VVhWSQpvZbL/00ISYNCho0yIhKvo7JGsLyUOp49E/MZjrnga3owAZRl/TGsb58CRNEbB7y806vBy9fpGTv6B5EwJ4HOuEqBr5y0dpTzEeVUPJiPsowiVgVActQ5rWG8hNaMoPpC33By3oD/WiJMnMUKb44DTh7zg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
