apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB/Z02vUr9MZni7g4Y8a7Fs7CJlEB5t43ANLGHmjrRjCeEBPlo7xzpE7mNzWdInmNh+agYntXetTEV/Re4+2ons1kRUh8+idTK9N9lvb9KOhcYU4vMCDbZVinTKcYVVHjmBlPS3CJvLAvVHVXblLvxuuFUEVYjbbl1MGQbMmYrHx0Tg8VzYTJ5Cz/fMDR8KlelMCOtythBRd6jWpBrreqcWRVfqOZqXWGikjg7oLvWXB2LDYVX/VguGk3i91MVLyO/oSIR19oXzsachkW3z0SQ03cQOdMAUxRnEjQEMBLS+rQ8wHUMlav5MtMP3ABFx8UM5m5B3dOKxikI/ROm1sEtpaAgqAzaRfRPg88tWz/9UBiTbMxtLnyFlTKTYD/i0qtxc/PntVcUtztw9YAIBO7igwjA7ZQ/mM3cbmJwUwbtZ9nyboDZAXYk4DiDLnTQng9zA7pFjl4+QIZcK7SNfckrRWo/OGZYz7KdJGgUGalLVl0sZ3NJVPFdqdr51dBjyUe/kT54qtGy2GYLpI867ySlHKl4cNJUk8VhwKHZ9JkUDQQJB/kZ8PNgurbhGr7LaN9WuZMHW4IYccs+EhrQ7xTeZPUoXlajLRsPiIF2fgvNRcDIliBOqM4D6tx7435rFd8DDKypg/A0AFCOyN+S16MrBEvK0bV0sQqDAn3qRJWphvk9zTlrQxB7qMZM+xKmnaImY/cY2K3FEZe9pk0bvnmceuqtM+A==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
