apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC+49bUsRiGJW6VY4gZbyAN87pEwV6/AjRvP/B3RLkXsrSFl4sGYVxZc2MnKiT5AE/QHbXh2LpmGtgP/20tRZU7OsEWX1sp7/6FJM0rQ1IGMjqAuVuR3PPQb+TaB7eaOfXCH19O3KofHqyDIz0sopf2DnoCPDQJoDLq6aAaPlQ32VA6LBuuIjEz5PruW0k0Vj6uc6hWA6fJwhfozYSlPq1wX4Mfs2DGgWy8JRgK0hv4qD6gcG04Kh0FzGIZIR05Jj21a/lJPnaVpMFOcP6d2Um1AVSvLmNbhdhHe+0utC/jMZXrLeOcXDewGvcbfAzbkexq7JF8U/HgrnHtup6GstNkAqp0mHzNKTxvZNogLpxbNFGFrVcVS0PlVzRQVH21ZYc0oeX+pb9a4SHs+i52ASy9MC6cYMdwh/beupGFT0R+OSP2fBGwS5YYYxs8fwq0kZ0UB5fqh/0PaFB4Quoqfa8Peo9Fyc2SGVH5INQDeWxAd/bjOF4eshM+sAOuHxfGFZi0XBAJjbUkIywkrRhl4X35W+vLjAcywCVJGeRz2lVcweBXKee+z3tx28nOMTM/+y2lrKIEg06Ac70MWXBBwNnXzGvAKFQQRnG9urmvzjNDQaEWLXYrw/26Dcxbgrop5WMaKJGtdSocL5+wiKzrMY8+zOMP/nbOJX7xAYEyBKT4/ht3rORNKZsjbzKaOP/PU4tJdTA=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
