apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC07HNkdfl9zChGPpaBaWF2mkS1yHkPIWSoJueiufTWfhdHd51b1AjtybE34nvubP9x8Rn2zG7U2rc00XW2E77SOv5hGfE8timwNkZi73818FpQS2OYJ3CIsp/PH/AcmvYnXGHGk9f+HUYK6GPcpY3W0zh/6pKgkJFEj4nrRiHnnrSMrSfEiz5KjnJtYed7ndoxGWL6Do9tVkQ4PHxu3f/gZYjgfKOKkw+pLAxM/uZ5wvlUfBHiyAIMTZjF37SvmevGpwSwZPwPo2+6t/ISuRGIZgeg/jlQOYN8nFJ16vGAvD0XVh4sU/v6b6XapcZq9JIwCty6nA7OgY8+kZ3uYAKCdEwdn35+J0cGkFpYYOoLgab/Yrs2/0yVvjAZNvBnHcs+mLI93WyVlTyU2qK3NjhOE7ZcO8/t7tQhfyrUagx3Fl0huo9fMkErqOSPn3157dO/jrqKHAvp/YsTEmoxghPd+aD1jfo91j3eN9QgwwDnzm8JVofKYtIgqo0QiVDLTynAQGaDw8VArwmFWmVXI4NO3ilY89O2L0dgZu8fld/0DTzgTtEHJl5jJ8Yqrxf1L3AZ6T7SEqY8vn4yxlyRXxkpEi5LdjU8JdMbqZnx3xcqDFEB1Bjtj367hAxF+mXUyvG3g5fUU35hnK/3wN79BZRkHfOYljBajzzXhSfNdxQ/xDv+BaIBEV4QkYHcRD4z5IlTKdo3gQEH8jn7Rf1tupouYROoMw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
