apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBSGcLHceEiexawlxS5ZiWHaG99q+i+pgqbXsA2ABHI7i7dOhxCpL5YQqPwaBk9Y3QmaNj3NbQ7TBj+uVQv2bKBXLkbf+Z/sSHChBm8O/pbkIS2vIV1wBqN6v0tqJhGsppx8xX607Y7AT4TWHI5VYFtQXMMQpoYJHsyAvzSkntEYBxt1hcbOM3kBLRHqek7uMltP5yfgVrwL1OPkJWteghFugSPSElal6nne/JfH/2oiFfO2jvdH9UrrJdDBvvMLxMby0E+/UOGQDW/UncsfKNZVbmp5bP/ewYBlnfx47W22UH6stMIsExkETgn/9yGGWra3+Lv1R3UqKGqnIb9QDZmWduEiuebwxZGZLGkCogOA5zKy4S/KhbDLDbYzdsOsMSYfuFulUpgxam20cjyLLUy44Mf7McbbUsB+D08m6q33lEX/5rct1Y8a0+F9361rNce9UFJU93UOSeYjpvZShEF8LYgXr3lgFzF1pFb6307kS4K+Mt+EPuzZ0ZXguqQsgHnmz6rP9kMgfYfbQlZmlGdI0SvoBMCLfsbNas0C3XgW480+87q2YM8OVeDz55KYzuOyyb+hnqOzoN9FpdOoTqGI8aZszxDQq66gKKPwxpQJovb+pJWB/n1suBpfJFitj6Iw9+GRWvFeooOKxH4WXoPgnlb8Dg3PlHRinlPPzBoqbMIX4ztUNHIx9hwo+nY47W39AMVbVY0WFsBCUTjMbGsE5FeRA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
