apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCkxgdKoVlg2bNqlZ9qrf5/j8KATfmrlYCv2OQW1Ff5QZRj95pl1N77Ag/1IG44MuFPPkQEUCx99pW9nr53hQ1Z9RjRMpviQFYNfaOAsK1r1O4tX/5vz91LdDZf2QWGnL/PBNtSZvyVWGpxvwp80z8odY5OcKXn1nhK+cjKIzvL4FSmR9d4kgTpymzI9nkDVQOJBytJWh+WlDhnHUhX2Sf63gdUFJHyJS9lpHNhm6cos0mbtzNUAVr0GMEVE+Q3dzqFCylKuhVqSqS99ljZz3wgCPebIaMOPodVhihFs2zBd27kDvACcr1I5QTRBNdF9kt+7Apc4Mk4p/s639iMcehEEMzRn75Wg3ZYUWMmnb4FEOohj87jxreLKnFwR94Q8IDt2UzwfEj4nHkTHWMwgtpjXE8wEjAzXAKfALBA3WA6tShPXpKcIz9hbH6wqWrpRVfe/xpc/g2ZKuH0mfZ68OJZCNOkJkBiQ4oeTUOjUe2pfTTj7NEvKaSZBefE9FfwZ+9THu+95ZkY5d1J4AqlP+t9emJr20uw+WuHivcwqmwBZ4O0X6gM4DbJNBr2UpIuQJ2gegBeh4z01DYmkYwqgWvBqaNmvayxHnF6Uw0cE+iVUUwLjmqfZzYTS3BBrn3Nh/EiOjvohwRgtsaT5/wWA8HKwdc3/yS7N39LKWJnYtl4aIQU1iULaULUjJ07qTpj/7miGL5AsI3LJUmisSBXJGA4hwTZ0w==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
