apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBeMkj3qF0W7p7/uM9EffIoRUpHXmEM4fQyNO/4mU8dg3xCJr3dScuYXcpaj7mAUa9mDWEpf9FIF9v6UuOlD1vtZhqCnBMa27YtVEya6Fup2/hGlZj0hwmS5R+zQMEPbnsUwufNa1qLLAunfYGIFDh8mUPnlbg98BF8ho9tHCmqxptO4XWMPMCPDtUwZ2fc8cKjrzUW5BqD8T7xetow3YkgGaA5QBi7DptM2vSqq+MB1d2PzGlNACurU/IjZR2a3LpUfnh7dKSpmTUhNGc2f1uWrU3ACQh9C7bmG5a0nU8WVsRbu78EjBEh9+YajMUMlC3LbNCRkb/V7cyHeZrQIT1BrqGyPMzFegvjl7Dmai0PQFL9HoButZzsDZ0b2kH2h1aAL6tUfIS+picqb37/6BeW+p3wpPelfAkb3o7D3nBR7x+aYurhkINzguK8VFLwhOouSS23boYQq93nKfoVyiJIXUV1emC3qN6NTLcmcR8V5uxK8iyV7Aj7ZOO5Lb6KUIEyXiXgNAZdMH7KPMALs8iWUfOFMd1t215oQD92s8FgcnqenebIp7IOOpaOCejJ7yr7x5i83yYVJ11R/BhjhhHQvnnhqv+TWbxqvYnHr1YRiYOpwEs/VVhqECT9Fmeu1ZQ+lfnJ9V9p7iAGnMyrpnaluEDG6MPakyXaG1l5BXLJ7LBPMfQ/VAFhGgqTfG5bI7uD1bh01FtzzvQVrg5xsn3BcbmIWQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
