apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC5UwpIYzOCaMsQrtofnOs0bz9bGKXXB/UDfLBk+17M5t2esybF/9t7M5OHcbjUqCGfZdKRKLjWggp36Q/MS3dpxQllykZ5KmqMb4mlX4zBc1Xql/QTzlEigukRvjz54y/y4gvqMBDfTx6JCOe216Gbg/rUQOJq+em0nb65PzhjKhiRBh6J3n2JVA0JWMYSQ9RRPLHXrInf6sxUnZ3Zi6F8+PElDlsejtcU52Tr1m1q7ylw3K+pA8C1tMHF3Ud/5J/6QA/QOS9PIYCSF3X8VqXgKqOIEIVBPcFt/5OdqijVJxZjFAjte+Eql9Fy83x7YgXRJ4zwZf/YddGFkIJ20rnVgnDVVsLVI/WNoe0hPNbrTYbKDiFFjpJhqJLgPn3SxvTRYgPSQ3mNthUEOUKtheYAMOL6gZLlbwylexWP41wtjM0gCkAD/WLRxX2CdC1mbFJfNGBisoBjFR3uBdLftoQ8rLf45pRF5Cy09VqkaakuGcdU0w4hXS7Z5QE0VXvXee3SUdfw7Ki8Xl6hC9npeNK6m2028JCT4TDciLgz+yonMA7M+2U8YNwAdTPszcxRMTzytG3mWPca+sUmv+7v1Pappyx/li4WtKoSD6p3gwrrD67EvX7w7Pdv7SlL1avOSvpCt/UizP2VEF9DfjbCxMdQllreYzqjoXPTrnQzi0e0oke7Ar9IxflSwB0zrgP+scPxyyBkIA7nbNcAkBTu7H9y/nPfvw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
