apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAFytcAqKvLEOBNr4RDWmbEp1BsRUZry2SzcL929v+nYGZg9YEZOM7rGlzupIvzHxsgpoRCQsu5BS56MVVhPynyYM+R5hD0J1loXf5dtEunutt8UQwNq1jnT+qXYGWvF9txUCyNV/GbwG8U7Wu6SGMmEXxEnreGKY7uKZxj9nFV01aXG+c9Ma5c4Yes+QoyAxMQw/eRyzr2Wi0Lw8jf6OkBE3kjdJG+CKl7WQiZ74xYn9U6F35BR+iYvw7buZZXG7sa95D3yxDXmCcgUmHj5rySofnaKeYs8HlTlITlLrQtZ7ti2ZOti3g4A3tqs7MgD+OoBoBGl2qSAAPndGh9/XjfhIaTTCyUe7jGXLgLtgD5IfUAAHNyXTP/3I5KNO2VQ4hPAoztqc7E29GwYdORXRDQAuawh9jr7dirLWR8V1v/xZCr9VqtNyJx4FtEiiOUIrUoXOncIupP/VBsOVGSdq8SPh0siju4TK1/0XsvEjfBy+d2/tiRqVsLggejYHOI0313h2qXIj7ogzo+mWNaTkMQ7BgU+/yjVrWstZE6fcmSZlYbRuw9lsdKWhTpiejBLEQ8n/M3/k2aIyGQ1zxKFTqkaa0pqMGnOk8imloWpOrYmEWVhHz0wCUmz1HWEI8s10Ax1z6dml4V/LERtTx1nqHswQJITBrUfQNUFpeGkReApRcZ5fKStTO7U1jppyvbyuxRQr59ENot2zJ9EQ6oXNGyebt8Aw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
