apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgDbur6oZUvrYM3C2o1oOy0/ePtqlbu1UNYvGljXNCC3bWseHTJrpenTTVusTSZgl0Ldp5FTdcls2p+aTrPIa6Dfyk9xCrMFZeQV2lz13+dqgbT0hXG1DFp6LFD8Vt5OlQI0hFTBXBglIxiKTn03PGIFGaOJjZsA2DoXKHbHKv+ADuJpBylNlGraeTdHfeVhgxaIkKLOEKruJc7Z087IuCt3xELRcCmwCzfprD8taHSD5Yc956wvp9FKx6MtLfpyvBd0srW6dF1kMCCmIbm490vuufsksFaAPuS2UIs4WkKEhTxcZHTYTuwoIERWc4Lq5N1ka9xyYFygfy+AvlJ7nw13zI/UtZG3Vur76cb7HltksoJQWr/gcH8OO/BqMX3W8Y14bmnvlXfiuGbRuSkz6HV3Khnec5pEPH4g7i1ywIDzj0rNNzmVlzBNewhiUBf8ywTCF+9BdpZJXpYrPNaQCy1iIS8LTIL/6dX+d7IOvx+6k+WmTK+FEtJQHRY/x/+p1mxqLsbEyE+b63NAAwyNEK6PW/DpFAbXbvvpEqwEKd2PWem3HQaKgA+PDlzMbP32v0vDC71INUUZRTCPk7oO6QlhshzkVjWJFPpKnYqX5rjDD4BxQ8Df+Grk2CRpb3ARt42VqoVDsDcPUUPqw91zxbWtC3mnESnacqoQrs6ggcSBfluFmXcfMDH3g/ZZLdEi2FEXzpY=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
