apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBiMgzyLwFE2XSvtNd75473Nzo4o18czfAEMSRyd3IWIv8+gQnRlWTRdDPyWCRymfzHz1Ug0msH7ndXDy9QdyPAslE5+vWQcjzYDkLJ/B4/EcsRWFgS0j0V49ADi03ewXJ7q4DptgjSabgP7F7zJ07tgArgDT1lAIMyL2xB2mkaCdv+DbVeaXTCEDEOcgPf23KijCrk950btl/+5o9mgKLYFq0mgh0Wssh0FMHSIeHkCeElETDs0M3ooT2BBVqfRzTTQzOQVa5TvsVpeuAlDGb3HaZqKqh6RzZLM4iVcuq02ZECbbKKPMIMGFqYSo6TIJOX9pvHiC/D+ocPOOCHGfohvIr11Jwli/XU0/4my5RYHyFuCLf+QhnvkaFrTBcKQsdEwwJ/2M0Hbuvr3ohuUzklHJEajAvb1rbz3SlFrlRvLq2pm+s3t9/TpMxn/QhoJTHGeCIYseZiIzL2d2MAd2dKrNDYi8Sbmt7sQnk/+F3k5yUtPGylCypBDN522V206y9aY4EtLLpJN/mKL5QsG9D0j6DJcs0b9RQfqhr4JKN3uxfhT3Y5yOer+mplt456bdyvW5zVHJOKr4vPzO/hQqDj1Yx8vKahtgNdi6KFBbiMHj8axpGJThHY45lZVi/8hkbfKcpdDQnetzIZKxtRbhCbbT5V1ml3OFiGHx7Nw78LGjNzW5BU/77iutvq+9Tk4HtGmNaNEu1YZDpG37KkeDBhp+u/gQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
