apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC0+pNcQy6P9VY0AOta7w8avymh67erq61SidjD9abDLz/bAMEI+9dH+H5gpg8KBAO/PLYTLmzQTIhe9Jr5aNYJGliisE/8hp+aJoXMi3fb63TAzc1Z1iw9JQSLM4gFdnOCiOPKNb0lONkR+C5BKKfe+YkhXsTfT+NEGubDTY0JrZ9Ijgm5G8EVRu1LlJAQJfQxpMm81brDSEgWvO1dxYClM6G53j0LvrYXHojSNl1DL/eRtdc7ctB5ahA5rGse1oW8dI3ztp5/d3l/iZXsWonvdM6l30wJ6gw9HAQt78Ls49ssQrebb771OwNRtGsA4PgLHF5Stsi9kcEtNMrm9GXQYwzcWY+aUgyJpU8OaqHJ9sI6B52DJZsfsfFBIU/n+KYpWsLNa/uShoHtLghmyUPcwF61EmBew90GeEGG5MGpnsKQTAXMh2J5ntEv4pqKzcqrxqLAeVEBIKJ9ejzVpdsgcw0Pbs5kOtij7AKvuupKpoFgs2rDOWOpg++7l+akOSo3eIz43tXwO4Td3gmcNPHyiUvmJ9h2ygd9uhBdMILKwAW0IH1pPqNQpsUETV80mZ/h+HrvCSbtxvaJHIkAYxzKzPjzrfrEvokmXqdmOoVr8i/bk6SrXjvvggQNMCL+coozDXJKWXhvXl+M+x43+Hu5hn7RQPasvzo9sNrc1cgv56fX8pjpEW0qlnAAZIHsdr/DeZz9P32YrDZGiOAz9UgKMbevRQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
