apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCtgdC/wDG6XiUvvKiywefwFjmLdps1FdLFbqXiGXlinMdxeHcyOiaFghEXxhnWflMU79lekzNBmTiNqXE971UgN/DUqmCfzjNv5IqaZilXTPf0gVw0yJ/LYdPcb6Py4VZStjT8+lWmneNivqy4UZwxS9fbJe48bC0wbX4c9Oa9gN3D6/EEVGHMyJFwrjuHJc+meG/emHzzJidysvs8N/pLvtvjApArEFWlccA57tLonYOk+0GKs9ZrorktImkUNRSypmrDD+uLKhvs9szZvm+Y1iXLn+13EWwy4BBXuUAO/MQ6KcfRF5lKng9JbRm7P1xaTj2K1fFyLB9Y9LRtn1P2QxIXdjEkZFnh7y+TfXFSbXeI3JayTSJ2zsAWaHPSLHVdiTV7ZJVOsW7fqxbO7wNSagCKCwPAFhigiXtYGax7WaXZUiPmZkuzLexGf+wQEC63h8gLCmyZWJLzvB8+vx81ODbmQ58FlaNzttYrTfSxDE+EBn+YSjUTz6ukfsfyfIZIxBsBx/259svyjuSC7xV7kDz7i96G9ZQ3epEGz/DttS6zof2P0+cD7TPdGmNKhbbrMKZ6Eqq6cOFX4QVyOw2YfR5xEpG2uRxrovaIDgzxiG31Yoy9DXch8QXsTC/KEyoJFPxK/Ut1fE7T/isG+veEWjEGR3qKpVFlYYuV5FGGsD0fGK75zKzitC4X2oNmp8z4Eah+irpgqIP6V56odB1ekUto4A==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
