apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAlicNUmdML3Gz9Iy6q2nAls66DzYmR+sdwvnrYboU5GIGsjt240j+qqrke0bLht0n8GBmBGIhXo7WUlFLaMw+yiWr7YMcKSPxLVePqpF6Vkk+0rigvqG2HdKY7cH9AL3Rv2PI3PKMBLN5OgBr9RHe6jsESEYq6gvny/WhST/QzBUhKcQyxKpDxDqSffwmPzYTxkwcXqphELSzG6Tr6umJWaZAWnKOD0tJCI13uUO45GRUOhdGSNAxaT7TD16sufjB9n0s2oewYmIVQ7z4zU5lx5x5l1bUVdmJigJlPihLdK/84qGEIziSidrfE7kxuJU/G1Vh95RCaw8MDLPArgrUeqC9pmxdZ+6Z0moMRtjjyaxNMtAdymnZRwgPLw9XwatkLMSn4b5zx2IuVQIBxGiQYqeIaIfSTd2ofkTn+lBvcE0tOvF0J4dNLzdvwya+2nuw8LJDoJbrdtOP2mC1yMl0lpss8wSYdDmWqJUnQqBXOw0Dz/DEbxyL5njWNaUdxct8Ed0EU5PTd4UYJrlhWTmqRDTyUQHlMDE/9dtO1ZiDSbEcY5LYDS6uo3UKOaBHHmP1ZVGSUSG4bRDl4cpYSUcrQrgM3CGJzdGlmNZvQOPEdj6Q53gmkmKmWynFyk7FZJDBa2q4d7GEK1hQ81WreFFEUSgnEVwnnDKabHKgo4j+3Qxxtrry+fcBcl1yxVfgKqkAYA5FreN7b66ZQXE8U5HpWIp0Yug==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
