apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-http
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCjcAuTh6+5RY1Ju0Hcv4c0MtKdj8g30wPlE0TGkA/uNWsXl3J737i/Csh8OibgQBiX7HschjEqtmVc1SIfFq5EDJNQGN+Fgs8139aoGYuEjJsI71HOSm+gFgrS/6Rr79VLiKQhAKmlJzdRgaDh8WEsR/BqeFbWo9tgIuqReKR7D6gvB7/WAC/swDwWaFexzGf+srGKGfnlEGgVrGjoFbeSQnCsj+2S0c5hIUz9lPuQKgysY/81OmwRZ+xNDTOGc6yw75WJm8UzU9IeyOKi5JhOQj2j10Y+C+fdD3qrMRugMseU0XEXfzYS66nRBbWDBmdSy170TOFB/wkKKWOeZsRw9bZtwfsIe0Kuk0AplsFPfqYi2q32VFtLelJmj8qMjdcJDAOp2pafz6dnFQhqBMnT0ELUT0q5rwe3mdWfevq0HT1RML9hhzCqq1jBPpwcyn3ZXHwjc8LP/BbEQ7AHb2R2lNTdmrBn8tDLKZqBh4s8vscs8hM/J+2xl3QujTS+EKZkWSWtFg4bc9bVwYqAb3T7MmvON+56hUjuYF5slB6P1ay0EWxUP9lRLxTmZDXv87jpmjZphlDA7Mg5/8BIM01nWPlveO+96kb9jPdyubS68A5xAjiJdu6PixcLcWCqUR0PwBfpDJyz9PK3aPh+IND55ikeHPK6AwH5LWRAvRfNkD8PfaU0pSIKhTX9Wqr5YVkDc/jbiQ71zpzOy2Ce9nogpH/zvw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-http
      namespace: cicd
    type: Opaque
status: {}
