apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAnvHGxnQTCXfH1c2MTOsJf5+X4W0T+/xKIACQgUKrLTGhp5sCJPelyTXDdC3FGt4kKrmARpgIAHjRBbVL/Fq+2EKSsg32bEycU/4aVuMMQSk3uTd9/s58TqxETjwAvRiEQ4VKA7FKxp0V+QGq0IcCYmi2NmqVH4tsD988uMu9KNybtHh7KHEXiEkFOq4ONaYE1Py3i0WNoxfloQttI17pERGuriLyJkZ0LBOUWS6jjltYpLsKI3fMsJeXm/mxh/8qdQfUTSoTYsKyZ1FFqt1vhXsQysu81H5ffyhsFROXzUoxRSR4KGrZvoxftkOUYZjDwHTvcDETZaKYWt4z40OC/VL02bA9/9baw2vzsYgCCx+xGmy9lANRm/zz7SQHZzvgzgKv9+J0FRr4dSBB7CHzOlROULswM4+0yOWCA9dV9uW1/hB7CUYmCq8IB4I5kbeoTLdmEBC3cWWQ6885zuUktQO+U3L5xxew6092tld59XpAXOrQBgzL2s2900BpW8SXIbtur1AwP2Mg9PxJpxtlAARHfGzwcp1LQz2cB9lmNoeoscSmuSJ1mrqN8kp2p/4P4n/CamjF+LoCF+/kQKvfLoVPo8aqWNzjKlQW7Gpy9/iG07YOXkhE7Ye/wS+jChG/F3ojOlx715EoSCZ0eiKt2oi7XnYjfg7NM15EQS8uBrcmITl3l9DfgTsymbYcYZ17NRTLeCW6BOOs89yqONSeMh7mNVw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
