apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCQYbL74lz4v9spTHYadW57w2bnBHtPkMbDjPplJbg1OjfhJdsZm89UMhxEeOcBYm41WbmtGp+83EqsWhic3MLr13O+A2NocE25vBSIj9nCetwgTojAZVu/BwIJn4NTf8hmZk/gHhpttg0DKj6TP4NAEzv/10xeHAeRIoUpwrTSTxsnE4OkeBRh+ygpi3Qo39Et5Z6FJoFfLCN5nXrkMurqJbRbf3/kyjXuW6x6xbuBZfs6iOX3JUltZrgPTknN8Fu17kuLQn5AWChFEVtCgJpm8I3597IMdy9CSaJ345BRS/krHYVeHvCjmj5MoL4U5Ah06Cy78BQ1/yTb0K2sPw8idDiZMNqecpNt/rRd4vvjWOBw7sVU6dRAk5K0oIddTjnZ7x1vLL6yhbg3BPBjqslOj0zWiEsy0UA2KWoVN63uVswKJA0kk5mG8mkACyg5Q8A5g+ev/28NJ7DIVLJY/CrCFmBxd6xBEneA7YZ5WTBa6jomk85uApyV/SoQu7OoAOkmHrhaYGuFXvd8Hs8mVBIscQBHyOb/+WDvsmERmbKM85E96qVgkkGe13QGOMjXEYS9sHHqEGCDOiVgVOS6kW1PadmT2X+8Yc6m853gvfYCI2CHkGxMK7+WSHAH8R9FJHMEmTYJnlhS7zHggyMe5pLpuwkWVti3E9je3QKwir3jObEvomffaqDJ8engo9wpz3IHrrUScpQqOK+v04qlXoyN+JKcGA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
