apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAy1MwbIZRkjSdbfFepVxuZw4uy8kf86S0khJLg93kfuPQSCLZ8rDGT5PhclIq64X5AzDgwmblggaVC67Dqo4P3bcz/5A9vlgrD1Y4IDaoOETOpvD6E2koY8rGhSlOt/bJjpWoiF4pRZwGsm2MDoSW+qWre8kM0cfwWYU1/9xCU6vpO5CGh9FaZbkEPWwFI6UQNFfvjp+7zqXKPmy7a1EMTDRAFnnAAPy7g5R4dPc0RWM1tz8qBC5gpWETWXSYzNpH+49z05EUhKtL49l1kd+pOViD0CxAj9Q4FfoYeoGWwvJN2upZZnftL3k+Z9FJ0rNpq8D7xW+Dl82SIeGLoK1mN/lhSXu3aHbh61iUzjYQh6qw/S10R0GvkBtQkxJBs0uZ1lPBzLK6FQN9KCtgvTvEF0lxlW8ANkoVIQJyU6qwRHH9myUcC5h5tRVCqXJEL/oWXq+Vfh6FBP9FCehHSJ3WQLMxMJKYA6hDdNfnlYaUkuYgYsqkSP2GmKU9e25+aawlGmC5/oM0hV0Kui/gE3KqFieGTFm0czJ+8PAxXkrL9mUp7Xe7nbM3bT+NEFDDY33G3XRnHE5brMLoFIwEUpu1ttyNglKfFRyHm8wvxYDy0o9b9sWcfe4yd1msQfGg07I6mGSeq4h95FYTNSIPiAHThAJWiOw1fusjj5RgalMXbYEMSK9WmYLDHxC7sHb/m077X6Cw=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
