apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA5WBBkibRMbDkwklOd56T31DHvbwdHU3EmrhVtBCilpbm6yiHZBMvc8idA01vT5t1RdCMP+4MT8a0CMiN0lEz6jlDFWdwXB/MbMAwa80Fp7PYasy8OehEJIRJeF5+qHb6ap/lavvTAmYqL9XEGmBEzyws5+mHGqypC+onR87HYR0a331sBNxFuOtbIspEJdv/6KTdJNPckAmMsPapUKepX7eTv1xojgj9NLVIhEbHbOB4YfEFZy0NwqzHzor+x5U0KrufjUKUdTufy0u3GjJoqMRIOpZRPIqgc7SAWezjr2uxK2hvHzCNJ0MCSmBttrQvdqHzN+ZCv6uwtFkUmViJBR8ZtfqD/h/LkxT+Bc+HXiy4smch87c/uMYI83QDqEWvRI5YBOevhZMuqckOSIZReTdyEnEDXSGsRYTc5MTYwCWe5Rso5bpwFjW0cVCqwp14uBk+4h48N/pXSfYg/wzhs/dlsUQI7Sh671RQHs/ELiZ2RHJra591GaFXqDT7g7Yr3HfNv/ropqG4denX4CrVTYWROuS+fpr4GKK7vPGYurK5CzVgNtM6DaY8oh/aZFztWmC6rBNCUoJ4IRi3Brm7UqgVrA9G02niaOXTKMy0xZdcgCfk15yXTmHMq657eHOWjCLY//IFoAuLIjW8z/ImkkjEN0XthCCpe5Z90brnFGTmBBLTZr/PLeRl/Ax0OuBaOnowz11XNNkMy6SyHv/50FsFwTA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
