apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBXjt09XNZDW51B1UmyRAeJ+YUMw7DE8AalTBgdhubebd+KCpfeHxgxpJNCkevj3PBjTR9spbt2YtlBSW4ieFAu7IWTmuDZ816Egc2cxIN5LtqauseBJIwcS9UIpsN8LAr2yViYHgIxwaLVfvuV3pAl4/xWSbHMPYu9If0Z3w/+Q20AYEmQ6gwNbow233ZyU1P32CmKd6PJqrMJ1EaZkiKnAv5pgyyJzYKl91BrH3QO6HbNsoN47xtSGnZQd/qP4GLmIYkAcGV5AwKnPkGwBV29Amj+573tuVz6Q5+M97EpWRAlJZvIhqAazKirt0hyIVLM0wRanJxBViY6LbFbTB5l9XHVJGooeChbwe2rZTLZKhPUC11mJaWWnjO9zntdb9RqIovkB7WTquQ+Jo1wvxKw+jWaM1mgRYVKNSpzi3OqjkL0cxsJchEeVG6b7FMCRtzoJl/WIu6ySCbK+NAnnd663K4ssObKPzULTELvcm2sC5oqxYK1CI6q4vN3ntivYc47iOs1kCF8Wj18aifAJWXo5YxR5C15BqXEuKLN08MvxI9SJk/wMSRtsW//cQCoddBN54Md7515B7ayum1PqM5icIfBqmYjy/hNITb0lQjhQhmGHHPu49vZUl3KD7t0DKluDJBuImpp03OtuuiRbn8tFPBPxCTLl2TqPjFjCgIRGDUAWvs9wmwajhhLYU7Xpdm4JcVTjkhj+k5kS/HIsVOe5J8/jQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
