apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgArmPxun25oat9AK1yUKcTeNlZCv0p4ojioEWUhxbChWq3qA1ICe05BFRYekJsud9RJUyo3mg004RcNS2QfFpcHOAV8jb2taQ7kC4zqIhT2GnQrFcuOfxO2ejK+YH8EpM9QisJe/3QwjWzJ8GItd6BHG4HgjtpdvrAcQ7A5QVypox6xmR2K0/Ydze8tGGWX4kjPz/t79C9ba8Vtf0WJeqJn0go44YApxFSPsB6eifZkuSpWfs29HPsJI/+F32cabPhmTym+e4kHkMiHuzXpohC8M13TbegTloBcoN/QkTDKUzPBc9UEoViKKmD1HzPkmhvrsjP5oCJ3PjZJj4z881PonS4a92D6Gb31mvIVoHn9GGvnCGPVZzqTjFfJfeL5bmT0UdjFuR4qmnkKfCuNxdJdYPQtTjpMvcjBkUeCYQmjMFMl06wzYyYtw4t8tly9hroSP51u5/qWfhK3OiqwLqVU2K3PVP+ni/560qgY7xL4AjEmrpsmlyEosGj1oBAMyzJb8SBa8MxP7owUUbUX7npVR2G16u4+jwS6iSQf+3/vME/Ir+szM4nbsCXZ6ZBGHq+14Y8LR7i/+DEYmLnQyohWGuW/dwjnRZ4nY3lhKXsj0cp7xceC5hF50b2Nrz+MFOgiW97SaDbd51snn4Xou2vyh9eLsb/yU/g+h9+FYb+vTmhxbn7QRnpcOhxYrCjBVmJul93UxB6brleDhaWXPXmk00etQA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
