apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB1iAHdpBuAbmV2ArOL3Dc3pc43QrAG1kwiwJY75KxQjepfW09mD0bwbiHCMmPQMaV7blgJdTSg99MWI9PrulqrzgbrYpin2h4+V32HUMstam9E0zLaWVY4pCfeg7q/AJTBfK49TjOesvjHA7a9Xm99ESUPxiVtBstSIk69eYbR0+SHFgZiXSiZ4IJro6pFznRmsiypWMYvGWwwKTb1K1fNYnxAaynKxdpJOzRqinFwObOk4y61YEBwKZ44hXldLSRrPdzr/3pSqZAitSdIDd4mysS6A9/CQfT8mS7SGmwy17jWAuljyhzN5novVJREvIV00KdF0T1mmYEhk9+1WnShouri9c5wYl4dmnfzSoz9tuGY68NPV8gURSwgwjZGTpn9lVdZ7vEh0HoGEtyThBNAqd8eKhSjSrfFC6M8MUjBSGGTwxx2MUSyUv2w7M2YqXfsyKDJrbN2xEoeRNMLN8wjzu5R7TTXx55D49Z9vUm5u/vY2cFSIasKtywCM+TVtC7BgIayUTPT7n6KFNEq0IEYSFV3nEMvG4OFbo5rjs83iarkp5JgIe4H93Y7DnA9QuOaGcOmVJ0QPh8lvmUe8wAb2Qzgp0iHSI241IzgcY+RrNGD1bUvU06JKO0zx/Od4GhpXN63Vu6nEQwZidRQB08faSLDWRH21HvB66gEDovGr30MnUWd8WIhBtuUJ+otC41dt31HJHm3xYqVIMRL/6sPZh+yOg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
