apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAipEIkq4reFYS2qnCCn1sLBzd3pzxDm18nBm10XA2GwBHXhwncEvOpw+LylXBq4LSwTYleCp7en9NnIulwZzUyBEnZXxfGT+SgTlEy+xKRpqFHb18yOh2UoFi5Qcdf9/GSv/iNhaL0B1bBt63HFIy10tyPba8Kutgdv3w45VEQvdhH3FwipkW8hUQ0/D7wXQOYux2l6PiSLT2URoY6W/ZGvGpd5qqiOyGmb/q/6QEHx0ICfTfKdv4AUKORxo5RPLFAuDas1W0+6IILgvHTs3Fala2e/SlYkCwCzf3j02OhgoTHqwhYiHYANLJ5gY2TKBvwvMyfVGh3MvU9CNKibBz0MTGZ873xZmQ6RevijqQI1JiwsGl6jbNLqjtNUwKllnQat7x+vTheaWq2UnhDsB62SPK4nw84Uo8Nprs04n+BYejHrvqI/K2+1BW+13Em3O0uQzBE1sK7VyZAuR3puVEJ/qvV3FQGEdMHwGXgklkI9xCHtpaf/SfLVRXnA/j2UByxoZMHLLKm2LMxMd/a4GWMBm+GW/m4BxDlgLtRprU6jhchY/zknrEoJ7hqwlTJo4x8rIIpfrOjd6bDnr2PoNaexNhcViedsSS5cm7nMas+frSFWHumlDlQEp3d3MRgP5EjfufsiUDb8MsgjNNPvH6nhgHZiSdgJq6XOWA/z+YjR1KMXyFgkMwc/LOJY8ViVmj2zlmeV8j7VlrdTWBbXMzJa+N0Ng==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
