apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB1WGuX1afzgt53Uu2t5oKDhUE7s0g794juB3TkUAjHDuJQdn4WTCGibAPt2lSoW9uykmXuE2KqwYijpk+LudwhUI2GPKjNk2DR7I+g8ANJuCpnhdxfFPZ9uzZBuSJ4N80RzUQ8Wt5ixl3NW4NvutbVgjVqLYR6YbD8blKA6J1vNmwfdNEmKfI11HJD24OK6H52i+KLgBbx8gWQWIij5dH7GfJcqXfvOTR4uxxGObRruz8jeEFWq5u/5T7V1U7qGUXpTmGrK91KJomwv095ePQVk+4zDyfWrRwoHCij5UUqeg6JfO2Ra5jIaS9pvpW/OQctolCdsNA+uzdMnH8JSp3y18/2odp3++VWNhmm6dNsB+mC7aYNw8GlkWkHR48J+C86BSJqg3Vyw3A5XFi9LzT+rlAPS54eoyLKONBLbK2Sx0LI4GuWAvHP1Pqg7MOnkBExKkIjm1dQKtA/u6nTEG07RK33CUt+KiVAIXaKmKY5V7W9CP+gsYdE5XOaSwt0RnuJrK+TyM/o0tGr1SjAClw7Pi/4TVq87CectYNj1ux1V0bFKeyxl7eYJ0n2bWdSdQPiQfW40spHh+0K0pyWzq1Hh4VJNSgzUCQQbzRvrji31gRBRb2JlgnpI2WFhZW8DJG/WTv0bj4e27AJS4Dni/GmvYZmEtUPRDg2yRiQ0AjLyPJn5ok1WZfBQksNNT6VU1sY+E4ghQNNl+WoYC3GDXdKOqKrmQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
