apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBdPgTjCBHuT2u7PYgXoVbTZxkCybsC8BcgZfRBOAvBMZgJl18hdw0m2XL297wE21KgxeA9u05IOPKlcfBvmE3Bq7fKKT5ZwX1cG8lkMvGidpqblEFqkRiShjd24wIjBYFRnvJ8gf2CcHhCMJcoG2ljKhd79E5aPIbJbRK6X4jopULMVZ6dXNFYMkMReoxsfvTeOSxC2DsgLG6n5TcnQMAlSf4iq17bjKAArc176eIad7qfeVP1xgZFfElV/s5AqJLsqmUvijZyp8r+9Njk7j8ZK3UB3aqi92P1Fc4r1jLB04fn/ry+p83Eq0WbZ6XJQZvdVa5EpRqtSvhviwSfhnYXsrasLw/d0Mwa4IdgmTYctEAP7Byyk5OCy++nJSGE0fgchVQ9CFK6ljnbtviuJeFAq0vaIeiH852qSeeyZE/AAwPBhErnQsayuUUZUIT83EKKOqiOwydKpy6Pf85y9KDqo5cEH5QO6V2y5TN4ruPnsb9tIEH201r//5VDwRz5ht6kjlJ2i3DFhEzlno4G0swhMI8h7xcOGa6gI2GW9gNUNZwUWJ/MhQ+vPGNxjpUM6QEOSKSQ8uu+OcLCfgGaCmgr5DzclUTV3hmfM8MQc5YszcYOrNdbO0GWS+HaDhuKdK7JRL2MYs3hMQviT5H+kjU3W9Bebwn1uRbWeNsNeGW6szKmX1SdKn8XwRaaAzUmWKRyKXZz6jTwkly51BuMaBLfTK93AA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
