apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAm3/kdJxHK06MVUdw60FaJxE7r0nGOq6TFTYLhxQB8GNShDWcqee/NC7tAFwHRKF4tlb5H2gxjGgaDg2WQifUEwDCwTU+/u/uayeCb0p8B8P1KPHsZKkFGZqIAn6bfCrvXxmVwyjNsK0ua2Bp4vhNWwslq3eyeF8XwINK1KkI3ADhbL0kv0n5CTYgWDyJE+2yvvyxBsKvq/e9u9iJaZmxbRhYOETM1zsFDYjyNX7cmjBUllq0GVVC+xMEI7SyrpaiPPtL4HK1RflEaLmVPocrbp+rsh2hNH7GRtxtdzZCNKJqrAYJFHHBJphjG20Kx4NGANMLDOnTSmawAPrOH35DL9VrhyCZ8TKsPhoIbyHoL0Ap7bW8xK7SerLGP9S11pV6hazbCQzyqj+juZmYobn/E3UYJ6E0GaSrisvdq3Gq3UDxWvhuzy2ts2wGnpmwwLDUJXfP769hJJKhs8JeAsqJeeX3QfQWWMO2pWOtyxOgmqyDVfzFnx8KgmaWHnlG7R7V4BZY1iPDkzEmOaqwn4O1WzQA1H4eiK00cGJg7+t0VCy84cVXvE1TSzC1ZcYNQ27MKI/h31DuPJ25PSsUHFbdt3tU756Omx/Hmr9Ix/qGevdMSCWbbfB5pHAi0SOUTPS3PFRbLQNC7sG2Ft7/M8IiehvZlmz1o1Ydp/7m1fBMVd5o4FvVHbc8HZpY2yrfplhBI0W2gqYPdYGEWq+ycd0g14JqtMg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
