apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-stage-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCCM3/iz5mA61hVNVRAwl4+zabQtDb9R+NLtPhzOgrvORMhWBw2D31F/7tVetE0Rz5W1Gx7EvTpuFrVNANTQkAIln7ADxQG9ODyg4V1pswcSaFq+5Mhj4y1mkJ3sxI4BWOLc/RBFyE+IXvCX+i6DB6Bj1tMd50JWXxMJPCb7d3ti8XT3K+GSVARZc5SntqqUVClAHBMa5XZvpAB+ZVuTJ0VZBUcPmsORbF2/4RChpFQYq0DN2qFLh/zpheKt36QgFXiz+s61l00/mZcg2RWsA1IH87nIrbY+2CIt7lo1tQGed4Hzrb+aDQgC6DsD2Z6etu9USZbq0WdQqshcGoOTcwoFaf68DzxY9voYsJl+pgxo+DZnIojsbaqzYL67J/C6PvBxQabwft9tiuMrlsV+1hL+o1Eneo5fKV3dUbAGKanbVRk94y0FhjuK6JLkMzRvIxXh45noIhcBmcoFB/Sezu+Jktm7AD8GxKWE2BZqragtSILNrN3bXFBSaL4CursoqGYXL9lcmqdwYnt6ck8zQTD0+DRBGFoI9LFfjxekIEuQUBqDlhg0oMlPXiO5MRrHD5e7cee1CMJ16dLewTJIF0STtyWSb+VJIgJD11qc3TTuVOzh/PPp6BXO46jpS2H85l1jKBmj93FYbo+nT3fihkI1z/EZ5238626N7KYHKsacG0FxNcrO8HKP2nFlhJytWg=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-stage-taxi
      namespace: cicd
    type: Opaque
