apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAShQaPvnVA8r49HqTUdRxjq0MPSgEXGKIcochfOlas4cQykV+auVjB4bIZcOJkbpBvlxKsetqVcujIYLO0zSkyuCCJBy/pL9+yPnTA6W02zN/e8d6CrR8kuac/t0LMD+sOJPrqjfFNfnCK6S+2+hjysQpy478SEycNNEppCDNCnHEikJVEPVtlcMh65bTx1cD3JLtm7nBjJyb5bx9MFIJc6V9halknliF4WwCnbNl+CX4quxf0jhLq9bu/1lL3P6oF4/4Wfu+rfyNyeBLoaHqer52kokFN/ZKptXI3yl1rkm0pCW60uZ2P9H3OWAx/1FIkg2bR5U1Z7MEYU6LQ6BjEP2oxLrqUYSLPYJZUOeJVcUAVoOHWgyrU2/Hd0bAJ+uWfLwcinVv9vdpZdyyteimP5ISPvrsIlnIDw3CzeMBkKhlPF9yWF2HvjZWUoKPESmfk0axX8tmau54aW/Sb3OU6kqREdr0aJDCodlELrqbnK/xUVgfd1RFqqbblIY2Zqj/SrQ0/+o0X6zgDsDi4/t6cxWGnPZ3qwvOiwPa83ihuNZM2LWH0B0041tXAODh8TpcGG7COGDNXbmet7stFBd09WGi6tQWX/DgOIEtkVFrmTdqeArCJAKEpax+OSqMEbieiWJYMkwA/Zi26z/IGbtaLBdMrUjVw12ELQgH/CqGTSm5zEK0NnxJPO7XE3dHiUkDVAfipHx9XWc+Blx9xp7+RNK8CUw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
