apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCDhDnP7UmabyC9j11b6fPjO0YBpdQoxIvBaC+TYDf4IxRINXXmPr1mVeYpgFWsNVCKG8bhzELl6Ri87c9R66RCnsESBSIvYTGOO1xW7OmoOZhJDr8UNekF9obhHO3TXX9mSL+z4Uno0wTJPzt5FyYrC6j48UpNLXo/i8satl3trGaXaIu7a/B7JkKGYuGJArSig94xqW5VOu+7Y8O4x4v98Evh/wEGMQ9dNajciWRKFeUET2ABsY9WA51vQmKpoEfR24sP5bo1nCwcmlGmrejoMTxE1sMsbrDWJC2U1yoIvH3WxAiOb8afPe3j0A3Q1sUWzbJOVQKXuQ3X00bBaDXVIY3NqQaPN8f4oIJSxkjooofKqw08Zksf8uOkeOIOnVqtZqWjNqEBKosfRzyW81X8ozRB0exgksgEfY38oPh33h61zEBAeqG5ecBRLvHInWHhANLN9ofFvnUhrulD8PmxrLhEo7S/UpAxIbAJb7YZKEcDt7mRbX1LCC9dtNwEiufxdJDTn+GZHwz8NyHOLenLUnqctRLu3SClcXVHvQl/AsHA/5M5zdW9fDerQWgGoMldwFiJ2SDK9erS0CCzqeUs2yYvf7jc6DKv0RL3fN/wIHpmqwEhjtd7jM8ioM0L86VHLGzKxMz9qFjVUB0lzo8xptx5eQccDx4Oq+Boua/JSewvHGuXtyD7rj/L8LRnNA/mlSu69gIe8we5KfxBn2rrPaLCRg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
