apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB3K7OudYAjRzmr1CCw6LrmshsVoNTNoRr+977klJQrh/xFo7n12icrtrnlvOd4FZP59T0a2vUWZSObC4qcVUwLURJxKAxgob0fRwubfUoflksXU4BI+2BhdGSirvPBpKYsRURCcKpjHG4kq0R7HU4ay8dkX3uYoC+Zphmq4LyF7Xp8ZOAAnClblJvt7+U9NvwhfBwRDWiK7BT6gOj1ZOTXZhWaTT7mWwBKZafOyxlpgeVfgcTpbyeJMg444+KYXNu/KLBbs+zzJgdrtHx3YVpIUszevURf0AOxo/uIfvawsqJbqd/b1VwtRXFlarGwgGefrRVVoRTvY+Olawz79OQXrLGhGd6QYynehHeXPtYGTICCWJknuqEJvMhrEHhZQ0l3O8/u/cEmWst8DctkEVgohbm5lk6otKmNheXPKfvT9ZHwENkxzgiMAO9QrsCVPKbPbC/8tNJaQguuVoHpnqZ9CsD9A4eY2SLao8pECGNUTEugP4x3rNcIkH7L/PlfsAHlnYY9iINtHyQWeVlp4fhc/at7FEvXY2wx08y9wd9OdCRMG1umksk7YYQd9TcGNP3NcahKkLUDFYUHRBRSaRh7e+Px+TpHKqQbPP8sNyfdrLtXgJx7gvH/JSDuRqq3bcN+q/7awGAI0VIGLz2iV+yBgAj1HH8ZSQHCifGvtD5S8xEnLHAkjPJ/ecXtKYfhoUtEpEF4Yb9bBhip5XfS+yTmL77r4Q==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
