apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBiHxSMf2+EEqMwPBqc7rXkDPdXhu5mqO2135yCTbWRPfEqFbmgPPkG1TK5WN608Vjst/BdzkaQLC6pQp7qX4ODPuKyMM4KxsWWXWYAUPCF/KW3gEtt7gqidMQwVtKF7bQwKyKuRwWfk+xEW04CUyyDavHuCawBha6bVnOsLxqgSLbNg2HjPnojTwmEMvkr8oxT+K/JZxKXM0NsCCqNe2/xgs5t4KKzG6Ccbn+SMswy7G/DnALgw2MoGU3gJ9GQwVRbxdMUfiahditjtbWimTcnjOn71SlkUqsYAJaeqiSnxwPxn7kbPxxMDq+dxHXrigN/qyuCGIgvqI6p6p901E0uFy7JzPr+a8lanyCKp4yrcJZ7wVki68TL8RqFlo13zVLeRj6m0CtE1FqljteuVeFjqT6CUOXbdCZ6xPBFWzN5SUzIsAH0XTcXdUW6DgITHXxdyFqyBBtHAujaA1IxDP08C7r9QtuCHOkidi79461v1K0W4vOMq5fVsgsuneXD1xQrnZ16hF03d/Ei1cd3IlOpb1vpzdqtuGS5UoXK42zcwEyYBeznuz61QYh6rgRn1ZUc3EQf5z89t2GuHBeuF8GfbPQ8LNOpZBsgcX230uHXVPsk3Y4SaERm+T2R8yYpQ+bNlPT7B6i8FN4CVL3TJEtbGwrnsGR4ov+TtuaL5AorA2ihkN0XQjo/FwyAeHXZREGKC9MXcfdtNhRVLAUdL2cCl7RnwA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
