apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgALQz12PIp6sgZEviiy2IcvEVyEzagK5nlutRFz//mMWMbdOXueo1P1pDIRyn1Q0FPB7zv/ilQG38RNj4VgTFz0LDBtfWgvWLmu5M/eRMWARFnU0sUvCAp4RVXM7gO/sohkuoqg+Mb2DX3PqHyPJV71x1HWXsyx3epQjm6V/y34cXKdpK2d7PZ6v1XcR07ofyFHgWnaCXWfM3CDEyNITBi/Cgqbi0LkpeNsfOeZfo9kB/5CeYYc06n2x64c8lXuNuz1Z/uGGmsxglksGalXbcJb1TZjCJC2GI0mR9nTkvKwRjzgDI2cnJXiVSD7kl20/bnwSZ6ulWh3lT+e59LQ5b2CTT0CCY1/eiIs847+Y5nPGFrbwxTy5U/mkyUpjeuSjGFbQEM4VoEe1CGVz6JUIffkNBgL5PKDSwSNROOlIep41t9KidSrPeSE/90fI7/RJaX93exJsgvQslyz5+osdV19hFnf90XAvvsVrEsJ3KuNk1Hn7C0xisivDnm8S8PSE3uo5OuO/JGeltxuidqzbN3YCxDEDov8gy9OPggDn7rYDeWRS7h8rhQ7BzXiOcfm7tBLO7Ar2UwtSo7m8ka2HY53ITcHWCEdWflNi9sPARosy4h+pftdoRrjm3C9RBDpJawgI4tOIpDw2VXx+ujLkfg7Og4/szoKm/O4q105cUDpW3UTu2b9PKZg5vrIepEwbQnfzPrKnzB2bH/EM4+igCs5E30o7Q==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
