apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAluU4d+2PK38HTZI94t6nutgL/Xi5qGCIvqo1r3WdF/GXuW1bpD0JRvNt5bdKI626hVFtwQBzxb3vGvh55qt5AiNzX4ncUb962HqGA5q3m95S3XT/z2g4kA3fUaKn1MkgFpk29fwby1GtxVhH3NrBQIJnKxytGKDMwevWpzJKveizeWStbCoK9tCpMWVLMuBHs4mCzNGOVWNtrkVL59yMxc7ml5vUACBkTOrTKJ/pdeJjNlTsLZ0Z1OFJLMA5aidWXFR1dlDLzHSEnhqtrSYlSo/lYRItYYlAP7ixhLX9Ynd+TpC28/IAU/pJOcXS039QmeJHKWYbB9c/LoZ52coHeJkEp+90xfXHntr+3jguS57S5aduTZdDOvNaPdZQetAoDa7k17cIUcr00ZFy2nUD1P1X/vQ5SCWmK74E/RID4sZv4xTtuOko4RqtuwKL/jq1fBGjmJhRpcDU6h+HbtU2FFCqkEbXKJ/a8Q4oL0pjUCmnBXkm0QgLx+g1fTp5jIqIMw0LmBFqaXfNRFsGEdcbsNCqGvrlP38FGFLlXTLx0vExOFPsduvaiyP5tjIm9juZUlL8ADY5aWjyRTblF1UKuKRjqVpvzspMQHx/rD5llN4bg0KBSxzikuPx2+VhTqO45yU9eErr70f9QhBGvnW7zpU8tbcC/AxkSV32xz+CoxXyHSXWTp51T8X6BvKIhc8NPubU=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
