apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBIF0gF1I5A59A3UVhSAWEaSwaZHaXUGGhOd+dMzNzaYynPb5KVmGYAIcsk+w7kj976ATyDm1JeC1OSC0p5nXd9mX5tpr3DcVjFmwEpWDddcng6JC8aVPpvCMuRcISccIjSqwXpIR19qu/H/8mnEznu3qmYAmnebFhE7xggnoGRp1fGfYx/KfZiMMtwD5e7hPm6l3w9fJsXtmof1ATDc/eQHpv0mn/21wo7jmna4EZQtf2baARktdIxyhalq1WIGulE5NzoPD5mFs2xwkv/5z5o9j1SFk2PdRfMcis9/11rErxhl7E8ZpniwCJFcoZWzaUD7mevhyQrqyv0b8K/HjXumcMBC06QtZXYA7wychA9JS4udnQ8tc9r/EN5josVCRSctjkzesutoCNWkb653hyJqS1JWLE0B/AqHJsMlYI3s9KQ6dfP4BSyQfxB0V+erz4wPt9Ye2CNPlxaLQNesumJDjTo/ungwGmL6EHEN/qgqt8nsJJSYhnV2I3ROf/J7IV7QmifJWHRTAtWOlv+8PLUf4nEEq+TAQ++UybSMX2VphGxrsD7kNmtwNss1+NI6gPC5KQVkUmYrl5++M3GbX8BNI+pT4IU4e/OESy62YeKqiWPvSbk0ckz5LR9fo6IAm/dEZpyP/RNB4ir8nk2UcoRsuJYXa8vdmvBIjw+5TxrXrMtZH2P7brIDsNU/UBV9U8OzZyXNTSY3zm1XeFaNKXa8S3XhQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
