apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBqHTVn+RpGbybGRzhUc++wyJus1DVm1tChlx7oJRbQqcx/q8E+CTyVROHULmyLFqx2quN8mPFZyw/Y9fKu8BKDNaGDjxfZENLPx7H5S6MybXyb1QcQf8FvuvkQv5Zg6tzzpPx7GI0RgODOjxzgOIBBeMBiUvP+rLedv4IxL7zYIn0O8o6n+gk4UcuOgVn8FfrxZEjrgV/1miTSLRhJNbEVVM+JgjZ/7Mb2tdfRyVOwLdKIx4Nne1/G+3kqgeyn2eXW7qPle2os28scaXEkE0jJJWjVBwT4o86F4tYRxytz0Se/dvgIO2pu9hqp8U6N+fQ1jrRyJnGgl+1TuWLMOZH1yDzzji8M9Vsr2uL/pZSlaANIK/R9/vYV4UdUVUKmL3inZD7+JUqw18Hm6q1lmQRazN41NgzCGW+OAK5kN0t99w649U2Oetl/fqv5TfCh4D2RKhgo1MtHmGJMKG/4R0zjTpllZoNgZLMT7uhT5gilABIaCNpjRxiDLeO9hYzvKtWLS3XS4sXbM7iqc+iyFfzLXmh4/LxDJV1tMyUtjVec8hK0RK+9ga23VQ6lRmcnjZmyHpYh/Uh2wSMun3sW69umL/8KARTFP1udyJv4pevLCWpzdJu/07g5DhhZCdjAhNTwgpehrdBtaXtQgb/e6WKJah+z/X5KEND7uZRWm1M1phfvQHo1YGwO3h4fquLbOFkXb+aDmX2qLrJZPtuZA0jhvAlTsg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
