apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBXxV60zvZq6qNTPsvOJOAdRU132h/N0bv6o4/psVXVrfluSu9le/jSUbDR4YWmOsCmYhzPiLi5OTpNXOXLDDJkyJm+WM2qMqxQCXuSFkUYdIga8f0ca53/3yjEvchHqInDIMlovLap5e62zMQk+Hnc7gKxu/YDb5+Uo3TvN+0Kv/G11mrljcJ0PdiXJVijS86ZjC1HfW3fOstSx9aNgLTtYJZ1A+58kbocrcb0i2PIv5Ei8aGrt8lK6sZkelM5EXXN0aKEjed2WXteWzd4f4dG4SmWspVPkJdEUgIrSXp3YMFBBA6ummVXWHfDJ95O2g40DaRmE1mzHqV9DahsXgXjDFdWz7ePBfqLdDWNvEa600NO9Kd2UV5RKWjA5J6y3qykYlOwPzjj/cXDpyYgxovfsaYKCLXn7hp8J6LFrrBbpRUraUKi51zpdwVQaeAYRFHBpfZSignAq6mffEw1LgyFZ/lYYt2YMfTqf0aRFpiVe+oZJAAkcffRuf/ayrrDFeHyGOiT6Q1CQ0XVdPRG6XC49w5RHcyk3Rp5DJic0fJHFGbDiTWS6N/AgULrVKPzwWYrpVIQGp2nIjH4H3AvsfOMEPcuKo2Z4jlJq9AUkWiFl0DK48QLjpPV26VpEuzQbHHxhoKc5gSLmbtsOoMgEsI7omsDAQ/dDoAM42Nn/OwsJtQue2y84PkcpE1JiMCtaBNQr5Q88lAkW5C0y7Hj6nCQqlb4Jg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
