apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCsCtuN3g0Dim1AMriGRaJVX/ZdIyHo2uo4B6XtRj0h8fBht5OoRWPEVJAWgdS2Y197eAFgFsyBhp0IvK9X+V1DQndDhVPgdfT4i3GuXfa5zyy3olce+ZosemN1x/Hg7eL1f0acGsltRhXce1AFFNQKmEjjcQlxkT+Qx01+2tyMDkOiXyb885Ua0ceeJZKD7RUobkau6TYTzsNghp4Q+E+lXe9+iOP9nhxzHReHT30gFUdWjgV9IWaOEA5HCezYAOEO7djAoElCLU8YKTj35WUmumDjPY0qGxu2HCOtc6q4ymdGnT6lDZ70jCGKE0dZthGiPYiZXd8FPqUYmadE1BncMjS6jG9RquUUm2BpZKC8bYiy3iRN5rRSiB2WmVdPqBeky2KNqvOV5eLyctbj36TV+2f7ItBA/Q3KnPIwaqKXlaovBe4UxzN63iJ2VhJjpXGfZDx9fKJL0xd/mNS5ylNNzSDDH3WNZbgcuTANP+kF6+2uT7Z8cLdHpzJqzp55O11vrTYygdftDEQ6NKKp9kof+A5rRzWoITng4AYu6EPfwYa7NRt4Tl12z1KER3NgoPW30gXY2eX+s83kN//IVHcyBAX2M7eBwsioOo8OuLl7JgcdnxVbxdKfpIVCrXxIsLH2jW0RPC6+dHleyCzrZFidh740eKTlikxM3asglc3LqxxSnUpBl4ywA7T0P0WaXuJNkgY963JHRO6RlxzSPlmuIedLHg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
