apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgByQiZKinfNVfZIRsLbJh/C1edk8JyHKIJG82FbMEa7x/fKbd1A5lSc+P5V50iQ8Nz+/IucS7IlgAH/iTO7Hze5jhMUDJzkTBNrQnX+EQdLkcmcnpbMzf1+nHczjsWjIX7HpmzAQG6Nf+hU7WJshgR8VWxxuuzILJ5laWoB3vVyE/Jxt6hlu/5H4WjB1PqV00ohaaOsH23nHbsnvysjuUSjyJxf+z50ukdA8maJmxHIoZ1km0hQoV1QefBCPNd6LzUItBsmWlvsuRIUDoSezdyNyuJSN/vAncjt6cKuh4Xf185EDvMoRQi8DC9oK1VGJZpX+55uQkjSesdfhmzw7cjJy58nG056Sy6om9WVnYty826yEaFyTubnu2ehwHmDDoklMh2IfWVpP6+uE0GsHi/6e7hhWbenlKmla2e35ZiuY8N3uJt8I+WrKXBgnmo5X9efUymVcCxA4dPgDRpBcsCuNRgEgg8cSinO5Td4XyLRLRkYSa7zww2sffaN5d0fE8Wg5iGZ6I1wSgunknnEhk8NocuYmgiXkRNdszo7juPMoB2S5vIPP3EzcZT556XI0UhMUD1/1YO+Inmu/A4zKJgnwv+5tcYaBjE0lBrlop9iYx4GdfL9XhS0N+qgrU3aFrOZGTNowFiUysPTCWqKe4mQg/RFLb+0ZET1Atl4109e/aMW9Fa38zdJghgTaqsteD6O9RCFEmkl5nLFqjYICtFR5lYQXQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
