apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC3ZEcdqkgaZSHEPX+2pPmSPl4PE2tPvrZbDVCCEEUsczEinBtE9+y/Q4hO5POEP9fpwi3jb8CeAgqYMwBC5tXXdkMZ6S7JdXOrn+MMLz9sQYd6C2RPtWTNOWnGUeVu9qq13wBx3fRDNGs0zhdEj4IDPYD0fxFzjzX5Da5WtPS4OrMz7Efas5kUHWuBZVjG7dAmtm4ajWNjAr+fS5lLOEBbLFZKn4ARDcas5SW2xyvNDpmj71UWxL6Lih0zOaa9ZN3a0ivaxnYp4TiszAMNSprzM2CrfDQaaBc4FUQjYr8yIV1LaAJ2T1o2NiEevCPqTTjgMDlhDNRJCtoq2L/yC4Wuxc+b1JFEHQy9xN5MtvuPGg4ExSnL3KdljeUTzQZXOljHLEpOpXt79tkUYgbkkAcsOUCHslLxNWzr+Fct3bcd8ejRDQvJXFKRCtjLe7ORGlAZxjElKEeWCAnG0E5RVxw9f6ISxa5pVYKr2CdEPGtzzISs59DMHchXsda6YU9o86vhNFvWptR5rNnEu9U/+JU6px2qZ10kzNGjuthYeMOpFNMi48IcA1yEbAmpFYSLgYk+m+7N89TQcH5zckKTXG94yXxXjIusDjlk16DK8rSBssq/Bt4ph9LU86gtP4dRnndUfrvVc1kMTZs6u5nJplnPw84qWimI1zET632Uo31cpmPlfNH2Myg5jbY0RV6vW/6EGy3A7TEgfpaS6MK85EgMzsjZsw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
