apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBxd0sbjl43C8xsd0P9rVS8DVbOnXS1SlLGaUe3aXXkw/TIC4gJT7+ilDOSuFkJKwsN4AGTrdv9Tx0vXFozGbUZ9B0BkyzpXMblA7/U9N1Ygeep4FR8FMlOBrDEDmCpIBesJ1GfIEm7dTdFaY6BcChevYggki8iUTBbUNF8LeMyYLgL7D+Prt+K43UQDH0HjEphA/e17uAjzV3LkCd9yOEVj9JtafVA85SCT0yBbpWyvPeYud9ink6r0bZ3OsyxdFyPanfkqxGfh93/Q8LddYjFmvhufeGch+mhWfomiWmMb9xMjZeFqaA2MFNXE0upXWIXbtD79Xn6/JYEQLglwrTLaiAcPqlclIPONjmWE9m7+zocU4IFMYVMhcKZVdwN184dkZ8Vo11LBideEc2yEMaQ9+OAPD2hO0b79MOznIWdBRCRjaT8x86c0CuccT/7peZSYyOWhD9d0R4heMp+dPO8dA0YOLjpyQKTZfUmxfdDvhMRbLPUPzPQg6SAzkCZHHtMSBHdaKPuOPxIhaYNtoSypOMtGuRlVkg4huNIw8jQ/ykTsmpjzueQ3pu7HUQZP3M8epBNd23naTA9XU5+jETvXgw2b+UyGaLXJg/TvRIE/+Rbt2+LTry6q7XbdmHT4uQukedanXu1djHt7iKosoeUZopEHi3Q+dzpjIGEkD8lkVXg6fv2RiVHfr4Lb+fqc/aiwgdVIDrfLbDfcYQHUK/NInj8RQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
