apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA2GrJ9GwhqCrjVUqhFILnaKcsDJaA7UTlYHDauUA0IgO0xMmaFnl621JtJacT5pcMQFMHcFGtmUFM4MP28ZFzp2sWQf2R77xIh2MV0Xe4+1oqeTQi5AkO8FOHJczSGmRm8qVrCyOfZ5bt5miMfj+E3A9QNVs6u60zrNb0lc+ttxmGau6NZLZu7eEeyUjX3x5ETjhLg81WeS3dJ3N9Effjtk4o3/AOMRPGLBwLmkpnCn16PeUkRST0IEW5Q21KDK9tfQxvo7GNezjhwup7cLgRdY/VMRx19T4usyLyW0nHRZ8AueoTrn8h0d+oclQMjYJGiVCUVGYqYeZqBz2+iBjmUJP/utDa1tlPYvYvYr6wDvac+a8IhlDZlAsKzxEnxYtFJxDfG0YdJ0Bih4uhwrIWT/vp5ehemWXnXLUPAAkrzfiIo+6AmbIMOEvP/uIeDGPwwts8BICUTs+nhH7UKVcidW76Z8L9XEqN5q1rhIBOdgBtr3JwSpUscdvGrd6Dk3pTR/m48BVjR04HNkqirF8IvTcf9wwj/nbvScWSmuR5kLYLx/xhmh8V5X0aCnEWoyXqFBRMEkemHXh1UUrfOMjuyQibDWmBM/wpX0MyfEtHxnsDn/g3LKDMWwDcMM6vFuYRvT334GncLGTj6P7wggwVr5GW+8ydoZeNugy0sk/PrlmoCAniFUkZX3/wQjqAZ9HhDOXu4xF1D7sEkUdJtfhPe4SrPfw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
