apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBuCbPRHSHu5AV32UVLKN47pD6iAaErRCVGwA2RgKuInvi3dlddJqutk0rZYxcN0ownY+kJWJEmXYkOQtFEQ3ohm8yrOgF+CC69owf/8rYPp0EGmD1BX5CelSeAQdXciiXIWU4hMKqhfi0kG6AK3BZDx9gOVHdSNG9h7CeLOzgaOWDZJ+3aKVnGePTNLCp75gg9zbc31IIBrBQam7qoqxTdDeOHFyNeoJgT8TBuRF4WAS7YKOZpjD+2KQ1nRQhvpjg8lPCjC4aeZGwYwg8bJiGLQYctVHZCP1lcFO9gqaE4+72opkfHgJy7IlEA927scgbQ2a0EKsWxxPD3zcRdr2p7ibH/7C7F5qSwp6xJjcL6yYpLky8aANKdwYPnf6TrS9uDWZpJYYCMqrdL9o0NDIYVfR39dCFGBUkFpFcJ9nM5cyRjmBJSqClBi0tg3BlXufp9wBbecvo7ZvOdY8sdnRCsZAgWK+VCjIwNIs/Nb/efNpGvNlUiNq/HaPE951A1TjdaadzRooRfKzq9QiirFKKkQpGGk+TP7gIrfjL1wdeDCkf5+SlBmwC1no2B4hMzapb9oA/hAWovuys6A7+hXl881VBdhdW3qS+ilHkYiQhbywJSPrqU0jug/MBVRDLWVcVYQNphvjwSyEmXKatMacq22VVCp1vrrjA0Ih/mMcihjaBot99mGmwgkQphn4jn+QME4I7vrZmRMDzOrs3cBVT/iPoDUw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
