apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-go-server
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCAL6KiuVwB5BPYht6oDiuPiA/HEcAaGoziwJ4r5TzHBq/hg5BawVrDDMhOQlEEGbt6kxuGWsJemZNEJijodZeOOcGu5VUsc2bfCFPMh3bm6JcFkujiaQg8T7aouXWkt2IfIKeybqNI752cssyWEGd/47+FmRQPHYL3bOGJXqsBwwkhwG0yUaOLj04UKZQLELqQDwmuxXQVbNTfSWsnFOYSOaXJRriklPPBYJ8xRyJ8y4P9LhoVekGUquBDwwTICvwLmpdAWy+qIbz2gms82fezyAer8eRP23/epI6jaQluTG9p1Wb31aBBLILhGggmKHv+QCDcKRVUMQDLKogTgXA0H12Z5FjZBvC0ZQz+nxkLCUnhFIYoep/Nv7gqk1usRwWFXPGLejxBD+x1HaOJQhdJO7nQ7zF6WnxkBDVqGaa2gSpVRspnc9StFl27qPKSJhGisn3fxWazEA1gz4+uGrSe6yRjbKE4A6tnu5VCY7e49diVFs3SncSn7SAv2ut9/Qh5NiF0Wf7o1eTwE0Ar3b0o55GiqtOowPWPC12Nv1g/6+GWMMsJlzthCufOe5JsQjcio2h0HujN9vFaRPhvql5WLeOGYZy/da/5D8zM43+so6oK1lYLU4q1macchYkSq7Kmq9ZdDXf8mNaASyChdGPopcS6YRi4TFgWV30MxZXWNEl4YActVn2VJqLAs9COtpJ5KcCAfXfvzEk8ubSE3/3pST9hfA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-go-server
      namespace: cicd
    type: Opaque
