apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAA3qYyx9Ems+tGEz8K47sGxcVuKvgc0TCy2faTzF7FO7aHxR1rnM5z9kF2EyGLLeOt39JODeuA5I+opL/+Rre2yzfbPhvCLeTn+CO4mzBANEkU6EZhIUxZ/OImN5lrGMr5TykUPBkFoA7898xZm7OlzMTEpBy1WPF7lYQ8xpPbzQoLzWeHZV756YO5rWVAGfnEwYUlb6b3BNts6mcgXiMmSVsHwr0puZIBfBh4w2y7HCFYbcbvANqxGo41YrnmBRbAY3OmKGIG4hLuX7viJ16qVc7bxudfrd8m7bDhNcQPb5M9wuQz56xoLYLWp4XAxBZ+Wg3S2ptO5CZJHzQuRwOVo6cKeQMkgNfI6OfWEjpvPZTqTyj3HVs3HKmEQLWP+WbAkReugdcQYVP7GW9F9fTy8BVppBtXSQe1rUnk4Gj9JYWRtXAjqtR91kD29kHD/lVy3o7u2Y5Lgsqh+z+NO1gGw4KaSo18XFJn/OOpKCRm7qgv8/ZCSNLGocKU+zo2oH7D3sw0PhRE4BXQ9N80mHJiGmIC/92/TU9R5dO/XfUolsqCfX7uUe+8VWoml14P4TgQLRo/G63izA+l0q0LqCoNRujWAU44hamUeAucZ/xjjXk4R7ULbA3/X9Fk/H3WN3S+nDnugwk2kd4hkUE7caavoVZ0/QJYccHZRKnn7wGh1Lyz7Dmh2RJPJgCsTsZ2VqhzV/OBnITm0XoWfvnFvIjZYE7QHA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
