apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgATeFH5D21bCFxzjMa/9zQk1La+S+371QYeiskj4aTp+NbaB4OIuLbKHdWKreW8XGe/La5yUvTCntfPOv0amgnPORyxw/qt9qtQPbCC75iNOaIez4bZbN7jyQGHpwRvERqj/IeD33UMmgCf3KR52+5qBfrFvHxibYfPAtHUAlac47crjvYNf8A6PalBJb+k1fTvtJ+UOYxn+A1JvD5GXAyDMBO1bOfrmqLPIA100gCJXux4A4CzSWj6xBIlNGtAVP4fstG1nc2vJriB8EM5dZgwlRC56TBrvaITM4OS049kG5B/KWj0IfRWTr86OmTkw3I21PcrIWcJGY3acApGNo8+AvONme7ZwcRJlpjhlQjRN+uGQloYm1zawZ/92Bfia8vRSVvJWiiJB73C4yrcuinYNY1pi4Tsw0QUv/ZY6T/hCQmDebmL+6o+idjmqbCP82jXJk8+mEO3qfLXzloe0yImej0iN2PNLl+uz67jx3lh9MZIjMlc4D6VslYGxZ4/C/Qbpr+CRWyeBKAm06wfvze/1tsR4LbTki67MuMH9p6RDfDSOmjO6462PJ8tXSHXpp5Lk/NpFz/n6pqQgBSCLVLEepLacaJFoouaymtHKNASvQtDAK6tdw7lvjIhYUi2OfrH3AckvrGiqJF8QSUuoFfv46QRYI4Ekl5A9q9ekPBC/gJNsta02+bvmzIHmL7mwZc0HzIXHJdjwlmfbL0GlOy/8uV8sQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
