apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgC7zLsbO73niLPweV+aaWmURvaKWOjsDRHHKdVLeigCY8XysCGxiRugOhnue/uhit5T+QHMHbODKslpVVF2GZWwYknsujjWSAxikIn3M51rrsUDIeLKXAjv3s39aD0pcF3c2t9FBDQSCsQxWKkzfPXOLFu3x4y6gYS/jrTn+c6eo+8ll7OEidvD+PvzzFQuE7DsKYsfJEH7zabcSIrE/RgmvqFIv6g9gPblQyvdi+0jk9lGh0qz+kB6W6Jm28//6U5Gu3Sdb6ixqhZZS86qq7wIWBsI09Cfv8iMIjiIafhGV4p3yzINQwwdfxz/lPQbcTnHlb+ZwrUy2Mlba2uf0GjbAH7VSjptAnvlEA0yVi3jkz8JmhL3hZ45kL7sOOkbf0dQimKClUuuqrNPzERw7Dx7K4oD1cquQNooUeuqrK+Q13yVBKiuZPVE3D9c46Im2tI0RGSFKtQ+LP+h1rkHkUiOYDJReyrCLgzxiPiCfgudj/7EUvtrqSyFWa2l5RqMY76+0tpwOt2zUr9ZzaBTZMTnU2Z6vj0++fh8WglIG8yok320DDANyGRUMX18IiDEQ1YBt35+sQMJZr1jYr6KQDEvEC29oLDh/xIOaWJ1rWh2UVGnITL6rYXNDa30DJ/zqDqm9QKkKsO3WstK4f5EWOfR8L1B25//vc8VO2SlRJVFFrhKz7fu4jz/SK6qlSmXlqS5NNa2+VBjk+mlnq4pLrEgDgSd5w==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
