apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgASg3k5Hlmur8kX+YSkKljtWxviBnKUV7MqIK/C5CTvIk1shmeE9ZEENUrj3t1VJbc5PHr8qOMD+qeISbo/MiCeYF0xMnWy0vLcUvYj8MfVwkbKe9E/CpbV0KU7nCSTm55ET2qgrc/ChMBldaq+oc0ehu+WFQIUJByk1xMrv9Uj2o1EXkBUe9/M+/w9SSb+z3sM0rYotZE2G4P5Pv40eYvd6iY9VrM/hOWNtidUUfxsvtz7E91Y/HvXNB7c9AGy4mxcHoWHTDqNQplUi6FiM5LQl+7sEEEMs3Re/jkSrtNEz97BFEuzTBFk7GRaMXxWewJXnudApKvWp7nhmDEgKhC/+mtwvQjMJYzcGaBxUne+PobYEMXWi25loENBIw8FzokAMSyhApcHVJIqL/FZde12c6jV70BipMiWA5Bs6nNkeF2LnPF4kcFbXlfqbjQdNcw/PUBjFkMP8QJEChyu+iYzKE5HBC4Mwgj1gdtAfh3Tk06uAq24Ov9kmURejrIyt384h0xoXFy+iq2bhRQ6YvtA5jDGC4U6cuCvvXOD6p1GhdUsPjtjlTw50nSNMzmUpVTefs2YY+P36c5KY3mHiU17smWEO1hk3WK/wfI062lYfETGjyoShKg9BPAUYWb8rsFEooykSX9AZkFpQQXHw6IXAQFlzLbhon7RszWKweURG1eoy3i9R0SbCbHK04GWWpQubDh0/I6FtHa7xz2LA5O7c5II0g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
