apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBdf4lDCaEzUMI5UynYAV17B9MGhUNoYjV6ExGm0F1nsmvMvV6+AM96rr0qnG+vVwLWFTBSINo59yHMWOkoRsTW9S3KB+SiqpPa0uwRZBkjTQwu6yYVQ/Ccb8eXc0JSd5jgZnBYSzKin0kEAABBKiz3QAa8CbAPNCitIrWPKYfBSnW5+HWnkKAboJyLk9Oydiz/NtpBb5/flMOe8x8hFe0qFP5Scwy6gx3cO72HMmNnDLiYaghPOIvkSOX1Fx7eIS1why13NC/XTkDORqrycSI3hB+l/hf2WYt184aLZMZFPiRYS0E+yNGv7Q3P4WCeNn6KwF/gsCl5AYNGMdOx0j59ovjPu+A+UT150ygBI+rpiw7soYfwl0eyFuvhSPZ4IjivyXmAqWbNWJiSBUJHtQo8qP7403ZCqBoBXnp5m7k3uTO1dahbb6zS2HSv2qSwjweWJBkSRr4koE5cF7l8zeoG8kkp0Q1MDjSl8fhZY7+rUkOzyTwbfONGpWIF7sa4H3gWW1KIFYemYtr4QOR9Chzep3thYQ6DwDxMxqQmThoqNVR7p+k/BSyVToBVvW4tlOAksvSoXJK14FgrJ7BasEPCW5yyB+vuA6fjQBKB8Nwk+Dyew5pZRUtoQgWxbho1usUU7ML2BpCwEv6zhHOR6g22OzP9kqMIXBUyNmTeTD2tnp4iIdCU4db9uss1SJ0HcATwjozfqs3BinafX6hbrzEApdcW5g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
