apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAXHj2hzdst+qauFIqJZN9PIpx2XM6Hln7a1iLFHPE9P5VBqlQa478z26ZR1rFVeSfMzW+vIFbNjJ82TMbC9c+QVNNMoWYNiITB1iXywX/+2Nduw2B/dK06S1fR+epvtQjqyXhlsafNN/mXPwcgW9j0Q8/YxM6QQljq+WR6Qu0CSohtmyjLB1yyd8Z7a9EN72WYipb4YV7UeFtSHfjeAmgbpDaVgpnZyH4yz4Jaj94Xc8k0+i6Peo/6reYowGIiwD8Yi8EABrIbNll2oNEKPB0esqedWarI3awLOnf0Y+N7c4IkcLyMWXmina+dmoP7Fzhm5ujRS/suwbLMRJX6QXG9dIMXjByOn5dMaP808yzf6E5vRyNqHxPA4QTs0nYT64TnvqjecT4+S/1Rikj8yT7WkFy3uD9/HPm+TzYCHh7/IstpxSLhkmFx9pBoqAOApniVovsoWnrFI6Ff1styeTbBKNjO/7kgFL3sualBbeixn7H3ccO3FcQdugKvrkhScLX7TXFqbWtlRvI0pjBmuWlBAJGNlnQgl0A8AsqijX2it9hZmTrZWKKcAlB2dbCJ2023r+aMlhL8sh2G4aX9LNTxx1yw8TIsIhCCBq6ULC3LZzvTMm9ePPNv1iiYCBV6IWBCma9DYazV7uFjw7YI0azv9eM8jY1E75FemkyctIc8TAYJQdPPxze9FB77jJkkY1J8WDXv+ptB67sCTsIRbMUtbca/Xg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
