apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAtLlbkC1UwKghWmFMcG27tpYUUzHpQtCfetrbpccXirm481QxgE5LLlOXmQ4hYY9b8eIebv11GXXrKMPVEisdht3oiqnxrcpN1HWY66l9l+fWVGl4MNVPicFmSz4pgf65C/C0FDlvkIC+I5UiyttzeRgiyVgDeFechU7rbCAY4kSPSrdtCbPR/r47mHcQ69n+KxIU6HawqaJ61ipWt0xSSbJfcYXKKstTqcLjuzTN50MGqbHMv4w4NybGJHfmmtyDvTmMjXchNqX6bZDyUqB3mtUTsFExYVf14Jn4cc/IVd9c4PzMmXE8GSE9GPxDevWRL3WAvN3zTp/ZddTeeIou3oODnFfbzBs6A4DNtEcXCWUJDeZncRV7/jh2ziVTZzkKrH5wi1oX6pQ71G05nZWkKkPppKB8aok+sv3qCxV5kGh++K0HTETKPG9/ppqylLOKZkEs+zdsA2XeApUVaBPQb9vzvYPHS/M4g6mZbCd6hRoKRHsgWU+VUuHf8d+CKuxVDKctp9HVpCNEr79FxCqwPsF4B/sicvb+XKDH9DMdx9jxkyG4CqaQB0GTimuv+CYm2jVp8nR04vG4Yd5kb70MY6lI1E+aQgDzQYff6rq8HR9XzTX/u2IN8CiG0SqXl0p1Vsrt2yT4fWoIipfS66+VM4szYsEcQQLJ6P+BqTTVKmTMCZWYfuARtSsakfNpyoxx7i+N3SA4rg2g0fb0sPD5aO+OXng==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
