apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-prod-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBGWLwKlL1SoR4toEThP0T1KgSn0dwOpGrHqxJ+cRjt0Spn7+2KLbwnCqT5gjaWR940H241LZqy7PBfsnWLVoq/PAhIphG/vDo+IlxqhtYZx58sVUXqCdyRfpEVxhtPDN0ccsJUecLyUexF3/AZG52mTegOWcDflHvG9pjUR3EPyFGH8S4VKYZ+Z2uySQs25OVQU1WcfAYiLiRIb9+cxiGil0cv+V9t+YySPrHpun8gRhPAV/75k8v9rcKKoKhGyh31+zZfnCt5VB9DnZRQqikix3aURHQZvA8nMOMTqgvlqZIXH5yqjfLn1reaNa2bg6BBIBqgQfDO46Uw4lbUSfgARiydwohD2Pdka/EHf2hMeMES6IGrGqaurmxVZU7/vGIIkGWgRgND08lJ17ZicRFi6d9PgpnSVutXK3tSxyopOIXHH8v/DChZ2v/Tw+McHM3kEqH3aJeP3kRgMMkzm+9nOLGnedr+Av2Cuc1/eTFAJfxHhDGiujpMAGYenSVjQOo9BgKf8rtmOrTNyZW4V4B0aIXCS49GUSPzW6NY0HHL01lldA7kjWsbepddYBNC5nv2iOfwkwrkTbvnu38iAKoqwboO+69f20OhxmXD7tFnJBouVN9rSql3VIYEebsDRezMUMdGD4RqTcem+XqSJvZGfyxt4MMX2ERBRJHtDkuKKz2IhtsHh41+kWwgPfo43Yg=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-prod-taxi
      namespace: cicd
    type: Opaque
