apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCYR/Culu4x4Yrn4mCWxRLGYMab0DGsyhUifK9G5iO1HNNl3VmF4hy4gXVWCHbsl2KqObauYvATt/cqySR2Tw/1hlqw01kgMLKO+F/YQzHw1NVHUxBrZ380y6Kp7+3m1aC1L7ivGdnwp/IO55TKFgBNL8xfTg+B9gkZEOQT0MS0Qq/PK+iA0rjfhp8lF8A0Uck03o+tyudZ1qVJevYUHw9hTvXxKMZrYx0gg5aHNGh42WDLY7XOl7wZMn6DEKrSMnkVGDsdSP+514+T+WuIq+KI2ld302JDCUErQfBNNNeBxKjAy/f6Y1AZeoCmBOnZyXd9L5i+Ne6I5CIFPgp3aeU95FVE7jh5YJhePj7UUa2hIt7JPrruIqVBqpB/sEM63/EUJwP6CC7MVVeVlg9TIz5+hIzaE+ZtZo0AftEDTDQGxSNRDjBci4a3RVku7XPlqhMgRfE2GH5DxEQiJ9ESnd5ze7xHPdiB5yIbClz0CV6x5NdCuqrdhXa7KZpqbDb9iORgms2mLzggfvOHivZnwZ15s24zhg/62jOaSQKIviPPEVmK1mDuxEvAn/y6DuQM39Dep83GTqG755B6BAPHaR1qB8OQoQXbMyOsZmldOOZDEY/FLZ1U3mBdf//QYUJDsFOiDHT4+dNlveB4sDGD6h8sPVsfSEudtVEFO7MdovqIvNpkh0iSCrF/Rcdv9yJ65Hku71jZ/1qiCmC9qsKRD7oq5CsDOw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
