apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBW65cYVaYUj8jlgOToFHNEBy96mfMCpjckngsVDI4FX+m2zemGfTsfqe1wSlUpBDPP4xLpi4PR+vzFGz8m4MWvRmsGl5HluQebwQ5MwBe6ggqZV7og4feXf1a5Rvab15EmLN0UjuifSZ++VJlXRR0NT+CugjOKfXjwjW7980Gr92+jRffkIKhGdnVaE+Z58YvppKMl20zdk9VJ9MMVTaCa8LGlW3sJ21h5/aLNXM7Tc74geXC298STrMSI67mzZjeNZl+7S5p1EUjs3SN/TBaxnavURZhPzOFZKbNapZreMCdOtjq58K6e4QDGfeiB+ozRa4GHUd9v+u84GpW0+TdwnCXf94KGke2xF6KGurWk7zXWXKEkLBjVuF2D5cC2bRKA1x7kaAbPbrIISOBi793B0xa7Rt/srIoylX2/S9klzluq9xFk4Sri6DeDcVITducjG6dkUBbqSTYjBqMRbSU1hiHy5yCUHJgSvBCGo4j1or+s5YF1pOy+s3BvhI9lHJKFvL5yp2dfW1OUYr8X//Ao7ol7V2jQ1a5TiO2r1wKqFzbGjIpZRMNnWJVCQWEYGg2ZrQheA+TXJ/1ceCeaTGPWcO04s/L0rnUCrLeUQ+qKjGSihoRxQALj8p2SkH98BRQyIXZBpFBZ7mf7V/hNdHuSo68KwuFsWvfvjhb9EXx3fG8+fZx7XmpLDdr6Ty3VNNN1oiRPMsGlcUbSrgFSmObAUAooCQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
