apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBmU173GJB1p+h3DEge9swgFNCvn3kVz89VnI7MEeG9p/Iz3+1IWyHkXxsbbyCFf18oVG45H/x17aBa7xhnO5LlGfYHaLl2soi4LKWlOnsDUs9ZKtYz0godpwrl1oMYupg4BBLrZCKOAkrQa6cA0Q92Dt/94RCFiSrNB/h23DX3URY5GCzA2GUIMn1C1hss0ra/fZFuXHFMbcMBixo8SvH/9X3zm03qQe4XwXAzWae+atnE4FK6jpyAnpkNOmwjhM2tQH6bgQ01oFLv6vKKwDZ1+b7719Duq2GfA5KvWxilBlRNkOncwiZguW9zAIXtUawos9rcez+UUsyh3tzdQxcZAVxWHgHA/erB5gB9jCEmgOhUWADjbs2EQFqdB4xnvIFBoLXT4QCCZlZrSenpFs39aTWD60j2O1B1HuCFMWHuCfXJhN3U0vJOcmAX5ODNtWeKhLFiCpCtfGz4HW2btrVUgjRcqOFK8qwqxzxPnn/QEI4zfO/R+DYcrqK4uFG5jiDPRv4dM8DDEaNK8PZl482dsl7VcaA2fIlLMZx/Cu7FEFgJYA7L/7M1GNcR6CH1XnJgLadz9A3fOSJeOz7lBvXhhJT8v5y5Jl433jFb6Z14NKw0NcvfGhz0n6CPMZtNjj29lWyFlYPmfU2QWesdsrM9TgxIU3AkLoddiXDqXxvJRTH5kFal+1IqeFwN3GofMxBQx8ETJrgRR2rLpMyijHVmR9YjPw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
