apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBS6+4gmtk7FGdCLhwOwHpl/6VxCMw4o6ibOyU/LHoUxdlzPZCxPUyMxGefLPJOhQV2EtnpIQ8DWPQb6Wqhtp/Kpg5w3sZE03asCJihBkXgSgopAJ24RF1qVzMsETPSwAAd3uJy3uWjLBWRACg8tNnLLdpDomIv4C67x1tQl/YnNnjex6nut3BzV3/nZgG5lr50wbtDfZjofJRiSaaH0ufS54587MI8AnE+eq5viOni63Gjj5YGJj5i8m8s1eFFa39D757D00SESBPcWg0Omimk/iTPC8rIlFDvFSfPE/shxEWTkMCHr8g7U5K4p0viUebDisX0zDmFTYFhEdc+5vBsjCsP4U4RfxcrqWJAS04wNuHvFjmoGnKyKxSm3Iqbbgn5QhYJiwpauQ3TlMLzlecdmDv6azuezEiECoU8hD5csrAQwcbCXNNOypXiMO2qIf/XPkZqsDxiuHH8M4EUtxgAeEtbkx5a/l8VulrI2CaKtrslnF2b1shYru4TZooiEIZsPY8wI5dRW8oD9ENQu9hiDwmoDSZ7SlXnrQk4Nvciy4lsw1WQk46u5dyqNf0Nr14qCoGnvTp/ugRC8GdjRXs57pm81Zjcxui83/SLClmCKYvZS4simhvwxziS2Wy+hQex5koGYYq/yC4vgK/H0zk863+I1I70OgSEUyl9ioWb/7mzHFPicWbDY0ZLFJcN3AT7EdE=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
