apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgChlkU8kdMSXxhcKQ+MO/NDjNXVLnDKmuICnqRV72D3epmCgAI+fIF3yeYtcpE3OJnA2q1LPDUElhcO9iNQhpJm9sV3BbbRkRU3lemwJdSI0Vjak837bYj1ZL50SQSrJfrSmfpmUcTmsrJRTZ5PGealV1eJSzNLuxgECAePC1sSZsIpVaTK/zOWmIsj/jpoE65wTjn5QtO/AkPF8BZuU8ncXroceEMs6BvlbawmO51xaa89Yd3z1+xJmmbCeXWaBBvOBspJaLF14/dyxIYly3bPYJLXrqE7cuVCP33Tn1jcqf29U0971nUTM7VsQ8RYLZtt45QZdj0+RxiC3BP23pBx4526VEUmUr9MtIg1V6+xTq3gpFsgYllUq2gbsL7QjeoDfmCS4RRalBwXL7wmoB35BGgOT2X2Cu5Br+AHRRTj5rWc1nnl4+ijb9FbBKhSYChPRmJ6vvEHClyDRyEYiRgsp0y651Xz4IEfth1uJ5n686rilbuWFdamLlEVjxaBpVveZ4BTyqqJOxDo1/z23tYMOBH2dsoZAyElrYV9ArMWq966zrWXqNScX5z4ieguZuoUUz6BDUkMA/k9B8PchcDB/d8PQLUzDNejOF6r0ZmrcodrrppVr/YQjT+kvVgfuA14C1MpMF5BOkPiSu0jammvVbWvRjzw0UqBDahFlVAOLD8kE+2njka6E/RMUY2f2+o7Nf7lF6qPS8o0AixENUlWhOD6fQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
