apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAOp2mTwE3Z27/2Iwhb2Fc1LGiqR4LVZUfDItP5/lotEVwlOYqG2oMZbvOi0+mhTyJVlqS57xW1IrMiTgGK9ZHohYubdd15960pLKdZKYBipGTdnLtM6w3IuSjfzM1OCeOjKH4HBDIE5BGRaGViDYncSAZIq7FHb4xoeKpL78t0kybJUPy7fiwp34iLOce6cFnl0hkVhemThRy9P3yr5jL/DFzZhDJE/JvJBh+e/UqPXI4vkDvgvtHyNkPLXZDfLIEzReTAoJGe7jUVsdfIT3LRfUeg75Ea6G70DzTvUZctaZzeONdd9yLam/ZLSd6XfjboZNs0X0uRTc3fmj41sGpoFHDHfBr+sObdZu3HarOEjG82m30PlZ3nu/Br9w+BKE/KU4q5UvG993cloflSP1tqG465Bn5ZzmXwRN3mhao9dwD3ZWzf7/1y/nJyX8sdIhT/Xw4mq7PLuNTJExCND07dPtAAFg+F8bLMddrjOJ6SpJcAFxu/hrGdlZ5uFZIVpZly1EGnXCe3jik8TYRCZsurtZjKwPfBIWLeF+AQ7lLiXOalvGBVDpvOVDEya/fQ9fWG8CpsW55lCu34hvpqOmcv2zO0J1bfSfnTGzPu9jr2Lga+8s6jFUtSD8WJZwHq5bMj+VboD8ioPsukigqmsCtMfVA3sLDEX2DsHq4fE4OCbbeMj9KRxRLsQH/gL01HUKk4jRBS/3ExAWa7w1Q1XHCopPcJwQ==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
status: {}
