resources:
- 01-namespaces/chetan-cicd-environment.yaml
- 02-rolebindings/chetan-pipeline-service-role.yaml
- 02-rolebindings/chetan-pipeline-service-rolebinding.yaml
- 03-tasks/chetan-deploy-from-source-task.yaml
- 03-tasks/deploy-using-kubectl-task.yaml
- 04-pipelines/cd-deploy-from-push-pipeline.yaml
- 04-pipelines/ci-dryrun-from-pr-pipeline.yaml
- 04-pipelines/app-cd-pipeline.yaml
- 04-pipelines/app-ci-pipeline.yaml
- 05-bindings/chetan-github-pr-binding.yaml
- 05-bindings/chetan-github-push-binding.yaml
- 06-templates/app-cd-template.yaml
- 06-templates/app-ci-template.yaml
- 06-templates/chetan-cd-deploy-from-push-template.yaml
- 06-templates/chetan-ci-dryrun-from-pr-template.yaml
- 07-eventlisteners/chetan-cicd-event-listener.yaml
- 08-routes/chetan-github-webhook-event-listener.yaml
---
