apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: database
  name: redis
  namespace: stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: database
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: database
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
