apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: ci-dryrun-from-push-pipeline
  namespace: cicd
spec:
  resources:
  - name: source-repo
    type: git
  params:
  - name: REPO
    type: string
  - name: COMMIT_SHA
    type: string
  - name: GIT_REPO
    type: string
  tasks:
  - name: set-commit-status
    taskRef:
      kind: Task
      name: set-commit-status
    params:
    - name: REPO
      value: $(params.REPO)
    - name: COMMIT_SHA
      value: $(params.COMMIT_SHA)
    - name: DESCRIPTION
      value: "Build has started"
    - name: STATE
      value: "pending"
  - name: apply-source
    params:
    - name: DRYRUN
      value: "true"
    resources:
      inputs:
      - name: source
        resource: source-repo
    taskRef:
      kind: Task
      name: deploy-from-source-task
  finally:
  - name: set-commit
    taskRef:
      name: set-commit-status
    params:
    - name: REPO
      value: $(params.REPO)
    - name: COMMIT_SHA
      value: $(params.COMMIT_SHA)
    - name: DESCRIPTION
      value: "Build has started"
    - name: STATE
      value: $(tasks.apply-source.status)