apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cicd-app
  namespace: argocd
spec:
  destination:
    namespace: cicd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/cicd/overlays
    repoURL: https://github.com/chetan-rns/gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
