apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: config-app
  namespace: argocd
spec:
  destination:
    namespace: cicd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config
    repoURL: https://github.com/chetan-rns/gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    jsonPointers:
    - /status
  - group: triggers.tekton.dev
    kind: EventListener
    jsonPointers:
    - /status
  - group: triggers.tekton.dev
    kind: TriggerTemplate
    jsonPointers:
    - /status
  - group: triggers.tekton.dev
    kind: TriggerBinding
    jsonPointers:
    - /status
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
