apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: chetan-stage-test-app
  namespace: argocd
spec:
  destination:
    namespace: chetan-stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/chetan-stage/apps/test-app/base
    repoURL: http://github.com/chetan-rns/gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
