apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  creationTimestamp: null
  name: argocd
  namespace: argocd
spec:
  resourceExclusions: "|\n\t\t- apiGroups:\n\t\t  - tekton.dev\n\t\t  kinds:\n\t\t
    \ - TaskRun\n\t\t  - PipelineRun\n\t\t  clusters:\n\t\t  - \"*\""
  server:
    route:
      enabled: true  
