apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  resource.exclusions: |
    - apiGroups:
      - tekton.dev
      kinds:
      - PipelineRun
      - TaskRun
      clusters:
      - *
