apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: taxi-svc
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi-svc
      app.kubernetes.io/part-of: taxi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: taxi-svc
        app.kubernetes.io/part-of: taxi
    spec:
      containers:
      - image: quay.io/cbanavik/taxi:745cc2aa72095664320d342403b1df0b53753f6a
        imagePullPolicy: Always
        name: taxi-svc
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
