apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: 2020-08-03T17:35:17Z
  labels:
    app: nodejs-rest-http-crud
    app.kubernetes.io/component: nodejs-rest-http-crud
    app.kubernetes.io/instance: nodejs-rest-http-crud
    app.kubernetes.io/part-of: nodejs-rest-http-crud-app
  name: nodejs-rest-http-crud
  namespace: chetan-prod
spec:
  clusterIP: 172.30.28.84
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodejs-rest-http-crud
    deploymentconfig: nodejs-rest-http-crud
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: 2020-08-03T17:35:17Z
  labels:
    app: nodejs-rest-http-crud
    app.kubernetes.io/component: nodejs-rest-http-crud
    app.kubernetes.io/instance: nodejs-rest-http-crud
    app.kubernetes.io/part-of: nodejs-rest-http-crud-app
    app.openshift.io/runtime-version: latest
  name: nodejs-rest-http-crud
  namespace: chetan-prod
spec:
  host: nodejs-rest-http-crud-chetan-prod.apps.viraj091920.devcluster.openshift.com
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: nodejs-rest-http-crud
    weight: 100
  wildcardPolicy: None

